--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Planet config

local function GetPlanet(planetUtilities, planetID)
	
	--local image = planetUtilities.planetImages[math.floor(math.random()*#planetUtilities.planetImages) + 1]
	local image = LUA_DIRNAME .. "images/planets/terran02.png"
	
	local planetData = {
		name = "Voholon Delta",
		startingPlanet = false,
		mapDisplay = {
			x = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][1]) or 0.34,
			y = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][2]) or 0.21,
			image = image,
			size = planetUtilities.PLANET_SIZE_MAP,
		},
		infoDisplay = {
			image = image,
			size = planetUtilities.PLANET_SIZE_INFO,
			backgroundImage = planetUtilities.backgroundImages[math.floor(math.random()*#planetUtilities.backgroundImages) + 1],
			terrainType = "Arid",
			radius = "8410 km",
			primary = "Seraz",
			primaryType = "G9V",
			milRating = 1,
			feedbackLink = "http://zero-k.info/Forum/Thread/24489",
			text = "This was one of the first rebel worlds, and one of the last to fall. To make sure it would never rebel again, the occupation force was allowed to use nuclear missiles against the next uprising."
			.. "\n "
			.. "\nThe nuclear silos are still there, but some long-forgotten rebel malware infiltrated part of the occupation forces. And it just signaled me that it is, and I quote, Liberation Time."
			,
			extendedText = "I must dominate the low ground with the raw power of the Tank Foundry, push through the enemy defenses and destroy their Nuclear Silo while protecting our own Anti-Nukes. Should be easy enough..."
		},
		tips = {
			{
				image = "unitpics/tankassault.png",
				text = [[The Minotaur assault tank is a very tough unit for a relatively affordable price. Use it to brute-force your way through enemy positions.]]
			},
			{
				image = "unitpics/tankarty.png",
				text = [[Use the Emissary artillery tank to weaken defenses that are too dangerous to attack directly with Minotaurs.]]
			},
			{
				image = "unitpics/factorycloak.png",
				text = [[Remember that you can build a second factory to supplement your Tanks with faster, lighter units.]]
			},
		},
		gameConfig = {
			mapName = "DeltaSiegeDry Deluxe V3",
			playerConfig = {
				startX = 3247,
				startZ = 4228,
				allyTeam = 0,
				commanderParameters = {
					facplop = true, --THIS IS DELIBERATE
					defeatIfDestroyedObjectiveID = 2,
				},
				extraUnlocks = {
					"factorytank",
					"tankcon",
					"tankassault",
					"tankarty",
					"tankaa",
				},
				startUnits = {
					{
						name = "energygeo",
						x = 2248,
						z = 4488,
						facing = 1,
					},
					{
						name = "staticmex",
						x = 1048,
						z = 4184,
						facing = 0,
					},
					{
						name = "staticmex",
						x = 1224,
						z = 4408,
						facing = 0,
					},
					{
						name = "staticmex",
						x = 1336,
						z = 4120,
						facing = 0,
					},
					{
						name = "factorytank",
						x = 3392,
						z = 4448,
						facing = 1,
					},
					{
						name = "staticmex",
						x = 3208,
						z = 4648,
						facing = 0,
					},
					{
						name = "staticmex",
						x = 3400,
						z = 4888,
						facing = 0,
					},
					{
						name = "staticcon",
						x = 3224,
						z = 4504,
						facing = 1,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {3392, 4448}},
						},
					},
					{
						name = "staticcon",
						x = 3224,
						z = 4424,
						facing = 1,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {3392, 4448}},
						},
					},
					{
						name = "staticcon",
						x = 3224,
						z = 4344,
						facing = 1,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {3392, 4448}},
						},
					},
					{
						name = "energysolar",
						x = 1128,
						z = 4280,
						facing = 0,
					},
					{
						name = "energysolar",
						x = 1288,
						z = 4248,
						facing = 0,
					},
					{
						name = "energysolar",
						x = 1304,
						z = 4376,
						facing = 0,
					},
					{
						name = "energysolar",
						x = 3192,
						z = 4744,
						facing = 0,
					},
					{
						name = "energysolar",
						x = 3272,
						z = 4856,
						facing = 0,
					},
					{
						name = "tankassault",
						x = 3777,
						z = 4265,
						facing = 1,
					},
					{
						name = "tankassault",
						x = 3768,
						z = 4363,
						facing = 1,
					},
					{
						name = "tankassault",
						x = 3763,
						z = 4465,
						facing = 1,
					},
					{
						name = "tankassault",
						x = 3764,
						z = 4565,
						facing = 1,
					},
					{
						name = "tankassault",
						x = 3757,
						z = 4668,
						facing = 1,
					},
					{
						name = "tankaa",
						x = 3662,
						z = 4309,
						facing = 1,
					},
					{
						name = "tankaa",
						x = 3655,
						z = 4628,
						facing = 1,
					},
					{
						name = "tankarty",
						x = 3604,
						z = 4525,
						facing = 1,
					},
					{
						name = "tankarty",
						x = 3604,
						z = 4408,
						facing = 1,
					},
				}
			},
			aiConfig = {
				{
					aiLib = "Circuit_difficulty_autofill_ally",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					humanName = "Salters",
					allyTeam = 0,
					unlocks = {
						--"staticantinuke",
						"staticmex",
						"energysolar",
						"staticradar",
						"staticcon",
						"factoryplane",
						"factoryshield",
						"factoryspider",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turretheavylaser",
						"turretaalaser",
						"turretaaclose",
						"turretemp",
						"planecon",
						"planescout",
						"planefighter",
						"planeheavyfighter",
						"bomberprec",
						"bomberriot",
						"bomberdisarm",
						"bomberheavy",
						"shieldcon",
						"shieldfelon",
						"shieldraid",
						"shieldriot",
						"shieldshield",
						"shieldskirm",
						"shieldarty",
						"shieldassault",
						"shieldaa",
						"spidercon",
						"spideraa",
						"spiderantiheavy",
						"spiderassault",
						"spidercrabe",
						"spideremp",
						"spiderriot",
						"spiderscout",
						"spiderskirm",
					},
					commander = false,
					startUnits = {
						{
							name = "staticantinuke",
							x = 1970,
							z = 4830,
							facing = 0,
							mapMarker = {
								text = "Defend",
								color = "green",
							},
						},
						--{
						--	name = "staticantinuke",
						--	x = 3000,
						--	z = 2750,
						--	facing = 0,
						--	mapMarker = {
						--		text = "Defend",
						--		color = "green",
						--	},
						--},
						{
							name = "staticantinuke",
							x = 2130,
							z = 386,
							facing = 0,
							mapMarker = {
								text = "Defend",
								color = "green",
							},
						},
						{
							name = "planescout",
							x = 4471,
							z = 1150,
							facing = 0,
						},
						{
							name = "planescout",
							x = 4471,
							z = 3450,
							facing = 0,
						},
						{
							name = "planescout",
							x = 4471,
							z = 6200,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 776,
							z = 888,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 856,
							z = 1144,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 1064,
							z = 952,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 680,
							z = 2856,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 1032,
							z = 2776,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 920,
							z = 3064,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 1128,
							z = 6264,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 776,
							z = 6296,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 1016,
							z = 6552,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 2376,
							z = 6584,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 2360,
							z = 488,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 2728,
							z = 232,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 3224,
							z = 408,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 2344,
							z = 2776,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 2664,
							z = 2568,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 2904,
							z = 2904,
							facing = 0,
						},
						{
							name = "energygeo",
							x = 3160,
							z = 1512,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 744,
							z = 2920,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 888,
							z = 2952,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 952,
							z = 2856,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 824,
							z = 920,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 872,
							z = 1048,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 968,
							z = 952,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 856,
							z = 6328,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 968,
							z = 6440,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 1016,
							z = 6296,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 2440,
							z = 2760,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 2584,
							z = 2664,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 2744,
							z = 2664,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 2840,
							z = 2776,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 2440,
							z = 408,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 2600,
							z = 296,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 2840,
							z = 296,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 3000,
							z = 360,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 3112,
							z = 440,
							facing = 0,
						},
						{
							name = "turretheavylaser",
							x = 3464,
							z = 6232,
							facing = 0,
						},
						{
							name = "turretmissile",
							x = 3008,
							z = 4864,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 3096,
							z = 6424,
							facing = 0,
						},
						{
							name = "factoryshield",
							x = 2400,
							z = 840,
							facing = 0,
						},
						{
							name = "factoryspider",
							x = 2376,
							z = 2344,
							facing = 2,
						},
						{
							name = "factoryplane",
							x = 1456,
							z = 6352,
							facing = 0,
						},
						{
							name = "staticcon",
							x = 1416,
							z = 6504,
							facing = 1,
						},
						{
							name = "staticcon",
							x = 1496,
							z = 6504,
							facing = 1,
						},
						{
							name = "staticcon",
							x = 2360,
							z = 664,
							facing = 1,
						},
						{
							name = "staticcon",
							x = 2440,
							z = 664,
							facing = 1,
						},
						{
							name = "staticcon",
							x = 2328,
							z = 2472,
							facing = 1,
						},
						{
							name = "staticcon",
							x = 2408,
							z = 2472,
							facing = 1,
						},
						{
							name = "energypylon",
							x = 1496,
							z = 2728,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 2376,
							z = 2584,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 3112,
							z = 2872,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 1416,
							z = 1800,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 1464,
							z = 1000,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 2216,
							z = 600,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 3016,
							z = 552,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 3528,
							z = 344,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 1240,
							z = 3544,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 840,
							z = 4248,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 888,
							z = 5192,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 952,
							z = 5992,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 1640,
							z = 6360,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 2328,
							z = 6232,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 2712,
							z = 1784,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 1768,
							z = 4440,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 680,
							z = 3016,
							facing = 0,
						},
						{
							name = "energyfusion",
							x = 456,
							z = 2944,
							facing = 0,
						},
						{
							name = "energyfusion",
							x = 456,
							z = 2800,
							facing = 0,
						},
						{
							name = "turretheavy",
							x = 3640,
							z = 696,
							facing = 1,
						},
						{
							name = "turretheavy",
							x = 3736,
							z = 200,
							facing = 1,
						},
						{
							name = "turretheavy",
							x = 3208,
							z = 2472,
							facing = 1,
						},
						{
							name = "turretheavy",
							x = 3368,
							z = 2840,
							facing = 1,
						},
						{
							name = "turretheavy",
							x = 3064,
							z = 3320,
							facing = 1,
						},
						{
							name = "turretheavy",
							x = 2648,
							z = 5944,
							facing = 1,
						},
						{
							name = "turretheavy",
							x = 2536,
							z = 6632,
							facing = 1,
						},
						{
							name = "staticheavyradar",
							x = 3456,
							z = 3328,
							facing = 0,
						},
						{
							name = "shieldassault",
							x = 4391,
							z = 2805,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 832,
							z = 6272,
							facing = 1,
						},
						{
							name = "shieldraid",
							x = 6442,
							z = 4895,
							facing = 1,
						},
						{
							name = "shieldcon",
							x = 4542,
							z = 4162,
							facing = 1,
						},
						{
							name = "shieldskirm",
							x = 6385,
							z = 1561,
							facing = 3,
						},
						{
							name = "shieldarty",
							x = 5700,
							z = 4511,
							facing = 1,
						},
						{
							name = "spidercon",
							x = 4091,
							z = 5098,
							facing = 2,
						},
						{
							name = "turretmissile",
							x = 3952,
							z = 4960,
							facing = 1,
						},
						{
							name = "shieldcon",
							x = 2400,
							z = 852,
							facing = 0,
							buildProgress = 0.73570001,
						},
						{
							name = "turretlaser",
							x = 3216,
							z = 6736,
							facing = 2,
						},
						{
							name = "turretmissile",
							x = 3440,
							z = 4736,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 2624,
							z = 752,
							facing = 1,
						},
						{
							name = "spideremp",
							x = 3949,
							z = 3426,
							facing = 0,
						},
						{
							name = "turretheavylaser",
							x = 3256,
							z = 1848,
							facing = 1,
						},
						{
							name = "spidercon",
							x = 4845,
							z = 6300,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 2544,
							z = 432,
							facing = 0,
						},
						{
							name = "spiderskirm",
							x = 3897,
							z = 3364,
							facing = 2,
						},
						{
							name = "turretmissile",
							x = 3632,
							z = 4032,
							facing = 1,
						},
						{
							name = "shieldassault",
							x = 4909,
							z = 4581,
							facing = 1,
						},
						{
							name = "staticradar",
							x = 2400,
							z = 304,
							facing = 0,
						},
						{
							name = "shieldraid",
							x = 3792,
							z = 4188,
							facing = 1,
						},
						{
							name = "staticradar",
							x = 976,
							z = 6112,
							facing = 1,
						},
						{
							name = "turretaafar",
							x = 3504,
							z = 6400,
							facing = 1,
						},
						{
							name = "staticradar",
							x = 2416,
							z = 2848,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 2368,
							z = 6496,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 2688,
							z = 2704,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 3128,
							z = 2152,
							facing = 0,
						},
						{
							name = "spidercon",
							x = 4551,
							z = 2004,
							facing = 1,
						},
						{
							name = "turretheavylaser",
							x = 3816,
							z = 3720,
							facing = 1,
						},
						{
							name = "spiderassault",
							x = 6495,
							z = 1692,
							facing = 0,
						},
						{
							name = "turretlaser",
							x = 976,
							z = 896,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 1200,
							z = 4288,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 2208,
							z = 1024,
							facing = 1,
						},
						{
							name = "turretheavylaser",
							x = 3256,
							z = 5064,
							facing = 1,
						},
						{
							name = "turretaalaser",
							x = 3176,
							z = 2168,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 800,
							z = 2960,
							facing = 1,
						},
						{
							name = "staticcon",
							x = 2376,
							z = 2520,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 3616,
							z = 3520,
							facing = 1,
						},
						{
							name = "staticradar",
							x = 896,
							z = 1136,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 4344,
							z = 6568,
							facing = 0,
						},
						{
							name = "staticradar",
							x = 1344,
							z = 4048,
							facing = 1,
						},
						{
							name = "turretaalaser",
							x = 3176,
							z = 2088,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 3432,
							z = 2008,
							facing = 0,
						},
						{
							name = "spideremp",
							x = 3906,
							z = 3461,
							facing = 2,
						},
						{
							name = "staticradar",
							x = 3056,
							z = 6384,
							facing = 2,
						},
						{
							name = "shieldarty",
							x = 5709,
							z = 4416,
							facing = 0,
						},
						{
							name = "turretlaser",
							x = 2160,
							z = 816,
							facing = 1,
						},
						{
							name = "staticrearm",
							x = 1448,
							z = 6152,
							facing = 0,
						},
						{
							name = "spiderassault",
							x = 5092,
							z = 4516,
							facing = 1,
						},
						{
							name = "shieldassault",
							x = 4271,
							z = 2192,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 4600,
							z = 872,
							facing = 0,
						},
						{
							name = "staticradar",
							x = 3312,
							z = 4576,
							facing = 1,
						},
						{
							name = "spidercrabe",
							x = 2376,
							z = 2308,
							facing = 2,
							buildProgress = 0.77850002,
						},
						{
							name = "shieldarty",
							x = 3863,
							z = 3390,
							facing = 2,
						},
						{
							name = "turretlaser",
							x = 3216,
							z = 4864,
							facing = 1,
						},
						{
							name = "shieldassault",
							x = 4878,
							z = 4610,
							facing = 2,
						},
						{
							name = "factoryshield",
							x = 3280,
							z = 6184,
							facing = 0,
						},
						{
							name = "shieldcon",
							x = 4179,
							z = 5660,
							facing = 2,
						},
						{
							name = "staticmex",
							x = 4152,
							z = 4920,
							facing = 0,
							buildProgress = 0.87330002,
						},
						{
							name = "turretaalaser",
							x = 3320,
							z = 3720,
							facing = 1,
						},
						{
							name = "turretaalaser",
							x = 3416,
							z = 4952,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 4400,
							z = 6608,
							facing = 2,
							buildProgress = 0.24250001,
						},
						{
							name = "spidercon",
							x = 3535,
							z = 2521,
							facing = 0,
						},
						{
							name = "shieldraid",
							x = 1998,
							z = 2015,
							facing = 3,
						},
						{
							name = "shieldraid",
							x = 6491,
							z = 4900,
							facing = 1,
						},
						{
							name = "shieldraid",
							x = 5256,
							z = 4530,
							facing = 1,
						},
						{
							name = "shieldraid",
							x = 6393,
							z = 4910,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 4432,
							z = 4240,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 4568,
							z = 4216,
							facing = 0,
						},
						{
							name = "shieldassault",
							x = 4835,
							z = 4608,
							facing = 1,
						},
						{
							name = "shieldraid",
							x = 1926,
							z = 2070,
							facing = 3,
						},
						{
							name = "shieldcon",
							x = 4555,
							z = 971,
							facing = 1,
						},
						{
							name = "shieldcon",
							x = 4308,
							z = 6582,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 3624,
							z = 2696,
							facing = 0,
						},
						{
							name = "turretlaser",
							x = 3120,
							z = 4672,
							facing = 1,
						},
						{
							name = "spidercrabe",
							x = 6632,
							z = 1324,
							facing = 0,
						},
						{
							name = "turretmissile",
							x = 3376,
							z = 2144,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 2336,
							z = 576,
							facing = 1,
						},
						{
							name = "spiderassault",
							x = 3895,
							z = 3409,
							facing = 2,
						},
						{
							name = "spiderassault",
							x = 5140,
							z = 4512,
							facing = 1,
						},
						{
							name = "turretaalaser",
							x = 3560,
							z = 6232,
							facing = 0,
						},
						{
							name = "turretmissile",
							x = 2608,
							z = 976,
							facing = 1,
						},
						{
							name = "shieldassault",
							x = 2990,
							z = 1210,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 3824,
							z = 4800,
							facing = 1,
						},
						{
							name = "shieldraid",
							x = 5278,
							z = 4549,
							facing = 1,
						},
						{
							name = "turretaalaser",
							x = 3592,
							z = 6536,
							facing = 0,
						},
						{
							name = "turretheavylaser",
							x = 3320,
							z = 6696,
							facing = 0,
						},
						{
							name = "shieldaa",
							x = 4265,
							z = 3674,
							facing = 3,
						},
						{
							name = "staticmex",
							x = 3640,
							z = 3704,
							facing = 0,
						},
						{
							name = "shieldshield",
							x = 1463,
							z = 3146,
							facing = 0,
						},
						{
							name = "shieldassault",
							x = 4940,
							z = 4551,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 3384,
							z = 6584,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 3160,
							z = 6824,
							facing = 0,
						},
						{
							name = "spideraa",
							x = 5767,
							z = 4120,
							facing = 3,
						},
						{
							name = "turretaalaser",
							x = 3832,
							z = 3544,
							facing = 1,
						},
						{
							name = "shieldassault",
							x = 4319,
							z = 2835,
							facing = 0,
						},
						{
							name = "spideremp",
							x = 3865,
							z = 3450,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 3752,
							z = 3496,
							facing = 0,
						},
						{
							name = "shieldraid",
							x = 5308,
							z = 4559,
							facing = 1,
						},
						{
							name = "shieldraid",
							x = 1800,
							z = 2170,
							facing = 3,
						},
						{
							name = "shieldassault",
							x = 3284,
							z = 6210,
							facing = 0,
							buildProgress = 0.34999999,
						},
						{
							name = "turretmissile",
							x = 4640,
							z = 4112,
							facing = 1,
							buildProgress = 0.63330001,
						},
						{
							name = "turretmissile",
							x = 3712,
							z = 2624,
							facing = 1,
							buildProgress = 0.7374,
						},
						{
							name = "staticmex",
							x = 5048,
							z = 6328,
							facing = 0,
							buildProgress = 0.30329999,
						},
						{
							name = "shieldassault",
							x = 4334,
							z = 664,
							facing = 0,
						},
						{
							name = "shieldassault",
							x = 4304,
							z = 874,
							facing = 0,
						},
						{
							name = "shieldassault",
							x = 4450,
							z = 1130,
							facing = 0,
						},
						{
							name = "shieldassault",
							x = 4455,
							z = 868,
							facing = 0,
						},
						{
							name = "shieldassault",
							x = 4378,
							z = 1468,
							facing = 0,
						},
						{
							name = "shieldraid",
							x = 4415,
							z = 1283,
							facing = 0,
						},
						{
							name = "shieldraid",
							x = 4379,
							z = 943,
							facing = 0,
						},
						{
							name = "shieldraid",
							x = 4440,
							z = 733,
							facing = 0,
						},
						{
							name = "shieldraid",
							x = 4353,
							z = 427,
							facing = 0,
						},
						{
							name = "shieldraid",
							x = 4304,
							z = 1703,
							facing = 0,
						},
						{
							name = "spidercrabe",
							x = 4401,
							z = 1674,
							facing = 0,
						},
						{
							name = "spidercrabe",
							x = 4142,
							z = 1885,
							facing = 0,
						},
						{
							name = "spideraa",
							x = 4220,
							z = 1119,
							facing = 0,
						},
						{
							name = "spideraa",
							x = 4166,
							z = 1517,
							facing = 0,
						},
						{
							name = "spideraa",
							x = 4081,
							z = 1726,
							facing = 0,
						},
						{
							name = "spideraa",
							x = 4083,
							z = 1232,
							facing = 0,
						},
						{
							name = "turretlaser",
							x = 2030,
							z = 4960,
							facing = 0,
						},
					}
				},
				{
					startX = 9867,
					startZ = 4521,
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					humanName = "Uraynites",
					allyTeam = 1,
					unlocks = {
						"staticmex",
						"energysolar",
						"staticradar",
						"staticcon",
						"factorygunship",
						"factoryjump",
						"factoryspider",
						"factoryveh",
						"planecon",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turretheavylaser",
						"turretaalaser",
						"turretaaclose",
						"turretemp",
						"gunshipaa",
						"gunshipassault",
						"gunshipbomb",
						"gunshipcon",
						"gunshipemp",
						"gunshipheavyskirm",
						"gunshipraid",
						"gunshipskirm",
						"jumpcon",
						"jumpaa",
						"jumpassault",
						"jumpblackhole",
						"jumpraid",
						"jumpscout",
						"jumpskirm",
						"jumparty",
						"spidercon",
						"spideraa",
						"spiderantiheavy",
						"spiderassault",
						"spidercrabe",
						"spideremp",
						"spiderriot",
						"spiderscout",
						"spiderskirm",
						"shieldcon",
						"shieldfelon",
						"shieldraid",
						"shieldriot",
						"shieldshield",
						"shieldskirm",
						"shieldarty",
						"shieldassault",
						"shieldaa",
						"vehcon",
						"vehaa",
						"veharty",
						"vehassault",
						"vehheavyarty",
						"vehraid",
						"vehriot",
						"vehscout",
						"vehsupport",
					},
					difficultyDependantUnlocks = {
						[2] = {"spiderantiheavy"},
						[3] = {"spiderantiheavy","vehcapture"},
						[4] = {"spiderantiheavy","vehcapture","striderhub","striderantiheavy"},
					},
					commanderLevel = 4,
					commander = {
						name = "Galatine",
						chassis = "guardian",
						decorations = {
						},
						modules = {
							"commweapon_heatray",
							"commweapon_heatray",
							"commweapon_personal_shield",
							"module_heavy_armor",
							"module_heavy_armor",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_dmg_booster",
							"module_dmg_booster",
						}
					},
					startUnits = {
						{
							name = "staticnuke",
							x = 9670,
							z = 5200,
							facing = 0,
							mapMarker = {
								text = "Nuclear Silo",
								color = "red",
							},
						},
						{
							name = "staticantinuke",
							x = 8900,
							z = 1300,
							facing = 0,
						},
						{
							name = "staticantinuke",
							x = 10000,
							z = 4700,
							facing = 0,
						},
						{
							name = "vehassault",
							x = 8800,
							z = 4700,
							facing = 3,
							difficultyAtLeast = 2,
						},
						{
							name = "vehassault",
							x = 8800,
							z = 4800,
							facing = 3,
							difficultyAtLeast = 2,
						},
						{
							name = "vehassault",
							x = 8800,
							z = 4900,
							facing = 3,
							difficultyAtLeast = 2,
						},
						{
							name = "vehassault",
							x = 8800,
							z = 5000,
							facing = 3,
							difficultyAtLeast = 3,
						},
						{
							name = "vehassault",
							x = 8800,
							z = 5100,
							facing = 3,
							difficultyAtLeast = 3,
						},
						{
							name = "vehassault",
							x = 8800,
							z = 5200,
							facing = 3,
							difficultyAtLeast = 3,
						},
						{
							name = "vehraid",
							x = 8900,
							z = 4700,
							facing = 3,
						},
						{
							name = "vehraid",
							x = 8900,
							z = 4800,
							facing = 3,
						},
						{
							name = "vehraid",
							x = 8900,
							z = 4900,
							facing = 3,
						},
						{
							name = "vehraid",
							x = 8900,
							z = 5000,
							facing = 3,
						},
						{
							name = "vehraid",
							x = 8900,
							z = 5100,
							facing = 3,
						},
						{
							name = "vehraid",
							x = 8900,
							z = 5200,
							facing = 3,
						},
						{
							name = "striderantiheavy",
							x = 9900,
							z = 6000,
							facing = 3,
							difficultyAtLeast = 4,
						},
						{
							name = "striderhub",
							x = 10000,
							z = 6000,
							facing = 3,
							difficultyAtLeast = 4,
						},
						{
							name = "turretemp",
							x = 9464,
							z = 5000,
							facing = 3,
						},
						{
							name = "turretemp",
							x = 9464,
							z = 5400,
							facing = 3,
						},
						{
							name = "turretemp",
							x = 9864,
							z = 5000,
							facing = 3,
						},
						{
							name = "turretemp",
							x = 9864,
							z = 5400,
							facing = 3,
						},
						{
							name = "turretaaclose",
							x = 9464,
							z = 5192,
							facing = 3,
						},
						{
							name = "turretaaflak",
							x = 9656,
							z = 5400,
							facing = 3,
						},
						{
							name = "turretaaclose",
							x = 9864,
							z = 5192,
							facing = 3,
						},
						{
							name = "turretaaflak",
							x = 9656,
							z = 5000,
							facing = 3,
						},
						{
							name = "turretheavylaser",
							x = 9200,
							z = 5192,
							facing = 3,
						},
						{
							name = "turretheavylaser",
							x = 9656,
							z = 5600,
							facing = 3,
						},
						{
							name = "turretheavylaser",
							x = 10000,
							z = 5192,
							facing = 3,
						},
						{
							name = "turretheavylaser",
							x = 9656,
							z = 4800,
							facing = 3,
						},
						{
							name = "staticmex",
							x = 10360,
							z = 968,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 10536,
							z = 824,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 10664,
							z = 1096,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 10328,
							z = 2760,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 10552,
							z = 2936,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 10600,
							z = 2648,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 9944,
							z = 4136,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 10056,
							z = 4552,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 10232,
							z = 4392,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 10232,
							z = 6312,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 10376,
							z = 6072,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 10552,
							z = 6376,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 8920,
							z = 6216,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 8056,
							z = 392,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 8568,
							z = 200,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 9000,
							z = 408,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 8488,
							z = 2744,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 8920,
							z = 2568,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 8952,
							z = 2904,
							facing = 0,
						},
						{
							name = "energygeo",
							x = 8120,
							z = 1464,
							facing = 0,
						},
						{
							name = "energygeo",
							x = 9128,
							z = 4440,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 8184,
							z = 360,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 8360,
							z = 312,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 8520,
							z = 280,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 8696,
							z = 296,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 8856,
							z = 376,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 8600,
							z = 2712,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 8760,
							z = 2664,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 8936,
							z = 2680,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 9000,
							z = 2824,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 10456,
							z = 904,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 10584,
							z = 1000,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 10472,
							z = 1048,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 10424,
							z = 2744,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 10552,
							z = 2728,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 10504,
							z = 2840,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 10008,
							z = 4248,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 10136,
							z = 4360,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 10024,
							z = 4440,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 10312,
							z = 6184,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 10440,
							z = 6296,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 10472,
							z = 6152,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 8328,
							z = 4536,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 8136,
							z = 4792,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 8344,
							z = 4664,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 8248,
							z = 4760,
							facing = 0,
						},
						{
							name = "factoryjump",
							x = 8728,
							z = 712,
							facing = 0,
						},
						{
							name = "factorygunship",
							x = 9736,
							z = 6264,
							facing = 3,
						},
						{
							name = "staticcon",
							x = 9928,
							z = 6264,
							facing = 3,
						},
						{
							name = "staticcon",
							x = 10024,
							z = 6264,
							facing = 3,
						},
						{
							name = "factoryspider",
							x = 8856,
							z = 2232,
							facing = 2,
						},
						{
							name = "staticcon",
							x = 8808,
							z = 2376,
							facing = 3,
						},
						{
							name = "staticcon",
							x = 8904,
							z = 2376,
							facing = 3,
						},
						{
							name = "staticcon",
							x = 8696,
							z = 568,
							facing = 3,
						},
						{
							name = "staticcon",
							x = 8776,
							z = 568,
							facing = 3,
						},
						{
							name = "energypylon",
							x = 7944,
							z = 440,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 8744,
							z = 440,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 9704,
							z = 584,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 10184,
							z = 1320,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 8440,
							z = 1176,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 9768,
							z = 2792,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 10312,
							z = 2200,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 10056,
							z = 3624,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 10328,
							z = 4376,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 8136,
							z = 2888,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 8808,
							z = 2856,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 10136,
							z = 5208,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 10216,
							z = 5944,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 9704,
							z = 6456,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 9032,
							z = 6504,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 9480,
							z = 4504,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 10552,
							z = 3000,
							facing = 0,
						},
						{
							name = "energyfusion",
							x = 10584,
							z = 3136,
							facing = 0,
						},
						{
							name = "energyfusion",
							x = 10424,
							z = 3248,
							facing = 0,
						},
						{
							name = "turretheavy",
							x = 7480,
							z = 600,
							facing = 3,
						},
						{
							name = "turretheavy",
							x = 8960,
							z = 4480,
							facing = 3,
						},
						{
							name = "turretheavy",
							x = 8470,
							z = 6320,
							facing = 3,
						},
						{
							name = "turretheavy",
							x = 9320,
							z = 6320,
							facing = 2,
						},
						-- {
							-- name = "turretheavy",
							-- x = 9000,
							-- z = 5920,
							-- facing = 2,
						-- },
						{
							name = "turretheavy",
							x = 7464,
							z = 264,
							facing = 3,
						},
						{
							name = "turretheavy",
							x = 7944,
							z = 2472,
							facing = 3,
						},
						{
							name = "turretheavy",
							x = 7832,
							z = 3000,
							facing = 3,
						},
						{
							name = "turretheavy",
							x = 8830,
							z = 3390,
							facing = 0,
						},
						-- {
							-- name = "turretheavy",
							-- x = 8584,
							-- z = 6088,
							-- facing = 3,
						-- },
						-- {
							-- name = "turretheavy",
							-- x = 8776,
							-- z = 6632,
							-- facing = 3,
						-- },
						{
							name = "factoryveh",
							x = 9784,
							z = 3848,
							facing = 3,
						},
						{
							name = "staticcon",
							x = 9896,
							z = 3928,
							facing = 3,
						},
						{
							name = "staticcon",
							x = 9896,
							z = 3832,
							facing = 3,
						},
						{
							name = "staticcon",
							x = 9896,
							z = 3736,
							facing = 3,
						},
						{
							name = "staticheavyradar",
							x = 7872,
							z = 3296,
							facing = 0,
						},
						{
							name = "dynassault3_10",
							x = 7646,
							z = 1259,
							facing = 1,
						},
						{
							name = "spiderassault",
							x = 4801,
							z = 3024,
							facing = 0,
						},
						{
							name = "spidercon",
							x = 6747,
							z = 2087,
							facing = 1,
						},
						{
							name = "gunshipemp",
							x = 7250,
							z = 1922,
							facing = 2,
						},
						{
							name = "spidercon",
							x = 5386,
							z = 2946,
							facing = 2,
						},
						{
							name = "vehraid",
							x = 6948,
							z = 3610,
							facing = 1,
						},
						{
							name = "vehraid",
							x = 5042,
							z = 2791,
							facing = 3,
						},
						{
							name = "spiderantiheavy",
							x = 6694,
							z = 3681,
							facing = 2,
						},
						{
							name = "vehcon",
							x = 6073,
							z = 3506,
							facing = 3,
						},
						{
							name = "spideremp",
							x = 6397,
							z = 3344,
							facing = 0,
						},
						{
							name = "jumpraid",
							x = 4411,
							z = 2952,
							facing = 3,
						},
						{
							name = "turretmissile",
							x = 8976,
							z = 672,
							facing = 3,
						},
						{
							name = "gunshipheavyskirm",
							x = 5906,
							z = 1150,
							facing = 1,
						},
						{
							name = "jumpassault",
							x = 8728,
							z = 736,
							facing = 0,
							buildProgress = 0.89499998,
						},
						{
							name = "vehassault",
							x = 9007,
							z = 3717,
							facing = 3,
						},
						{
							name = "vehcon",
							x = 6954,
							z = 1735,
							facing = 2,
						},
						{
							name = "jumpcon",
							x = 7056,
							z = 2224,
							facing = 2,
						},
						{
							name = "spideremp",
							x = 6559,
							z = 2209,
							facing = 3,
						},
						{
							name = "jumpassault",
							x = 7411,
							z = 939,
							facing = 2,
						},
						{
							name = "spiderassault",
							x = 4836,
							z = 3209,
							facing = 3,
						},
						{
							name = "vehassault",
							x = 7572,
							z = 3773,
							facing = 1,
						},
						{
							name = "gunshipaa",
							x = 5393,
							z = 2919,
							facing = 2,
						},
						{
							name = "jumpcon",
							x = 5350,
							z = 2998,
							facing = 3,
						},
						{
							name = "spidercrabe",
							x = 4780,
							z = 2880,
							facing = 0,
						},
						{
							name = "turretlaser",
							x = 8496,
							z = 608,
							facing = 3,
						},
						{
							name = "vehheavyarty",
							x = 7400,
							z = 3979,
							facing = 1,
						},
						{
							name = "vehraid",
							x = 5053,
							z = 2812,
							facing = 3,
						},
						{
							name = "vehheavyarty",
							x = 6856,
							z = 3556,
							facing = 1,
						},
						{
							name = "vehaa",
							x = 6296,
							z = 3350,
							facing = 2,
						},
						{
							name = "turretlaser",
							x = 8704,
							z = 432,
							facing = 3,
						},
						{
							name = "jumpassault",
							x = 4495,
							z = 3192,
							facing = 0,
						},
						{
							name = "jumpcon",
							x = 7472,
							z = 1450,
							facing = 2,
						},
						{
							name = "turretlaser",
							x = 8544,
							z = 848,
							facing = 3,
						},
						{
							name = "spidercrabe",
							x = 4834,
							z = 2868,
							facing = 0,
						},
						{
							name = "jumparty",
							x = 7153,
							z = 3972,
							facing = 1,
						},
						{
							name = "spidercon",
							x = 5006,
							z = 2723,
							facing = 3,
						},
						{
							name = "jumpraid",
							x = 8506,
							z = 1859,
							facing = 1,
						},
						{
							name = "vehscout",
							x = 6711,
							z = 3649,
							facing = 1,
						},
						{
							name = "jumpraid",
							x = 5258,
							z = 2907,
							facing = 2,
						},
						{
							name = "spiderantiheavy",
							x = 6294,
							z = 3438,
							facing = 0,
						},
						{
							name = "vehassault",
							x = 6339,
							z = 3333,
							facing = 1,
						},
						{
							name = "jumparty",
							x = 8653,
							z = 885,
							facing = 2,
						},
						{
							name = "spideremp",
							x = 6523,
							z = 2231,
							facing = 3,
						},
						{
							name = "gunshipassault",
							x = 6486,
							z = 1077,
							facing = 0,
						},
						{
							name = "vehraid",
							x = 5044,
							z = 2767,
							facing = 2,
						},
						{
							name = "gunshipassault",
							x = 6716,
							z = 1049,
							facing = 0,
						},
						{
							name = "vehheavyarty",
							x = 7121,
							z = 3553,
							facing = 1,
						},
						{
							name = "vehcon",
							x = 6310,
							z = 3387,
							facing = 2,
						},
						{
							name = "jumpcon",
							x = 5160,
							z = 3100,
							facing = 1,
						},
						{
							name = "gunshipraid",
							x = 4671,
							z = 2275,
							facing = 3,
						},
						{
							name = "spiderassault",
							x = 6145,
							z = 3209,
							facing = 1,
						},
						{
							name = "spiderassault",
							x = 5400,
							z = 2826,
							facing = 1,
						},
						{
							name = "spiderassault",
							x = 4773,
							z = 2989,
							facing = 1,
						},
						{
							name = "spiderassault",
							x = 4716,
							z = 3163,
							facing = 0,
						},
						{
							name = "vehraid",
							x = 5026,
							z = 2811,
							facing = 2,
						},
						{
							name = "vehraid",
							x = 5055,
							z = 2836,
							facing = 2,
						},
						{
							name = "spidercon",
							x = 7498,
							z = 1562,
							facing = 0,
						},
						{
							name = "jumpcon",
							x = 8695,
							z = 875,
							facing = 2,
						},
						{
							name = "spiderriot",
							x = 4536,
							z = 3107,
							facing = 3,
						},
						{
							name = "vehcon",
							x = 5158,
							z = 3197,
							facing = 3,
						},
						{
							name = "vehassault",
							x = 9144,
							z = 3785,
							facing = 3,
						},
						{
							name = "gunshipassault",
							x = 6693,
							z = 1032,
							facing = 3,
						},
						{
							name = "factoryshield",
							x = 8112,
							z = 6136,
							facing = 0,
						},
						{
							name = "turretheavylaser",
							x = 7368,
							z = 6632,
							facing = 0,
						},
						{
							name = "turretheavylaser",
							x = 7848,
							z = 5864,
							facing = 0,
						},
						{
							name = "turretaafar",
							x = 7632,
							z = 6352,
							facing = 3,
						},
						{
							name = "vehraid",
							x = 5017,
							z = 2788,
							facing = 2,
						},
						{
							name = "vehraid",
							x = 9829,
							z = 2596,
							facing = 0,
						},
						{
							name = "gunshipheavyskirm",
							x = 7373,
							z = 3183,
							facing = 2,
						},
						{
							name = "spiderassault",
							x = 6484,
							z = 2216,
							facing = 2,
						},
						{
							name = "jumpraid",
							x = 8028,
							z = 1485,
							facing = 1,
						},
						{
							name = "spidercrabe",
							x = 8856,
							z = 2196,
							facing = 2,
							buildProgress = 0.74180001,
						},
						{
							name = "vehcon",
							x = 8493,
							z = 4023,
							facing = 3,
						},
						{
							name = "jumpcon",
							x = 7803,
							z = 1208,
							facing = 3,
						},
						{
							name = "turretheavylaser",
							x = 8056,
							z = 4040,
							facing = 3,
						},
						{
							name = "turretheavylaser",
							x = 8504,
							z = 4488,
							facing = 3,
						},
						{
							name = "turretheavylaser",
							x = 8472,
							z = 4984,
							facing = 3,
						},
						{
							name = "turretheavylaser",
							x = 7768,
							z = 5592,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 7408,
							z = 5632,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 7696,
							z = 5056,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 7792,
							z = 4592,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 7584,
							z = 4112,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 7424,
							z = 3680,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 9088,
							z = 3648,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 9280,
							z = 4224,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 9136,
							z = 4832,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 8880,
							z = 5424,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 8432,
							z = 5568,
							facing = 3,
						},
						{
							name = "shieldcon",
							x = 7722,
							z = 6569,
							facing = 0,
						},
						{
							name = "shieldcon",
							x = 7981,
							z = 6375,
							facing = 0,
						},
						{
							name = "shieldcon",
							x = 7877,
							z = 6481,
							facing = 0,
						},
						{
							name = "shieldcon",
							x = 7827,
							z = 6722,
							facing = 0,
						},
						{
							name = "shieldraid",
							x = 6894,
							z = 6448,
							facing = 0,
						},
						{
							name = "shieldraid",
							x = 7028,
							z = 6247,
							facing = 0,
						},
						{
							name = "shieldraid",
							x = 7120,
							z = 6346,
							facing = 0,
						},
						{
							name = "shieldraid",
							x = 7222,
							z = 6174,
							facing = 0,
						},
						{
							name = "shieldraid",
							x = 7118,
							z = 5895,
							facing = 0,
						},
						{
							name = "shieldraid",
							x = 7222,
							z = 5519,
							facing = 0,
						},
						{
							name = "shieldskirm",
							x = 7373,
							z = 6037,
							facing = 0,
						},
						{
							name = "shieldskirm",
							x = 7477,
							z = 5848,
							facing = 0,
						},
						{
							name = "shieldskirm",
							x = 7240,
							z = 6587,
							facing = 0,
						},
						{
							name = "spiderscout",
							x = 2280,
							z = 290,
							facing = 0,
						},
						{
							name = "spiderscout",
							x = 2980,
							z = 3050,
							facing = 0,
						},
						{
							name = "spiderscout",
							x = 1830,
							z = 5170,
							facing = 0,
						},
						{
							name = "turretaafar",
							x = 8624,
							z = 5852,
							facing = 3,
						},
						{
							name = "turretaafar",
							x = 7960,
							z = 2816,
							facing = 3,
						},
					}
				},
			},
			defeatConditionConfig = {
				-- Indexed by allyTeam.
				[0] = { },
				[1] = {
					ignoreUnitLossDefeat = false,
					vitalCommanders = false,
					vitalUnitTypes = {
						"staticnuke",
					},
					loseAfterSeconds = false,
					allyTeamLossObjectiveID = 1,
				},
			},
			objectiveConfig = {
				-- This is just related to displaying objectives on the UI.
				[1] = {
					description = "Destroy the Nuclear Silo",
				},
				[2] = {
					description = "Protect your Commander",
				},
			},
			bonusObjectiveConfig = {
				[1] = { -- Make twelve Reapers
					satisfyOnce = true,
					countRemovedUnits = true,
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 12, -- You start with 5.
					unitTypes = {
						"tankassault",
					},
					image = planetUtilities.ICON_DIR .. "tankassault.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.REPAIR,
					description = "Build 7 Minotaurs",
					experience = planetUtilities.BONUS_EXP,
				},
				[2] = {
					victoryByTime = 900,
					image = planetUtilities.ICON_OVERLAY.CLOCK,
					description = "Win by 15:00",
					experience = planetUtilities.BONUS_EXP,
				},
			},
		},
		completionReward = {
			experience = planetUtilities.MAIN_EXP,
			units = {
				"tankassault",
				"tankarty",
				"tankaa",
			},
			modules = {
				"commweapon_heatray",
			},
			abilities = {
			},
			codexEntries = {
				"faction_rebels"
			},
		},
	}
	
	return planetData
end

return GetPlanet
