--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Planet config

local function GetPlanet(planetUtilities, planetID)
	
	--local image = planetUtilities.planetImages[math.floor(math.random()*#planetUtilities.planetImages) + 1]
	local image = LUA_DIRNAME .. "images/planets/desert02.png"
	
	local planetData = {
		name = "Old Kam",
		startingPlanet = false,
		mapDisplay = {
			x = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][1]) or 0.53,
			y = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][2]) or 0.40,
			image = image,
			size = planetUtilities.PLANET_SIZE_MAP,
		},
		infoDisplay = {
			image = image,
			size = planetUtilities.PLANET_SIZE_INFO,
			backgroundImage = planetUtilities.backgroundImages[math.floor(math.random()*#planetUtilities.backgroundImages) + 1],
			terrainType = "Minimal",
			radius = "6570 km",
			primary = "Nataa",
			primaryType = "G1V",
			milRating = 1,
			feedbackLink = "http://zero-k.info/Forum/Thread/24566",
			text = "This was a nightmare scenario for the Empire: a rebellion on an special arsenal world. The loyalists barricaded themselves in the mountains with the stockpiles, waiting for reinforcements that never came."
			.. "\n "
			.. "\nI should crack that fortress open and raze it once and for all. There are things buried down there, that should never have been built."
			,
			extendedText = "The loyalist positions are dependent on a few critical structures, but the rough terrain will make it very difficult to get close. The Tactical Missile Silo is exactly what I need for this."
		},
		tips = {
			{
				image = "unitpics/tacnuke.png",
				text = [[The Eos tactical nuke doesn't cause a large explosion, but whatever it hits directly will take a lot of damage. It is quite expensive and should only be used against high-value stationary targets.]]
			},
			{
				image = "unitpics/empmissile.png",
				text = [[Shockley missiles deliver a massive amount of EMP damage in a small radius, and are not affected by shields. Use this to disable the most important part of your opponent's defenses just before you attack.]]
			},
			{
				image = "unitpics/napalmmissile.png",
				text = [[Inferno missiles create fire in a large radius, which inflicts damage over time. This is very useful for destroying low-HP economic buildings like Wind Generators and Caretakers, or preventing production from a Factory.]]
			},
			{
				image = "unitpics/seismic.png",
				text = [[The Quake seismic missile's main purpose is reducing terraformed walls so that other missiles can strike their targets. It can also be used to smooth other difficult terrain.]]
			},
		},
		gameConfig = {
			mapName = "Xenolithic_v1",
			playerConfig = {
				startX = 1900,
				startZ = 2400,
				allyTeam = 0,
				facplop = false,
				commanderParameters = {
					facplop = false,
					defeatIfDestroyedObjectiveID = 2,
				},
				extraUnlocks = {
					"staticmissilesilo",
					"tacnuke",
					"napalmmissile",
					"empmissile",
					"seismic",
				},
				startUnits = {
					{
						name = "staticmissilesilo",
						x = 2128,
						z = 3088,
						facing = 3,
					},
 					{
						name = "turretlaser",
						x = 1888,
						z = 2368,
						facing = 1,
					},
 					{
						name = "turretlaser",
						x = 2064,
						z = 2672,
						facing = 1,
					},
 					{
						name = "staticmex",
						x = 1672,
						z = 2968,
						facing = 3,
					},
 					{
						name = "staticmex",
						x = 1528,
						z = 2680,
						facing = 3,
					},
 					{
						name = "staticmex",
						x = 1864,
						z = 2712,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 1640,
						z = 2872,
						facing = 1,
					},
 					{
						name = "energysolar",
						x = 1640,
						z = 2712,
						facing = 1,
					},
 					{
						name = "energysolar",
						x = 1784,
						z = 2776,
						facing = 1,
					},
 					{
						name = "staticcon",
						x = 1800,
						z = 3032,
						facing = 1,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {1800, 3032}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {1825, 3057}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 1800,
						z = 3128,
						facing = 1,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {1800, 3128}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {1825, 3153}, options = {"shift"}},
						},
					},
 					{
						name = "turretheavylaser",
						x = 2216,
						z = 3208,
						facing = 1,
					},
 					{
						name = "turretriot",
						x = 2232,
						z = 2920,
						facing = 1,
					},
 					{
						name = "turretriot",
						x = 1944,
						z = 3272,
						facing = 0,
					},
 					{
						name = "turretlaser",
						x = 1680,
						z = 3344,
						facing = 0,
					},
				}
			},
			aiConfig = {
				{
					humanName = "Sorrali",
					aiLib = "Circuit_difficulty_autofill_ally",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					commanderParameters = {
						facplop = false,
					},
					allyTeam = 0,
					unlocks = {
						"staticcon",
						"staticmex",
						"staticradar",
						"staticantinuke",
						"energysolar",
						"energywind",
						"energypylon",
						"turretlaser",
						"turretmissile",
						"factoryspider",
						"spidercon",
						"spiderscout",
						"spideremp",
						"spiderassault",
						"spiderskirm",
						"spiderriot",
						"spidercrabe",
						"factoryplane",
						"planescout",
						"bomberdisarm",
						"factoryshield",
						"shieldcon",
						"shieldraid",
						"shieldriot",
						"shieldassault",
						"shieldskirm",
						"shieldfelon",
						"shieldshield",
						"shieldarty",
					},
					commander = false,
					startUnits = {
						{
							name = "turretriot",
							x = 2296,
							z = 6552,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 320,
							z = 1792,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 960,
							z = 1600,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 1704,
							z = 4360,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2008,
							z = 4216,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1736,
							z = 4024,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1704,
							z = 5432,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 1592,
							z = 5704,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 1944,
							z = 5672,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 632,
							z = 2248,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 456,
							z = 5944,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 280,
							z = 6216,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 472,
							z = 1896,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 712,
							z = 6216,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 248,
							z = 2136,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 904,
							z = 920,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 1928,
							z = 792,
							facing = 3,
						},
 						{
							name = "energyfusion",
							x = 32,
							z = 4360,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 32,
							z = 4280,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 32,
							z = 4200,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 360,
							z = 7480,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 1592,
							z = 8088,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 592,
							z = 2384,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 1432,
							z = 6648,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 3000,
							z = 4536,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 2456,
							z = 7544,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 3080,
							z = 3272,
							facing = 3,
						},
 						{
							name = "factoryplane",
							x = 56,
							z = 3664,
							facing = 1,
						},
						{
							name = "planescout",
							x = 200,
							z = 3664,
							facing = 1,
						},
						{
							name = "planescout",
							x = 200,
							z = 200,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1856,
							z = 5424,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 32,
							z = 3096,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 312,
							z = 2488,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 32,
							z = 3016,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 32,
							z = 2936,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 680,
							z = 1608,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 1992,
							z = 808,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 288,
							z = 6368,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 1912,
							z = 856,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 1864,
							z = 776,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 1944,
							z = 728,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 1368,
							z = 904,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 280,
							z = 3672,
							facing = 1,
						},
 						{
							name = "staticrearm",
							x = 72,
							z = 3464,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 200,
							z = 4968,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 24,
							z = 3800,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 552,
							z = 5864,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 1224,
							z = 2536,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 1480,
							z = 5576,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 1192,
							z = 3512,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 1560,
							z = 4360,
							facing = 1,
						},
 						{
							name = "staticheavyradar",
							x = 1552,
							z = 6416,
							facing = 1,
						},
 						{
							name = "staticheavyradar",
							x = 1744,
							z = 1568,
							facing = 1,
						},
 						{
							name = "factoryspider",
							x = 872,
							z = 1880,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 744,
							z = 1848,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 744,
							z = 1928,
							facing = 1,
						},
 						{
							name = "factoryshield",
							x = 1448,
							z = 4144,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1288,
							z = 4104,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1288,
							z = 4200,
							facing = 1,
						},
 						{
							name = "factoryspider",
							x = 824,
							z = 5960,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 712,
							z = 5928,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 712,
							z = 5992,
							facing = 1,
						},
 						{
							name = "staticstorage",
							x = 24,
							z = 3912,
							facing = 3,
						},
 						{
							name = "staticstorage",
							x = 24,
							z = 3976,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 112,
							z = 4128,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 112,
							z = 4432,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 2904,
							z = 3224,
							facing = 1,
						},
 						{
							name = "turretaaclose",
							x = 2760,
							z = 3336,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 2864,
							z = 3472,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 2896,
							z = 3344,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 96,
							z = 3168,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 2480,
							z = 2240,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 96,
							z = 2880,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 2448,
							z = 2112,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 1992,
							z = 1000,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 2016,
							z = 1136,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 2000,
							z = 592,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1232,
							z = 4016,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1472,
							z = 4336,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1952,
							z = 4448,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 2824,
							z = 4552,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 2616,
							z = 7496,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 2976,
							z = 4640,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 2640,
							z = 7392,
							facing = 1,
						},
 						{
							name = "turretgauss",
							x = 2952,
							z = 4456,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 2496,
							z = 7680,
							facing = 1,
						},
 						{
							name = "turretaaclose",
							x = 2376,
							z = 7448,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 2424,
							z = 7288,
							facing = 2,
						},
 						{
							name = "turretemp",
							x = 3168,
							z = 6000,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 3128,
							z = 5784,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 3056,
							z = 6048,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 880,
							z = 6224,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1760,
							z = 5824,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 496,
							z = 5744,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 3064,
							z = 3576,
							facing = 1,
							buildProgress = 0.33329999,
						},
 						{
							name = "shieldcon",
							x = 3144,
							z = 3653,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 2104,
							z = 632,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 2462,
							z = 6503,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 664,
							z = 5976,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 3360,
							z = 5680,
							facing = 2,
						},
 						{
							name = "spidercon",
							x = 2391,
							z = 7965,
							facing = 1,
						},
 						{
							name = "shieldcon",
							x = 2548,
							z = 2309,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 2608,
							z = 2295,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 1528,
							z = 3032,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 2416,
							z = 448,
							facing = 0,
							buildProgress = 0.403,
						},
 						{
							name = "turretlaser",
							x = 1824,
							z = 4240,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1728,
							z = 5600,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 976,
							z = 976,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 2232,
							z = 4328,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 1664,
							z = 5392,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1776,
							z = 2864,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 368,
							z = 2224,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1032,
							z = 7640,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 1472,
							z = 6736,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 1136,
							z = 848,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 1696,
							z = 3040,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 440,
							z = 6680,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 1512,
							z = 5016,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 3096,
							z = 3736,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 2055,
							z = 7017,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 1528,
							z = 4888,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 1256,
							z = 7640,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 664,
							z = 5928,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 544,
							z = 6032,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 3436,
							z = 5486,
							facing = 2,
						},
 						{
							name = "spiderassault",
							x = 2491,
							z = 2579,
							facing = 1,
							patrolRoute = {
								{2477, 2544},
								{2517, 2595},
							},
						},
 						{
							name = "spidercon",
							x = 2919,
							z = 3268,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 1432,
							z = 6408,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 3319,
							z = 3196,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 456,
							z = 6552,
							facing = 1,
						},
 						{
							name = "spiderassault",
							x = 4194,
							z = 4708,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 368,
							z = 7296,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1632,
							z = 8048,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 3000,
							z = 4296,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 2841,
							z = 706,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 256,
							z = 7488,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1816,
							z = 2648,
							facing = 1,
						},
 						{
							name = "spideremp",
							x = 3696,
							z = 4330,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 3152,
							z = 4432,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1064,
							z = 6088,
							facing = 1,
						},
 						{
							name = "spiderscout",
							x = 1859,
							z = 4287,
							facing = 2,
						},
 						{
							name = "shieldskirm",
							x = 3665,
							z = 5217,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 1096,
							z = 6184,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 2552,
							z = 2216,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 2960,
							z = 4528,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 2072,
							z = 6824,
							facing = 2,
							buildProgress = 0.2899,
						},
 						{
							name = "energywind",
							x = 1064,
							z = 5976,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 3200,
							z = 5536,
							facing = 2,
						},
 						{
							name = "spiderskirm",
							x = 860,
							z = 5960,
							facing = 1,
							buildProgress = 0.53210002,
						},
 						{
							name = "spiderskirm",
							x = 3130,
							z = 4361,
							facing = 0,
							patrolRoute = {
								{3167, 4380},
								{3048, 4616},
							},
						},
 						{
							name = "turretmissile",
							x = 3408,
							z = 5456,
							facing = 2,
						},
 						{
							name = "shieldassault",
							x = 3758,
							z = 4289,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 3480,
							z = 5608,
							facing = 2,
						},
 						{
							name = "shieldarty",
							x = 1877,
							z = 4437,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 2904,
							z = 2184,
							facing = 0,
						},
 						{
							name = "shieldassault",
							x = 3728,
							z = 5311,
							facing = 2,
						},
 						{
							name = "shieldassault",
							x = 1953,
							z = 4152,
							facing = 1,
						},
 						{
							name = "spiderassault",
							x = 2441,
							z = 2579,
							facing = 1,
							patrolRoute = {
								{2434, 2597},
								{2475, 2547},
							},
						},
 						{
							name = "shieldassault",
							x = 3552,
							z = 4429,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 3384,
							z = 5944,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 3568,
							z = 5600,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 2120,
							z = 4328,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 3008,
							z = 5616,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 360,
							z = 7240,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 760,
							z = 7592,
							facing = 2,
						},
 						{
							name = "spiderassault",
							x = 2503,
							z = 2504,
							facing = 0,
							patrolRoute = {
								{2454, 2487},
								{2475, 2547},
							},
						},
 						{
							name = "turretlaser",
							x = 2048,
							z = 4256,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 2728,
							z = 7240,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 472,
							z = 6408,
							facing = 1,
						},
 						{
							name = "shieldarty",
							x = 3656,
							z = 4485,
							facing = 0,
						},
 						{
							name = "spideremp",
							x = 3594,
							z = 3806,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 2424,
							z = 4328,
							facing = 1,
						},
 						{
							name = "shieldassault",
							x = 3728,
							z = 5395,
							facing = 2,
						},
 						{
							name = "shieldcon",
							x = 2314,
							z = 746,
							facing = 0,
						},
 						{
							name = "shieldfelon",
							x = 2446,
							z = 4128,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 1978,
							z = 6458,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 1000,
							z = 7736,
							facing = 2,
						},
 						{
							name = "shieldcon",
							x = 3161,
							z = 2150,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 2955,
							z = 3228,
							facing = 0,
						},
 						{
							name = "spiderskirm",
							x = 3655,
							z = 5283,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 3320,
							z = 8024,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 1941,
							z = 6669,
							facing = 0,
						},
 						{
							name = "shieldassault",
							x = 3678,
							z = 5368,
							facing = 2,
						},
 						{
							name = "spidercon",
							x = 1945,
							z = 1474,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 2136,
							z = 7448,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 1592,
							z = 7848,
							facing = 2,
						},
 						{
							name = "shieldassault",
							x = 3791,
							z = 4235,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 3248,
							z = 8016,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 3240,
							z = 4984,
							facing = 2,
						},
 						{
							name = "spidercon",
							x = 3127,
							z = 4399,
							facing = 1,
						},
 						{
							name = "spiderassault",
							x = 1573,
							z = 5338,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 2120,
							z = 2536,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 2088,
							z = 7576,
							facing = 2,
						},
 						{
							name = "spiderscout",
							x = 1094,
							z = 2711,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 872,
							z = 7672,
							facing = 2,
							buildProgress = 0.4285,
						},
 						{
							name = "energypylon",
							x = 3304,
							z = 7800,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 1176,
							z = 7592,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 3000,
							z = 6920,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 1048,
							z = 7432,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 1256,
							z = 7560,
							facing = 2,
						},
 						{
							name = "spiderskirm",
							x = 3723,
							z = 5104,
							facing = 2,
						},
 						{
							name = "spiderassault",
							x = 3695,
							z = 5265,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 928,
							z = 768,
							facing = 0,
						},
 						{
							name = "shieldraid",
							x = 3577,
							z = 2824,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 3224,
							z = 2936,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 648,
							z = 6024,
							facing = 1,
							buildProgress = 0.98180002,
						},
 						{
							name = "spiderskirm",
							x = 3735,
							z = 4995,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 792,
							z = 7672,
							facing = 2,
						},
 						{
							name = "spiderassault",
							x = 2462,
							z = 2507,
							facing = 2,
							patrolRoute = {
								{2475, 2547},
								{2473, 2483},
							},
						},
 						{
							name = "turretlaser",
							x = 3536,
							z = 5808,
							facing = 2,
						},
 						{
							name = "spiderassault",
							x = 2875,
							z = 5319,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 757,
							z = 7511,
							facing = 0,
						},
 						{
							name = "spiderscout",
							x = 4432,
							z = 2373,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 3192,
							z = 4824,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 2600,
							z = 312,
							facing = 0,
						},
 						{
							name = "spiderassault",
							x = 2795,
							z = 5400,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 512,
							z = 7440,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 3424,
							z = 5984,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 1520,
							z = 5552,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 2864,
							z = 3024,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 3152,
							z = 3312,
							facing = 1,
						},
 						{
							name = "shieldassault",
							x = 3907,
							z = 4012,
							facing = 3,
						},
 						{
							name = "shieldfelon",
							x = 1460,
							z = 4144,
							facing = 1,
							buildProgress = 0.3204,
						},
 						{
							name = "spiderscout",
							x = 5190,
							z = 1299,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1600,
							z = 2640,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 3816,
							z = 2696,
							facing = 0,
							buildProgress = 0.1355,
						},
 						{
							name = "shieldassault",
							x = 2435,
							z = 2537,
							facing = 1,
						},
 						{
							name = "spiderscout",
							x = 5060,
							z = 1403,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 3288,
							z = 5112,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 384,
							z = 2016,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 3072,
							z = 3520,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 2373,
							z = 1416,
							facing = 1,
						},
 						{
							name = "spiderscout",
							x = 2979,
							z = 2661,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 2592,
							z = 352,
							facing = 0,
						},
 						{
							name = "spiderscout",
							x = 4255,
							z = 3295,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 2152,
							z = 7368,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 1648,
							z = 6624,
							facing = 2,
						},
 						{
							name = "spidercon",
							x = 636,
							z = 6147,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 3072,
							z = 3104,
							facing = 1,
						},
 						{
							name = "spiderscout",
							x = 4344,
							z = 2138,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 3448,
							z = 2968,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 2784,
							z = 4320,
							facing = 1,
						},
 						{
							name = "spiderscout",
							x = 4014,
							z = 2017,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1840,
							z = 8064,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 448,
							z = 6224,
							facing = 1,
						},
 						{
							name = "shieldassault",
							x = 2235,
							z = 4129,
							facing = 1,
						},
 						{
							name = "spiderskirm",
							x = 1415,
							z = 1949,
							facing = 1,
						},
 						{
							name = "spiderskirm",
							x = 908,
							z = 1880,
							facing = 1,
							buildProgress = 0.59399998,
						},
 						{
							name = "turretmissile",
							x = 3552,
							z = 5312,
							facing = 2,
							buildProgress = 0.3299,
						},
 						{
							name = "staticcon",
							x = 3032,
							z = 3416,
							facing = 1,
							buildProgress = 0.0772,
						},
					}
				},
				{
					startX = 7000,
					startZ = 4000,
					humanName = "Krake East",
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					commanderParameters = {
						facplop = false,
					},
					allyTeam = 1,
					unlocks = {
						"staticcon",
						"staticmex",
						"staticradar",
						"staticantinuke",
						"energysolar",
						"energywind",
						"energypylon",
						"turretlaser",
						"turretmissile",
						"factoryspider",
						"spidercon",
						"spiderscout",
						"spideremp",
						"spiderassault",
						"spiderskirm",
						"spiderriot",
						"factorycloak",
						"cloakcon",
						"cloakraid",
						"cloakriot",
						"cloakskirm",
						"cloakassault",
						"cloakarty",
					},
					difficultyDependantUnlocks = {
						[2] = {"spidercrabe"},
						[3] = {"spidercrabe","spiderantiheavy"},
						[3] = {"striderhub","striderfunnelweb","spidercrabe","spiderantiheavy","staticantinuke",},
					},
					commanderLevel = 5,
					commander = {
						name = "Janii Lass",
						chassis = "guardian",
						modules = {
							"commweapon_slamrocket",
							"commweapon_heavymachinegun",
							"module_autorepair",
							"module_autorepair",
							"module_heavy_armor",
							"module_heavy_armor",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_nano",
							"module_adv_nano",
						}
					},
					startUnits = {
						{
							name = "staticarty",
							x = 4056,
							z = 1112,
							facing = 3,
						},
						{
							name = "staticarty",
							x = 5208,
							z = 4552,
							facing = 3,
						},
						{
							name = "staticarty",
							x = 4584,
							z = 7672,
							facing = 2,
						},
						{
							name = "staticarty",
							x = 6220,
							z = 5412,
							facing = 3,
							terraformHeight = 320,
						},
						{
							name = "staticarty",
							x = 6150,
							z = 3780,
							facing = 3,
							terraformHeight = 320,
						},
						{
							name = "staticarty",
							x = 6400,
							z = 2200,
							facing = 3,
							terraformHeight = 320,
						},
						{
							name = "staticantinuke",
							x = 7628,
							z = 4400,
							facing = 3,
						},
						{
							name = "staticshield",
							x = 6320,
							z = 5412,
							facing = 3,
						},
						{
							name = "staticshield",
							x = 6250,
							z = 3780,
							facing = 3,
						},
						{
							name = "staticshield",
							x = 6500,
							z = 2200,
							facing = 3,
						},
						{
							name = "turretantiheavy",
							x = 7250,
							z = 3320,
							facing = 3,
						},
						{
							name = "turretantiheavy",
							x = 6350,
							z = 4500,
							facing = 3,
						},
						{
							name = "turretantiheavy",
							x = 6240,
							z = 2600,
							facing = 3,
						},
						{
							name = "striderhub",
							x = 7792,
							z = 4000,
							facing = 3,
							difficultyAtLeast = 4,
						},
 						{
							name = "factoryspider",
							x = 7112,
							z = 4040,
							facing = 3,
						},
 						
 						{
							name = "staticcon",
							x = 7240,
							z = 4008,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7240,
							z = 4088,
							facing = 3,
						},
 						
 						{
							name = "staticshield",
							x = 5392,
							z = 4656,
							facing = 3,
						},
 						
 						{
							name = "energysingu",
							x = 7560,
							z = 3208,
							facing = 2,
						},
 						{
							name = "energysingu",
							x = 7560,
							z = 3512,
							facing = 2,
						},
 						{
							name = "turretantiheavy",
							x = 4736,
							z = 6080,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7800,
							z = 5832,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7800, 5832}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7638, 5784}, options = {"shift"}},
							},
						},
 						{
							name = "energypylon",
							x = 6968,
							z = 3320,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 7624,
							z = 2184,
							facing = 0,
						},
 						{
							name = "turretantiheavy",
							x = 5136,
							z = 2720,
							facing = 3,
						},
 						{
							name = "factorycloak",
							x = 7648,
							z = 5784,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 7768,
							z = 1864,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6904,
							z = 5496,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 8024,
							z = 2152,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 7944,
							z = 2904,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6552,
							z = 5560,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6312,
							z = 2920,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 7768,
							z = 6456,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 7832,
							z = 6104,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7800,
							z = 5736,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 8056,
							z = 6408,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6680,
							z = 4232,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 6008,
							z = 3176,
							facing = 3,
						},
 						{
							name = "staticshield",
							x = 4784,
							z = 7792,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 5544,
							z = 2504,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6552,
							z = 2632,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6824,
							z = 3032,
							facing = 3,
						},
 						{
							name = "cloakarty",
							x = 7339,
							z = 1967,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6408,
							z = 4008,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 4568,
							z = 1144,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 5784,
							z = 3976,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6328,
							z = 4360,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 5640,
							z = 5384,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 7496,
							z = 4120,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 6584,
							z = 4360,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 5240,
							z = 6248,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 6296,
							z = 1880,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 5512,
							z = 7016,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 6488,
							z = 5224,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 7128,
							z = 1640,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 5048,
							z = 7736,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 7816,
							z = 2152,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6632,
							z = 5256,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 5688,
							z = 4712,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 7384,
							z = 5048,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 7688,
							z = 5992,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 4016,
							z = 1280,
							facing = 0,
						},
 						{
							name = "turretemp",
							x = 3888,
							z = 1040,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 4136,
							z = 1032,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 4000,
							z = 864,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 5104,
							z = 4736,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 4544,
							z = 7824,
							facing = 3,
						},
 						{
							name = "staticheavyradar",
							x = 6736,
							z = 4640,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 4168,
							z = 1272,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 3904,
							z = 896,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 4448,
							z = 960,
							facing = 1,
						},
 						{
							name = "turretaaflak",
							x = 4312,
							z = 1048,
							facing = 3,
						},
 						{
							name = "turretaaflak",
							x = 4184,
							z = 888,
							facing = 3,
						},
 						{
							name = "turretgauss",
							x = 4712,
							z = 4120,
							facing = 3,
						},
 						{
							name = "cloakarty",
							x = 7418,
							z = 5791,
							facing = 3,
						},
 						{
							name = "turretaaflak",
							x = 5240,
							z = 4776,
							facing = 3,
						},
 						{
							name = "turretaaflak",
							x = 5368,
							z = 4312,
							facing = 3,
						},
 						{
							name = "turretgauss",
							x = 5208,
							z = 4200,
							facing = 3,
						},
 						{
							name = "turretgauss",
							x = 4936,
							z = 4920,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 5368,
							z = 4744,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 5352,
							z = 4520,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 5056,
							z = 2544,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 5008,
							z = 2896,
							facing = 3,
						},
 						{
							name = "turretaalaser",
							x = 5320,
							z = 2600,
							facing = 3,
						},
 						{
							name = "turretaalaser",
							x = 5288,
							z = 2952,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 4352,
							z = 7680,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 4768,
							z = 7520,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 4488,
							z = 7544,
							facing = 2,
						},
 						{
							name = "turretriot",
							x = 4584,
							z = 8040,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 5016,
							z = 7560,
							facing = 2,
						},
 						{
							name = "turretaaflak",
							x = 4696,
							z = 7912,
							facing = 2,
						},
 						{
							name = "turretaaflak",
							x = 4888,
							z = 7720,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 4624,
							z = 6240,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 4704,
							z = 5872,
							facing = 3,
						},
 						{
							name = "turretaalaser",
							x = 4808,
							z = 6312,
							facing = 3,
						},
 						{
							name = "turretaalaser",
							x = 4904,
							z = 5976,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 4776,
							z = 7992,
							facing = 3,
						},
 						{
							name = "factorycloak",
							x = 7488,
							z = 1928,
							facing = 3,
						},
 						{
							name = "turretaafar",
							x = 6000,
							z = 896,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 5696,
							z = 896,
							facing = 3,
						},
 						{
							name = "turretaafar",
							x = 6992,
							z = 4288,
							facing = 3,
						},
 						{
							name = "turretaafar",
							x = 6096,
							z = 7488,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 7544,
							z = 3336,
							facing = 3,
						},
 						{
							name = "turretheavy",
							x = 7288,
							z = 2952,
							facing = 3,
						},
 						{
							name = "turretheavy",
							x = 7288,
							z = 3656,
							facing = 3,
						},
 						{
							name = "turretheavy",
							x = 7800,
							z = 2952,
							facing = 1,
						},
 						{
							name = "turretheavy",
							x = 7800,
							z = 3656,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 7640,
							z = 1880,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7640, 1880}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7478, 1928}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 7640,
							z = 1960,
							facing = 3,
						},
 						{
							name = "dynassault4_00",
							x = 5511,
							z = 4036,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 5448,
							z = 4184,
							facing = 0,
						},
 						{
							name = "cloakraid",
							x = 4783,
							z = 3911,
							facing = 3,
						},
 						{
							name = "cloakarty",
							x = 6904,
							z = 5856,
							facing = 3,
						},
 						{
							name = "cloakcon",
							x = 6337,
							z = 579,
							facing = 3,
						},
 						{
							name = "cloakraid",
							x = 4888,
							z = 3864,
							facing = 3,
						},
 						{
							name = "cloakcon",
							x = 6778,
							z = 6481,
							facing = 0,
						},
 						{
							name = "spiderskirm",
							x = 4477,
							z = 5118,
							facing = 0,
						},
 						{
							name = "cloakcon",
							x = 4827,
							z = 2670,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 6744,
							z = 4232,
							facing = 3,
						},
 						{
							name = "cloakskirm",
							x = 4189,
							z = 5152,
							facing = 3,
						},
 						{
							name = "cloakcon",
							x = 5789,
							z = 1216,
							facing = 0,
						},
 						{
							name = "cloakcon",
							x = 5928,
							z = 7045,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 6560,
							z = 4128,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 7259,
							z = 2632,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 7776,
							z = 2144,
							facing = 3,
						},
 						{
							name = "cloakarty",
							x = 4891,
							z = 3218,
							facing = 3,
						},
 						{
							name = "cloakcon",
							x = 6390,
							z = 1316,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 7744,
							z = 1952,
							facing = 3,
						},
 						{
							name = "cloakskirm",
							x = 4335,
							z = 5121,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 6800,
							z = 5440,
							facing = 3,
						},
 						{
							name = "cloakassault",
							x = 4710,
							z = 2400,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 7219,
							z = 2615,
							facing = 2,
						},
 						{
							name = "cloakcon",
							x = 6660,
							z = 6621,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 7760,
							z = 4208,
							facing = 3,
						},
 						{
							name = "spiderassault",
							x = 4964,
							z = 4137,
							facing = 0,
							patrolRoute = {
								{4962, 4100},
								{4944, 4162},
							},
						},
 						{
							name = "cloakassault",
							x = 4874,
							z = 5300,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 6704,
							z = 5216,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 7952,
							z = 6272,
							facing = 3,
						},
 						{
							name = "cloakskirm",
							x = 4629,
							z = 2406,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 6704,
							z = 1712,
							facing = 3,
						},
 						{
							name = "spiderskirm",
							x = 4991,
							z = 4060,
							facing = 1,
							patrolRoute = {
								{4966, 4101},
								{5023, 4082},
							},
						},
 						{
							name = "cloakcon",
							x = 5917,
							z = 1133,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 6512,
							z = 2800,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 6608,
							z = 2976,
							facing = 3,
						},
 						{
							name = "cloakcon",
							x = 4832,
							z = 6241,
							facing = 1,
						},
 						{
							name = "spiderskirm",
							x = 4989,
							z = 4103,
							facing = 3,
							patrolRoute = {
								{4920, 4051},
								{4962, 4100},
							},
						},
 						{
							name = "cloakskirm",
							x = 4659,
							z = 2403,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 7704,
							z = 392,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 6832,
							z = 6544,
							facing = 3,
						},
 						{
							name = "cloakskirm",
							x = 4688,
							z = 5083,
							facing = 2,
						},
 						{
							name = "cloakcon",
							x = 5729,
							z = 1761,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 6584,
							z = 2904,
							facing = 3,
						},
 						{
							name = "cloakcon",
							x = 6752,
							z = 6520,
							facing = 0,
						},
 						{
							name = "cloakskirm",
							x = 5458,
							z = 2247,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 5408,
							z = 4096,
							facing = 3,
						},
 						{
							name = "spiderskirm",
							x = 5239,
							z = 4010,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4962, 4100}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4898, 4095}, options = {"shift"}},
							},
						},
 						{
							name = "energysolar",
							x = 6968,
							z = 5528,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6712,
							z = 1656,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 7744,
							z = 288,
							facing = 0,
						},
 						{
							name = "cloakskirm",
							x = 6242,
							z = 6495,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6792,
							z = 6664,
							facing = 0,
						},
 						{
							name = "cloakskirm",
							x = 5440,
							z = 2229,
							facing = 0,
						},
 						{
							name = "cloakarty",
							x = 5862,
							z = 5792,
							facing = 3,
						},
 						{
							name = "spiderassault",
							x = 5301,
							z = 3920,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4962, 4100}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4982, 4161}, options = {"shift"}},
							},
						},
 						{
							name = "staticmex",
							x = 6760,
							z = 392,
							facing = 0,
						},
 						{
							name = "cloakarty",
							x = 6018,
							z = 2017,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 7128,
							z = 5624,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 5816,
							z = 1096,
							facing = 0,
						},
 						{
							name = "cloakskirm",
							x = 5956,
							z = 2316,
							facing = 3,
						},
 						{
							name = "cloakskirm",
							x = 6295,
							z = 6456,
							facing = 3,
						},
 						{
							name = "spiderassault",
							x = 5683,
							z = 3904,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4962, 4100}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4928, 4155}, options = {"shift"}},
							},
						},
 						{
							name = "staticmex",
							x = 5848,
							z = 6312,
							facing = 0,
						},
 						{
							name = "cloakskirm",
							x = 6071,
							z = 2248,
							facing = 3,
						},
 						{
							name = "cloakarty",
							x = 6491,
							z = 5792,
							facing = 3,
						},
 						{
							name = "cloakcon",
							x = 6356,
							z = 1852,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 6434,
							z = 5029,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 7240,
							z = 5704,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 6776,
							z = 3832,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 6768,
							z = 480,
							facing = 0,
						},
 						{
							name = "cloakskirm",
							x = 6495,
							z = 2076,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 4936,
							z = 2648,
							facing = 0,
						},
 						{
							name = "spiderskirm",
							x = 6603,
							z = 4129,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 5648,
							z = 1104,
							facing = 0,
						},
 						{
							name = "cloakraid",
							x = 6342,
							z = 1973,
							facing = 3,
						},
 						{
							name = "cloakraid",
							x = 5910,
							z = 5606,
							facing = 2,
						},
 						{
							name = "cloakarty",
							x = 7078,
							z = 2113,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 6744,
							z = 6664,
							facing = 3,
							buildProgress = 0.39489999,
						},
 						{
							name = "cloakarty",
							x = 7225,
							z = 5855,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 5840,
							z = 1056,
							facing = 0,
						},
 						{
							name = "spiderassault",
							x = 6890,
							z = 4081,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 5928,
							z = 7144,
							facing = 0,
							buildProgress = 0.3222,
						},
 						{
							name = "cloakraid",
							x = 7425,
							z = 5577,
							facing = 2,
						},
 						{
							name = "spiderskirm",
							x = 7076,
							z = 4040,
							facing = 3,
							buildProgress = 0.32260001,
						},
 						{
							name = "staticmex",
							x = 4936,
							z = 6248,
							facing = 0,
							buildProgress = 0.15109999,
						},
 						{
							name = "cloakriot",
							x = 7638,
							z = 5784,
							facing = 3,
							buildProgress = 0.27419999,
						},
 						{
							name = "cloakassault",
							x = 7478,
							z = 1928,
							facing = 3,
							buildProgress = 0.1199,
						},
 						{
							name = "energysolar",
							x = 7336,
							z = 2440,
							facing = 3,
							buildProgress = 0.1464,
						},
					}
				},
			},
			terraform = {
				{
					terraformShape = planetUtilities.TERRAFORM_SHAPE.RECTANGLE,
					terraformType = planetUtilities.TERRAFORM_TYPE.LEVEL,
					position = {7392, 3008, 7424, 3616},
					height = 450,
				},
				{
					terraformShape = planetUtilities.TERRAFORM_SHAPE.RECTANGLE,
					terraformType = planetUtilities.TERRAFORM_TYPE.LEVEL,
					position = {7392, 3008, 7680, 3040},
					height = 450,
				},
				{
					terraformShape = planetUtilities.TERRAFORM_SHAPE.RECTANGLE,
					terraformType = planetUtilities.TERRAFORM_TYPE.LEVEL,
					position = {7392, 3584, 7680, 3616},
					height = 450,
				},
				{
					terraformShape = planetUtilities.TERRAFORM_SHAPE.RECTANGLE,
					terraformType = planetUtilities.TERRAFORM_TYPE.LEVEL,
					position = {7680, 3008, 7712, 3616},
					height = 450,
				},
			},
			defeatConditionConfig = {
				-- Indexed by allyTeam.
				[0] = { },
				[1] = {
					ignoreUnitLossDefeat = false,
					vitalCommanders = false,
					vitalUnitTypes = {
						"staticarty",
						"energysingu",
					},
					loseAfterSeconds = false,
					allyTeamLossObjectiveID = 1,
				},
			},
			objectiveConfig = {
				-- This is just related to displaying objectives on the UI.
				[1] = {
					description = "Destroy all Cerberus artillery batteries and Singularity Reactors",
				},
				[2] = {
					description = "Protect your Commander",
				},
			},
			bonusObjectiveConfig = {
				[1] = { -- Build another silo
					satisfyOnce = true,
					countRemovedUnits = true, -- count units that previously died.
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 2,
					unitTypes = {
						"staticmissilesilo",
					},
					image = planetUtilities.ICON_DIR .. "staticmissilesilo.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.REPAIR,
					description = "Build a second Missile Silo",
					experience = planetUtilities.BONUS_EXP,
				},
				[2] = { -- Make the enemy lose two Lucifers by 8:00
					onlyCountRemovedUnits = true,
					satisfyByTime = 300,
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 2,
					enemyUnitTypes = {
						"turretantiheavy",
					},
					image = planetUtilities.ICON_DIR .. "turretantiheavy.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.ATTACK,
					description = "Destroy two Lucifer turrets by 5:00",
					experience = planetUtilities.BONUS_EXP,
				},
				[3] = { -- Win by 12:30
					victoryByTime = 750,
					image = planetUtilities.ICON_OVERLAY.CLOCK,
					description = "Win by 12:30",
					experience = planetUtilities.BONUS_EXP,
				},
			}
		},
		completionReward = {
			experience = planetUtilities.MAIN_EXP,
			units = {
				"staticmissilesilo",
				"tacnuke",
				"napalmmissile",
				"empmissile",
			},
			modules = {
				"commweapon_slamrocket",
			},
			abilities = {
			},
			codexEntries = {
				"faction_rebels"
			},
		},
	}
	
	return planetData
end

return GetPlanet
