--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Planet config

local function GetPlanet(planetUtilities, planetID)
	
	local image = LUA_DIRNAME .. "images/planets/barren03.png"
	
	local planetData = {
		name = "Intrepid",
		startingPlanet = false,
		mapDisplay = {
			x = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][1]) or 0.835,
			y = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][2]) or 0.32,
			image = image,
			size = planetUtilities.PLANET_SIZE_MAP,
		},
		infoDisplay = {
			image = image,
			size = planetUtilities.PLANET_SIZE_INFO,
			backgroundImage = planetUtilities.backgroundImages[math.floor(math.random()*#planetUtilities.backgroundImages) + 1],
			terrainType = "Barren",
			radius = "6900 km",
			primary = "Vallaf",
			primaryType = "G4V",
			milRating = 1,
			feedbackLink = "http://zero-k.info/Forum/Thread/24642",
			text = "Planet Intrepid, crown jewel of the Empire, garden of the East - this dead, barren world?"
			.. "\n "
			.. "\nI can see it now. Left unsupervised, maintenance failed, gardens dried and the entire ecosystem fell into a death spiral."
			.. "\n "
			.. "\nLeaving nothing but grey sand, haunted by decaying armies and fading memories."
			,
			extendedText = "This battle takes place on what was once a shallow lake, renowed across the entire galaxy for its splendor."
			.. "\n "
			.. "\nI remember seeing it as a child. Poets of all worlds tried to capture its beauty, but I doubt any could have succeeded."
			.. "\n "
			.. "\nAll that is left is now a massive salt plain, littered with odd, towering spikes."
			.. "\n "
			.. "\nUsed well, Paladin striders will dominate all aspects of the fight. Armies should never have come to this place. I shall make sure none will ever again."
		},
		tips = {
			{
				image = "unitpics/striderbantha.png",
				text = [[The Paladin strider wields a massive laser beam, manual-fire EMP missiles (press D to fire), and Lightning Gun sidearms. Paladins are expensive but effective against almost any opposition.]]
			},
			{
				image = "unitpics/striderdante.png",
				text = [[You can expect to face many enemy Striders from here on out. The Paladin's Tachyon Accelerator is very effective against most Striders - keep it away from Ultimatums and multiple Scorpions, though.]]
			},
		},
		gameConfig = {
			mapName = "Valiant_Saltscape",
			playerConfig = {
				startX = 8300,
				startZ = 2900,
				allyTeam = 0,
				commanderParameters = {
					facplop = true,
					defeatIfDestroyedObjectiveID = 2,
				},
				extraUnlocks = {
					"striderhub",
					"striderbantha",
				},
				startUnits = {
 					{
						name = "staticmex",
						x = 8312,
						z = 2808,
						facing = 0,
					},
 					{
						name = "energyheavygeo",
						x = 8552,
						z = 2376,
						facing = 3,
					},
 					{
						name = "staticmex",
						x = 8264,
						z = 3384,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 7608,
						z = 3944,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 7112,
						z = 3752,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 7224,
						z = 3224,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 7160,
						z = 2632,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 7640,
						z = 2280,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 8072,
						z = 1800,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 8680,
						z = 1768,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 9032,
						z = 2328,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 9080,
						z = 2728,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 9288,
						z = 3448,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 7992,
						z = 4712,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 6568,
						z = 3992,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 6200,
						z = 3208,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 6712,
						z = 2184,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 7224,
						z = 1576,
						facing = 0,
					},
 					{
						name = "energygeo",
						x = 7336,
						z = 4568,
						facing = 3,
					},
 					{
						name = "energyheavygeo",
						x = 8424,
						z = 4392,
						facing = 3,
					},
 					{
						name = "energypylon",
						x = 7560,
						z = 5048,
						facing = 3,
					},
 					{
						name = "energypylon",
						x = 6936,
						z = 4888,
						facing = 3,
					},
 					{
						name = "energypylon",
						x = 6456,
						z = 4488,
						facing = 3,
					},
 					{
						name = "energypylon",
						x = 7144,
						z = 4088,
						facing = 3,
					},
 					{
						name = "energypylon",
						x = 7800,
						z = 4296,
						facing = 3,
					},
 					{
						name = "energypylon",
						x = 8168,
						z = 3592,
						facing = 3,
					},
 					{
						name = "energypylon",
						x = 7288,
						z = 3320,
						facing = 3,
					},
 					{
						name = "energypylon",
						x = 6680,
						z = 3272,
						facing = 3,
					},
 					{
						name = "energypylon",
						x = 6696,
						z = 2504,
						facing = 3,
					},
 					{
						name = "energypylon",
						x = 7544,
						z = 2488,
						facing = 3,
					},
 					{
						name = "energypylon",
						x = 8360,
						z = 2680,
						facing = 3,
					},
 					{
						name = "energypylon",
						x = 8360,
						z = 1992,
						facing = 3,
					},
 					{
						name = "energypylon",
						x = 7576,
						z = 1656,
						facing = 3,
					},
 					{
						name = "energypylon",
						x = 6824,
						z = 1608,
						facing = 3,
					},
 					{
						name = "staticheavyradar",
						x = 8144,
						z = 1296,
						facing = 3,
					},
 					{
						name = "staticheavyradar",
						x = 7360,
						z = 4272,
						facing = 3,
					},
 					{
						name = "striderhub",
						x = 7824,
						z = 2896,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7824, 2896}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7799, 2921}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 7944,
						z = 2824,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7944, 2824}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7919, 2849}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 8008,
						z = 2824,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8008, 2824}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7983, 2849}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 8008,
						z = 2888,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8008, 2888}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7983, 2913}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 7944,
						z = 2888,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7944, 2888}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7919, 2913}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 7944,
						z = 2952,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7944, 2952}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7919, 2977}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 8008,
						z = 2952,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8008, 2952}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7983, 2977}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 8008,
						z = 3016,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7983, 3041}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8008, 3016}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 7944,
						z = 3016,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7944, 3016}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7919, 3041}, options = {"shift"}},
						},
					},
 					{
						name = "staticstorage",
						x = 8504,
						z = 3080,
						facing = 3,
					},
 					{
						name = "staticstorage",
						x = 8536,
						z = 2968,
						facing = 3,
					},
 					{
						name = "staticcon",
						x = 8024,
						z = 2472,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8024, 2472}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7999, 2497}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 8024,
						z = 2536,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8024, 2536}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7999, 2561}, options = {"shift"}},
						},
					},
 					{
						name = "striderbantha",
						x = 7694,
						z = 2524,
						facing = 3,
					},
 					{
						name = "striderdante",
						x = 7775,
						z = 2602,
						facing = 3,
					},
 					{
						name = "striderarty",
						x = 7781,
						z = 2463,
						facing = 3,
					},
 					{
						name = "turretheavylaser",
						x = 6984,
						z = 1896,
						facing = 3,
					},
 					{
						name = "turretriot",
						x = 7624,
						z = 1912,
						facing = 3,
					},
 					{
						name = "turretriot",
						x = 7624,
						z = 2072,
						facing = 3,
					},
 					{
						name = "turretaafar",
						x = 7360,
						z = 3920,
						facing = 3,
					},
 					{
						name = "turretriot",
						x = 7272,
						z = 3832,
						facing = 3,
					},
 					{
						name = "turretriot",
						x = 7256,
						z = 3992,
						facing = 3,
					},
 					{
						name = "turretheavy",
						x = 6424,
						z = 3384,
						facing = 3,
					},
 					{
						name = "turretheavy",
						x = 6376,
						z = 2200,
						facing = 3,
					},
 					{
						name = "turretgauss",
						x = 6360,
						z = 2552,
						facing = 3,
					},
 					{
						name = "turretemp",
						x = 6320,
						z = 2848,
						facing = 3,
					},
 					{
						name = "turretemp",
						x = 6288,
						z = 3056,
						facing = 3,
					},
 					{
						name = "turretgauss",
						x = 6232,
						z = 3400,
						facing = 3,
					},
 					{
						name = "turretgauss",
						x = 6312,
						z = 3688,
						facing = 3,
					},
 					{
						name = "turretgauss",
						x = 6248,
						z = 1960,
						facing = 3,
					},
 					{
						name = "turretgauss",
						x = 6344,
						z = 1544,
						facing = 3,
					},
 					{
						name = "turretemp",
						x = 6320,
						z = 1408,
						facing = 3,
					},
 					{
						name = "turretaalaser",
						x = 6504,
						z = 1768,
						facing = 3,
					},
 					{
						name = "turretaalaser",
						x = 6552,
						z = 2552,
						facing = 3,
					},
 					{
						name = "turretaalaser",
						x = 6632,
						z = 3672,
						facing = 3,
					},
 					{
						name = "turretaalaser",
						x = 6504,
						z = 4792,
						facing = 3,
					},
 					{
						name = "turretheavylaser",
						x = 6936,
						z = 3896,
						facing = 3,
					},
 					{
						name = "turretheavylaser",
						x = 7048,
						z = 3176,
						facing = 3,
					},
 					{
						name = "turretheavylaser",
						x = 7016,
						z = 2536,
						facing = 3,
					},
 					{
						name = "turretaafar",
						x = 7712,
						z = 1984,
						facing = 3,
					},
 					{
						name = "staticantinuke",
						x = 8384,
						z = 2968,
						facing = 3,
					},
				}
			},
			aiConfig = {
				{
					aiLib = "Circuit_difficulty_autofill_ally",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					humanName = "Unovis",
					allyTeam = 0,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energyheavygeo",
						"energysingu",
						"energypylon",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turrettorp",
						"turretgauss",
						"turretheavylaser",
						"turretaalaser",
						"turretaaclose",
						"turretaaflak",
						"shieldshield",
						"staticradar",
						"staticheavyradar",
						"staticcon",
						"staticantinuke",
						"staticrearm",
						"turretaafar",
						"turretheavy",
						"staticnuke",
						"staticheavyarty",
						"staticarty",
						"factoryspider",
						"spidercon",
						"spideremp",
						"spiderskirm",
						"spiderassault",
						"spidercrabe",
						"spiderantiheavy",
						"spideraa",
						"factorytank",
						"tankcon",
						"tankassault",
						"tankheavyassault",
						"tankarty",
						"tankheavyarty",
						"tankaa",
						"tankriot",
						"factoryjump",
						"jumpcon",
						"jumpassault",
						"jumpsumo",
						"jumparty",
						"jumpaa",
						"factoryplane",
						"planecon",
						"planescout",
						"planefighter",
						"planeheavyfighter",
						"bomberprec",
						"bomberdisarm",
						"bomberheavy",
						-- "striderhub",
						-- "striderdante",
						-- "striderarty",
						-- "striderscorpion",
						-- "striderfunnelweb",
						-- "striderantiheavy",
					},
					commander = false,
					startUnits = {
 						{
							name = "staticmex",
							x = 8792,
							z = 472,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8840,
							z = 4920,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9096,
							z = 1224,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9720,
							z = 2024,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8616,
							z = 5400,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9672,
							z = 712,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7928,
							z = 5336,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 10328,
							z = 680,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7640,
							z = 5992,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 10776,
							z = 1448,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 10936,
							z = 184,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6664,
							z = 5096,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 11096,
							z = 2824,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6088,
							z = 5192,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 10792,
							z = 3608,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6136,
							z = 4392,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 11160,
							z = 3704,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 10056,
							z = 3064,
							facing = 0,
						},
 						{
							name = "spidercrabe",
							x = 8163,
							z = 5110,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 9384,
							z = 4072,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7832,
							z = 728,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 10088,
							z = 4712,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7160,
							z = 280,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9768,
							z = 5272,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6952,
							z = 824,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9480,
							z = 5960,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6344,
							z = 472,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 10584,
							z = 5400,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 11176,
							z = 5832,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 11032,
							z = 4568,
							facing = 0,
						},
 						{
							name = "energyheavygeo",
							x = 10184,
							z = 4024,
							facing = 3,
						},
 						{
							name = "energysingu",
							x = 11128,
							z = 5112,
							facing = 3,
						},
 						{
							name = "energysingu",
							x = 11128,
							z = 1288,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 9160,
							z = 5720,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 10744,
							z = 5656,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 9160,
							z = 4984,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 10760,
							z = 4184,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 9176,
							z = 4248,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 10776,
							z = 3448,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 9176,
							z = 3512,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 9192,
							z = 2776,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 9192,
							z = 2040,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 10808,
							z = 1240,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 9944,
							z = 1320,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 10824,
							z = 504,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 9208,
							z = 1240,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 8968,
							z = 552,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 10744,
							z = 2152,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 8328,
							z = 1048,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 10872,
							z = 2712,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 7784,
							z = 472,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 6904,
							z = 440,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 10600,
							z = 5000,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 8424,
							z = 5736,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 9960,
							z = 5656,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 7752,
							z = 5400,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 7256,
							z = 5960,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 6888,
							z = 5384,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 6408,
							z = 5912,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 9992,
							z = 2712,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 6328,
							z = 5224,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 10008,
							z = 1976,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 10024,
							z = 504,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 10024,
							z = 4792,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 10056,
							z = 4136,
							facing = 3,
						},
 						{
							name = "energysingu",
							x = 11112,
							z = 3320,
							facing = 3,
						},
 						{
							name = "factorytank",
							x = 7120,
							z = 4944,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7240,
							z = 4920,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7304,
							z = 4984,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7279, 4959}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7304, 4984}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 7240,
							z = 4984,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 8104,
							z = 1000,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 8168,
							z = 1000,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 8168,
							z = 1064,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {8143, 1089}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {8168, 1064}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 8104,
							z = 1064,
							facing = 3,
						},
 						{
							name = "factoryjump",
							x = 7976,
							z = 1032,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 9480,
							z = 1832,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 9544,
							z = 1832,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 9544,
							z = 1896,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 9480,
							z = 1896,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 10456,
							z = 3112,
							facing = 3,
						},
 						{
							name = "staticantinuke",
							x = 9712,
							z = 4472,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 9480,
							z = 5176,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 9544,
							z = 5176,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 9544,
							z = 5240,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {9519, 5215}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {9544, 5240}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 9480,
							z = 5240,
							facing = 3,
						},
 						{
							name = "factoryplane",
							x = 10376,
							z = 3248,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 10328,
							z = 3112,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 10392,
							z = 3112,
							facing = 3,
						},
 						{
							name = "striderhub",
							x = 9536,
							z = 1984,
							facing = 3,
						},
 						{
							name = "staticrearm",
							x = 8872,
							z = 3384,
							facing = 3,
						},
 						{
							name = "staticrearm",
							x = 8872,
							z = 3592,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 9016,
							z = 3464,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 9016,
							z = 3560,
							facing = 3,
						},
 						{
							name = "turretheavy",
							x = 5960,
							z = 5224,
							facing = 3,
						},
 						{
							name = "turretgauss",
							x = 6152,
							z = 3992,
							facing = 3,
						},
 						{
							name = "turretgauss",
							x = 6008,
							z = 4440,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 6128,
							z = 4256,
							facing = 3,
						},
 						{
							name = "turretgauss",
							x = 5944,
							z = 4888,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 5840,
							z = 5200,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 6888,
							z = 1000,
							facing = 3,
						},
 						{
							name = "turretgauss",
							x = 5912,
							z = 5464,
							facing = 3,
						},
 						{
							name = "turretgauss",
							x = 5928,
							z = 5768,
							facing = 3,
						},
 						{
							name = "turretgauss",
							x = 5928,
							z = 6008,
							facing = 3,
						},
 						{
							name = "turretaalaser",
							x = 6344,
							z = 4696,
							facing = 3,
						},
 						{
							name = "turretaalaser",
							x = 6312,
							z = 5640,
							facing = 3,
						},
 						{
							name = "turretheavy",
							x = 6456,
							z = 744,
							facing = 3,
						},
 						{
							name = "turretgauss",
							x = 6360,
							z = 1144,
							facing = 3,
						},
 						{
							name = "turretgauss",
							x = 6248,
							z = 552,
							facing = 3,
						},
 						{
							name = "turretgauss",
							x = 6312,
							z = 280,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 6272,
							z = 416,
							facing = 3,
						},
 						{
							name = "staticstorage",
							x = 9640,
							z = 5304,
							facing = 1,
						},
 						{
							name = "staticstorage",
							x = 9688,
							z = 5208,
							facing = 1,
						},
 						{
							name = "staticstorage",
							x = 10376,
							z = 3384,
							facing = 1,
						},
 						{
							name = "staticstorage",
							x = 9720,
							z = 1864,
							facing = 1,
						},
 						{
							name = "staticstorage",
							x = 9672,
							z = 1768,
							facing = 1,
						},
 						{
							name = "staticantinuke",
							x = 9840,
							z = 2056,
							facing = 3,
						},
 						{
							name = "factoryspider",
							x = 9352,
							z = 5144,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 8456,
							z = 4776,
							facing = 3,
						},
 						{
							name = "spideremp",
							x = 7763,
							z = 4833,
							facing = 3,
						},
 						{
							name = "tankriot",
							x = 7726,
							z = 4749,
							facing = 0,
						},
 						{
							name = "jumpassault",
							x = 6846,
							z = 2941,
							facing = 3,
							patrolRoute = {
								{6850, 2984},
								{6819, 2928},
							},
						},
 						{
							name = "bomberheavy",
							x = 8833,
							z = 3630,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 7014,
							z = 3764,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 6434,
							z = 3118,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 7061,
							z = 5362,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 7260,
							z = 1020,
							facing = 0,
						},
 						{
							name = "jumpcon",
							x = 9987,
							z = 960,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 6264,
							z = 2696,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 6972,
							z = 2671,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 9528,
							z = 5128,
							facing = 3,
						},
 						{
							name = "jumpcon",
							x = 6500,
							z = 1454,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 7364,
							z = 2358,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 9480,
							z = 5080,
							facing = 3,
						},
 						{
							name = "jumpaa",
							x = 7053,
							z = 2775,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 9968,
							z = 864,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 9480,
							z = 5128,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {9455, 5103}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {9480, 5128}, options = {"shift"}},
							},
						},
 						{
							name = "spidercon",
							x = 6046,
							z = 5429,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 7504,
							z = 4096,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 9592,
							z = 5176,
							facing = 3,
						},
 						{
							name = "jumpcon",
							x = 6394,
							z = 3799,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 9576,
							z = 5128,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {9551, 5103}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {9576, 5128}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 9592,
							z = 5224,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 6104,
							z = 5718,
							facing = 3,
						},
 						{
							name = "tankassault",
							x = 7795,
							z = 4927,
							facing = 2,
						},
 						{
							name = "jumparty",
							x = 6342,
							z = 1252,
							facing = 3,
						},
 						{
							name = "spideremp",
							x = 7717,
							z = 4792,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 7072,
							z = 576,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 7592,
							z = 5667,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 7584,
							z = 3888,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 7280,
							z = 3754,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 7824,
							z = 5120,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 9920,
							z = 656,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 6362,
							z = 1490,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 7088,
							z = 4704,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 6168,
							z = 3736,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 10032,
							z = 3184,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 7399,
							z = 3513,
							facing = 3,
						},
 						{
							name = "jumpcon",
							x = 8069,
							z = 2693,
							facing = 1,
						},
 						{
							name = "tankassault",
							x = 7590,
							z = 4582,
							facing = 3,
						},
 						{
							name = "spiderassault",
							x = 7530,
							z = 4561,
							facing = 3,
						},
 						{
							name = "jumpcon",
							x = 8581,
							z = 2494,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 7240,
							z = 3752,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 9120,
							z = 2592,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 9568,
							z = 5776,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 9376,
							z = 6016,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 7152,
							z = 5200,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 9624,
							z = 5128,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {9599, 5103}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {9624, 5128}, options = {"shift"}},
							},
						},
 						{
							name = "spidercon",
							x = 6411,
							z = 3041,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 6256,
							z = 1488,
							facing = 0,
						},
 						{
							name = "jumpaa",
							x = 6560,
							z = 5435,
							facing = 0,
						},
 						{
							name = "spideraa",
							x = 6562,
							z = 5968,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 7680,
							z = 6016,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 11136,
							z = 5920,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 10640,
							z = 1536,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 6452,
							z = 3053,
							facing = 3,
						},
 						{
							name = "spidercrabe",
							x = 7673,
							z = 4774,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 9672,
							z = 3080,
							facing = 3,
						},
 						{
							name = "jumpcon",
							x = 6273,
							z = 1402,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 7792,
							z = 5840,
							facing = 2,
						},
 						{
							name = "planecon",
							x = 6334,
							z = 1373,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 7584,
							z = 5824,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 9560,
							z = 3160,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 10896,
							z = 3728,
							facing = 3,
						},
 						{
							name = "jumparty",
							x = 6349,
							z = 1192,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 10912,
							z = 4624,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 6464,
							z = 3856,
							facing = 2,
							buildProgress = 0.63700002,
						},
 						{
							name = "turretlaser",
							x = 10016,
							z = 2976,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 8640,
							z = 5168,
							facing = 3,
						},
 						{
							name = "tankarty",
							x = 6598,
							z = 5005,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 6752,
							z = 2192,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 8384,
							z = 3264,
							facing = 3,
						},
 						{
							name = "bomberheavy",
							x = 8313,
							z = 3742,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 7322,
							z = 3738,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 10960,
							z = 5616,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 7616,
							z = 1775,
							facing = 0,
						},
 						{
							name = "tankassault",
							x = 7781,
							z = 4768,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 10392,
							z = 3016,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 6458,
							z = 3010,
							facing = 3,
						},
 						{
							name = "spiderassault",
							x = 7523,
							z = 5179,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 10504,
							z = 3016,
							facing = 3,
						},
 						{
							name = "jumpassault",
							x = 6902,
							z = 2992,
							facing = 2,
							patrolRoute = {
								{6914, 2992},
								{6850, 2984},
							},
						},
 						{
							name = "turretlaser",
							x = 7504,
							z = 2528,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 6263,
							z = 2825,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 9440,
							z = 3760,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 8208,
							z = 2992,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 7055,
							z = 3859,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 7080,
							z = 2104,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 6723,
							z = 3208,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 9496,
							z = 520,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 9480,
							z = 5288,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {9455, 5263}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {9480, 5288}, options = {"shift"}},
							},
						},
 						{
							name = "spidercon",
							x = 9433,
							z = 5181,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 9936,
							z = 4864,
							facing = 3,
						},
 						{
							name = "jumpassault",
							x = 6873,
							z = 2983,
							facing = 3,
							patrolRoute = {
								{6911, 3004},
								{6850, 2984},
							},
						},
 						{
							name = "spidercrabe",
							x = 7676,
							z = 4831,
							facing = 1,
						},
 						{
							name = "tankheavyassault",
							x = 7712,
							z = 4881,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 8352,
							z = 1680,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 9560,
							z = 5016,
							facing = 3,
						},
 						{
							name = "planeheavyfighter",
							x = 6726,
							z = 5614,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7192,
							z = 2168,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 7472,
							z = 3712,
							facing = 3,
						},
 						{
							name = "spiderassault",
							x = 7722,
							z = 4830,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 6216,
							z = 1384,
							facing = 0,
						},
 						{
							name = "spiderantiheavy",
							x = 6177,
							z = 2531,
							facing = 0,
						},
 						{
							name = "jumpcon",
							x = 6361,
							z = 2845,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 9216,
							z = 1184,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 6080,
							z = 3072,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 6232,
							z = 2952,
							facing = 3,
						},
 						{
							name = "jumpassault",
							x = 6848,
							z = 2973,
							facing = 2,
							patrolRoute = {
								{6850, 2984},
								{6853, 2920},
							},
						},
 						{
							name = "spidercon",
							x = 9222,
							z = 5134,
							facing = 1,
						},
 						{
							name = "planeheavyfighter",
							x = 8833,
							z = 3553,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 6846,
							z = 3270,
							facing = 2,
						},
 						{
							name = "turretmissile",
							x = 5728,
							z = 5744,
							facing = 2,
						},
 						{
							name = "spiderassault",
							x = 7982,
							z = 5017,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 6144,
							z = 6016,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 7272,
							z = 3912,
							facing = 3,
						},
 						{
							name = "planeheavyfighter",
							x = 6429,
							z = 6027,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 6368,
							z = 2912,
							facing = 3,
						},
 						{
							name = "jumpcon",
							x = 7138,
							z = 3213,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 7419,
							z = 5404,
							facing = 3,
						},
 						{
							name = "jumpcon",
							x = 6574,
							z = 2298,
							facing = 0,
						},
 						{
							name = "spidercrabe",
							x = 8381,
							z = 5176,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 6480,
							z = 3088,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 7440,
							z = 5968,
							facing = 2,
						},
 						{
							name = "jumpassault",
							x = 7750,
							z = 1603,
							facing = 2,
							patrolRoute = {
								{7779, 1634},
								{7761, 1573},
							},
						},
 						{
							name = "turretaafar",
							x = 6288,
							z = 2928,
							facing = 3,
							buildProgress = 0.51789999,
						},
 						{
							name = "turretlaser",
							x = 6480,
							z = 1312,
							facing = 0,
						},
 						{
							name = "spiderassault",
							x = 8458,
							z = 5149,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 9512,
							z = 5000,
							facing = 3,
						},
 						{
							name = "spiderassault",
							x = 8583,
							z = 5103,
							facing = 3,
						},
 						{
							name = "jumpassault",
							x = 7903,
							z = 1270,
							facing = 0,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7761, 1573}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7824, 1587}, options = {"shift"}},
							},
						},
 						{
							name = "energypylon",
							x = 6216,
							z = 1336,
							facing = 0,
							buildProgress = 0.64819998,
						},
 						{
							name = "energywind",
							x = 7336,
							z = 728,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 9399,
							z = 5255,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 6560,
							z = 1520,
							facing = 0,
						},
 						{
							name = "tankassault",
							x = 7092,
							z = 4944,
							facing = 3,
							buildProgress = 0.29409999,
						},
 						{
							name = "spidercon",
							x = 9344,
							z = 5228,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 9528,
							z = 5288,
							facing = 3,
						},
 						{
							name = "jumpcon",
							x = 7944,
							z = 1197,
							facing = 0,
						},
 						{
							name = "spiderassault",
							x = 9287,
							z = 5245,
							facing = 0,
						},
 						{
							name = "jumpassault",
							x = 7952,
							z = 1032,
							facing = 3,
							buildProgress = 0.0983,
						},
 						{
							name = "turretmissile",
							x = 7344,
							z = 3552,
							facing = 3,
							buildProgress = 0.0899,
						},
 						{
							name = "spidercrabe",
							x = 9316,
							z = 5144,
							facing = 3,
							buildProgress = 0.0391,
						},
					}
				},
				{
					startX = 1330,
					startZ = 3300,
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					humanName = "Bilious",
					commanderParameters = {
						facplop = false,
					},
					allyTeam = 1,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energyheavygeo",
						"energysingu",
						"energypylon",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turrettorp",
						"turretgauss",
						"turretheavylaser",
						"turretaalaser",
						"turretaaclose",
						"turretaaflak",
						"shieldshield",
						"staticradar",
						"staticheavyradar",
						"staticcon",
						"staticantinuke",
						"staticrearm",
						"turretaafar",
						"turretheavy",
						"staticnuke",
						"staticheavyarty",
						"staticarty",
						"spidercon",
						"spideremp",
						"spiderskirm",
						"spiderassault",
						"spidercrabe",
						"spiderantiheavy",
						"spideraa",
						"factorytank",
						"tankcon",
						"tankassault",
						"tankheavyassault",
						"tankarty",
						"tankheavyarty",
						"tankaa",
						"tankriot",
						"factoryamph",
						"amphcon",
						"amphfloater",
						"amphriot",
						"amphassault",
						"amphaa",
						"factoryjump",
						"jumpcon",
						"jumpassault",
						"jumpsumo",
						"jumparty",
						"jumpaa",
						"factoryplane",
						"planecon",
						"planescout",
						"planefighter",
						"planeheavyfighter",
						"bomberprec",
						"bomberdisarm",
						"bomberheavy",
						-- "striderhub",
						-- "striderdante",
						-- "striderarty",
						-- "striderscorpion",
						-- "striderfunnelweb",
						-- "striderantiheavy",
					},
					commanderLevel = 7,
					commander = {
						name = "Vespid",
						chassis = "strike",
						decorations = {
						},
						modules = {
							"commweapon_shotgun",
							"commweapon_disintegrator",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_personal_cloak",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_autorepair",
							"module_autorepair",
						}
					},
					startUnits = {
 						{
							name = "staticmex",
							x = 3000,
							z = 2760,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2232,
							z = 3816,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1976,
							z = 2696,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2952,
							z = 3336,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2184,
							z = 3416,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3192,
							z = 4344,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1880,
							z = 2072,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1544,
							z = 4120,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2584,
							z = 4376,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4040,
							z = 2920,
							facing = 0,
						},
 						{
							name = "energyheavygeo",
							x = 2712,
							z = 3784,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 1176,
							z = 1432,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4152,
							z = 2392,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2168,
							z = 4920,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1496,
							z = 872,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3656,
							z = 2200,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2472,
							z = 5672,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1784,
							z = 184,
							facing = 0,
						},
 						{
							name = "energyheavygeo",
							x = 1096,
							z = 2136,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 3272,
							z = 1432,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1592,
							z = 5432,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3432,
							z = 5416,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3336,
							z = 808,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2648,
							z = 744,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 936,
							z = 5464,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4104,
							z = 5864,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2424,
							z = 1224,
							facing = 0,
						},
 						{
							name = "energyheavygeo",
							x = 2840,
							z = 1752,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 328,
							z = 5960,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4312,
							z = 5320,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4920,
							z = 5672,
							facing = 0,
						},
 						{
							name = "energygeo",
							x = 3928,
							z = 1576,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 488,
							z = 4696,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 680,
							z = 744,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3624,
							z = 152,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5048,
							z = 4760,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 88,
							z = 312,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 168,
							z = 3320,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4552,
							z = 3960,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4600,
							z = 1048,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 232,
							z = 1576,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4104,
							z = 3512,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5176,
							z = 952,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1208,
							z = 3080,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3624,
							z = 3864,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5128,
							z = 1752,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 104,
							z = 2440,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 472,
							z = 2536,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4040,
							z = 4568,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4696,
							z = 2152,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5096,
							z = 2408,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 520,
							z = 2056,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 520,
							z = 1176,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 504,
							z = 568,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 1368,
							z = 568,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 1352,
							z = 1384,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 4040,
							z = 568,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 4008,
							z = 1304,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 1320,
							z = 2984,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 1320,
							z = 3720,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 4664,
							z = 552,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 3928,
							z = 2776,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 1304,
							z = 4456,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 4648,
							z = 1288,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 3896,
							z = 3512,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 1304,
							z = 5192,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 4632,
							z = 2024,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 1288,
							z = 5928,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 4600,
							z = 3496,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 3800,
							z = 5720,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 3720,
							z = 5048,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 4584,
							z = 4232,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 3720,
							z = 4392,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 4568,
							z = 4968,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 280,
							z = 2824,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 4552,
							z = 5704,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 312,
							z = 3560,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 328,
							z = 4296,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 3832,
							z = 2120,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 360,
							z = 5032,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 4568,
							z = 2824,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 376,
							z = 5768,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 2328,
							z = 440,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 2312,
							z = 1176,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 2296,
							z = 2648,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 2280,
							z = 3384,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 2280,
							z = 4120,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 2264,
							z = 4856,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 2248,
							z = 5592,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 1992,
							z = 1976,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 3240,
							z = 488,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 3224,
							z = 1224,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 3176,
							z = 2696,
							facing = 3,
						},
 						{
							name = "energysingu",
							x = 136,
							z = 5544,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 3160,
							z = 3432,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 3144,
							z = 4168,
							facing = 3,
						},
 						{
							name = "energysingu",
							x = 568,
							z = 3736,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 3144,
							z = 5048,
							facing = 3,
						},
 						{
							name = "energysingu",
							x = 504,
							z = 2312,
							facing = 3,
						},
 						{
							name = "energysingu",
							x = 424,
							z = 120,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 2968,
							z = 1960,
							facing = 3,
						},
 						{
							name = "staticheavyradar",
							x = 3904,
							z = 1872,
							facing = 3,
						},
 						{
							name = "staticheavyradar",
							x = 3952,
							z = 4944,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 3448,
							z = 1432,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 3512,
							z = 1432,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 3512,
							z = 1496,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 3448,
							z = 1496,
							facing = 1,
						},
 						{
							name = "factorytank",
							x = 3488,
							z = 1616,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 3400,
							z = 4408,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 3464,
							z = 4408,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 3464,
							z = 4472,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 3400,
							z = 4472,
							facing = 1,
						},
 						{
							name = "factorytank",
							x = 3440,
							z = 4592,
							facing = 1,
						},
 						{
							name = "staticrearm",
							x = 3704,
							z = 3096,
							facing = 1,
						},
 						{
							name = "staticrearm",
							x = 3704,
							z = 2888,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 3448,
							z = 3048,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 3368,
							z = 3048,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 3288,
							z = 3048,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 3320,
							z = 3128,
							facing = 1,
						},
 						{
							name = "factoryamph",
							x = 3320,
							z = 3256,
							facing = 1,
						},
 						{
							name = "factoryjump",
							x = 1192,
							z = 5384,
							facing = 1,
						},
 						{
							name = "factoryplane",
							x = 936,
							z = 2928,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 904,
							z = 2760,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1000,
							z = 5288,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 968,
							z = 2760,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1032,
							z = 2760,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1064,
							z = 5288,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1064,
							z = 5352,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1000,
							z = 5352,
							facing = 1,
						},
 						{
							name = "factoryspider",
							x = 1240,
							z = 856,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1080,
							z = 808,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1080, 808}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1276, 856}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 1144,
							z = 808,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1144,
							z = 872,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1080,
							z = 872,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1944,
							z = 2344,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 2008,
							z = 2344,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 2072,
							z = 2344,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 2072,
							z = 2408,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 2008,
							z = 2408,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 1944,
							z = 2408,
							facing = 3,
						},
 						{
							name = "striderhub",
							x = 2016,
							z = 2496,
							facing = 1,
						},
 						{
							name = "turretheavy",
							x = 4888,
							z = 5336,
							facing = 1,
						},
 						{
							name = "turretgauss",
							x = 5112,
							z = 5288,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 5104,
							z = 5456,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 5040,
							z = 5104,
							facing = 1,
						},
 						{
							name = "turretgauss",
							x = 5032,
							z = 5864,
							facing = 1,
						},
 						{
							name = "turretgauss",
							x = 4968,
							z = 4680,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 5008,
							z = 4496,
							facing = 1,
						},
 						{
							name = "turretgauss",
							x = 5032,
							z = 4296,
							facing = 1,
						},
 						{
							name = "turretgauss",
							x = 4984,
							z = 3912,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 4976,
							z = 3680,
							facing = 1,
						},
 						{
							name = "turretgauss",
							x = 5080,
							z = 3480,
							facing = 1,
						},
 						{
							name = "turretgauss",
							x = 5016,
							z = 3064,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 5072,
							z = 2848,
							facing = 1,
						},
 						{
							name = "turretgauss",
							x = 5064,
							z = 2664,
							facing = 1,
						},
 						{
							name = "turretgauss",
							x = 5096,
							z = 2264,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 5136,
							z = 2112,
							facing = 1,
						},
 						{
							name = "turretgauss",
							x = 5144,
							z = 1960,
							facing = 1,
						},
 						{
							name = "turretgauss",
							x = 5144,
							z = 1480,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 5200,
							z = 1312,
							facing = 1,
						},
 						{
							name = "turretgauss",
							x = 5304,
							z = 1160,
							facing = 1,
						},
 						{
							name = "turretaafar",
							x = 3568,
							z = 5040,
							facing = 1,
						},
 						{
							name = "turretgauss",
							x = 5208,
							z = 488,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 5264,
							z = 352,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 520,
							z = 280,
							facing = 1,
						},
 						{
							name = "turretgauss",
							x = 5240,
							z = 200,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 408,
							z = 456,
							facing = 1,
						},
 						{
							name = "turretaaheavy",
							x = 1872,
							z = 4528,
							facing = 1,
						},
 						{
							name = "turretheavy",
							x = 728,
							z = 2264,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 600,
							z = 3528,
							facing = 1,
						},
 						{
							name = "turretaaheavy",
							x = 1680,
							z = 1504,
							facing = 1,
						},
 						{
							name = "turretantiheavy",
							x = 4736,
							z = 4432,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 680,
							z = 3864,
							facing = 1,
						},
 						{
							name = "turretheavy",
							x = 4792,
							z = 3688,
							facing = 1,
						},
 						{
							name = "turretheavy",
							x = 4840,
							z = 2888,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 344,
							z = 5320,
							facing = 1,
						},
 						{
							name = "turretaafar",
							x = 3552,
							z = 1136,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 520,
							z = 5688,
							facing = 1,
						},
 						{
							name = "turretheavy",
							x = 4952,
							z = 2248,
							facing = 1,
						},
 						{
							name = "turretaafar",
							x = 3648,
							z = 2608,
							facing = 1,
						},
 						{
							name = "turretantiheavy",
							x = 4896,
							z = 1456,
							facing = 1,
						},
 						{
							name = "turretheavy",
							x = 5128,
							z = 792,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 4296,
							z = 888,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 3128,
							z = 968,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 2872,
							z = 2968,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 4424,
							z = 2936,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 2808,
							z = 4456,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 4264,
							z = 4936,
							facing = 1,
						},
 						{
							name = "turretaaflak",
							x = 632,
							z = 5048,
							facing = 1,
						},
 						{
							name = "turretaaflak",
							x = 776,
							z = 5544,
							facing = 1,
						},
 						{
							name = "turretaaflak",
							x = 984,
							z = 3544,
							facing = 1,
						},
 						{
							name = "turretaaflak",
							x = 840,
							z = 1864,
							facing = 1,
						},
 						{
							name = "turretaaflak",
							x = 824,
							z = 648,
							facing = 1,
						},
 						{
							name = "staticantinuke",
							x = 1616,
							z = 1656,
							facing = 3,
						},
 						{
							name = "staticantinuke",
							x = 1216,
							z = 3208,
							facing = 3,
						},
 						{
							name = "staticantinuke",
							x = 1152,
							z = 4648,
							facing = 3,
						},
 						{
							name = "staticantinuke",
							x = 3328,
							z = 3448,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 1320,
							z = 2232,
							facing = 3,
						},
 						{
							name = "staticstorage",
							x = 3048,
							z = 2728,
							facing = 1,
						},
 						{
							name = "tankriot",
							x = 3941,
							z = 2829,
							facing = 1,
						},
 						{
							name = "tankriot",
							x = 4922,
							z = 3399,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 4272,
							z = 3622,
							facing = 3,
						},
 						{
							name = "jumpassault",
							x = 3850,
							z = 3877,
							facing = 0,
							patrolRoute = {
								{3942, 3757},
								{3808, 3984},
							},
						},
 						{
							name = "bomberheavy",
							x = 956,
							z = 2890,
							facing = 3,
						},
 						{
							name = "spidercrabe",
							x = 4459,
							z = 1625,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 1256,
							z = 3016,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 4553,
							z = 3150,
							facing = 3,
						},
 						{
							name = "tankcon",
							x = 5491,
							z = 1045,
							facing = 0,
						},
 						{
							name = "jumpcon",
							x = 4040,
							z = 5208,
							facing = 2,
						},
 						{
							name = "amphaa",
							x = 5320,
							z = 5838,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 3312,
							z = 4296,
							facing = 1,
						},
 						{
							name = "jumpassault",
							x = 5400,
							z = 2690,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 2920,
							z = 2728,
							facing = 1,
						},
 						{
							name = "tankcon",
							x = 5111,
							z = 2772,
							facing = 2,
						},
 						{
							name = "tankcon",
							x = 5407,
							z = 2100,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 3504,
							z = 1376,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 2989,
							z = 3010,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 1848,
							z = 3768,
							facing = 1,
						},
 						{
							name = "staticstorage",
							x = 2920,
							z = 2680,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 2281,
							z = 2550,
							facing = 1,
						},
 						{
							name = "tankassault",
							x = 4578,
							z = 1714,
							facing = 2,
							patrolRoute = {
								{4572, 1739},
								{4551, 1679},
							},
						},
 						{
							name = "turretlaser",
							x = 3776,
							z = 3792,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 4320,
							z = 5696,
							facing = 2,
						},
 						{
							name = "jumpcon",
							x = 3969,
							z = 1398,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 2160,
							z = 4976,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 3696,
							z = 3552,
							facing = 1,
						},
 						{
							name = "amphassault",
							x = 5349,
							z = 1791,
							facing = 0,
						},
 						{
							name = "spidercrabe",
							x = 4484,
							z = 1680,
							facing = 1,
						},
 						{
							name = "jumpassault",
							x = 4335,
							z = 5103,
							facing = 3,
						},
 						{
							name = "tankcon",
							x = 5409,
							z = 1492,
							facing = 2,
						},
 						{
							name = "staticstorage",
							x = 3064,
							z = 2680,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 2712,
							z = 4472,
							facing = 1,
						},
 						{
							name = "tankassault",
							x = 6049,
							z = 4198,
							facing = 1,
						},
 						{
							name = "jumpassault",
							x = 4267,
							z = 5664,
							facing = 3,
						},
 						{
							name = "tankcon",
							x = 3489,
							z = 1290,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 2208,
							z = 4720,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 528,
							z = 4768,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 4128,
							z = 4672,
							facing = 2,
						},
 						{
							name = "jumpassault",
							x = 1901,
							z = 5535,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 5032,
							z = 4536,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 5064,
							z = 2936,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 1816,
							z = 2808,
							facing = 1,
						},
 						{
							name = "jumpcon",
							x = 4205,
							z = 2178,
							facing = 2,
						},
 						{
							name = "tankassault",
							x = 4187,
							z = 3527,
							facing = 1,
							patrolRoute = {
								{4176, 3616},
								{4304, 3502},
							},
						},
 						{
							name = "staticmex",
							x = 5000,
							z = 3448,
							facing = 0,
						},
 						{
							name = "tankcon",
							x = 5463,
							z = 1728,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 2992,
							z = 4368,
							facing = 1,
						},
 						{
							name = "planecon",
							x = 5244,
							z = 1878,
							facing = 1,
						},
 						{
							name = "jumpcon",
							x = 4793,
							z = 5430,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 5312,
							z = 944,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 448,
							z = 4576,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1904,
							z = 2304,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1344,
							z = 5568,
							facing = 1,
						},
 						{
							name = "jumparty",
							x = 4773,
							z = 5083,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 4976,
							z = 4752,
							facing = 2,
						},
 						{
							name = "tankcon",
							x = 5198,
							z = 1832,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 792,
							z = 2904,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 4960,
							z = 3296,
							facing = 1,
						},
 						{
							name = "amphaa",
							x = 5340,
							z = 5800,
							facing = 3,
						},
 						{
							name = "spiderassault",
							x = 4536,
							z = 1603,
							facing = 3,
							patrolRoute = {
								{4551, 1679},
								{4511, 1629},
							},
						},
 						{
							name = "energypylon",
							x = 4840,
							z = 3192,
							facing = 1,
						},
 						{
							name = "planeheavyfighter",
							x = 6617,
							z = 5787,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1768,
							z = 5752,
							facing = 1,
						},
 						{
							name = "planecon",
							x = 5384,
							z = 1702,
							facing = 0,
						},
 						{
							name = "tankcon",
							x = 5376,
							z = 1875,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 336,
							z = 2416,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 4620,
							z = 827,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 2224,
							z = 3680,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 5143,
							z = 3094,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 3264,
							z = 1200,
							facing = 1,
						},
 						{
							name = "planescout",
							x = 2856,
							z = 5038,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 5168,
							z = 3216,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1344,
							z = 3088,
							facing = 1,
						},
 						{
							name = "tankcon",
							x = 5165,
							z = 1521,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 2496,
							z = 864,
							facing = 1,
						},
 						{
							name = "spiderassault",
							x = 4507,
							z = 1634,
							facing = 0,
							patrolRoute = {
								{4511, 1628},
								{4551, 1679},
							},
						},
 						{
							name = "tankcon",
							x = 5408,
							z = 1846,
							facing = 2,
						},
 						{
							name = "jumpaa",
							x = 5201,
							z = 5767,
							facing = 3,
						},
 						{
							name = "tankassault",
							x = 3516,
							z = 1616,
							facing = 1,
							buildProgress = 0.7148,
						},
 						{
							name = "turretlaser",
							x = 3056,
							z = 3072,
							facing = 1,
						},
 						{
							name = "tankcon",
							x = 5284,
							z = 1785,
							facing = 2,
						},
 						{
							name = "spiderantiheavy",
							x = 5291,
							z = 1953,
							facing = 3,
						},
 						{
							name = "amphaa",
							x = 5435,
							z = 5950,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 1560,
							z = 184,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 5216,
							z = 3008,
							facing = 1,
							buildProgress = 0.43489999,
						},
 						{
							name = "tankcon",
							x = 5277,
							z = 3481,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 432,
							z = 2592,
							facing = 1,
						},
 						{
							name = "staticstorage",
							x = 2872,
							z = 2712,
							facing = 1,
						},
 						{
							name = "amphaa",
							x = 5361,
							z = 5870,
							facing = 1,
						},
 						{
							name = "jumparty",
							x = 4039,
							z = 5293,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 5640,
							z = 104,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 5224,
							z = 1208,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 4800,
							z = 3168,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 3696,
							z = 336,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 4113,
							z = 1051,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 3440,
							z = 1872,
							facing = 1,
						},
 						{
							name = "tankcon",
							x = 3428,
							z = 2700,
							facing = 1,
						},
 						{
							name = "spideraa",
							x = 1374,
							z = 893,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 5168,
							z = 1728,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5624,
							z = 2152,
							facing = 0,
						},
 						{
							name = "spideraa",
							x = 4192,
							z = 3685,
							facing = 1,
						},
 						{
							name = "tankcon",
							x = 5291,
							z = 1217,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 1376,
							z = 1296,
							facing = 1,
						},
 						{
							name = "tankcon",
							x = 4832,
							z = 5708,
							facing = 2,
						},
 						{
							name = "amphaa",
							x = 5201,
							z = 5672,
							facing = 1,
						},
 						{
							name = "spiderantiheavy",
							x = 1795,
							z = 931,
							facing = 1,
						},
 						{
							name = "tankassault",
							x = 4548,
							z = 1662,
							facing = 2,
							patrolRoute = {
								{4551, 1679},
								{4505, 1633},
							},
						},
 						{
							name = "jumpassault",
							x = 3724,
							z = 5793,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 5000,
							z = 2984,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 224,
							z = 5840,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 4016,
							z = 2208,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1888,
							z = 128,
							facing = 1,
						},
 						{
							name = "spiderantiheavy",
							x = 4295,
							z = 1770,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 5488,
							z = 2016,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 1328,
							z = 1088,
							facing = 1,
						},
 						{
							name = "amphfloater",
							x = 4295,
							z = 2129,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4551, 1679}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4584, 1733}, options = {"shift"}},
							},
						},
 						{
							name = "tankcon",
							x = 5287,
							z = 3520,
							facing = 2,
						},
 						{
							name = "spidercon",
							x = 3962,
							z = 1008,
							facing = 1,
						},
 						{
							name = "jumpassault",
							x = 3754,
							z = 5792,
							facing = 1,
						},
 						{
							name = "amphfloater",
							x = 4370,
							z = 1938,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4551, 1679}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4519, 1734}, options = {"shift"}},
							},
						},
 						{
							name = "turretlaser",
							x = 5184,
							z = 4704,
							facing = 2,
						},
 						{
							name = "tankassault",
							x = 5122,
							z = 3286,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 5344,
							z = 1856,
							facing = 0,
						},
 						{
							name = "spidercrabe",
							x = 2237,
							z = 1184,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 5256,
							z = 1064,
							facing = 0,
							buildProgress = 0.58740002,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5256, 1064}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5281, 1089}, options = {"shift"}},
							},
						},
 						{
							name = "tankcon",
							x = 3901,
							z = 3842,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 5176,
							z = 1368,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 624,
							z = 752,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 3375,
							z = 2658,
							facing = 1,
						},
 						{
							name = "tankheavyassault",
							x = 4251,
							z = 1673,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4551, 1679}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4581, 1735}, options = {"shift"}},
							},
						},
 						{
							name = "planeheavyfighter",
							x = 3849,
							z = 5457,
							facing = 2,
						},
 						{
							name = "turretmissile",
							x = 5520,
							z = 976,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 240,
							z = 1536,
							facing = 1,
						},
 						{
							name = "jumpcon",
							x = 4217,
							z = 4254,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 4632,
							z = 3069,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 5680,
							z = 128,
							facing = 0,
						},
 						{
							name = "jumpassault",
							x = 3184,
							z = 5731,
							facing = 1,
						},
 						{
							name = "tankcon",
							x = 3913,
							z = 2951,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 4823,
							z = 3504,
							facing = 2,
						},
 						{
							name = "tankcon",
							x = 5353,
							z = 3491,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 5448,
							z = 776,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 4093,
							z = 2352,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 3400,
							z = 152,
							facing = 0,
						},
 						{
							name = "jumpcon",
							x = 2729,
							z = 5372,
							facing = 2,
						},
 						{
							name = "planeheavyfighter",
							x = 5382,
							z = 6085,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 5224,
							z = 2040,
							facing = 0,
						},
 						{
							name = "amphassault",
							x = 3356,
							z = 3256,
							facing = 1,
							buildProgress = 0.87620002,
						},
 						{
							name = "tankheavyassault",
							x = 3468,
							z = 4592,
							facing = 1,
							buildProgress = 0.73720002,
						},
 						{
							name = "jumpcon",
							x = 2572,
							z = 4080,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 2524,
							z = 1205,
							facing = 1,
						},
 						{
							name = "planeheavyfighter",
							x = 4386,
							z = 5344,
							facing = 1,
						},
 						{
							name = "jumpcon",
							x = 2957,
							z = 5661,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 5160,
							z = 3432,
							facing = 1,
						},
 						{
							name = "spiderassault",
							x = 1714,
							z = 1077,
							facing = 1,
						},
 						{
							name = "jumpassault",
							x = 1318,
							z = 5391,
							facing = 1,
						},
 						{
							name = "planeheavyfighter",
							x = 956,
							z = 2965,
							facing = 1,
							buildProgress = 0.7166,
						},
 						{
							name = "striderarty",
							x = 879,
							z = 1249,
							facing = 0,
						},
 						{
							name = "striderarty",
							x = 171,
							z = 4768,
							facing = 0,
						},
 						{
							name = "striderscorpion",
							x = 2576,
							z = 5397,
							facing = 0,
						},
 						{
							name = "striderscorpion",
							x = 2810,
							z = 981,
							facing = 0,
						},
 						{
							name = "striderdante",
							x = 3698,
							z = 2157,
							facing = 0,
						},
 						{
							name = "striderdante",
							x = 3481,
							z = 3654,
							facing = 1,
						},
 						{
							name = "jumpassault",
							x = 1216,
							z = 5384,
							facing = 1,
							buildProgress = 0.0694,
						},
 						{
							name = "turretaalaser",
							x = 5384,
							z = 1656,
							facing = 0,
							buildProgress = 0.0482,
						},
 						{
							name = "spideraa",
							x = 1276,
							z = 856,
							facing = 1,
							buildProgress = 0.1891,
						},
 						{
							name = "striderfunnelweb",
							x = 2169,
							z = 2438,
							facing = 0,
						},
 						{
							name = "striderfunnelweb",
							x = 2150,
							z = 2644,
							facing = 0,
						},
					}
				},
			},
			defeatConditionConfig = {
				[0] = { },
				[1] = {
					ignoreUnitLossDefeat = false,
					vitalCommanders = false,
					vitalUnitTypes = {
						"energysingu",
						"energygeo",
						"energyheavygeo",
					},
					loseAfterSeconds = false,
					allyTeamLossObjectiveID = 1,
				},
			},
			objectiveConfig = {
				-- This is just related to displaying objectives on the UI.
				[1] = {
					description = "Destroy all enemy Singularity Reactors and Geothermals",
				},
				[2] = {
					description = "Protect your Commander",
				},
			},
			bonusObjectiveConfig = {
				[1] = {
					satisfyOnce = true,
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 3,
					unitTypes = {
						"striderbantha",
					},
					image = planetUtilities.ICON_DIR .. "striderbantha.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.REPAIR,
					description = "Have 3 Paladins",
					experience = planetUtilities.BONUS_EXP,
				},
				[2] = {
					victoryByTime = 30*60,
					image = planetUtilities.ICON_OVERLAY.CLOCK,
					description = "Win by 30:00",
					experience = planetUtilities.BONUS_EXP,
				},
			}
		},
		completionReward = {
			experience = planetUtilities.MAIN_EXP,
			units = {
				"striderhub",
				"striderbantha",
			},
			modules = {
				"weaponmod_stun_booster",
			},
			abilities = {
			},
			codexEntries = {
				"faction_survivors",
				"location_intrepid"
			},
		},
	}
	
	return planetData
end

return GetPlanet
