--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Planet config

local function GetPlanet(planetUtilities, planetID)
	
	local image = LUA_DIRNAME .. "images/planets/desert02.png"
	
	local planetData = {
		name = "Deuliah",
		startingPlanet = false,
		mapDisplay = {
			x = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][1]) or 0.605,
			y = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][2]) or 0.06,
			image = image,
			size = planetUtilities.PLANET_SIZE_MAP,
		},
		infoDisplay = {
			image = image,
			size = planetUtilities.PLANET_SIZE_INFO,
			backgroundImage = planetUtilities.backgroundImages[math.floor(math.random()*#planetUtilities.backgroundImages) + 1],
			terrainType = "Desert",
			radius = "7270 km",
			primary = "Nassia",
			primaryType = "G4V",
			milRating = 1,
			feedbackLink = "http://zero-k.info/Forum/Thread/24510",
			text = "There is technology on this world, that is both much more ancient and more andvanced than it should be. There are the remains of several raiding parties sent by the Empire to try - without success - and capture it."
			.. "\n "
			.. "\nAutomated defenses have suffered from the raids, but are still operational - and a Detriment roaming around. How can it be working after half an eternity exposed and without maintenance?"
			,
			extendedText = "That Detriment will crush any attempt to build a base. I have to stay on the move with Athena mobile constructors, until I can build up an army strong enough to take it down."
		},
		tips = {
			{
				image = "unitpics/athena.png",
				text = [[The Athena SpecOps Engineer can build a variety of useful units. It cloaks and moves quite fast, so unlike factories it can avoid enemy attacks.]]
			},
			{
				image = "unitpics/module_resurrect.png",
				text = [[Previous attempts to take this planet have left many wreckages. Athenas can resurrect these wrecks and add them to your army.]]
			},
			{
				image = "unitpics/striderdetriment.png",
				text = [[The Detriment is a fearsome strider armed with gauss guns, missiles, and powerful laser beams. A fair fight against the Detriment would be futile - destroy its escorts then counter it with anti-heavies to balance the odds.]]
			},
			{
				image = "unitpics/strike.png",
				text = [[A small Interloper base is still active, which will distract the Detriment while you establish an army and economy.]]
			}
		},
		gameConfig = {
			mapName = "Grts_DesertValley_012",
			playerConfig = {
				startX = 320,
				startZ = 450,
				allyTeam = 0,
				facplop = false,
				commanderParameters = {
					facplop = false,
					defeatIfDestroyedObjectiveID = 2,
				},
				extraUnlocks = {
					"striderhub",
					"athena",
					"staticcon",
					"staticradar",
					"staticheavyradar",
					"staticjammer",
					"cloakcon",
					"spiderscout",
					"shieldraid",
					"hoverassault",
					"spiderantiheavy",
					"cloakheavyraid",
					"jumpskirm",
					"spiderskirm",
					"tankheavyraid",
					"cloakassault",
					"cloaksnipe",
					"vehheavyarty",
					"cloakaa",
					"shieldshield",
					"cloakjammer",
					"amphtele",
				},
				startUnits = {
					{
						name = "gunshipheavytrans",
						x = 373,
						z = 100,
						facing = 1,
					},
 					{
						name = "staticmex",
						x = 264,
						z = 264,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 440,
						z = 472,
						facing = 0,
					},
 					{
						name = "energypylon",
						x = 150,
						z = 130,
						facing = 0,
					},
 					{
						name = "energyfusion",
						x = 200,
						z = 32,
						facing = 0,
					},
 					{
						name = "energyfusion",
						x = 32,
						z = 232,
						facing = 1,
					},
					{
						name = "energyfusion",
						x = 32,
						z = 120,
						facing = 1,
					},
 					{
						name = "planescout",
						x = 10160,
						z = 266,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.RAW_MOVE, pos = {2670, 297}},
						},
					},
					{
						name = "planescout",
						x = 4200,
						z = 9929,
						facing = 2,
						commands = {
							{cmdID = planetUtilities.COMMAND.RAW_MOVE, pos = {1818, 3628}},
						},
					},
 					{
						name = "striderhub",
						x = 400,
						z = 272,
						facing = 1,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {425, 297}},
						},
					},
 					{
						name = "staticheavyradar",
						x = 416,
						z = 624,
						facing = 1,
						terraformHeight = 1621,
					},
 					{
						name = "athena",
						x = 512,
						z = 160,
						facing = 1,
					},
 					{
						name = "athena",
						x = 560,
						z = 240,
						facing = 1,
					},
 					{
						name = "athena",
						x = 528,
						z = 336,
						facing = 1,
					},
 					{
						name = "athena",
						x = 528,
						z = 432,
						facing = 1,
					},
				}
			},
			aiConfig = {
				{
					startX = 8600,
					startZ = 1000,
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					humanName = "Interloper",
					commanderParameters = {
						facplop = false,
					},
					allyTeam = 1,
					unlocks = {
						"turretlaser",
						"staticmex",
						"energysolar",
						"staticcon",
						"staticradar",
						"cloakcon",
						"cloakraid",
						"cloakskirm",
						"cloakriot",
						"cloakassault",
						"cloakarty",
						"cloakaa",
					},
					commanderLevel = 4,
					commander = {
						name = "Dolor",
						chassis = "strike",
						decorations = {
						},
						modules = {
							"commweapon_shotgun",
							"commweapon_shotgun",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_adv_targeting",
							"module_adv_targeting",
						}
					},
					startUnits = {
						{
							name = "factorycloak",
							x = 8584,
							z = 1856,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8136,
							z = 1720,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8184,
							z = 1384,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8520,
							z = 1416,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8936,
							z = 1560,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9144,
							z = 1768,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 9016,
							z = 1736,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 8856,
							z = 1640,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 8680,
							z = 1576,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 8488,
							z = 1528,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 8312,
							z = 1448,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 8216,
							z = 1608,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 8584,
							z = 1704,
							facing = 0,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {8584, 1704}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {8559, 1729}, options = {"shift"}},
							},
						},
 						{
							name = "cloakcon",
							x = 9918,
							z = 1600,
							facing = 1,
						},
 						{
							name = "cloakcon",
							x = 8461,
							z = 1176,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9432,
							z = 1528,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9912,
							z = 1448,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8920,
							z = 936,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 10040,
							z = 1176,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 9976,
							z = 1272,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8840,
							z = 568,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 9832,
							z = 1400,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 8872,
							z = 808,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 9656,
							z = 1464,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 8856,
							z = 680,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 9480,
							z = 1448,
							facing = 0,
						},
 						{
							name = "turretaalaser",
							x = 8344,
							z = 1704,
							facing = 0,
						},
 						{
							name = "turretaalaser",
							x = 9144,
							z = 1336,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 8624,
							z = 560,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 8032,
							z = 1472,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 8640,
							z = 992,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 9392,
							z = 1696,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 8376,
							z = 1944,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 10016,
							z = 1600,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 8760,
							z = 1944,
							facing = 0,
						},
 						{
							name = "cloakassault",
							x = 8559,
							z = 1081,
							facing = 2,
						},
 						{
							name = "cloakassault",
							x = 7987,
							z = 783,
							facing = 2,
						},
 						{
							name = "cloakriot",
							x = 9698,
							z = 1661,
							facing = 1,
						},
 						{
							name = "cloakriot",
							x = 8698,
							z = 1091,
							facing = 2,
						},
 						{
							name = "cloakarty",
							x = 7935,
							z = 1774,
							facing = 3,
						},
 						{
							name = "cloakarty",
							x = 9072,
							z = 1456,
							facing = 1,
						},
 						{
							name = "cloakskirm",
							x = 7818,
							z = 1680,
							facing = 3,
						},
 						{
							name = "cloakskirm",
							x = 9070,
							z = 1490,
							facing = 1,
						},
					}
				},
				{
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					humanName = "Automaton",
					commanderParameters = {
						facplop = false,
					},
					allyTeam = 2,
					unlocks = {
						"vehscout",
						"vehraid",
						"vehriot",
						"vehassault",
						"vehsupport",
						"vehaa",
						"shieldraid",
						"shieldskirm",
						"shieldriot",
						"shieldassault",
						"shieldaa",
					},
					commander = false,
					startUnits = {
						-- {
							-- name = "striderbantha",
							-- x = 8163,
							-- z = 9240,
							-- facing = 2,
						-- },
						{
							name = "striderdetriment",
							x = 8163,
							z = 9240,
							facing = 2,
						},
 						{
							name = "staticheavyradar",
							x = 6272,
							z = 5984,
							facing = 0,
						},
 						{
							name = "staticheavyradar",
							x = 4832,
							z = 1456,
							facing = 0,
						},
 						{
							name = "staticheavyradar",
							x = 16,
							z = 7232,
							facing = 0,
						},
 						{
							name = "staticheavyradar",
							x = 4848,
							z = 9552,
							facing = 0,
						},
 						{
							name = "staticheavyradar",
							x = 10208,
							z = 3520,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 8600,
							z = 8816,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 10040,
							z = 8584,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 9960,
							z = 8632,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 9912,
							z = 8552,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 9992,
							z = 8504,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 8904,
							z = 8832,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 8904,
							z = 8560,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 8616,
							z = 8560,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9672,
							z = 7528,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 9736,
							z = 7544,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 9656,
							z = 7592,
							facing = 2,
						},
						{
							name = "staticcon",
							x = 8760,
							z = 8680,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 9608,
							z = 7512,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 9688,
							z = 7464,
							facing = 0,
						},
 						{
							name = "factoryshield",
							x = 9928,
							z = 8016,
							facing = 3,
						},
 						{
							name = "turretaaflak",
							x = 9944,
							z = 7880,
							facing = 3,
						},
 						{
							name = "turretaaflak",
							x = 9944,
							z = 8168,
							facing = 3,
						},
 						{
							name = "staticheavyradar",
							x = 8608,
							z = 9856,
							facing = 0,
						},
 						{
							name = "shieldraid",
							x = 8010,
							z = 9118,
							facing = 1,
						},
 						{
							name = "shieldraid",
							x = 8209,
							z = 9427,
							facing = 2,
						},
 						{
							name = "shieldraid",
							x = 8009,
							z = 9347,
							facing = 2,
						},
 						{
							name = "shieldraid",
							x = 8230,
							z = 9096,
							facing = 1,
						},
 						{
							name = "shieldraid",
							x = 8303,
							z = 9251,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 2008,
							z = 9224,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2328,
							z = 9304,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1464,
							z = 8552,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 1704,
							z = 8600,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 1880,
							z = 8376,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 2120,
							z = 9208,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 2232,
							z = 9112,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 2248,
							z = 9240,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 1576,
							z = 8584,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 1784,
							z = 8488,
							facing = 3,
						},
 						{
							name = "factoryveh",
							x = 1768,
							z = 8952,
							facing = 1,
						},
 						{
							name = "vehraid",
							x = 1037,
							z = 8082,
							facing = 3,
						},
 						{
							name = "vehraid",
							x = 2428,
							z = 9020,
							facing = 1,
						},
 						{
							name = "vehraid",
							x = 1556,
							z = 8285,
							facing = 2,
						},
 						{
							name = "vehsupport",
							x = 2197,
							z = 8502,
							facing = 1,
						},
 						{
							name = "vehsupport",
							x = 2868,
							z = 9365,
							facing = 1,
						},
 						{
							name = "striderdante",
							x = 1576,
							z = 8725,
							facing = 0,
							difficultyAtLeast = 3,
						},
 						{
							name = "shieldraid",
							x = 5243,
							z = 4884,
							facing = 0,
						},
 						{
							name = "turretaaclose",
							x = 1576,
							z = 8776,
							facing = 1,
						},
 						{
							name = "turretaaclose",
							x = 1800,
							z = 9144,
							facing = 1,
						},
 						{
							name = "turretaaclose",
							x = 2072,
							z = 8680,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 1624,
							z = 8440,
							facing = 2,
						},
 						{
							name = "turretriot",
							x = 2104,
							z = 9336,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 2392,
							z = 9160,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 112,
							z = 7184,
							facing = 1,
						},
 						{
							name = "shieldraid",
							x = 5260,
							z = 4995,
							facing = 0,
						},
 						{
							name = "shieldraid",
							x = 5349,
							z = 5144,
							facing = 0,
						},
 						{
							name = "shieldraid",
							x = 5502,
							z = 5072,
							facing = 0,
						},
 						{
							name = "shieldraid",
							x = 5547,
							z = 4903,
							facing = 0,
						},
 						{
							name = "shieldraid",
							x = 5390,
							z = 4854,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 4944,
							z = 1344,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 10208,
							z = 3424,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 6288,
							z = 5936,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 4768,
							z = 9584,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 3704,
							z = 1256,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 2040,
							z = 2808,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 2408,
							z = 2744,
							facing = 0,
						},
 						{
							name = "turretemp",
							x = 1472,
							z = 5552,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 1360,
							z = 5584,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 1568,
							z = 5648,
							facing = 2,
						},
 						{
							name = "turretriot",
							x = 2488,
							z = 7096,
							facing = 2,
						},
					}
				},
			},
			neutralUnits = {
				{
					name = "pw_metal",
					x = 8736,
					z = 8096,
					facing = 0,
					invincible = true,
					ignoredByAI = true,
				},
				{
					name = "pw_warpgate",
					x = 9392,
					z = 8696,
					facing = 0,
					invincible = true,
					ignoredByAI = true,
				},
				{
					name = "pw_inhibitor",
					x = 9400,
					z = 8088,
					facing = 0,
					invincible = true,
					ignoredByAI = true,
				},
				{
					name = "pw_mstorage2",
					x = 9400,
					z = 8216,
					facing = 0,
					invincible = true,
					ignoredByAI = true,
				},
				{
					name = "pw_mstorage2",
					x = 9400,
					z = 7960,
					facing = 0,
					invincible = true,
					ignoredByAI = true,
				},
				{
					name = "pw_bomberfac",
					x = 1216,
					z = 8984,
					facing = 0,
					invincible = true,
					ignoredByAI = true,
				},
			},
			initialWrecks = {
				{
					name = "spiderassault_dead",
					x = 445,
					z = 3774,
					facing = 0,
				},
				{
					name = "spiderassault_dead",
					x = 539,
					z = 3668,
					facing = 0,
				},
				{
					name = "spiderassault_dead",
					x = 718,
					z = 3714,
					facing = 0,
				},
				{
					name = "spiderassault_dead",
					x = 647,
					z = 4007,
					facing = 0,
				},
				{
					name = "spiderassault_dead",
					x = 365,
					z = 3586,
					facing = 0,
				},
				{
					name = "tankassault_dead",
					x = 3904,
					z = 7102,
					facing = 0,
				},
				{
					name = "tankassault_dead",
					x = 4111,
					z = 7237,
					facing = 0,
				},
				{
					name = "tankassault_dead",
					x = 4402,
					z = 7284,
					facing = 0,
				},
				{
					name = "shieldarty_dead",
					x = 4956,
					z = 2606,
					facing = 0,
				},
				{
					name = "shieldarty_dead",
					x = 5008,
					z = 2888,
					facing = 0,
				},
				{
					name = "shieldskirm_dead",
					x = 5093,
					z = 2758,
					facing = 0,
				},
				{
					name = "shieldskirm_dead",
					x = 5075,
					z = 2614,
					facing = 0,
				},
				{
					name = "shieldskirm_dead",
					x = 4916,
					z = 3232,
					facing = 0,
				},
				{
					name = "shieldskirm_dead",
					x = 4922,
					z = 3065,
					facing = 0,
				},
				{
					name = "cloakraid_dead",
					x = 1261,
					z = 1984,
					facing = 0,
				},
				{
					name = "cloakraid_dead",
					x = 1396,
					z = 1938,
					facing = 0,
				},
				{
					name = "cloakraid_dead",
					x = 1490,
					z = 1798,
					facing = 0,
				},
				{
					name = "cloakraid_dead",
					x = 1386,
					z = 1799,
					facing = 0,
				},
				{
					name = "cloakraid_dead",
					x = 1542,
					z = 1696,
					facing = 0,
				},
				{
					name = "cloakraid_dead",
					x = 1669,
					z = 1780,
					facing = 0,
				},
				{
					name = "cloakraid_dead",
					x = 1869,
					z = 1633,
					facing = 0,
				},
				{
					name = "cloakraid_dead",
					x = 1809,
					z = 1589,
					facing = 0,
				},
				{
					name = "cloakraid_dead",
					x = 1903,
					z = 1440,
					facing = 0,
				},
				{
					name = "cloakraid_dead",
					x = 1987,
					z = 1323,
					facing = 0,
				},
				{
					name = "cloakraid_dead",
					x = 1634,
					z = 1514,
					facing = 0,
				},
				{
					name = "tankarty_dead",
					x = 4288,
					z = 7124,
					facing = 0,
				},
				{
					name = "striderscorpion_dead",
					x = 6176,
					z = 8172,
					facing = 0,
				},
				{
					name = "spideremp_dead",
					x = 6028,
					z = 8077,
					facing = 0,
				},
				{
					name = "spideremp_dead",
					x = 6337,
					z = 8319,
					facing = 0,
				},
				{
					name = "spideremp_dead",
					x = 6319,
					z = 8067,
					facing = 0,
				},
				{
					name = "jumpsumo_dead",
					x = 9953,
					z = 5034,
					facing = 0,
				},
				{
					name = "jumpraid_dead",
					x = 9765,
					z = 5023,
					facing = 0,
				},
				{
					name = "hoverskirm_dead",
					x = 5966,
					z = 3317,
					facing = 0,
				},
				{
					name = "hoverskirm_dead",
					x = 6115,
					z = 3430,
					facing = 0,
				},
				{
					name = "hoverskirm_dead",
					x = 6168,
					z = 3562,
					facing = 0,
				},
				{
					name = "hoverraid_dead",
					x = 6140,
					z = 3604,
					facing = 0,
				},
				{
					name = "hoverraid_dead",
					x = 6197,
					z = 3766,
					facing = 0,
				},
				{
					name = "hoverraid_dead",
					x = 5984,
					z = 3643,
					facing = 0,
				},
				{
					name = "hoverraid_dead",
					x = 6086,
					z = 3300,
					facing = 0,
				},
				{
					name = "shieldriot_dead",
					x = 2187,
					z = 4230,
					facing = 0,
				},
				{
					name = "shieldassault_dead",
					x = 2123,
					z = 4185,
					facing = 0,
				},
				{
					name = "shieldassault_dead",
					x = 2224,
					z = 4253,
					facing = 0,
				},
				{
					name = "staticmex_dead",
					x = 2184,
					z = 232,
					facing = 0,
				},
				{
					name = "staticmex_dead",
					x = 2296,
					z = 776,
					facing = 0,
				},
				{
					name = "staticmex_dead",
					x = 472,
					z = 3896,
					facing = 0,
				},
				{
					name = "staticmex_dead",
					x = 680,
					z = 3480,
					facing = 0,
				},
				{
					name = "staticmex_dead",
					x = 4472,
					z = 2616,
					facing = 0,
				},
				{
					name = "cloakheavyraid_dead",
					x = 177,
					z = 8212,
					facing = 0,
				},
				{
					name = "cloakheavyraid_dead",
					x = 236,
					z = 8433,
					facing = 0,
				},
				{
					name = "cloakheavyraid_dead",
					x = 201,
					z = 8782,
					facing = 0,
				},
				{
					name = "cloakheavyraid_dead",
					x = 402,
					z = 9086,
					facing = 0,
				},
				{
					name = "cloakheavyraid_dead",
					x = 666,
					z = 9326,
					facing = 0,
				},
				{
					name = "cloakheavyraid_dead",
					x = 542,
					z = 9319,
					facing = 0,
				},
				{
					name = "cloakassault_dead",
					x = 6973,
					z = 456,
					facing = 0,
				},
				{
					name = "cloakassault_dead",
					x = 7115,
					z = 435,
					facing = 0,
				},
				{
					name = "cloakassault_dead",
					x = 7664,
					z = 93,
					facing = 0,
				},
				{
					name = "cloakassault_dead",
					x = 7831,
					z = 138,
					facing = 0,
				},
				{
					name = "amphfloater_dead",
					x = 6853,
					z = 6532,
					facing = 0,
				},
				{
					name = "amphfloater_dead",
					x = 7072,
					z = 6444,
					facing = 0,
				},
				{
					name = "amphfloater_dead",
					x = 7277,
					z = 6663,
					facing = 0,
				},
				{
					name = "amphfloater_dead",
					x = 7697,
					z = 6120,
					facing = 0,
				},
				{
					name = "amphfloater_dead",
					x = 7753,
					z = 5838,
					facing = 0,
				},
			},
			defeatConditionConfig = {
				-- Indexed by allyTeam.
				[0] = { },
				[1] = {
					ignoreUnitLossDefeat = true,
					loseAfterSeconds = false,
				},
				[2] = {
					ignoreUnitLossDefeat = false,
					vitalCommanders = false,
					vitalUnitTypes = {
						"striderdetriment",
					},
					loseAfterSeconds = false,
					allyTeamLossObjectiveID = 1,
					defeatOtherAllyTeamsOnLoss = {1},
					doNotExplodeOnLoss = true,
				},
			},
			objectiveConfig = {
				[1] = {
					description = "Destroy the enemy Detriment",
				},
				[2] = {
					description = "Protect your Commander",
				},
			},
			bonusObjectiveConfig = {
				[1] = { --
					satisfyByTime = 600,
					comparisionType = planetUtilities.COMPARE.AT_MOST,
					targetNumber = 0,
					enemyUnitTypes = {
						"factoryveh",
						"factoryshield",
					},
					image = planetUtilities.ICON_DIR .. "factoryshield.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.ATTACK,
					description = "Destroy the Automaton Factories before 10:00",
					experience = planetUtilities.BONUS_EXP,
				},
				[2] = { -- Win by 20:00
					victoryByTime = 1200,
					image = planetUtilities.ICON_OVERLAY.CLOCK,
					description = "Win by 20:00",
					experience = planetUtilities.BONUS_EXP,
				},
				[3] = { --
					satisfyForever = true,
					comparisionType = planetUtilities.COMPARE.AT_MOST,
					targetNumber = 0,
					unitTypes = {
						"factorycloak",
						"factoryshield",
						"factoryjump",
						"factoryamph",
						"factoryspider",
						"factoryveh",
						"factoryhover",
						"factorytank",
						"factoryplane",
						"factorygunship",
						"factoryship",
					},
					image = planetUtilities.ICON_DIR .. "factoryspider.png",
					--imageOverlay = planetUtilities.ICON_DIR .. "module_none",
					description = "Don't have any Factories",
					experience = planetUtilities.BONUS_EXP,
				},
			},
		},
		completionReward = {
			experience = planetUtilities.MAIN_EXP,
			units = {
				"striderhub",
				"athena",
			},
			modules = {
				"module_resurrect"
			},
			abilities = {
			},
			codexEntries = {
				"faction_rebels",
				"faction_dynasty",
				"anomaly_deuliah",
			},
		},
	}
	
	return planetData
end

return GetPlanet
