--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Planet config

local function GetPlanet(planetUtilities, planetID)
	
	local image = LUA_DIRNAME .. "images/planets/ocean03.png"
	
	local planetData = {
		name = "Sapphire",
		startingPlanet = false,
		mapDisplay = {
			x = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][1]) or 0.74,
			y = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][2]) or 0.32,
			image = image,
			size = planetUtilities.PLANET_SIZE_MAP,
		},
		infoDisplay = {
			image = image,
			size = planetUtilities.PLANET_SIZE_INFO,
			backgroundImage = planetUtilities.backgroundImages[math.floor(math.random()*#planetUtilities.backgroundImages) + 1],
			terrainType = "Crystalline",
			radius = "6700 km",
			primary = "Malnoa",
			primaryType = "B5II",
			milRating = 1,
			feedbackLink = "http://zero-k.info/Forum/Thread/24614",
			text = "Not wanting to risk damaging the unique environment of this strange crystalline planet, the Empire refrained from exterminating the Chicken swarm laying there, periodically culling them instead."
			.. "\n "
			.. "\nScience teams were sent to study both planet and Chicken - and maybe find a way to control them. As far as is known, no one has ever succeeded at such task, but there have always been others to keep trying."
			,
			extendedText = "This is a nightmare. Somehow a Queen subjugated the army stationed here to cull them! What have these fools done, while attempting to control it?"
			.. "\n "
			.. "\nWhatever happens, I must hold on to this Tech Lab long enough to download their data."
		},
		tips = {
			{
				image = "unitpics/turretheavy.png",
				text = [[The Desolator turret is the final word in general-purpose defensive emplacements. It has a massive cannon, a heat ray sidearm, and the ability to armor up against artillery fire. Its only weakness is that it must be connected to a large energy grid.]]
			},
			{
				image = "unitpics/turretantiheavy.png",
				text = [[Lucifer tachyon projectors fire an incredibly powerful beam at a single target. It requires an energy grid connection and the refire rate is low, so this turret is not so effective against groups of smaller targets.]]
			},
			{
				image = "unitpics/turretaaheavy.png",
				text = [[The Artemis fires incredibly powerful anti-air missiles at long range. Each missile takes 20 seconds to produce, but they can be fired in quick succession.]]
			},
			{
				image = "unitpics/energysingu.png",
				text = [[Of all energy producers the Singularity Reactor is the most powerful. Make sure to protect them against enemy attack; if a Singularity Reactor is destroyed the explosion is liable to destroy most of your base.]]
			},
		},
		gameConfig = {
			mapName = "SapphireShores_Dry_V2.2",
			modoptions = {
				graceperiod = 4,
				chicken_nominiqueen = 1,
				chicken_minaggro = 5,	-- aggro influences chicken tech-up rate (and queen time reduction from killing burrows, but queens are disabled here)
				chicken_maxaggro = 5,
				chicken_endless = 1,
				chicken_hidepanel = 1,
				chicken_nowavemessages = 1,
				campaign_chicken_types_special = {},
			},
			modoptionDifficulties = {
				[1] = {
					chickenspawnrate = 70,
					burrowspawnrate = 300,
					campaign_chicken_types_offense = {
						chicken				=  {time = -60,  squadSize = 3, obsolete = 12},
						chicken_pigeon		=  {time = 3,  squadSize = 1.4, obsolete = 15},
						chickens			=  {time = 6,  squadSize = 1, obsolete = 18},
						chickena			=  {time = 9,  squadSize = 0.5, obsolete = 21},
						chickenr			=  {time = 12,  squadSize = 1.2, obsolete = 24},
						chicken_leaper	=  {time = 12,  squadSize = 1.0, obsolete = 27},
						chicken_roc			=  {time = 15,  squadSize = 0.4},
						chicken_sporeshooter=  {time = 15,  squadSize = 0.5},
						chickenf			=  {time = 18,  squadSize = 0.5},
						chickenc			=  {time = 18,  squadSize = 0.5},
						chickenblobber		=  {time = 21,  squadSize = 0.3},
						chicken_blimpy		=  {time = 24,  squadSize = 0.2},
						chicken_tiamat		=  {time = 24,  squadSize = 0.2},
					},
					campaign_chicken_types_defense = {
						chickend = {time = 4, squadSize = 0.6, cost = 1 },
						chicken_rafflesia =  {time = 8, squadSize = 0.4, cost = 2 },
					},
					campaign_chicken_types_support = {
						chicken_shield =  {time = 18, squadSize = 0.4},
						chicken_dodo = {time = 4, squadSize = 2},
						chicken_spidermonkey =  {time = 18, squadSize = 0.6},
					},
				},
				[2] = {
					chickenspawnrate = 60,
					burrowspawnrate = 280,
					campaign_chicken_types_offense = {
						chicken				=  {time = -60,  squadSize = 3*1.1, obsolete = 12},
						chicken_pigeon		=  {time = 3,  squadSize = 1.4*1.1, obsolete = 15},
						chickens			=  {time = 6,  squadSize = 1*1.1, obsolete = 18},
						chickena			=  {time = 9,  squadSize = 0.5*1.1, obsolete = 21},
						chickenr			=  {time = 12,  squadSize = 1.2*1.1, obsolete = 24},
						chicken_leaper	=  {time = 12,  squadSize = 1.0*1.1, obsolete = 27},
						chicken_roc			=  {time = 15,  squadSize = 0.4*1.1},
						chicken_sporeshooter=  {time = 15,  squadSize = 0.5*1.1},
						chickenf			=  {time = 18,  squadSize = 0.5*1.1},
						chickenc			=  {time = 18,  squadSize = 0.5*1.1},
						chickenblobber		=  {time = 21,  squadSize = 0.3*1.1},
						chicken_blimpy		=  {time = 24,  squadSize = 0.2*1.1},
						chicken_tiamat		=  {time = 24,  squadSize = 0.2*1.1},
					},
					campaign_chicken_types_defense = {
						chickend = {time = 4, squadSize = 0.6, cost = 1 },
						chicken_rafflesia =  {time = 8, squadSize = 0.4, cost = 2 },
					},
					campaign_chicken_types_support = {
						chicken_shield =  {time = 16, squadSize = 0.4},
						chicken_dodo = {time = 4, squadSize = 2},
						chicken_spidermonkey =  {time = 16, squadSize = 0.6},
					},
				},
				[3] = {
					chickenspawnrate = 55,
					burrowspawnrate = 260,
					campaign_chicken_types_offense = {
						chicken				=  {time = -60,  squadSize = 3*1.25, obsolete = 12},
						chicken_pigeon		=  {time = 3,  squadSize = 1.4*1.25, obsolete = 15},
						chickens			=  {time = 6,  squadSize = 1*1.25, obsolete = 18},
						chickena			=  {time = 9,  squadSize = 0.5*1.25, obsolete = 21},
						chickenr			=  {time = 12,  squadSize = 1.2*1.25, obsolete = 24},
						chicken_leaper	=  {time = 12,  squadSize = 1.0*1.25, obsolete = 27},
						chicken_roc			=  {time = 15,  squadSize = 0.4*1.25},
						chicken_sporeshooter=  {time = 15,  squadSize = 0.5*1.25},
						chickenf			=  {time = 18,  squadSize = 0.5*1.25},
						chickenc			=  {time = 18,  squadSize = 0.5*1.25},
						chickenblobber		=  {time = 21,  squadSize = 0.3*1.25},
						chicken_blimpy		=  {time = 24,  squadSize = 0.2*1.25},
						chicken_tiamat		=  {time = 24,  squadSize = 0.2*1.25},
					},
					campaign_chicken_types_defense = {
						chickend = {time = 4, squadSize = 0.6, cost = 1 },
						chicken_rafflesia =  {time = 8, squadSize = 0.4, cost = 2 },
					},
					campaign_chicken_types_support = {
						chicken_shield =  {time = 14, squadSize = 0.4},
						chicken_dodo = {time = 4, squadSize = 2},
						chicken_spidermonkey =  {time = 14, squadSize = 0.6},
					},
				},
				[4] = {
					chickenspawnrate = 45,
					burrowspawnrate = 240,
					campaign_chicken_types_offense = {
						chicken				=  {time = -60,  squadSize = 3*1.4, obsolete = 12},
						chicken_pigeon		=  {time = 3,  squadSize = 1.4*1.4, obsolete = 15},
						chickens			=  {time = 6,  squadSize = 1*1.4, obsolete = 18},
						chickena			=  {time = 9,  squadSize = 0.5*1.4, obsolete = 21},
						chickenr			=  {time = 12,  squadSize = 1.2*1.4, obsolete = 24},
						chicken_leaper	=  {time = 12,  squadSize = 1.0*1.4, obsolete = 27},
						chicken_roc			=  {time = 15,  squadSize = 0.4*1.4},
						chicken_sporeshooter=  {time = 15,  squadSize = 0.5*1.4},
						chickenf			=  {time = 18,  squadSize = 0.5*1.4},
						chickenc			=  {time = 18,  squadSize = 0.5*1.4},
						chickenblobber		=  {time = 21,  squadSize = 0.3*1.4},
						chicken_blimpy		=  {time = 24,  squadSize = 0.2*1.4},
						chicken_tiamat		=  {time = 24,  squadSize = 0.2*1.4},
					},
					campaign_chicken_types_defense = {
						chickend = {time = 4, squadSize = 0.6, cost = 1 },
						chicken_rafflesia =  {time = 8, squadSize = 0.4, cost = 2 },
					},
					campaign_chicken_types_support = {
						chicken_shield =  {time = 12, squadSize = 0.4},
						chicken_dodo = {time = 4, squadSize = 2},
						chicken_spidermonkey =  {time = 12, squadSize = 0.6},
					},
				},
			},
			playerConfig = {
				startX = 8200,
				startZ = 2100,
				allyTeam = 0,
				commanderParameters = {
					facplop = true,
					defeatIfDestroyedObjectiveID = 2,
				},
				extraUnlocks = {
					"turretheavy",
					"turretantiheavy",
					"energysingu",
					"turretaaheavy",
				},
				startUnits = {
					{
						name = "staticantinuke",
						x = 8200,
						z = 2300,
						facing = 1,
					},
					{
						name = "staticmex",
						x = 8552,
						z = 1048,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 1208,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 3176,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 3176,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 3096,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 3096,
						facing = 3,
					},
 					{
						name = "staticmex",
						x = 8568,
						z = 3288,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 1128,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 3016,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 3016,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 2936,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 2936,
						facing = 3,
					},
 					{
						name = "staticmex",
						x = 8568,
						z = 2152,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9016,
						z = 1128,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 1128,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 2856,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 2856,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8280,
						z = 4072,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 1896,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 2776,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9016,
						z = 136,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 2776,
						facing = 3,
					},
 					{
						name = "pw_techlab",
						x = 8656,
						z = 3032,
						facing = 0,
						defeatIfDestroyedObjectiveID = 1,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 1896,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 968,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 136,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9016,
						z = 1048,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 2696,
						facing = 3,
					},
 					{
						name = "staticmex",
						x = 8408,
						z = 3656,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 2696,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 136,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 2616,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 2616,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9016,
						z = 1288,
						facing = 3,
					},
 					{
						name = "staticmex",
						x = 8376,
						z = 2936,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8840,
						z = 3912,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8760,
						z = 3912,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9016,
						z = 1208,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 56,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8680,
						z = 3912,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 2536,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 56,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8600,
						z = 3912,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 2536,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9016,
						z = 56,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8936,
						z = 56,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8520,
						z = 3912,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 2456,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 2456,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8440,
						z = 3912,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8856,
						z = 56,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 1048,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8360,
						z = 3912,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8776,
						z = 56,
						facing = 3,
					},
 					{
						name = "staticmex",
						x = 8456,
						z = 2552,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8696,
						z = 56,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 2376,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8280,
						z = 3912,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 2376,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8280,
						z = 3992,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8616,
						z = 56,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8360,
						z = 3992,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 2296,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8440,
						z = 3992,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8536,
						z = 56,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 2296,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8520,
						z = 3992,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 968,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8456,
						z = 56,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8600,
						z = 3992,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 1048,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8376,
						z = 56,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8680,
						z = 3992,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 2216,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 2216,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8296,
						z = 56,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8760,
						z = 3992,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8296,
						z = 136,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 2136,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8376,
						z = 136,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8840,
						z = 3992,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 2136,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8456,
						z = 136,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8840,
						z = 4072,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9016,
						z = 968,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8536,
						z = 136,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8760,
						z = 4072,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8680,
						z = 4072,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 1208,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8616,
						z = 136,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8600,
						z = 4072,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 2056,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 2056,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8696,
						z = 136,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8520,
						z = 4072,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 1976,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8776,
						z = 136,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8440,
						z = 4072,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 1976,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 1288,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8856,
						z = 136,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8360,
						z = 4072,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 1288,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8936,
						z = 136,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8936,
						z = 1288,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8856,
						z = 1288,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8856,
						z = 1368,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8936,
						z = 1368,
						facing = 3,
					},
 					{
						name = "energysingu",
						x = 8712,
						z = 3592,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9016,
						z = 1368,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 1368,
						facing = 3,
					},
 					{
						name = "energypylon",
						x = 8296,
						z = 3432,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 9176,
						z = 1368,
						facing = 3,
					},
 					{
						name = "energysingu",
						x = 8776,
						z = 1832,
						facing = 3,
					},
 					{
						name = "energypylon",
						x = 8552,
						z = 2632,
						facing = 3,
					},
 					{
						name = "staticmex",
						x = 8520,
						z = 1832,
						facing = 3,
					},
 					{
						name = "energypylon",
						x = 8408,
						z = 1672,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8296,
						z = 216,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8376,
						z = 216,
						facing = 3,
					},
 					{
						name = "turretheavy",
						x = 8072,
						z = 2440,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8456,
						z = 216,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8456,
						z = 296,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8376,
						z = 296,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8296,
						z = 296,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8296,
						z = 376,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8376,
						z = 376,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8456,
						z = 376,
						facing = 3,
					},
 					{
						name = "turretantiheavy",
						x = 7984,
						z = 1344,
						facing = 3,
						terraformHeight = 629,
					},
 					{
						name = "turretantiheavy",
						x = 7920,
						z = 3104,
						facing = 3,
						terraformHeight = 626,
					},
 					{
						name = "turretheavy",
						x = 7912,
						z = 3656,
						facing = 3,
					},
 					{
						name = "energypylon",
						x = 8168,
						z = 808,
						facing = 3,
					},
 					{
						name = "turretheavy",
						x = 7912,
						z = 408,
						facing = 3,
					},
 					{
						name = "turretaaheavy",
						x = 8096,
						z = 2832,
						facing = 3,
					},
 					{
						name = "staticmex",
						x = 8408,
						z = 696,
						facing = 0,
					},
 					{
						name = "tankcon",
						x = 8092,
						z = 1960,
						facing = 0,
					},
 					{
						name = "tankcon",
						x = 8098,
						z = 2051,
						facing = 0,
					},
 					{
						name = "spidercon",
						x = 8084,
						z = 1879,
						facing = 0,
					},
 					{
						name = "spidercon",
						x = 8085,
						z = 2127,
						facing = 0,
					},
 					{
						name = "staticcon",
						x = 8216,
						z = 1752,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8216, 1752}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8191, 1777}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 8296,
						z = 1752,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8296, 1752}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8271, 1777}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 8376,
						z = 1752,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8376, 1752}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8351, 1777}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 8376,
						z = 1832,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8376, 1832}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8351, 1857}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 8296,
						z = 1832,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8296, 1832}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8271, 1857}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 8216,
						z = 1832,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8216, 1832}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8191, 1857}, options = {"shift"}},
						},
					},
 					{
						name = "staticheavyradar",
						x = 8016,
						z = 2560,
						facing = 1,
					},
				}
			},
			aiConfig = {
				{
					startX = 660,
					startZ = 1070,
					aiLib = "Circuit_difficulty_autofill",
					humanName = "Directorate",
					bitDependant = true,
					commanderParameters = {
						facplop = false,
					},
					allyTeam = 1,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energypylon",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turrettorp",
						"turretgauss",
						"turretheavylaser",
						"turretaalaser",
						"turretaaclose",
						"turretaaflak",
						"shieldshield",
						"staticradar",
						"staticheavyradar",
						"staticcon",
						"staticantinuke",
						"staticrearm",
						"turretaafar",
						"turretheavy",
						"factorycloak",
						"cloakcon",
						"cloakraid",
						"cloakriot",
						"cloakskirm",
						"cloakassault",
						"cloakaa",
						"cloakarty",
						"cloaksnipe",
						"cloakheavyraid",
						"cloakbomb",
						"factoryshield",
						"shieldcon",
						"shieldraid",
						"shieldassault",
						"shieldriot",
						"shieldskirm",
						"shieldbomb",
						"shieldaa",
						"shieldfelon",
						"shieldshield",
						"shieldarty",
						"factorytank",
						"tankcon",
						"tankassault",
						"tankheavyassault",
						"tankarty",
						"tankheavyarty",
						"tankaa",
						"tankriot",
						"factoryamph",
						"amphcon",
						"amphraid",
						"amphimpulse",
						"amphfloater",
						"amphriot",
						"amphassault",
						"amphbomb",
						"amphaa",
						"factoryplane",
						"planecon",
						"planescout",
						"planefighter",
						"planeheavyfighter",
						"bomberprec",
						"bomberdisarm",
						"bomberheavy",
						"striderhub",
						"striderdante",
						"striderarty",
						"striderfunnelweb",
						"striderscorpion",
						"striderantiheavy",
						"striderbantha",
					},
					difficultyDependantUnlocks = {
						[3] = {"staticnuke"},
						[4] = {"staticnuke","staticheavyarty"},
					},
					commanderLevel = 6,
					commander = {
						name = "Dekki",
						chassis = "recon",
						decorations = {
						  "skin_recon_dark",
						},
						modules = {
							"commweapon_lightninggun",
							"commweapon_concussion",
							"module_autorepair",
							"module_autorepair",
							"module_autorepair",
							"module_autorepair",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_adv_nano",
							"module_adv_nano",
							"module_adv_nano",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
						}
					},
					midgameUnits = {
						{
							name = "nebula",
							x = 1600,
							z = 900,
							facing = 0,
							spawnRadius = 50,
							delay = 15*30*60,
							orbitalDrop = true,
						},
						{
							name = "nebula",
							x = 1600,
							z = 900,
							facing = 0,
							spawnRadius = 50,
							delay = 15*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 4,
						},
						{
							name = "nebula",
							x = 1600,
							z = 2200,
							facing = 0,
							spawnRadius = 50,
							delay = 15*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 2,
						},
						{
							name = "nebula",
							x = 1600,
							z = 2200,
							facing = 0,
							spawnRadius = 50,
							delay = 15*30*60,
							orbitalDrop = true,
						},
						{
							name = "nebula",
							x = 1600,
							z = 2200,
							facing = 0,
							spawnRadius = 50,
							delay = 15*30*60,
							orbitalDrop = true,
						},
						{
							name = "chicken_dragon",
							x = 1600,
							z = 900,
							facing = 0,
							spawnRadius = 50,
							delay = 19*30*60,
							orbitalDrop = true,
						},
						{
							name = "chicken_dragon",
							x = 1600,
							z = 2200,
							facing = 0,
							spawnRadius = 50,
							delay = 19*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 3,
						},
						{
							name = "striderbantha",
							x = 1600,
							z = 900,
							facing = 0,
							spawnRadius = 50,
							delay = 22*30*60,
							orbitalDrop = true,
						},
						{
							name = "striderbantha",
							x = 1600,
							z = 2200,
							facing = 0,
							spawnRadius = 50,
							delay = 22*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 2,
						},
						{
							name = "chickenflyerqueen",
							x = 2500,
							z = 2200,
							facing = 0,
							spawnRadius = 50,
							delay = 28*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 1,
							difficultyAtMost = 1,
						},
						{
							name = "striderdetriment",
							x = 2700,
							z = 2200,
							facing = 0,
							spawnRadius = 50,
							delay = 28*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 1,
							difficultyAtMost = 1,
						},
						{
							name = "chickenflyerqueen",
							x = 2500,
							z = 2200,
							facing = 0,
							spawnRadius = 50,
							delay = 27.5*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 2,
							difficultyAtMost = 2,
						},
						{
							name = "striderdetriment",
							x = 2700,
							z = 2200,
							facing = 0,
							spawnRadius = 50,
							delay = 27.5*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 2,
							difficultyAtMost = 2,
						},
						{
							name = "chickenflyerqueen",
							x = 2500,
							z = 2200,
							facing = 0,
							spawnRadius = 50,
							delay = 26.75*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 3,
							difficultyAtMost = 3,
						},
						{
							name = "striderdetriment",
							x = 2700,
							z = 2200,
							facing = 0,
							spawnRadius = 50,
							delay = 26.75*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 3,
							difficultyAtMost = 3,
						},
						{
							name = "chickenflyerqueen",
							x = 2500,
							z = 2200,
							facing = 0,
							spawnRadius = 50,
							delay = 26*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 4,
							difficultyAtMost = 4,
						},
						{
							name = "striderdetriment",
							x = 2700,
							z = 2200,
							facing = 0,
							spawnRadius = 50,
							delay = 26*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 4,
							difficultyAtMost = 4,
						},
					},
					startUnits = {
						{
							name = "gunshipcon",
							x = 1781,
							z = 2749,
							facing = 0,
						},
 						{
							name = "staticantinuke",
							x = 496,
							z = 1576,
							facing = 1,
						},
 						{
							name = "gunshipcon",
							x = 1023,
							z = 2797,
							facing = 2,
						},
 						{
							name = "staticantinuke",
							x = 768,
							z = 696,
							facing = 1,
						},
 						{
							name = "energysingu",
							x = 504,
							z = 200,
							facing = 3,
						},
 						{
							name = "staticshield",
							x = 352,
							z = 208,
							facing = 1,
						},
 						{
							name = "staticshield",
							x = 384,
							z = 352,
							facing = 1,
						},
 						{
							name = "factorytank",
							x = 848,
							z = 2448,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 728,
							z = 2424,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {728, 2424}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {753, 2399}, options = {"shift"}},
							},
						},
 						{
							name = "factoryamph",
							x = 1848,
							z = 2728,
							facing = 1,
						},
 						{
							name = "gunshipcon",
							x = 361,
							z = 3805,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1720,
							z = 2680,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1720, 2680}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1745, 2655}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 792,
							z = 2328,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {792, 2328}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {817, 2303}, options = {"shift"}},
							},
						},
 						{
							name = "factorycloak",
							x = 1776,
							z = 504,
							facing = 1,
						},
 						{
							name = "gunshipcon",
							x = 1658,
							z = 527,
							facing = 3,
						},
 						{
							name = "staticshield",
							x = 320,
							z = 3808,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1640,
							z = 536,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1640, 536}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1665, 561}, options = {"shift"}},
							},
						},
 						{
							name = "staticshield",
							x = 1088,
							z = 336,
							facing = 3,
						},
 						{
							name = "staticshield",
							x = 368,
							z = 3936,
							facing = 1,
						},
 						{
							name = "staticshield",
							x = 1040,
							z = 704,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 424,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 424,
							facing = 3,
						},
 						{
							name = "staticshield",
							x = 1056,
							z = 1040,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 424,
							facing = 3,
						},
 						{
							name = "staticshield",
							x = 1088,
							z = 1536,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 424,
							facing = 3,
						},
 						{
							name = "staticshield",
							x = 1008,
							z = 1984,
							facing = 3,
						},
 						{
							name = "staticshield",
							x = 1024,
							z = 2352,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 504,
							facing = 3,
						},
 						{
							name = "staticshield",
							x = 1120,
							z = 2800,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 504,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 504,
							facing = 3,
						},
 						{
							name = "staticshield",
							x = 1184,
							z = 3216,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 504,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 584,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 584,
							facing = 3,
						},
 						{
							name = "staticshield",
							x = 1168,
							z = 3744,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 584,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 584,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 664,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 664,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 664,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 664,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 744,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 744,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 744,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 744,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 824,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 824,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 824,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 824,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 904,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 904,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 904,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 904,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 984,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 984,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 984,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 984,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 1064,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 1064,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 1064,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 1064,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 1144,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 1144,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 1144,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 1144,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 1224,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 1224,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 1224,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 1224,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 1304,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 1304,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 1304,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 1304,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 1384,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 1384,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 1384,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 1384,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 1464,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 1464,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 1464,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 1464,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 1544,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 1544,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 1544,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 1544,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 1624,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 1624,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 1624,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 1624,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 1704,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 1704,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 1704,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 1704,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 1784,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 1784,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 1784,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 1784,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 1864,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 1864,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 1864,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 1864,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 1944,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 1944,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 1944,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 1944,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 2024,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 2024,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 2024,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 2024,
							facing = 3,
						},
 						{
							name = "staticarty",
							x = 1336,
							z = 1448,
							facing = 1,
							terraformHeight = 594,
						},
 						{
							name = "staticarty",
							x = 1336,
							z = 1608,
							facing = 1,
							terraformHeight = 608,
						},
 						{
							name = "energywind",
							x = 264,
							z = 2104,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 2104,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 2104,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 2104,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 2184,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 2184,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 2184,
							facing = 3,
						},
 						{
							name = "staticarty",
							x = 1320,
							z = 1752,
							facing = 1,
							terraformHeight = 610,
						},
 						{
							name = "energywind",
							x = 264,
							z = 2184,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 2264,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 2264,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 2264,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 2264,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 824,
							z = 1576,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 24,
							z = 2344,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 2344,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 2344,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 2344,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 2424,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 2424,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 2424,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 2424,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 2504,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 2504,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 2504,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 2504,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 2584,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 2584,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 2584,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 2584,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 2664,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 2664,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 2664,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 2664,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 344,
							z = 1384,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 264,
							z = 2744,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 344,
							z = 1464,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 184,
							z = 2744,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 2744,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 2744,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 344,
							z = 1544,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 24,
							z = 2824,
							facing = 3,
						},
 						{
							name = "staticarty",
							x = 1448,
							z = 3064,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 104,
							z = 2824,
							facing = 3,
						},
 						{
							name = "staticarty",
							x = 1416,
							z = 3480,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 184,
							z = 2824,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 344,
							z = 1624,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 264,
							z = 2824,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 344,
							z = 1704,
							facing = 1,
						},
 						{
							name = "turretantiheavy",
							x = 1392,
							z = 3264,
							facing = 1,
							terraformHeight = 599,
						},
 						{
							name = "energywind",
							x = 344,
							z = 1784,
							facing = 1,
						},
 						{
							name = "turretheavy",
							x = 1416,
							z = 2968,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 264,
							z = 2904,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 600,
							z = 984,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 184,
							z = 2904,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 2904,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 2904,
							facing = 3,
						},
 						{
							name = "turretheavy",
							x = 1432,
							z = 3608,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 936,
							z = 440,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 24,
							z = 2984,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 2984,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 2984,
							facing = 3,
						},
 						{
							name = "turretheavy",
							x = 1224,
							z = 2296,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 1112,
							z = 3592,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 600,
							z = 2344,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 1000,
							z = 2840,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 264,
							z = 2984,
							facing = 3,
						},
 						{
							name = "turretheavy",
							x = 1224,
							z = 2040,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 264,
							z = 3064,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 520,
							z = 3192,
							facing = 1,
						},
 						{
							name = "turretantiheavy",
							x = 1264,
							z = 1920,
							facing = 1,
						},
 						{
							name = "turretantiheavy",
							x = 1264,
							z = 2432,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 184,
							z = 3064,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 952,
							z = 2184,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 104,
							z = 3064,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 3064,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 1568,
							z = 2432,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 1584,
							z = 2368,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 24,
							z = 3144,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 1600,
							z = 2304,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 104,
							z = 3144,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 1568,
							z = 1904,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 1600,
							z = 1968,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 1616,
							z = 2048,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 184,
							z = 3144,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 984,
							z = 1016,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 264,
							z = 3144,
							facing = 3,
						},
 						{
							name = "staticshield",
							x = 1056,
							z = 960,
							facing = 1,
						},
 						{
							name = "staticshield",
							x = 1056,
							z = 1104,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 264,
							z = 3224,
							facing = 3,
						},
 						{
							name = "staticshield",
							x = 1040,
							z = 2192,
							facing = 1,
						},
 						{
							name = "staticshield",
							x = 1136,
							z = 1600,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 184,
							z = 3224,
							facing = 3,
						},
 						{
							name = "turretheavy",
							x = 1304,
							z = 1240,
							facing = 1,
						},
 						{
							name = "turretheavy",
							x = 1256,
							z = 1160,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 104,
							z = 3224,
							facing = 3,
						},
 						{
							name = "turretheavy",
							x = 1272,
							z = 712,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 24,
							z = 3224,
							facing = 3,
						},
 						{
							name = "turretheavy",
							x = 1224,
							z = 792,
							facing = 1,
						},
 						{
							name = "turretantiheavy",
							x = 1168,
							z = 976,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 24,
							z = 3304,
							facing = 3,
						},
 						{
							name = "turretantiheavy",
							x = 1376,
							z = 288,
							facing = 1,
						},
 						{
							name = "turretheavy",
							x = 1464,
							z = 3928,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 104,
							z = 3304,
							facing = 3,
						},
 						{
							name = "turretheavy",
							x = 1384,
							z = 376,
							facing = 1,
						},
 						{
							name = "turretaaheavy",
							x = 1088,
							z = 560,
							facing = 1,
						},
 						{
							name = "turretaaheavy",
							x = 1072,
							z = 3440,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 184,
							z = 3304,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 3304,
							facing = 3,
						},
 						{
							name = "turretaaheavy",
							x = 800,
							z = 2128,
							facing = 1,
						},
 						{
							name = "turretaafar",
							x = 1200,
							z = 3040,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 264,
							z = 3384,
							facing = 3,
						},
 						{
							name = "turretaafar",
							x = 992,
							z = 2688,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 184,
							z = 3384,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 3384,
							facing = 3,
						},
 						{
							name = "turretaafar",
							x = 976,
							z = 1360,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 24,
							z = 3384,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 3464,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 3464,
							facing = 3,
						},
 						{
							name = "factoryshield",
							x = 760,
							z = 1104,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 184,
							z = 3464,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 632,
							z = 1096,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {632, 1096}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {657, 1121}, options = {"shift"}},
							},
						},
 						{
							name = "striderhub",
							x = 768,
							z = 1744,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {768, 1744}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {793, 1769}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 632,
							z = 1176,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {632, 1176}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {657, 1201}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 776,
							z = 1832,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {776, 1832}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {801, 1857}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 680,
							z = 1832,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {680, 1832}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {705, 1857}, options = {"shift"}},
							},
						},
 						{
							name = "energywind",
							x = 264,
							z = 3464,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 680,
							z = 1752,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {680, 1752}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {705, 1777}, options = {"shift"}},
							},
						},
 						{
							name = "energywind",
							x = 264,
							z = 3544,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 3544,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 3544,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 3544,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 3624,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 104,
							z = 3624,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 3624,
							facing = 3,
						},
 						{
							name = "staticrearm",
							x = 968,
							z = 3320,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 264,
							z = 3624,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 264,
							z = 3704,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 184,
							z = 3704,
							facing = 3,
						},
 						{
							name = "factoryplane",
							x = 664,
							z = 3344,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 104,
							z = 3704,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 24,
							z = 3704,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 536,
							z = 3320,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {536, 3320}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {561, 3295}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 552,
							z = 3416,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {552, 3416}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {577, 3391}, options = {"shift"}},
							},
						},
 						{
							name = "energysingu",
							x = 440,
							z = 3832,
							facing = 3,
						},
 						{
							name = "staticrearm",
							x = 840,
							z = 3160,
							facing = 1,
						},
 						{
							name = "staticantinuke",
							x = 640,
							z = 2936,
							facing = 1,
						},
 						{
							name = "staticantinuke",
							x = 464,
							z = 2360,
							facing = 1,
						},
					}
				},
				{
					humanName = "Chickens",
					aiLib = "Chicken: Custom",
					bitDependant = false,
					--aiLib = "Null AI",
					--bitDependant = false,
					allyTeam = 1,
					unlocks = {
					},
					commander = false,
					startUnits = {
						{
							name = "roost",
							x = 952,
							z = 840,
							facing = 0,
						},
 						{
							name = "roost",
							x = 2056,
							z = 760,
							facing = 0,
						},
 						{
							name = "roost",
							x = 968,
							z = 2072,
							facing = 0,
						},
 						{
							name = "roost",
							x = 2040,
							z = 2088,
							facing = 0,
						},
 						{
							name = "roost",
							x = 984,
							z = 3128,
							facing = 0,
						},
 						{
							name = "roost",
							x = 2072,
							z = 3112,
							facing = 0,
						},
 						{
							name = "roost",
							x = 2968,
							z = 1176,
							facing = 0,
						},
 						{
							name = "roost",
							x = 2984,
							z = 2040,
							facing = 0,
						},
					}
				},
			},
			defeatConditionConfig = {
				-- Indexed by allyTeam.
				[0] = { },
				[1] = {
					ignoreUnitLossDefeat = false,
					loseAfterSeconds = 30*60,
					allyTeamLossObjectiveID = 1,
				},
			},
			objectiveConfig = {
				-- This is just related to displaying objectives on the UI.
				[1] = {
					description = "Protect the Tech Lab for 30 minutes",
				},
				[2] = {
					description = "Protect your Commander",
				},
			},
			bonusObjectiveConfig = {
				[1] = {
					satisfyOnce = true,
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 5,
					unitTypes = {
						"energysingu",
					},
					image = planetUtilities.ICON_DIR .. "energysingu.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.REPAIR,
					description = "Have 5 Singularity Reactors",
					experience = planetUtilities.BONUS_EXP,
				},
				[2] = { -- Lose no more than 3 grizzlies
					onlyCountRemovedUnits = true,
					satisfyForever = true,
					comparisionType = planetUtilities.COMPARE.AT_MOST,
					targetNumber = 0,
					unitTypes = {
						"turretantiheavy"
					},
					image = planetUtilities.ICON_DIR .. "turretantiheavy.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.GUARD,
					description = "Do not lose any Lucifers",
					experience = planetUtilities.BONUS_EXP,
				},
				[3] = {
					satisfyAfterTime = 10*60,
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 12,
					unitTypes = {
						"staticmex",
					},
					image = planetUtilities.ICON_DIR .. "staticmex.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.REPAIR,
					description = "Have 12 Metal Extractors at all times after 10:00",
					experience = planetUtilities.BONUS_EXP,
				},
			}
		},
		completionReward = {
			experience = planetUtilities.MAIN_EXP,
			units = {
				"turretheavy",
				"turretantiheavy",
				"energysingu",
				"turretaaheavy",
			},
			modules = {
				"module_battle_drone_LIMIT_C_2",
			},
			abilities = {
			},
			codexEntries = {
				"threat_chickens",
				"threat_chickens_intelligence"
			}
		},
	}
	
	return planetData
end

return GetPlanet
