--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Planet config

local function GetPlanet(planetUtilities, planetID)
	
	--local image = planetUtilities.planetImages[math.floor(math.random()*#planetUtilities.planetImages) + 1]
	local image = LUA_DIRNAME .. "images/planets/tundra02.png"
	
	local planetData = {
		name = "Rosnek",
		startingPlanet = false,
		mapDisplay = {
			x = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][1]) or 0.52,
			y = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][2]) or 0.04,
			image = image,
			size = planetUtilities.PLANET_SIZE_MAP,
		},
		infoDisplay = {
			image = image,
			size = planetUtilities.PLANET_SIZE_INFO,
			backgroundImage = planetUtilities.backgroundImages[math.floor(math.random()*#planetUtilities.backgroundImages) + 1],
			terrainType = "Tundra",
			radius = "5174 km",
			primary = "Rirnef",
			primaryType = "G6V",
			milRating = 1,
			feedbackLink = "http://zero-k.info/Forum/Thread/24510",
			text = "This world was both wealthy and peripheral, making it an ideal place to start a rebellion. Long after everyone is gone, the rebel army is still facing the expeditionary force the Empire sent to crush them to a standstill."
			.. "\n "
			.. "\nWith no one left to do geomaintenance, it is slowly freezing, returning to its original ice world state."
			,
			extendedText = "I've got lucky, the rebel forces recognized one of my IFF signals. The dormant armies are both reactivating, though. This time, it will not end in a cold war."
			.. "\n "
			.. "\nThe other side is about to complete a Krow heavy gunship. I must quickly build Tridents to defeat it, then build my own Krows and return the favour."
		},
		tips = {
			{
				image = "unitpics/gunshipaa.png",
				text = [[Tridents should be your first line of defense against any aerial threat; their long-range AA missiles are effective against all flying targets, and unlike static turrets they can retreat easily if threatened by ground forces.]]
			},
			{
				image = "unitpics/gunshipkrow.png",
				text = [[Make sure your own units are well out of the way when you use the manual fire weapon of the Krow (default hotkey D). Its massive barrage of Cluster Bombs do not distinguish between friend and foe.]]
			},
		},
		gameConfig = {
			mapName = "FrostBiteV2",
			playerConfig = {
				startX = 8069,
				startZ = 720,
				allyTeam = 0,
				facplop = false,
				commanderParameters = {
					facplop = false,
					defeatIfDestroyedObjectiveID = 2,
				},
				extraUnlocks = {
					"factorygunship",
					"gunshipcon",
					"gunshipraid",
					"gunshipaa",
					"gunshipkrow",
					"turrettorp",
				},
				startUnits = {
					{
						name = "staticmex",
						x = 7944,
						z = 184,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 7832,
						z = 712,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 7944,
						z = 1208,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 8056,
						z = 2744,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 7704,
						z = 3368,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 7944,
						z = 3864,
						facing = 0,
					},
 					{
						name = "turretaalaser",
						x = 7656,
						z = 3896,
						facing = 3,
					},
 					{
						name = "gunshipaa",
						x = 7750,
						z = 950,
						facing = 0,
					},
 					{
						name = "gunshipaa",
						x = 7950,
						z = 950,
						facing = 0,
					},
					{
						name = "gunshipskirm",
						x = 7675,
						z = 1000,
						facing = 0,
					},
 					{
						name = "gunshipskirm",
						x = 8025,
						z = 1000,
						facing = 0,
					},
					{
						name = "gunshipheavyskirm",
						x = 7850,
						z = 1000,
						facing = 0,
					},
 					{
						name = "energysolar",
						x = 8008,
						z = 1224,
						facing = 2,
					},
 					{
						name = "energysolar",
						x = 7928,
						z = 1272,
						facing = 1,
					},
 					{
						name = "staticradar",
						x = 7584,
						z = 2992,
						facing = 0,
					},
 					{
						name = "turretaalaser",
						x = 7896,
						z = 3000,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 7880,
						z = 1192,
						facing = 0,
					},
 					{
						name = "staticradar",
						x = 7600,
						z = 1216,
						facing = 0,
					},
 					{
						name = "energysolar",
						x = 7960,
						z = 1144,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 8008,
						z = 200,
						facing = 2,
					},
 					{
						name = "energysolar",
						x = 7928,
						z = 248,
						facing = 1,
					},
 					{
						name = "energysolar",
						x = 7880,
						z = 168,
						facing = 0,
					},
 					{
						name = "energysolar",
						x = 7960,
						z = 120,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 7768,
						z = 728,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 7848,
						z = 776,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 7896,
						z = 696,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 7816,
						z = 648,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 8120,
						z = 2760,
						facing = 2,
					},
 					{
						name = "energysolar",
						x = 8040,
						z = 2808,
						facing = 1,
					},
 					{
						name = "energysolar",
						x = 7992,
						z = 2728,
						facing = 0,
					},
 					{
						name = "energysolar",
						x = 8072,
						z = 2680,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 7768,
						z = 3384,
						facing = 2,
					},
 					{
						name = "energysolar",
						x = 7688,
						z = 3432,
						facing = 1,
					},
 					{
						name = "energysolar",
						x = 7640,
						z = 3352,
						facing = 0,
					},
 					{
						name = "energysolar",
						x = 7720,
						z = 3304,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 8008,
						z = 3880,
						facing = 2,
					},
 					{
						name = "energysolar",
						x = 7928,
						z = 3928,
						facing = 1,
					},
 					{
						name = "energysolar",
						x = 7880,
						z = 3848,
						facing = 0,
					},
 					{
						name = "energysolar",
						x = 7960,
						z = 3800,
						facing = 3,
					},
 					{
						name = "factorygunship",
						x = 8136,
						z = 920,
						facing = 3,
					},
 					{
						name = "staticcon",
						x = 8168,
						z = 1032,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8168, 1032}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8143, 1057}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 8168,
						z = 792,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8168, 792}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8143, 817}, options = {"shift"}},
						},
					},
 					{
						name = "turretaafar",
						x = 8016,
						z = 496,
						facing = 3,
					},
 					{
						name = "turretheavylaser",
						x = 7576,
						z = 296,
						facing = 3,
					},
 					{
						name = "turretheavylaser",
						x = 7544,
						z = 1032,
						facing = 3,
					},
 					{
						name = "turretheavylaser",
						x = 7464,
						z = 2984,
						facing = 3,
					},
 					{
						name = "turretheavylaser",
						x = 7368,
						z = 3624,
						facing = 3,
					},
				}
			},
			aiConfig = {
				{
					humanName = "Itesro",
					--aiLib = "Null AI",
					--bitDependant = false,
					aiLib = "Circuit_difficulty_autofill_ally",
					bitDependant = true,
					allyTeam = 0,
					unlocks = {
						"staticcon",
						"energysolar",
						"energywind",
						"staticradar",
						"staticcon",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turrettorp",
						"turretgauss",
						"shipcon",
						"subraider",
						"shiparty",
						"shipassault",
						"shipriot",
						"shipscout",
						"shipskirm",
						"shiptorpraider",
						"spidercon",
						"spideremp",
						"spiderriot",
						"spiderscout",
						"spiderskirm",
						"spiderassault",
						"spiderantiheavy",
						"spidercrabe",
						--"spideraa",
						"cloakcon",
						"cloakraid",
						"cloakriot",
						"cloakskirm",
						"cloakassault",
						"cloakarty",
						"cloakbomb",
						"cloakheavyraid",
						"cloaksnipe",
					},
					commanderLevel = 2,
					commander = false,
					startUnits = {
						{
							name = "turrettorp",
							x = 7350,
							z = 1600,
							facing = 3,
						},
						{
							name = "turrettorp",
							x = 7350,
							z = 1700,
							facing = 3,
						},
						{
							name = "turrettorp",
							x = 7350,
							z = 2200,
							facing = 3,
						},
						{
							name = "turrettorp",
							x = 7350,
							z = 2300,
							facing = 3,
						},
						{
							name = "turrettorp",
							x = 8000,
							z = 1900,
							facing = 3,
						},
						{
							name = "turrettorp",
							x = 8000,
							z = 2000,
							facing = 3,
						},
						{
							name = "staticmex",
							x = 7160,
							z = 744,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6840,
							z = 1992,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 5008,
							z = 2944,
							facing = 3,
						},
 						{
							name = "turretgauss",
							x = 4904,
							z = 3160,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 5136,
							z = 1488,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 5336,
							z = 1176,
							facing = 0,
						},
 						{
							name = "cloakheavyraid",
							x = 5814,
							z = 2632,
							facing = 3,
							buildProgress = 0.53729999,
						},
 						{
							name = "staticmex",
							x = 7064,
							z = 2392,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 7256,
							z = 1992,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6824,
							z = 3608,
							facing = 3,
						},
 						{
							name = "cloakassault",
							x = 5330,
							z = 1741,
							facing = 2,
						},
 						{
							name = "shipassault",
							x = 4679,
							z = 396,
							facing = 1,
						},
 						{
							name = "cloakcon",
							x = 5337,
							z = 2232,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 5288,
							z = 696,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 5288,
							z = 600,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 5288,
							z = 200,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 5288,
							z = 104,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 5544,
							z = 216,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6120,
							z = 232,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6440,
							z = 632,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6584,
							z = 808,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5992,
							z = 1304,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5736,
							z = 1096,
							facing = 0,
						},
 						{
							name = "factoryship",
							x = 7664,
							z = 2032,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 5656,
							z = 1448,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6264,
							z = 1720,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5656,
							z = 3144,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 5864,
							z = 2984,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6392,
							z = 2792,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6584,
							z = 3016,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 5592,
							z = 2776,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7864,
							z = 2040,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 6152,
							z = 3912,
							facing = 3,
						},
 						{
							name = "shipscout",
							x = 6815,
							z = 1287,
							facing = 2,
						},
 						{
							name = "factorycloak",
							x = 5824,
							z = 2632,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 5960,
							z = 2632,
							facing = 3,
						},
 						{
							name = "factoryspider",
							x = 5768,
							z = 1640,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 5880,
							z = 1720,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 6888,
							z = 2072,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 6968,
							z = 2072,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 7048,
							z = 2072,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 7128,
							z = 2072,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 7208,
							z = 2072,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 7064,
							z = 2152,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 7064,
							z = 2232,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 7064,
							z = 2312,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 7080,
							z = 792,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 7096,
							z = 696,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 7192,
							z = 808,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 7688,
							z = 2152,
							facing = 0,
						},
 						{
							name = "turretaaclose",
							x = 5800,
							z = 2840,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 6856,
							z = 3672,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 6776,
							z = 3672,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 6744,
							z = 3576,
							facing = 1,
						},
 						{
							name = "shipassault",
							x = 7477,
							z = 1630,
							facing = 1,
						},
 						{
							name = "turretaaclose",
							x = 5880,
							z = 2152,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 8120,
							z = 2032,
							facing = 0,
						},
 						{
							name = "turretgauss",
							x = 4952,
							z = 2408,
							facing = 3,
						},
 						{
							name = "turretgauss",
							x = 4968,
							z = 2008,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 5040,
							z = 2800,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 5208,
							z = 3080,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 4992,
							z = 1568,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 5240,
							z = 1416,
							facing = 3,
						},
 						{
							name = "turretaaclose",
							x = 5816,
							z = 1368,
							facing = 1,
						},
 						{
							name = "staticstorage",
							x = 8120,
							z = 2280,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 8136,
							z = 2184,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 5608,
							z = 2920,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 5624,
							z = 2840,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 4992,
							z = 1776,
							facing = 3,
						},
 						{
							name = "cloakcon",
							x = 5157,
							z = 2439,
							facing = 3,
						},
 						{
							name = "subraider",
							x = 7520,
							z = 2279,
							facing = 3,
						},
 						{
							name = "shiparty",
							x = 5043,
							z = 412,
							facing = 1,
						},
 						{
							name = "spidercrabe",
							x = 5732,
							z = 1640,
							facing = 3,
							buildProgress = 0.67269999,
						},
 						{
							name = "energysolar",
							x = 5896,
							z = 2824,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 5168,
							z = 2480,
							facing = 2,
						},
 						{
							name = "cloakassault",
							x = 3934,
							z = 573,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 5704,
							z = 2856,
							facing = 3,
						},
 						{
							name = "spiderskirm",
							x = 3838,
							z = 544,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 5768,
							z = 2936,
							facing = 3,
						},
 						{
							name = "cloakskirm",
							x = 5390,
							z = 1624,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 4374,
							z = 586,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 5688,
							z = 2936,
							facing = 3,
						},
 						{
							name = "turretgauss",
							x = 5000,
							z = 1096,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 5896,
							z = 1560,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 5688,
							z = 2440,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 5720,
							z = 1448,
							facing = 3,
						},
 						{
							name = "spiderantiheavy",
							x = 5852,
							z = 2075,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 5464,
							z = 2600,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 4904,
							z = 920,
							facing = 0,
						},
 						{
							name = "cloakcon",
							x = 5589,
							z = 1817,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 5440,
							z = 1536,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 5254,
							z = 1801,
							facing = 1,
						},
 						{
							name = "cloakskirm",
							x = 5379,
							z = 1668,
							facing = 2,
						},
 						{
							name = "spidercon",
							x = 4633,
							z = 763,
							facing = 1,
						},
 						{
							name = "cloakheavyraid",
							x = 6452,
							z = 813,
							facing = 3,
						},
 						{
							name = "cloakriot",
							x = 5287,
							z = 1784,
							facing = 1,
						},
 						{
							name = "cloakraid",
							x = 4018,
							z = 576,
							facing = 2,
						},
 						{
							name = "cloakraid",
							x = 3964,
							z = 557,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 5192,
							z = 2248,
							facing = 0,
						},
 						{
							name = "cloakskirm",
							x = 5373,
							z = 1639,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 5448,
							z = 3144,
							facing = 0,
							terraformHeight = 120,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5456, 3151}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5307, 2808}, options = {"shift"}},
							},
						},
 						{
							name = "turretmissile",
							x = 4800,
							z = 1248,
							facing = 0,
						},
 						{
							name = "cloakheavyraid",
							x = 5513,
							z = 2441,
							facing = 2,
						},
 						{
							name = "shipcon",
							x = 7664,
							z = 2040,
							facing = 3,
							buildProgress = 0.1469,
						},
 						{
							name = "shipriot",
							x = 6840,
							z = 2559,
							facing = 2,
						},
 						{
							name = "shipriot",
							x = 4841,
							z = 3872,
							facing = 3,
						},
 						{
							name = "shipassault",
							x = 5135,
							z = 3935,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 5384,
							z = 3720,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 5400,
							z = 4008,
							facing = 0,
						},
 						{
							name = "cloakarty",
							x = 5571,
							z = 1965,
							facing = 2,
						},
 						{
							name = "cloakarty",
							x = 5506,
							z = 2144,
							facing = 2,
						},
 						{
							name = "cloakarty",
							x = 5527,
							z = 2017,
							facing = 2,
						},
 						{
							name = "cloakarty",
							x = 5570,
							z = 2345,
							facing = 2,
						},
 						{
							name = "cloakassault",
							x = 5035,
							z = 2141,
							facing = 1,
						},
 						{
							name = "cloakassault",
							x = 5061,
							z = 2364,
							facing = 1,
						},
 						{
							name = "spidercrabe",
							x = 5178,
							z = 1666,
							facing = 0,
						},
 						{
							name = "shipriot",
							x = 5063,
							z = 3779,
							facing = 2,
						},
 						{
							name = "spiderassault",
							x = 5239,
							z = 1974,
							facing = 2,
							difficultyAtMost = 2,
						},
 						{
							name = "spiderassault",
							x = 5259,
							z = 2160,
							facing = 2,
							difficultyAtMost = 2,
						},
 						{
							name = "spiderassault",
							x = 5150,
							z = 2392,
							facing = 2,
							difficultyAtMost = 2,
						},
 						{
							name = "spiderassault",
							x = 5282,
							z = 2619,
							facing = 1,
							difficultyAtMost = 2,
						},
 						{
							name = "spiderassault",
							x = 5318,
							z = 2267,
							facing = 2,
							difficultyAtMost = 2,
						},
 						{
							name = "spiderassault",
							x = 5172,
							z = 1824,
							facing = 1,
							difficultyAtMost = 2,
						},
					}
				},
				{
					startX = 2600,
					startZ = 2000,
					humanName = "Lepsum",
					--aiLib = "Null AI",
					--bitDependant = false,
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					commanderParameters = {
						facplop = false,
					},
					allyTeam = 1,
					unlocks = {
						"staticcon",
						"energysolar",
						"energywind",
						"staticradar",
						"staticcon",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turrettorp",
						"turretemp",
						"shipcon",
						"subraider",
						"shiparty",
						"shipassault",
						"shipriot",
						"shipscout",
						"shipskirm",
						"shiptorpraider",
						"spidercon",
						"spideremp",
						"spiderriot",
						"spiderscout",
						"spiderskirm",
						"spiderassault",
						"spiderantiheavy",
						"spidercrabe",
						--"spideraa",
						"shieldcon",
						"shieldraid",
						"shieldriot",
						"shieldskirm",
						"shieldassault",
						"shieldarty",
						"shieldbomb",
						"shieldfelon",
						--"shieldshield",
						--"shieldaa",
						--"turretaalaser",
						--"turretaaclose",
						"gunshipcon",
						"gunshipaa",
						"gunshipassault",
						"gunshipbomb",
						"gunshipheavyskirm",
						"gunshipraid",
						"gunshipskirm",
						"gunshipkrow"
					},
					difficultyDependantUnlocks = {
						[3] = {"shieldaa"},
						[4] = {"shieldaa","shieldshield"},
					},
					commanderLevel = 5,
					commander = {
						name = "Valco",
						chassis = "guardian",
						decorations = {
						  "skin_bombard_steel",
						},
						modules = {
							"commweapon_riotcannon",
							"commweapon_riotcannon",
							"weaponmod_napalm_warhead",
							"module_heavy_armor",
							"module_heavy_armor",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_high_power_servos",
							"module_high_power_servos",
							"commweapon_personal_shield",
						}
					},
					midgameUnits = {
						{
							name = "gunshipkrow",
							x = 200,
							z = 800,
							facing = 2,
							spawnRadius = 50,
							delay = 6*30*60,
							difficultyAtLeast = 4,
							orbitalDrop = false,
						},
						{
							name = "gunshipaa",
							x = 200,
							z = 800,
							facing = 2,
							spawnRadius = 50,
							delay = 6*30*60,
							orbitalDrop = false,
						},
						{
							name = "gunshipaa",
							x = 200,
							z = 800,
							facing = 2,
							spawnRadius = 50,
							delay = 6*30*60,
							orbitalDrop = false,
						},
						{
							name = "gunshipaa",
							x = 200,
							z = 800,
							facing = 2,
							spawnRadius = 50,
							delay = 6*30*60,
							orbitalDrop = false,
						},
					},
					startUnits = {
						{
							name = "gunshipkrow",
							x = 55,
							z = 3224,
							facing = 1,
							buildProgress = 0.85,
						},
						{
							name = "staticantinuke",
							x = 580,
							z = 1380,
							facing = 0,
						},
						{
							name = "turretaaflak",
							x = 3300,
							z = 1200,
							facing = 1,
						},
						{
							name = "turretaaflak",
							x = 3400,
							z = 2700,
							facing = 1,
						},
						{
							name = "gunshipskirm",
							x = 200,
							z = 3224,
							facing = 1,
						},
						{
							name = "gunshipskirm",
							x = 200,
							z = 3300,
							facing = 1,
						},
						{
							name = "gunshipassault",
							x = 200,
							z = 3400,
							facing = 1,
						},
						{
							name = "gunshipheavyskirm",
							x = 200,
							z = 500,
							facing = 1,
						},
						{
							name = "spiderassault",
							x = 3000,
							z = 2000,
							facing = 1,
						},
						{
							name = "spiderassault",
							x = 3000,
							z = 2050,
							facing = 1,
						},
						{
							name = "spiderassault",
							x = 3000,
							z = 2100,
							facing = 1,
						},
						{
							name = "spiderassault",
							x = 3000,
							z = 2150,
							facing = 1,
						},
						{
							name = "spiderassault",
							x = 3000,
							z = 2200,
							facing = 1,
						},
						{
							name = "gunshipaa",
							x = 300,
							z = 500,
							facing = 1,
						},
						{
							name = "turretemp",
							x = 3536,
							z = 2832,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 3488,
							z = 2336,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 688,
							z = 2992,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 3152,
							z = 2560,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 3136,
							z = 1344,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 608,
							z = 1040,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 248,
							z = 2920,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 520,
							z = 3416,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 216,
							z = 3960,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 104,
							z = 1384,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 456,
							z = 856,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 232,
							z = 264,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 280,
							z = 3976,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 200,
							z = 4024,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 152,
							z = 3944,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 232,
							z = 3896,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 312,
							z = 2936,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 232,
							z = 2984,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 184,
							z = 2904,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 264,
							z = 2856,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 168,
							z = 1400,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 88,
							z = 1448,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 40,
							z = 1368,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 120,
							z = 1320,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 440,
							z = 920,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 392,
							z = 840,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 296,
							z = 280,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 216,
							z = 328,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 168,
							z = 248,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 248,
							z = 200,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 520,
							z = 888,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 424,
							z = 760,
							facing = 3,
						},
 						{
							name = "factorygunship",
							x = 56,
							z = 3224,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 24,
							z = 3112,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 504,
							z = 3480,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 456,
							z = 3400,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 536,
							z = 3352,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 536,
							z = 3560,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 24,
							z = 3336,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 3112,
							z = 4056,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 3112,
							z = 3944,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 3112,
							z = 3496,
							facing = 3,
						},
 						{
							name = "spiderscout",
							x = 2141,
							z = 2066,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 3064,
							z = 392,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 2589,
							z = 2608,
							facing = 2,
						},
 						{
							name = "spiderscout",
							x = 2784,
							z = 2438,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 2616,
							z = 152,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2008,
							z = 216,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1336,
							z = 568,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1784,
							z = 1112,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1976,
							z = 1336,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2520,
							z = 1160,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2792,
							z = 968,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2792,
							z = 1368,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1912,
							z = 2408,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1336,
							z = 2136,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 904,
							z = 2136,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1096,
							z = 1736,
							facing = 0,
						},
 						{
							name = "factoryship",
							x = 512,
							z = 2032,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 2712,
							z = 2488,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 2632,
							z = 2840,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 2376,
							z = 2632,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 1224,
							z = 3336,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 1784,
							z = 3272,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 1944,
							z = 3464,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 2264,
							z = 3912,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 312,
							z = 2040,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 2840,
							z = 3912,
							facing = 3,
						},
 						{
							name = "factoryspider",
							x = 2360,
							z = 2872,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 2232,
							z = 2904,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 2424,
							z = 1608,
							facing = 1,
						},
 						{
							name = "factoryshield",
							x = 2552,
							z = 1600,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1256,
							z = 616,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1288,
							z = 504,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1384,
							z = 616,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1096,
							z = 1832,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1096,
							z = 1912,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1096,
							z = 1992,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1096,
							z = 2072,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 968,
							z = 2120,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1048,
							z = 2104,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1176,
							z = 2104,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1256,
							z = 2136,
							facing = 1,
						},
 						{
							name = "turretaaflak",
							x = 2632,
							z = 1752,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 1896,
							z = 2296,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 504,
							z = 2120,
							facing = 0,
						},
 						{
							name = "turretaalaser",
							x = 2728,
							z = 2024,
							facing = 1,
						},
 						{
							name = "turretaaflak",
							x = 2248,
							z = 2728,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 1912,
							z = 1192,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 72,
							z = 2032,
							facing = 0,
						},
 						{
							name = "turretaalaser",
							x = 296,
							z = 3736,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 168,
							z = 1048,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 88,
							z = 424,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 408,
							z = 3096,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1176,
							z = 3416,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1256,
							z = 3400,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1176,
							z = 3304,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 1912,
							z = 3336,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 3320,
							z = 2520,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 3224,
							z = 1304,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 3400,
							z = 696,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 3416,
							z = 1208,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 3416,
							z = 1592,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 3440,
							z = 1408,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 3440,
							z = 928,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 3448,
							z = 2120,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 3528,
							z = 2504,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 3480,
							z = 3000,
							facing = 1,
						},
 						{
							name = "staticstorage",
							x = 24,
							z = 2200,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 72,
							z = 2296,
							facing = 0,
						},
 						{
							name = "shiptorpraider",
							x = 1496,
							z = 2669,
							facing = 3,
						},
 						{
							name = "spiderantiheavy",
							x = 3311,
							z = 1527,
							facing = 2,
						},
 						{
							name = "spiderantiheavy",
							x = 3359,
							z = 1368,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 4229,
							z = 2118,
							facing = 0,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4881, 1426}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4080, 2225}, options = {"shift"}},
							},
						},
 						{
							name = "shieldfelon",
							x = 2779,
							z = 2066,
							facing = 3,
						},
 						{
							name = "shieldassault",
							x = 2886,
							z = 1961,
							facing = 0,
						},
 						{
							name = "shieldassault",
							x = 4611,
							z = 2232,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 3808,
							z = 2025,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3540, 1758}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4339, 2558}, options = {"shift"}},
							},
						},
 						{
							name = "spidercon",
							x = 4164,
							z = 1895,
							facing = 3,
						},
 						{
							name = "shiptorpraider",
							x = 1501,
							z = 2625,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 128,
							z = 2992,
							facing = 1,
						},
 						{
							name = "shipriot",
							x = 625,
							z = 2294,
							facing = 2,
						},
 						{
							name = "shieldcon",
							x = 4172,
							z = 2104,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3338, 1342}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4138, 2142}, options = {"shift"}},
							},
						},
 						{
							name = "shieldassault",
							x = 4726,
							z = 2202,
							facing = 2,
						},
 						{
							name = "shieldcon",
							x = 3912,
							z = 2465,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3266, 3136}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4064, 2336}, options = {"shift"}},
							},
						},
 						{
							name = "spiderscout",
							x = 2889,
							z = 2707,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 3165,
							z = 547,
							facing = 2,
						},
 						{
							name = "shieldarty",
							x = 4188,
							z = 2531,
							facing = 0,
						},
 						{
							name = "spidercrabe",
							x = 4377,
							z = 2260,
							facing = 1,
						},
 						{
							name = "shieldcon",
							x = 3441,
							z = 796,
							facing = 2,
						},
 						{
							name = "spiderscout",
							x = 2399,
							z = 1899,
							facing = 2,
						},
 						{
							name = "spiderassault",
							x = 3830,
							z = 2932,
							facing = 1,
						},
 						{
							name = "shieldassault",
							x = 2707,
							z = 2423,
							facing = 3,
						},
 						{
							name = "shieldraid",
							x = 2773,
							z = 3232,
							facing = 1,
						},
 						{
							name = "shieldassault",
							x = 4678,
							z = 2214,
							facing = 2,
						},
 						{
							name = "spiderscout",
							x = 4204,
							z = 2070,
							facing = 2,
						},
 						{
							name = "shieldassault",
							x = 4697,
							z = 2171,
							facing = 1,
						},
 						{
							name = "shipcon",
							x = 2030,
							z = 1686,
							facing = 0,
						},
 						{
							name = "spiderscout",
							x = 2821,
							z = 1705,
							facing = 2,
						},
 						{
							name = "shieldassault",
							x = 4715,
							z = 2321,
							facing = 1,
						},
 						{
							name = "spiderscout",
							x = 2079,
							z = 3384,
							facing = 0,
						},
 						{
							name = "spiderskirm",
							x = 3905,
							z = 2208,
							facing = 3,
						},
 						{
							name = "spiderscout",
							x = 2515,
							z = 1443,
							facing = 3,
						},
 						{
							name = "shiptorpraider",
							x = 1467,
							z = 2782,
							facing = 0,
						},
 						{
							name = "shiptorpraider",
							x = 1433,
							z = 2830,
							facing = 2,
						},
 						{
							name = "shieldcon",
							x = 3454,
							z = 1017,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 2760,
							z = 2472,
							facing = 1,
							buildProgress = 0.1285,
						},
 						{
							name = "spiderassault",
							x = 3958,
							z = 2443,
							facing = 3,
						},
 						{
							name = "shipassault",
							x = 4811,
							z = 3931,
							facing = 1,
						},
 						{
							name = "shieldassault",
							x = 4739,
							z = 2156,
							facing = 1,
						},
 						{
							name = "shiparty",
							x = 492,
							z = 2024,
							facing = 1,
							buildProgress = 0.95050001,
						},
 						{
							name = "shieldskirm",
							x = 4441,
							z = 2231,
							facing = 3,
						},
 						{
							name = "spiderscout",
							x = 3434,
							z = 1770,
							facing = 3,
						},
 						{
							name = "spideremp",
							x = 4757,
							z = 2346,
							facing = 1,
						},
 						{
							name = "shieldskirm",
							x = 4476,
							z = 2228,
							facing = 3,
						},
 						{
							name = "shiparty",
							x = 1719,
							z = 3618,
							facing = 1,
						},
 						{
							name = "spiderscout",
							x = 4127,
							z = 2130,
							facing = 0,
						},
 						{
							name = "spiderscout",
							x = 4155,
							z = 2066,
							facing = 0,
						},
 						{
							name = "shieldskirm",
							x = 2616,
							z = 2245,
							facing = 0,
						},
 						{
							name = "spiderscout",
							x = 4192,
							z = 2127,
							facing = 2,
						},
 						{
							name = "spiderscout",
							x = 2407,
							z = 2908,
							facing = 3,
						},
 						{
							name = "shieldassault",
							x = 2575,
							z = 1754,
							facing = 0,
						},
 						{
							name = "spiderscout",
							x = 3465,
							z = 2648,
							facing = 1,
						},
 						{
							name = "turrettorp",
							x = 3096,
							z = 40,
							facing = 0,
						},
 						{
							name = "shipassault",
							x = 3034,
							z = 175,
							facing = 2,
						},
 						{
							name = "shipskirm",
							x = 2895,
							z = 172,
							facing = 3,
						},
 						{
							name = "spiderscout",
							x = 2834,
							z = 2779,
							facing = 1,
						},
 						{
							name = "spiderscout",
							x = 2547,
							z = 2818,
							facing = 1,
						},
 						{
							name = "shieldraid",
							x = 2564,
							z = 1600,
							facing = 1,
							buildProgress = 0.91109997,
						},
 						{
							name = "spiderassault",
							x = 2396,
							z = 2872,
							facing = 1,
							buildProgress = 0.30410001,
						},
					}
				},
			},
			defeatConditionConfig = {
				-- Indexed by allyTeam.
				[0] = { },
				[1] = {
					ignoreUnitLossDefeat = false,
					vitalCommanders = false,
					vitalUnitTypes = {
						"factorygunship",
						"factoryshield",
						"factoryship",
						"factoryspider"
					},
					loseAfterSeconds = false,
					allyTeamLossObjectiveID = 1,
				},
			},
			objectiveConfig = {
				-- This is just related to displaying objectives on the UI.
				[1] = {
					description = "Destroy all enemy factories",
				},
				[2] = {
					description = "Protect your Commander",
				},
			},
			bonusObjectiveConfig = {
				[1] = { -- Make the enemy lose one Krow by 5:00
					onlyCountRemovedUnits = true,
					satisfyByTime = 300,
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 1,
					enemyUnitTypes = {
						"gunshipkrow",
					},
					image = planetUtilities.ICON_DIR .. "gunshipkrow.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.ATTACK,
					description = "Destroy an enemy Krow before 5:00",
					experience = planetUtilities.BONUS_EXP,
				},
				[2] = { -- Have a Krow by 5 minutes
					satisfyByTime = 300,
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 1,
					unitTypes = {
						"gunshipkrow",
					},
					image = planetUtilities.ICON_DIR .. "gunshipkrow.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.REPAIR,
					description = "Build a Krow before 5:00",
					experience = planetUtilities.BONUS_EXP,
				},
				[3] = { -- Complete all bonus objectives
					completeAllBonusObjectives = true,
					image = planetUtilities.ICON_OVERLAY.ALL,
					description = "Complete all bonus objectives (in one battle).",
					experience = planetUtilities.BONUS_EXP,
				},
			}
		},
		completionReward = {
			experience = planetUtilities.MAIN_EXP,
			units = {
				"gunshipaa",
				"gunshipkrow",
			},
			modules = {
				"module_companion_drone_LIMIT_D_2",
			},
			abilities = {
			},
			codexEntries = {
				"faction_rebels"
			},
		},
	}
	
	return planetData
end

return GetPlanet
