--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Planet config

local function GetPlanet(planetUtilities, planetID)
	
	local image = LUA_DIRNAME .. "images/planets/ocean01.png"
	
	local planetData = {
		name = "Harsar Lief",
		startingPlanet = false,
		mapDisplay = {
			x = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][1]) or 0.46,
			y = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][2]) or 0.82,
			image = image,
			size = planetUtilities.PLANET_SIZE_MAP,
		},
		infoDisplay = {
			image = image,
			size = planetUtilities.PLANET_SIZE_INFO,
			backgroundImage = planetUtilities.backgroundImages[math.floor(math.random()*#planetUtilities.backgroundImages) + 1],
			terrainType = "Terran",
			radius = "6550 km",
			primary = "Blank",
			primaryType = "G8V",
			milRating = 1,
			feedbackLink = "http://zero-k.info/Forum/Thread/24530",
			text = "This chokepoint defended the territory of something called Haven. The Empire attempted to break through, and managed to gain a foothold on this world. That battle is still going, with mindless automata carrying their last recieved orders."
			.. "\n "
			.. "\nOne of the local garrisons somehow identified me as an enemy of the Empire and gave me IFF codes. I wonder on how many Haven worlds those will work."
			,
			extendedText = "Crossing a river under enemy fire is a daunting prospect, but it becomes easier if I control the river. There are several old Sunlance defense systems, but I can bombard the shoreline with Envoy cruisers to force passage through the shallows."
		},
		tips = {
			{
				image = "unitpics/shiparty.png",
				text = [[Envoys are effective artillery units and should be your first choice for clearing any shoreline of enemies.]]
			},
			{
				image = "unitpics/shipscout.png",
				text = [[To enable more accurate fire, find the exact locations of enemy turrets with Cutters. These boats are armed with a short-range disarming missile but their primary use is for scouting.]]
			},
			{
				image = "unitpics/shiptorpraider.png",
				text = [[Protect your other ships from underwater threats with Hunter torpedo boats. Airborne threats can be dealt with by Zephyrs.]]
			},
		},
		gameConfig = {
			mapName = "AquariusCrossing",
			playerConfig = {
				startX = 640,
				startZ = 1060,
				allyTeam = 0,
				facplop = false,
				commanderParameters = {
					facplop = false,
					defeatIfDestroyedObjectiveID = 2,
				},
				extraUnlocks = {
					"factoryship",
					"shipcon",
					"shiparty",
					"shipscout",
					"shiptorpraider",
					"shipaa",
					"turrettorp",
				},
				startUnits = {
 					{
						name = "staticmex",
						x = 456,
						z = 456,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 200,
						z = 328,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 216,
						z = 712,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 616,
						z = 808,
						facing = 0,
					},
 					{
						name = "factoryship",
						x = 880,
						z = 736,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 248,
						z = 392,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 328,
						z = 456,
						facing = 1,
					},
					{
						name = "energywind",
						x = 176,
						z = 456,
						facing = 1,
					},
					{
						name = "energywind",
						x = 80,
						z = 456,
						facing = 1,
					},
					{
						name = "energywind",
						x = 176,
						z = 590,
						facing = 1,
					},
					{
						name = "energywind",
						x = 80,
						z = 590,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 408,
						z = 536,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 328,
						z = 616,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 296,
						z = 712,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 392,
						z = 776,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 504,
						z = 808,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 568,
						z = 872,
						facing = 1,
					},
 					{
						name = "turrettorp",
						x = 584,
						z = 408,
						facing = 1,
					},
 					{
						name = "turrettorp",
						x = 552,
						z = 1032,
						facing = 1,
					},
 					{
						name = "turretaaflak",
						x = 536,
						z = 680,
						facing = 1,
					},
 					{
						name = "turrettorp",
						x = 1096,
						z = 472,
						facing = 1,
					},
 					{
						name = "shipcon",
						x = 1123,
						z = 970,
						facing = 1,
					},
 					{
						name = "shiparty",
						x = 1252,
						z = 910,
						facing = 1,
					},
 					{
						name = "shipaa",
						x = 1256,
						z = 1052,
						facing = 1,
					},
 					{
						name = "staticcon",
						x = 744,
						z = 920,
						facing = 1,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {744, 920}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {769, 945}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 744,
						z = 1000,
						facing = 1,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {744, 1000}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {769, 1025}, options = {"shift"}},
						},
					},
 					{
						name = "staticradar",
						x = 624,
						z = 1136,
						facing = 3,
					},
 					{
						name = "shiptorpraider",
						x = 1444,
						z = 766,
						facing = 1,
					},
 					{
						name = "shipscout",
						x = 1447,
						z = 880,
						facing = 1,
					},
 					{
						name = "shiptorpraider",
						x = 1436,
						z = 993,
						facing = 1,
					},
				}
			},
			aiConfig = {
				{
					humanName = "Lief Easter",
					--aiLib = "Null AI",
					--bitDependant = false,
					aiLib = "Circuit_difficulty_autofill_ally",
					bitDependant = true,
					commanderParameters = {
						facplop = false,
					},
					allyTeam = 0,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energygeo",
						"staticstorage",
						"staticcon",
						"staticradar",
						"factorycloak",
						--"cloakcon",
						"cloakraid",
						"cloakriot",
						"cloakskirm",
						"cloakassault",
						"cloakheavyraid",
						"cloakaa",
						"factoryjump",
						--"jumpcon",
						"jumpraid",
						"jumpskirm",
						"jumpblackhole",
						--"jumpscout",
						"jumparty",
						"jumpsumo",
						"jumpaa",
						"factoryplane",
						"planescout",
						--"planecon",
						"planeheavyfighter",
						"bomberprec",
					},
					commander = false,
					startUnits = {
						{
							name = "turretriot",
							x = 2040,
							z = 3830,
							facing = 1,
						},
						{
							name = "turretriot",
							x = 2140,
							z = 4200,
							facing = 1,
						},
						{
							name = "turretriot",
							x = 2500,
							z = 4200,
							facing = 1,
						},
						{
							name = "turretriot",
							x = 2270,
							z = 4800,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 1064,
							z = 3464,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 536,
							z = 3672,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 168,
							z = 3192,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 104,
							z = 3912,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 200,
							z = 2456,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 568,
							z = 4536,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 760,
							z = 2296,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 552,
							z = 4840,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 824,
							z = 1816,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 120,
							z = 5000,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 248,
							z = 1752,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1128,
							z = 4328,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1400,
							z = 2344,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2024,
							z = 4696,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2856,
							z = 4648,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2472,
							z = 3672,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1800,
							z = 3560,
							facing = 0,
						},
 						{
							name = "energygeo",
							x = 1208,
							z = 4552,
							facing = 3,
						},
 						{
							name = "energygeo",
							x = 744,
							z = 2744,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 504,
							z = 2184,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 584,
							z = 3304,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 728,
							z = 4264,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 1528,
							z = 2440,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 1960,
							z = 3400,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 2840,
							z = 3944,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 3000,
							z = 4600,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 2328,
							z = 4344,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 1672,
							z = 3704,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 1048,
							z = 2472,
							facing = 1,
						},
 						{
							name = "cloakcon",
							x = 2040,
							z = 2682,
							facing = 2,
						},
 						{
							name = "factorycloak",
							x = 2472,
							z = 4256,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 2488,
							z = 4392,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {2488, 4392}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {2472, 4246}, options = {"shift"}},
							},
						},
 						{
							name = "factoryjump",
							x = 1224,
							z = 2696,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1096,
							z = 2696,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1504,
							z = 2272,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1568,
							z = 2576,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 1776,
							z = 3152,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 1872,
							z = 3280,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 2880,
							z = 4032,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 2016,
							z = 3584,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 2704,
							z = 3888,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 3040,
							z = 4448,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 3056,
							z = 4720,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 424,
							z = 2728,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 936,
							z = 4264,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 2376,
							z = 4408,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1096,
							z = 2616,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 2768,
							z = 3936,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 1712,
							z = 3104,
							facing = 3,
						},
 						{
							name = "staticstorage",
							x = 904,
							z = 2520,
							facing = 3,
						},
 						{
							name = "staticstorage",
							x = 2152,
							z = 4344,
							facing = 3,
						},
 						{
							name = "jumpskirm",
							x = 2242,
							z = 2335,
							facing = 0,
						},
 						{
							name = "jumpraid",
							x = 1370,
							z = 2813,
							facing = 2,
							patrolRoute = {
								{1296, 2864},
								{1423, 2734},
							},
						},
 						{
							name = "energysolar",
							x = 2872,
							z = 4712,
							facing = 2,
						},
 						{
							name = "jumpskirm",
							x = 2161,
							z = 2910,
							facing = 2,
						},
 						{
							name = "jumpaa",
							x = 1739,
							z = 2839,
							facing = 3,
						},
 						{
							name = "cloakriot",
							x = 2223,
							z = 2281,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 2792,
							z = 4664,
							facing = 2,
						},
 						{
							name = "cloakriot",
							x = 2089,
							z = 2583,
							facing = 2,
						},
 						{
							name = "jumpskirm",
							x = 2137,
							z = 2530,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 2808,
							z = 4536,
							facing = 2,
						},
 						{
							name = "cloakriot",
							x = 1976,
							z = 2627,
							facing = 0,
						},
 						{
							name = "jumpskirm",
							x = 2404,
							z = 2562,
							facing = 2,
						},
 						{
							name = "cloakriot",
							x = 2292,
							z = 2509,
							facing = 3,
						},
 						{
							name = "cloakskirm",
							x = 2289,
							z = 2614,
							facing = 2,
						},
 						{
							name = "jumpskirm",
							x = 2077,
							z = 2509,
							facing = 1,
						},
 						{
							name = "jumpraid",
							x = 1928,
							z = 2908,
							facing = 2,
							patrolRoute = {
								{1948, 2900},
								{1894, 2933},
							},
						},
 						{
							name = "cloakriot",
							x = 1939,
							z = 2538,
							facing = 2,
						},
 						{
							name = "jumpaa",
							x = 2204,
							z = 2621,
							facing = 2,
						},
 						{
							name = "cloakskirm",
							x = 1979,
							z = 2876,
							facing = 0,
						},
 						{
							name = "cloakskirm",
							x = 2324,
							z = 2599,
							facing = 1,
						},
 						{
							name = "cloakskirm",
							x = 1991,
							z = 2658,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 2328,
							z = 2648,
							facing = 1,
						},
 						{
							name = "cloakraid",
							x = 2797,
							z = 3541,
							facing = 1,
							patrolRoute = {
								{2827, 3556},
								{2763, 3553},
							},
						},
 						{
							name = "cloakraid",
							x = 2918,
							z = 3532,
							facing = 2,
							patrolRoute = {
								{2827, 3556},
								{2818, 3493},
							},
						},
 						{
							name = "cloakraid",
							x = 2823,
							z = 3556,
							facing = 1,
							patrolRoute = {
								{2827, 3556},
								{2814, 3494},
							},
						},
 						{
							name = "jumpraid",
							x = 3291,
							z = 3396,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 2360,
							z = 2744,
							facing = 1,
						},
 						{
							name = "cloakraid",
							x = 2857,
							z = 3541,
							facing = 0,
							patrolRoute = {
								{2827, 3556},
								{2776, 3518},
							},
						},
 						{
							name = "cloakraid",
							x = 2845,
							z = 3563,
							facing = 1,
							patrolRoute = {
								{2831, 3556},
								{2888, 3576},
							},
						},
 						{
							name = "jumpaa",
							x = 2108,
							z = 2486,
							facing = 3,
						},
 						{
							name = "cloakaa",
							x = 3697,
							z = 3310,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 2248,
							z = 2792,
							facing = 1,
						},
 						{
							name = "cloakskirm",
							x = 2367,
							z = 3328,
							facing = 2,
						},
 						{
							name = "cloakraid",
							x = 2832,
							z = 3535,
							facing = 0,
							patrolRoute = {
								{2890, 3542},
								{2827, 3556},
							},
						},
 						{
							name = "staticmex",
							x = 2296,
							z = 2712,
							facing = 0,
						},
 						{
							name = "cloakraid",
							x = 2755,
							z = 3503,
							facing = 1,
							patrolRoute = {
								{2827, 3556},
								{2812, 3494},
							},
						},
 						{
							name = "cloakraid",
							x = 2893,
							z = 3554,
							facing = 0,
							patrolRoute = {
								{2827, 3556},
								{2838, 3493},
							},
						},
 						{
							name = "cloakraid",
							x = 2956,
							z = 3520,
							facing = 2,
							patrolRoute = {
								{2827, 3556},
								{2777, 3517},
							},
						},
 						{
							name = "cloakskirm",
							x = 2242,
							z = 3223,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 2016,
							z = 2736,
							facing = 1,
						},
 						{
							name = "jumpraid",
							x = 1620,
							z = 2843,
							facing = 1,
							patrolRoute = {
								{1892, 2931},
								{1834, 2959},
							},
						},
 						{
							name = "cloakraid",
							x = 3138,
							z = 3522,
							facing = 2,
						},
 						{
							name = "cloakskirm",
							x = 2151,
							z = 4200,
							facing = 3,
						},
 						{
							name = "cloakskirm",
							x = 2290,
							z = 4192,
							facing = 3,
						},
 						{
							name = "jumpraid",
							x = 1248,
							z = 2696,
							facing = 1,
							buildProgress = 0.2212,
						},
 						{
							name = "staticcon",
							x = 2024,
							z = 2584,
							facing = 1,
							buildProgress = 0.0909,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {2024, 2584}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {2049, 2559}, options = {"shift"}},
							},
						},
 						{
							name = "cloakraid",
							x = 2499,
							z = 4190,
							facing = 2,
							patrolRoute = {
								{2827, 3556},
								{2810, 3618},
							},
						},
 						{
							name = "cloakskirm",
							x = 2472,
							z = 4246,
							facing = 2,
							buildProgress = 0.0407,
						},
					}
				},
				{
					startX = 6700,
					startZ = 1200,
					humanName = "Lief Maquis",
					--aiLib = "Null AI",
					--bitDependant = false,
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					commanderParameters = {
						facplop = false,
					},
					allyTeam = 1,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energygeo",
						"staticstorage",
						"staticradar",
						"staticcon",
						"factoryjump",
						--"jumpcon",
						"jumpraid",
						"jumpblackhole",
						--"jumpscout",
						"jumpskirm",
						"jumparty",
						"jumpassault",
						"factorycloak",
						--"cloakcon",
						"cloakraid",
						"cloakskirm",
						"cloakassault",
						"cloakriot",
						"cloakarty",
						"cloakheavyraid",
						"factoryamph",
						--"amphcon",
						"amphraid",
						"amphimpulse",
						"amphfloater",
						"factorygunship",
						--"gunshipcon",
						"gunshipaa",
						"gunshipraid",
						"gunshipskirm",
						"gunshipassault",
						"gunshipheavyskirm",
						"gunshipemp",
						"gunshipbomb",
					},
					difficultyDependantUnlocks = {
						[2] = {"cloaksnipe"},
						[3] = {"cloaksnipe","jumpsumo"},
						[4] = {"cloaksnipe","jumpsumo","amphassault"},
					},
					commanderLevel = 5,
					commander = {
						name = "Alginon",
						chassis = "recon",
						decorations = {
						},
						modules = {
							"commweapon_heavymachinegun",
							"module_heavy_armor",
							"module_heavy_armor",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_dmg_booster",
							"module_dmg_booster",
							"module_dmg_booster",
							"module_autorepair",
							"module_autorepair"
						}
					},
					midgameUnits = {
						{
							name = "jumpsumo",
							x = 6800,
							z = 2200,
							facing = 2,
							difficultyAtLeast = 4,
							spawnRadius = 50,
							delay = 3.5*30*60,
							orbitalDrop = true,
						},
						{
							name = "jumpsumo",
							x = 6800,
							z = 2200,
							facing = 2,
							difficultyAtLeast = 3,
							difficultyAtMost = 3,
							spawnRadius = 50,
							delay = 6.5*30*60,
							orbitalDrop = true,
						},
						{
							name = "jumpsumo",
							x = 6800,
							z = 2200,
							facing = 2,
							difficultyAtLeast = 2,
							difficultyAtMost = 2,
							spawnRadius = 50,
							delay = 9.5*30*60,
							orbitalDrop = true,
						},
						{
							name = "amphassault",
							x = 6800,
							z = 2200,
							facing = 2,
							difficultyAtLeast = 4,
							spawnRadius = 50,
							delay = 6.5*30*60,
							orbitalDrop = true,
						},
						{
							name = "amphassault",
							x = 6800,
							z = 2200,
							facing = 2,
							difficultyAtLeast = 4,
							spawnRadius = 50,
							delay = 6.5*30*60,
							orbitalDrop = true,
						},
						{
							name = "amphassault",
							x = 6800,
							z = 2200,
							facing = 2,
							spawnRadius = 50,
							delay = 12.5*30*60,
							orbitalDrop = true,
						},
						{
							name = "amphassault",
							x = 6800,
							z = 2200,
							facing = 2,
							difficultyAtLeast = 3,
							spawnRadius = 50,
							delay = 12.5*30*60,
							orbitalDrop = true,
						},
						{
							name = "gunshipkrow",
							x = 6800,
							z = 2200,
							facing = 2,
							difficultyAtLeast = 4,
							spawnRadius = 50,
							delay = 9.5*30*60,
							orbitalDrop = true,
						},
						{
							name = "gunshipkrow",
							x = 6800,
							z = 2200,
							facing = 2,
							difficultyAtLeast = 3,
							spawnRadius = 50,
							delay = 13.5*30*60,
							orbitalDrop = true,
						},
						{
							name = "gunshipkrow",
							x = 6800,
							z = 2200,
							facing = 2,
							difficultyAtLeast = 4,
							spawnRadius = 50,
							delay = 13.5*30*60,
							orbitalDrop = true,
						},
					},
					startUnits = {
						{
							name = "turretsunlance",
							x = 4320,
							z = 1072,
							facing = 3,
							bonusObjectiveID = 3,
							mapMarker = {
								text = "Sunlance",
								color = "red_small"
							},
						},
						{
							name = "turretsunlance",
							x = 4752,
							z = 3136,
							facing = 3,
							bonusObjectiveID = 3,
							mapMarker = {
								text = "Sunlance",
								color = "red_small"
							},
						},
						{
							name = "turretsunlance",
							x = 5232,
							z = 1840,
							facing = 3,
							bonusObjectiveID = 3,
							mapMarker = {
								text = "Sunlance",
								color = "red_small"
							},
						},
						{
							name = "turretsunlance",
							x = 5024,
							z = 4320,
							facing = 3,
							bonusObjectiveID = 3,
							mapMarker = {
								text = "Sunlance",
								color = "red_small"
							},
						},
						{
							name = "amphassault",
							x = 5800,
							z = 2800,
							facing = 0,
							difficultyAtLeast = 2,
						},
						{
							name = "amphassault",
							x = 5800,
							z = 1000,
							facing = 0,
							difficultyAtLeast = 4,
						},
						{
							name = "staticshield",
							x = 5392,
							z = 1648,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6136,
							z = 936,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6520,
							z = 1496,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6520,
							z = 776,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6152,
							z = 1624,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6472,
							z = 312,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6184,
							z = 2088,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6824,
							z = 184,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6760,
							z = 1864,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6920,
							z = 1320,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6904,
							z = 2520,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5320,
							z = 1576,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6536,
							z = 2792,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4568,
							z = 1448,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6104,
							z = 3160,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5752,
							z = 2696,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4296,
							z = 488,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5064,
							z = 408,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6856,
							z = 3320,
							facing = 0,
						},
 						{
							name = "energygeo",
							x = 6392,
							z = 2264,
							facing = 3,
						},
 						{
							name = "turretaaflak",
							x = 6216,
							z = 424,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 6664,
							z = 2840,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 6632,
							z = 1672,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 6392,
							z = 792,
							facing = 3,
						},
 						{
							name = "factorygunship",
							x = 6920,
							z = 3016,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7048,
							z = 3000,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 4744,
							z = 4664,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 6024,
							z = 2488,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {6024, 2488}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5999, 2513}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 7048,
							z = 2904,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 6024,
							z = 2408,
							facing = 3,
						},
 						{
							name = "factorycloak",
							x = 6752,
							z = 440,
							facing = 3,
						},
 						{
							name = "factoryjump",
							x = 4712,
							z = 968,
							facing = 3,
						},
 						{
							name = "turretaaclose",
							x = 5848,
							z = 184,
							facing = 3,
						},
 						{
							name = "energyheavygeo",
							x = 6024,
							z = 424,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 5936,
							z = 336,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 5936,
							z = 528,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 6096,
							z = 528,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 6096,
							z = 336,
							facing = 3,
						},
 						{
							name = "turretaaclose",
							x = 5832,
							z = 648,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 6904,
							z = 408,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 4296,
							z = 920,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 4664,
							z = 840,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 4504,
							z = 952,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 4416,
							z = 1200,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 4368,
							z = 768,
							facing = 3,
						},
 						{
							name = "turretaalaser",
							x = 4584,
							z = 744,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 4696,
							z = 1560,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 5656,
							z = 1560,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 5368,
							z = 1928,
							facing = 0,
						},
 						{
							name = "turretaalaser",
							x = 5528,
							z = 1512,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 5200,
							z = 1728,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 5168,
							z = 1648,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 5136,
							z = 1552,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 5552,
							z = 2048,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 5440,
							z = 2016,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 5784,
							z = 2792,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 5608,
							z = 2488,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 5720,
							z = 3096,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 6296,
							z = 3352,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 6472,
							z = 3384,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 7096,
							z = 2776,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 4808,
							z = 3256,
							facing = 0,
						},
 						{
							name = "turretaalaser",
							x = 4920,
							z = 2760,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 4744,
							z = 2712,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 4808,
							z = 2328,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 4800,
							z = 2192,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 4272,
							z = 2400,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 4160,
							z = 2512,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 4144,
							z = 2656,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 4312,
							z = 2552,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 4952,
							z = 2392,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 5080,
							z = 2808,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 6192,
							z = 3360,
							facing = 0,
						},
 						{
							name = "turretemp",
							x = 6544,
							z = 3440,
							facing = 0,
						},
 						{
							name = "turretaalaser",
							x = 5128,
							z = 4360,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 4056,
							z = 3336,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 4040,
							z = 3208,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 3232,
							z = 1840,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 3440,
							z = 1664,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 3408,
							z = 1872,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 3472,
							z = 1984,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 3448,
							z = 2520,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 3504,
							z = 2432,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 3984,
							z = 3472,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 3456,
							z = 2640,
							facing = 3,
						},
 						{
							name = "staticheavyradar",
							x = 5328,
							z = 1872,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 5256,
							z = 2936,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 5912,
							z = 2344,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 5432,
							z = 760,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 5320,
							z = 3880,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 4920,
							z = 3848,
							facing = 1,
						},
 						{
							name = "factoryamph",
							x = 5864,
							z = 2504,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 5240,
							z = 3656,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 4072,
							z = 2888,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 4184,
							z = 2088,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 5032,
							z = 4936,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 3720,
							z = 1320,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 3624,
							z = 824,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 3624,
							z = 328,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 6224,
							z = 1888,
							facing = 3,
						},
 						{
							name = "cloakraid",
							x = 5691,
							z = 2108,
							facing = 3,
						},
 						{
							name = "jumpskirm",
							x = 2998,
							z = 2019,
							facing = 1,
						},
 						{
							name = "gunshipskirm",
							x = 4430,
							z = 3296,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 6904,
							z = 1256,
							facing = 3,
						},
 						{
							name = "gunshipassault",
							x = 4148,
							z = 1480,
							facing = 2,
						},
 						{
							name = "jumpassault",
							x = 3022,
							z = 2053,
							facing = 2,
							patrolRoute = {
								{3014, 2044},
								{3078, 2037},
							},
						},
 						{
							name = "energywind",
							x = 7000,
							z = 1352,
							facing = 3,
						},
 						{
							name = "amphfloater",
							x = 2870,
							z = 1916,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3014, 2044}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {2952, 2028}, options = {"shift"}},
							},
						},
 						{
							name = "cloakriot",
							x = 3069,
							z = 2029,
							facing = 3,
						},
 						{
							name = "cloakraid",
							x = 5417,
							z = 2269,
							facing = 3,
						},
 						{
							name = "amphraid",
							x = 5384,
							z = 3223,
							facing = 0,
						},
 						{
							name = "amphfloater",
							x = 3595,
							z = 2619,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3014, 2044}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3066, 2081}, options = {"shift"}},
							},
						},
 						{
							name = "staticmex",
							x = 6552,
							z = 4168,
							facing = 0,
						},
 						{
							name = "jumpassault",
							x = 3029,
							z = 2028,
							facing = 3,
							patrolRoute = {
								{3014, 2044},
								{3049, 1990},
							},
						},
 						{
							name = "amphfloater",
							x = 3632,
							z = 2650,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3014, 2044}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3072, 2016}, options = {"shift"}},
							},
						},
 						{
							name = "staticmex",
							x = 6888,
							z = 4488,
							facing = 0,
						},
 						{
							name = "cloakskirm",
							x = 3098,
							z = 2044,
							facing = 2,
							patrolRoute = {
								{3014, 2044},
								{3069, 2011},
							},
						},
 						{
							name = "staticmex",
							x = 6856,
							z = 4936,
							facing = 0,
							buildProgress = 0.1733,
						},
 						{
							name = "amphfloater",
							x = 3692,
							z = 2657,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3014, 2044}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3012, 2108}, options = {"shift"}},
							},
						},
 						{
							name = "cloakriot",
							x = 4396,
							z = 1363,
							facing = 3,
						},
 						{
							name = "jumpassault",
							x = 4150,
							z = 1507,
							facing = 3,
							patrolRoute = {
								{4139, 1492},
								{4170, 1548},
							},
						},
 						{
							name = "staticradar",
							x = 6592,
							z = 4000,
							facing = 3,
						},
 						{
							name = "amphraid",
							x = 3441,
							z = 2400,
							facing = 3,
						},
 						{
							name = "cloakriot",
							x = 5638,
							z = 320,
							facing = 1,
						},
 						{
							name = "amphimpulse",
							x = 3753,
							z = 2689,
							facing = 3,
						},
 						{
							name = "amphraid",
							x = 5774,
							z = 2345,
							facing = 2,
						},
 						{
							name = "amphraid",
							x = 5556,
							z = 4411,
							facing = 3,
						},
 						{
							name = "gunshipbomb",
							x = 2327,
							z = 1817,
							facing = 3,
						},
 						{
							name = "jumpraid",
							x = 4823,
							z = 1495,
							facing = 0,
						},
 						{
							name = "cloakraid",
							x = 5596,
							z = 2624,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6648,
							z = 4632,
							facing = 0,
						},
 						{
							name = "amphraid",
							x = 5283,
							z = 3522,
							facing = 3,
						},
 						{
							name = "amphraid",
							x = 5824,
							z = 2657,
							facing = 0,
						},
 						{
							name = "gunshipskirm",
							x = 6119,
							z = 3039,
							facing = 3,
						},
 						{
							name = "cloakriot",
							x = 6331,
							z = 349,
							facing = 1,
						},
 						{
							name = "amphraid",
							x = 5823,
							z = 2834,
							facing = 0,
						},
 						{
							name = "gunshipskirm",
							x = 6919,
							z = 3016,
							facing = 1,
							buildProgress = 0.8488,
						},
 						{
							name = "cloakskirm",
							x = 6503,
							z = 483,
							facing = 3,
						},
 						{
							name = "jumpassault",
							x = 4688,
							z = 968,
							facing = 3,
							buildProgress = 0.28220001,
						},
 						{
							name = "cloakskirm",
							x = 6742,
							z = 440,
							facing = 3,
							buildProgress = 0.84439999,
						},
					}
				},
			},
			terraform = {
				{
					terraformShape = planetUtilities.TERRAFORM_SHAPE.RECTANGLE,
					terraformType = planetUtilities.TERRAFORM_TYPE.LEVEL,
					position = {3416, 5700, 4740, 5990},
					height = 6,
				},
			},
			defeatConditionConfig = {
				-- Indexed by allyTeam.
				[0] = { },
				[1] = {
					ignoreUnitLossDefeat = false,
					vitalCommanders = false,
					vitalUnitTypes = {
						"factorycloak",
						"factoryjump",
						"factoryamph",
						"factorygunship",
						"energygeo",
						"energyheavygeo"
					},
					loseAfterSeconds = false,
					allyTeamLossObjectiveID = 1,
				},
			},
			objectiveConfig = {
				-- This is just related to displaying objectives on the UI.
				[1] = {
					description = "Destroy all enemy Factories and Geothermals",
				},
				[2] = {
					description = "Protect your Commander",
				},
			},
			bonusObjectiveConfig = {
				[1] = {
					satisfyOnce = true,
					countRemovedUnits = true, -- count units that previously died.
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 9,
					unitTypes = {
						"shiparty",
					},
					image = planetUtilities.ICON_DIR .. "shiparty.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.REPAIR,
					description = "Build 8 Envoys",
					experience = planetUtilities.BONUS_EXP,
				},
				[2] = {
					victoryByTime = 20*60,
					image = planetUtilities.ICON_OVERLAY.CLOCK,
					description = "Win by 20:00",
					experience = planetUtilities.BONUS_EXP,
				},
				[3] = {
					satisfyByTime = 10*60,
					comparisionType = planetUtilities.COMPARE.AT_MOST,
					targetNumber = 0,
					-- See bonusObjectiveID in units table
					image = planetUtilities.ICON_DIR .. "turretsunlance.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.ATTACK,
					description = "Destroy all 4 enemy Sunlances before 10:00",
					experience = planetUtilities.BONUS_EXP,
				},
			}
		},
		completionReward = {
			experience = planetUtilities.MAIN_EXP,
			units = {
				"factoryship",
				"shipcon",
				"shiparty",
				"shipscout",
				"shiptorpraider",
				"shipaa",
				"turrettorp",
			},
			modules = {
				"module_adv_nano_LIMIT_D_1",
			},
			abilities = {
			}
		},
	}
	
	return planetData
end

return GetPlanet
