--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Planet config

local function GetPlanet(planetUtilities, planetID)
	
	local image = LUA_DIRNAME .. "images/planets/terran03.png"
	
	local planetData = {
		name = "Bavhakya",
		startingPlanet = false,
		mapDisplay = {
			x = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][1]) or 0.66,
			y = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][2]) or 0.72,
			image = image,
			size = planetUtilities.PLANET_SIZE_MAP,
		},
		infoDisplay = {
			image = image,
			size = planetUtilities.PLANET_SIZE_INFO,
			backgroundImage = planetUtilities.backgroundImages[math.floor(math.random()*#planetUtilities.backgroundImages) + 1],
			terrainType = "Terran",
			radius = "6080 km",
			primary = "Topps",
			primaryType = "G2V",
			milRating = 1,
			feedbackLink = "http://zero-k.info/Forum/Thread/24566",
			text = "A long time ago, this world was a jewel, sculpted to perfection - or so its original terraformers said. Even after so much decay, I can still see their work from orbit, and I am not impressed. Their mountain work is inferior, their seas pretentious and unsubtle, and they couldn't even stabilize the polar ice caps."
			.. "\n "
			.. "\nThey were so insecure, they even left a force to assault anyone disagreeing, which is now set to \"everyone\"."
			,
			extendedText = "A splinter force born from a technical disagreement over river drawing has identified me as an ally. What the hell was wrong with that Empire!?"
			.. "\n "
			.. "\nMy new allies had built a few strong anti-air bastions, so the enemy is relying on ground-to-air emplacements of their own rather than attempt to contest air control with fighters. Which was short-sighted - it won't hold against the resilient and deadly Likho."
		},
		tips = {
			{
				image = "unitpics/bomberheavy.png",
				text = [[The Likho carries a bomb which inflicts heavy damage in a small area of effect. It is best used against tight clusters of enemies. Likhos require considerably more time to rearm than other bombers so plan ahead.]]
			},
			{
				image = "unitpics/staticantinuke.png",
				text = [[Make sure your allies' Antinukes remain intact or you might end up in a spot of bother.]]
			},
			{
				image = "unitpics/shieldassault.png",
				text = [[The Likho's bomb is strong enough to penetrate most shields, so it is especially effective against Shieldbots.]]
			},
		},
		gameConfig = {
			mapName = "Colorado_v1",
			playerConfig = {
				startX = 8600,
				startZ = 3200,
				allyTeam = 0,
				facplop = false,
				commanderParameters = {
					facplop = false,
					defeatIfDestroyedObjectiveID = 2,
				},
				extraUnlocks = {
					"factoryplane",
					"planecon",
					"planefighter",
					"bomberheavy",
					"staticrearm",
				},
				startUnits = {
					{
						name = "planecon",
						x = 8700,
						z = 3200,
						facing = 0,
					},
					{
						name = "bomberheavy",
						x = 8700,
						z = 3300,
						facing = 0,
					},
					{
						name = "staticmex",
						x = 9016,
						z = 2792,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 8648,
						z = 3064,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 9032,
						z = 3304,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 9032,
						z = 3208,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 9112,
						z = 3208,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 9112,
						z = 3128,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 9032,
						z = 3128,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 9032,
						z = 3048,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 9112,
						z = 3048,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 9112,
						z = 2968,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 9032,
						z = 2968,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 9032,
						z = 2888,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 9112,
						z = 2888,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 9112,
						z = 3288,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 9096,
						z = 2808,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 9192,
						z = 3256,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 9192,
						z = 3176,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 9192,
						z = 3096,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 9192,
						z = 3016,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 9192,
						z = 2936,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 9192,
						z = 2856,
						facing = 1,
					},
 					{
						name = "staticcon",
						x = 8808,
						z = 3048,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8808, 3048}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8783, 3073}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 8888,
						z = 3048,
						facing = 3,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8888, 3048}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {8863, 3073}, options = {"shift"}},
						},
					},
 					{
						name = "staticrearm",
						x = 8840,
						z = 2920,
						facing = 3,
					},
 					{
						name = "factoryplane",
						x = 8872,
						z = 3168,
						facing = 3,
					},
 					{
						name = "staticheavyradar",
						x = 8432,
						z = 3072,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8584,
						z = 2904,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8664,
						z = 2904,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8664,
						z = 2984,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 8584,
						z = 2984,
						facing = 3,
					},
 					{
						name = "turretmissile",
						x = 8672,
						z = 3440,
						facing = 3,
					},
 					{
						name = "turretmissile",
						x = 8464,
						z = 3232,
						facing = 3,
					},
 					{
						name = "turretmissile",
						x = 8464,
						z = 2880,
						facing = 3,
					},
 					{
						name = "turretmissile",
						x = 8672,
						z = 2720,
						facing = 3,
					},
 					{
						name = "energygeo",
						x = 8424,
						z = 1976,
						facing = 3,
					},
				}
			},
			aiConfig = {
				{
					humanName = "Hulukak",
					--aiLib = "Null AI",
					--bitDependant = false,
					aiLib = "Circuit_difficulty_autofill_ally",
					bitDependant = true,
					allyTeam = 0,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energypylon",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turretaalaser",
						"turretaaclose",
						"staticradar",
						"staticcon",
						"staticantinuke",
						"factoryjump",
						"jumpcon",
						"jumpraid",
						"jumpskirm",
						"jumpassault",
						"jumpsumo",
						"jumparty",
						"jumpblackhole",
						"jumpaa",
						"factoryamph",
						"amphcon",
						"amphraid",
						"amphimpulse",
						"amphfloater",
						"amphriot",
						"amphassault",
						"amphbomb",
						"amphaa",
					},
					commander = false,
					startUnits = {
						{
							name = "staticantinuke",
							x = 7896,
							z = 2192,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9048,
							z = 568,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8808,
							z = 824,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8712,
							z = 280,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7928,
							z = 744,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7688,
							z = 952,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7672,
							z = 504,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6760,
							z = 392,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6600,
							z = 1112,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6984,
							z = 1816,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6840,
							z = 2408,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7832,
							z = 2040,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8184,
							z = 1816,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8216,
							z = 2312,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 8744,
							z = 360,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8824,
							z = 424,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8904,
							z = 504,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8984,
							z = 568,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8904,
							z = 648,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8824,
							z = 728,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8888,
							z = 792,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8936,
							z = 712,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 9000,
							z = 632,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8984,
							z = 472,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8904,
							z = 408,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8280,
							z = 2264,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8824,
							z = 328,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8280,
							z = 1912,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8200,
							z = 1896,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8360,
							z = 2088,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8104,
							z = 1912,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8008,
							z = 1960,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7912,
							z = 1992,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8328,
							z = 2168,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7752,
							z = 888,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7800,
							z = 808,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7848,
							z = 728,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7864,
							z = 664,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7816,
							z = 584,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7784,
							z = 504,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7768,
							z = 984,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7832,
							z = 904,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7880,
							z = 824,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7928,
							z = 632,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7896,
							z = 552,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7864,
							z = 472,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7976,
							z = 2040,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8056,
							z = 2024,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8136,
							z = 2008,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8216,
							z = 1976,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8248,
							z = 2152,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8280,
							z = 2072,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7608,
							z = 1960,
							facing = 3,
						},
 						{
							name = "factoryamph",
							x = 7480,
							z = 1960,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7960,
							z = 1304,
							facing = 3,
						},
 						{
							name = "factoryjump",
							x = 7832,
							z = 1272,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 6808,
							z = 2184,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 6680,
							z = 2360,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 6664,
							z = 2024,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 7616,
							z = 1472,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 7680,
							z = 1184,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 7616,
							z = 384,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 7504,
							z = 96,
							facing = 3,
						},
 						{
							name = "turretaaheavy",
							x = 7840,
							z = 1680,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 7768,
							z = 1592,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 7768,
							z = 1768,
							facing = 3,
						},
 						{
							name = "turretaaflak",
							x = 7912,
							z = 1528,
							facing = 3,
						},
 						{
							name = "turretaaflak",
							x = 7912,
							z = 1832,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 5654,
							z = 1357,
							facing = 2,
						},
 						{
							name = "jumpraid",
							x = 6121,
							z = 2454,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 6341,
							z = 1502,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 5824,
							z = 3152,
							facing = 3,
							buildProgress = 0.73610002,
						},
 						{
							name = "amphcon",
							x = 7675,
							z = 772,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 7504,
							z = 1744,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 5159,
							z = 3099,
							facing = 3,
						},
 						{
							name = "jumpassault",
							x = 3991,
							z = 3197,
							facing = 1,
						},
 						{
							name = "amphraid",
							x = 4613,
							z = 2670,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 7960,
							z = 1256,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 5835,
							z = 3052,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 8080,
							z = 2208,
							facing = 3,
						},
 						{
							name = "jumpcon",
							x = 6724,
							z = 987,
							facing = 2,
						},
 						{
							name = "staticstorage",
							x = 7816,
							z = 856,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 7584,
							z = 752,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 7828,
							z = 769,
							facing = 3,
						},
 						{
							name = "jumpcon",
							x = 6869,
							z = 476,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 6992,
							z = 2160,
							facing = 3,
						},
 						{
							name = "jumpassault",
							x = 6507,
							z = 2068,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 6672,
							z = 3424,
							facing = 3,
						},
 						{
							name = "amphfloater",
							x = 5248,
							z = 3326,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 8008,
							z = 1272,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {8008, 1272}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7808, 1272}, options = {"shift"}},
							},
						},
 						{
							name = "staticmex",
							x = 5784,
							z = 2216,
							facing = 0,
						},
 						{
							name = "amphfloater",
							x = 5469,
							z = 3176,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 6688,
							z = 3168,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 6904,
							z = 2408,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 8008,
							z = 1224,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 6736,
							z = 464,
							facing = 0,
						},
 						{
							name = "amphfloater",
							x = 6679,
							z = 1895,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5752,
							z = 1368,
							facing = 0,
						},
 						{
							name = "jumpassault",
							x = 6588,
							z = 1998,
							facing = 3,
						},
 						{
							name = "energyfusion",
							x = 7744,
							z = 696,
							facing = 3,
							buildProgress = 0.4145,
						},
 						{
							name = "staticradar",
							x = 6880,
							z = 592,
							facing = 0,
							buildProgress = 0.93629998,
						},
 						{
							name = "turretlaser",
							x = 5808,
							z = 2256,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 7438,
							z = 2053,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 7688,
							z = 872,
							facing = 3,
						},
 						{
							name = "jumpassault",
							x = 7785,
							z = 1272,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 5752,
							z = 3096,
							facing = 3,
						},
 						{
							name = "amphimpulse",
							x = 7444,
							z = 1960,
							facing = 3,
							buildProgress = 0.81160003,
						},
 						{
							name = "turretlaser",
							x = 7456,
							z = 2160,
							facing = 3,
							buildProgress = 0.60829997,
						},
 						{
							name = "energysolar",
							x = 5752,
							z = 1432,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 5632,
							z = 1248,
							facing = 0,
							buildProgress = 0.0194,
						},
					}
				},
				{
					humanName = "Boyar",
					--aiLib = "Null AI",
					--bitDependant = false,
					aiLib = "Circuit_difficulty_autofill_ally",
					bitDependant = true,
					allyTeam = 0,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energypylon",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turretaalaser",
						"turretaaclose",
						"staticradar",
						"staticcon",
						"staticantinuke",
						"factoryspider",
						"spidercon",
						"spiderscout",
						"spiderriot",
						"spideremp",
						"spiderskirm",
						"spiderassault",
						"spidercrabe",
						"spiderantiheavy",
						"spideraa",
						"factoryshield",
						"shieldcon",
						"shieldraid",
						"shieldassault",
						"shieldriot",
						"shieldskirm",
						"shieldbomb",
						"shieldaa",
						"shieldfelon",
						"shieldshield",
						"shieldarty",
					},
					commander = false,
					startUnits = {
						{
							name = "staticantinuke",
							x = 8088,
							z = 4496,
							facing = 0,
						},
 						{
							name = "factoryshield",
							x = 7000,
							z = 5296,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 9048,
							z = 5592,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8776,
							z = 5864,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8712,
							z = 5336,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8520,
							z = 4680,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8152,
							z = 4376,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8440,
							z = 4008,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7272,
							z = 3784,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6696,
							z = 4200,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6664,
							z = 3352,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6968,
							z = 5080,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7224,
							z = 5656,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7656,
							z = 5896,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7624,
							z = 5352,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 8760,
							z = 5400,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8840,
							z = 5464,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8920,
							z = 5528,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 9000,
							z = 5592,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8936,
							z = 5672,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8856,
							z = 5736,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8776,
							z = 5800,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8840,
							z = 5368,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8920,
							z = 5432,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 9000,
							z = 5496,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 9016,
							z = 5688,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8936,
							z = 5752,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8856,
							z = 5816,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7304,
							z = 5656,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7368,
							z = 5576,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7432,
							z = 5496,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7512,
							z = 5416,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7576,
							z = 5336,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7400,
							z = 5720,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7480,
							z = 5784,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7560,
							z = 5848,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8440,
							z = 4616,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8360,
							z = 4552,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8280,
							z = 4488,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8200,
							z = 4424,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8216,
							z = 4328,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8264,
							z = 4248,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8296,
							z = 4168,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8344,
							z = 4088,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8376,
							z = 4008,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8408,
							z = 4072,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8376,
							z = 4152,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8328,
							z = 4232,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8296,
							z = 4312,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8264,
							z = 4392,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8344,
							z = 4440,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8424,
							z = 4504,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8504,
							z = 4568,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7464,
							z = 5640,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7528,
							z = 5560,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7592,
							z = 5480,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7544,
							z = 5704,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7624,
							z = 5768,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7176,
							z = 5368,
							facing = 3,
						},
 						{
							name = "factoryspider",
							x = 8088,
							z = 3992,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 8216,
							z = 3992,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 6744,
							z = 5576,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 6632,
							z = 5336,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 6664,
							z = 5832,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 7464,
							z = 4392,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 7448,
							z = 3096,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 7504,
							z = 3936,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 7504,
							z = 3744,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 7296,
							z = 2944,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 7344,
							z = 4528,
							facing = 3,
						},
 						{
							name = "turretaaheavy",
							x = 7888,
							z = 4928,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 7816,
							z = 4840,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 7816,
							z = 5016,
							facing = 3,
						},
 						{
							name = "turretaaflak",
							x = 7992,
							z = 4728,
							facing = 3,
						},
 						{
							name = "turretaaflak",
							x = 7992,
							z = 5160,
							facing = 3,
						},
 						{
							name = "shieldcon",
							x = 4824,
							z = 2855,
							facing = 3,
						},
 						{
							name = "spideremp",
							x = 4769,
							z = 3913,
							facing = 0,
						},
 						{
							name = "spiderscout",
							x = 6779,
							z = 3385,
							facing = 3,
						},
 						{
							name = "spiderscout",
							x = 7502,
							z = 3673,
							facing = 3,
						},
 						{
							name = "shieldskirm",
							x = 4792,
							z = 4015,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 6960,
							z = 5488,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 4907,
							z = 3193,
							facing = 3,
						},
 						{
							name = "shieldcon",
							x = 6378,
							z = 3216,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 7424,
							z = 5392,
							facing = 3,
						},
 						{
							name = "shieldcon",
							x = 5356,
							z = 4489,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 8200,
							z = 3944,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 6239,
							z = 4506,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 5960,
							z = 5640,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 7720,
							z = 5480,
							facing = 3,
						},
 						{
							name = "shieldcon",
							x = 8752,
							z = 4569,
							facing = 2,
						},
 						{
							name = "spiderassault",
							x = 7045,
							z = 4046,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 8431,
							z = 2183,
							facing = 3,
						},
 						{
							name = "spiderassault",
							x = 7086,
							z = 4106,
							facing = 3,
						},
 						{
							name = "shieldassault",
							x = 6609,
							z = 4303,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 5952,
							z = 5696,
							facing = 2,
						},
 						{
							name = "spiderassault",
							x = 5296,
							z = 3546,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 8200,
							z = 4088,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 7272,
							z = 3848,
							facing = 3,
						},
 						{
							name = "shieldassault",
							x = 6638,
							z = 4331,
							facing = 2,
						},
 						{
							name = "staticstorage",
							x = 7592,
							z = 5272,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 8232,
							z = 4040,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 6040,
							z = 5672,
							facing = 2,
						},
 						{
							name = "spidercon",
							x = 5937,
							z = 3478,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 7688,
							z = 5384,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 8504,
							z = 3976,
							facing = 3,
						},
 						{
							name = "spiderassault",
							x = 6681,
							z = 4327,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 8825,
							z = 4411,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 6752,
							z = 3584,
							facing = 3,
						},
 						{
							name = "shieldassault",
							x = 5331,
							z = 5065,
							facing = 1,
						},
 						{
							name = "spiderassault",
							x = 6555,
							z = 4254,
							facing = 3,
						},
 						{
							name = "spiderassault",
							x = 6650,
							z = 4293,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 8264,
							z = 3992,
							facing = 3,
						},
 						{
							name = "shieldskirm",
							x = 5478,
							z = 5100,
							facing = 3,
						},
 						{
							name = "shieldskirm",
							x = 5554,
							z = 5171,
							facing = 2,
						},
 						{
							name = "spiderscout",
							x = 4576,
							z = 2840,
							facing = 2,
						},
 						{
							name = "spiderscout",
							x = 6327,
							z = 4614,
							facing = 0,
						},
 						{
							name = "spiderassault",
							x = 6619,
							z = 4261,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 8584,
							z = 4696,
							facing = 3,
						},
 						{
							name = "spiderassault",
							x = 6664,
							z = 4253,
							facing = 3,
						},
 						{
							name = "shieldassault",
							x = 5289,
							z = 5066,
							facing = 1,
						},
 						{
							name = "spiderscout",
							x = 7277,
							z = 3666,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 6033,
							z = 3153,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 8248,
							z = 3944,
							facing = 3,
						},
 						{
							name = "spiderassault",
							x = 6512,
							z = 4252,
							facing = 3,
						},
 						{
							name = "shieldassault",
							x = 5637,
							z = 5195,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6008,
							z = 3640,
							facing = 0,
						},
 						{
							name = "shieldassault",
							x = 6662,
							z = 4365,
							facing = 2,
						},
 						{
							name = "spideremp",
							x = 6639,
							z = 4221,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 7024,
							z = 5088,
							facing = 3,
						},
 						{
							name = "spideremp",
							x = 6694,
							z = 4289,
							facing = 3,
						},
 						{
							name = "spiderscout",
							x = 6592,
							z = 3678,
							facing = 0,
						},
 						{
							name = "shieldcon",
							x = 6356,
							z = 5309,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 5944,
							z = 3640,
							facing = 3,
						},
 						{
							name = "spiderscout",
							x = 6957,
							z = 4365,
							facing = 0,
						},
 						{
							name = "spiderscout",
							x = 7123,
							z = 3541,
							facing = 1,
						},
 						{
							name = "spiderscout",
							x = 6997,
							z = 4333,
							facing = 0,
						},
 						{
							name = "shieldraid",
							x = 6634,
							z = 5208,
							facing = 3,
						},
 						{
							name = "spiderscout",
							x = 7369,
							z = 4233,
							facing = 3,
						},
 						{
							name = "spiderscout",
							x = 7856,
							z = 3697,
							facing = 3,
						},
 						{
							name = "shieldfelon",
							x = 6988,
							z = 5296,
							facing = 3,
							buildProgress = 0.1655,
						},
 						{
							name = "staticmex",
							x = 4728,
							z = 2840,
							facing = 0,
							buildProgress = 0.2888,
						},
 						{
							name = "spiderriot",
							x = 8052,
							z = 3992,
							facing = 3,
							buildProgress = 0.97970003,
						},
 						{
							name = "staticmex",
							x = 4728,
							z = 3272,
							facing = 0,
							buildProgress = 0.1833,
						},
					}
				},
				{
					startX = 2000,
					startZ = 2000,
					humanName = "Quatuiey",
					--aiLib = "Null AI",
					--bitDependant = false,
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					commanderParameters = {
						facplop = false,
						bonusObjectiveID = 2,
					},
					allyTeam = 1,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energypylon",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turretaalaser",
						"turretaaclose",
						"staticradar",
						"staticcon",
						"staticantinuke",
						"jumpcon",
						"jumpraid",
						"jumpskirm",
						"jumpassault",
						--"jumpsumo",
						"jumparty",
						"jumpblackhole",
						"jumpaa",
						"spidercon",
						"spiderscout",
						"spiderriot",
						"spideremp",
						"spiderskirm",
						"spiderassault",
						"spidercrabe",
						"spiderantiheavy",
						"spideraa",
					},
					difficultyDependantUnlocks = {
						[3] = {"jumpsumo"},
						[4] = {"jumpsumo","factoryjump"},
					},
					commanderLevel = 7,
					commander = {
						name = "Tessica",
						chassis = "strike",
						modules = {
							"commweapon_shotgun",
							"commweapon_disintegrator",
							"module_personal_cloak",
							"module_autorepair",
							"module_autorepair",
							"module_autorepair",
							"module_autorepair",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_high_power_servos",
						}
					},
					startUnits = {
						{
							name = "staticmex",
							x = 504,
							z = 840,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 200,
							z = 520,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 488,
							z = 232,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1544,
							z = 296,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1720,
							z = 632,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2056,
							z = 312,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2440,
							z = 776,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2056,
							z = 2072,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1112,
							z = 2120,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 792,
							z = 2392,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 792,
							z = 1800,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2728,
							z = 1672,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 2616,
							z = 2680,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 216,
							z = 3464,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 232,
							z = 3032,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 600,
							z = 3240,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 360,
							z = 584,
							facing = 1,
						},
 						{
							name = "turretaaclose",
							x = 424,
							z = 3592,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 64,
							z = 696,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 64,
							z = 824,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 48,
							z = 3320,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 48,
							z = 3176,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 672,
							z = 2120,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 904,
							z = 2088,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1144,
							z = 2296,
							facing = 1,
						},
 						{
							name = "factoryspider",
							x = 1304,
							z = 2312,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1144,
							z = 2376,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 2072,
							z = 696,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 2072,
							z = 600,
							facing = 1,
						},
 						{
							name = "factoryjump",
							x = 2200,
							z = 472,
							facing = 1,
						},
 						{
							name = "turretaafar",
							x = 768,
							z = 3216,
							facing = 1,
						},
 						{
							name = "turretaaclose",
							x = 408,
							z = 2904,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 136,
							z = 3240,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 280,
							z = 3272,
							facing = 1,
						},
 						{
							name = "staticnuke",
							x = 416,
							z = 3264,
							facing = 2,
						},
 						{
							name = "turretriot",
							x = 232,
							z = 2792,
							facing = 2,
						},
 						{
							name = "turretriot",
							x = 216,
							z = 3704,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 616,
							z = 3480,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 616,
							z = 2984,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 680,
							z = 760,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 744,
							z = 344,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 632,
							z = 520,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 344,
							z = 872,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1888,
							z = 2944,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1744,
							z = 2608,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1680,
							z = 2304,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1744,
							z = 1872,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1936,
							z = 1424,
							facing = 1,
						},
 						{
							name = "turretaafar",
							x = 2496,
							z = 976,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 2632,
							z = 760,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 2648,
							z = 280,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 2768,
							z = 192,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 2784,
							z = 800,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 2176,
							z = 1152,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 2096,
							z = 3184,
							facing = 1,
						},
 						{
							name = "turretaaclose",
							x = 1368,
							z = 2072,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 3352,
							z = 2408,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 3368,
							z = 1944,
							facing = 1,
						},
 						{
							name = "energygeo",
							x = 3480,
							z = 2184,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 3400,
							z = 2024,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 3400,
							z = 2344,
							facing = 1,
						},
 						{
							name = "turretaaclose",
							x = 3608,
							z = 2088,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 3912,
							z = 2152,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 3808,
							z = 1888,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 3680,
							z = 2352,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 3304,
							z = 2184,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 3120,
							z = 2368,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 3168,
							z = 2016,
							facing = 1,
						},
 						{
							name = "jumparty",
							x = 1284,
							z = 775,
							facing = 3,
						},
 						{
							name = "spiderriot",
							x = 3969,
							z = 2937,
							facing = 1,
						},
 						{
							name = "jumpskirm",
							x = 3969,
							z = 2801,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 2392,
							z = 1880,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 600,
							z = 1539,
							facing = 0,
						},
 						{
							name = "jumpcon",
							x = 3338,
							z = 512,
							facing = 1,
						},
 						{
							name = "jumpskirm",
							x = 4039,
							z = 2899,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 1184,
							z = 2112,
							facing = 1,
						},
 						{
							name = "jumpassault",
							x = 4017,
							z = 3128,
							facing = 1,
						},
 						{
							name = "spiderscout",
							x = 5920,
							z = 4225,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 752,
							z = 2016,
							facing = 1,
						},
 						{
							name = "staticstorage",
							x = 1944,
							z = 2088,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 740,
							z = 5200,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1792,
							z = 464,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 2241,
							z = 4345,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 2024,
							z = 456,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 2213,
							z = 1263,
							facing = 0,
						},
 						{
							name = "jumpassault",
							x = 4047,
							z = 2852,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 3330,
							z = 4114,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1976,
							z = 456,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 3499,
							z = 1141,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 3268,
							z = 2112,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 224,
							z = 3072,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1296,
							z = 3936,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 2608,
							z = 1728,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 512,
							z = 3024,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 2440,
							z = 552,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 2336,
							z = 3456,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 3295,
							z = 652,
							facing = 2,
						},
 						{
							name = "spiderscout",
							x = 5854,
							z = 4134,
							facing = 2,
						},
 						{
							name = "spiderscout",
							x = 5844,
							z = 4277,
							facing = 2,
						},
 						{
							name = "spiderscout",
							x = 5909,
							z = 3722,
							facing = 2,
						},
 						{
							name = "jumpraid",
							x = 3101,
							z = 2977,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 2304,
							z = 736,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 2177,
							z = 1241,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 2768,
							z = 1712,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1056,
							z = 2304,
							facing = 1,
						},
 						{
							name = "jumpraid",
							x = 3840,
							z = 2992,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 2280,
							z = 1352,
							facing = 1,
						},
 						{
							name = "spiderassault",
							x = 3405,
							z = 2962,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 2008,
							z = 408,
							facing = 0,
						},
 						{
							name = "spiderassault",
							x = 3164,
							z = 2879,
							facing = 1,
						},
 						{
							name = "jumpassault",
							x = 2648,
							z = 1348,
							facing = 1,
							patrolRoute = {
								{2664, 1270},
								{2662, 1334},
							},
						},
 						{
							name = "energysolar",
							x = 2360,
							z = 984,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 656,
							z = 672,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 2184,
							z = 1000,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 1720,
							z = 4104,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 336,
							z = 5584,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 2264,
							z = 1000,
							facing = 1,
						},
 						{
							name = "jumpskirm",
							x = 2366,
							z = 751,
							facing = 0,
						},
 						{
							name = "spiderscout",
							x = 3560,
							z = 2668,
							facing = 0,
						},
 						{
							name = "spiderscout",
							x = 2839,
							z = 2591,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 2088,
							z = 1064,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 3448,
							z = 504,
							facing = 0,
							buildProgress = 0.88660002,
						},
 						{
							name = "energysolar",
							x = 2184,
							z = 1384,
							facing = 1,
						},
 						{
							name = "spiderscout",
							x = 2476,
							z = 2467,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 1340,
							z = 2312,
							facing = 1,
							buildProgress = 0.52160001,
						},
 						{
							name = "energysolar",
							x = 2104,
							z = 1432,
							facing = 1,
						},
 						{
							name = "jumpraid",
							x = 2224,
							z = 472,
							facing = 1,
							buildProgress = 0.59539998,
						},
 						{
							name = "turretlaser",
							x = 2432,
							z = 4400,
							facing = 1,
							buildProgress = 0.15549999,
						},
					}
				},
				{
					humanName = "Babbas",
					--aiLib = "Null AI",
					--bitDependant = false,
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					allyTeam = 1,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energypylon",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turretaalaser",
						"turretaaclose",
						"staticradar",
						"staticcon",
						"staticantinuke",
						"amphcon",
						"amphraid",
						"amphimpulse",
						"amphfloater",
						"amphriot",
						"amphassault",
						"amphbomb",
						"amphaa",
						"shieldcon",
						"shieldraid",
						"shieldassault",
						"shieldriot",
						"shieldskirm",
						"shieldbomb",
						"shieldaa",
						"shieldfelon",
						"shieldshield",
						"shieldarty",
						"cloakcon",
						"cloakraid",
						"cloakriot",
						"cloakskirm",
						"cloakassault",
						--"cloakaa",
						"cloakarty",
						"cloaksnipe",
						"cloakheavyraid",
						"cloakbomb",
					},
					difficultyDependantUnlocks = {
						[3] = {"cloakaa"},
						[4] = {"cloakaa","factorycloak"},
					},
					midgameUnits = {
						{
							name = "amphassault",
							x = 1450,
							z = 2800,
							facing = 0,
							spawnRadius = 150,
							delay = 4*30*60,
							orbitalDrop = true,
						},
						{
							name = "amphassault",
							x = 1450,
							z = 2800,
							facing = 0,
							spawnRadius = 150,
							delay = 4*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 2,
						},
						{
							name = "amphassault",
							x = 1450,
							z = 2800,
							facing = 0,
							spawnRadius = 150,
							delay = 4*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 3,
						},
						{
							name = "amphassault",
							x = 1450,
							z = 2800,
							facing = 0,
							spawnRadius = 150,
							delay = 4*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 4,
						},
					},
					commander = false,
					startUnits = {
						{
							name = "staticmex",
							x = 168,
							z = 5576,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 392,
							z = 5832,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 392,
							z = 5192,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1304,
							z = 5368,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1544,
							z = 5560,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1544,
							z = 5096,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1160,
							z = 4216,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1624,
							z = 4008,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1208,
							z = 3704,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2376,
							z = 3432,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2440,
							z = 4344,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2600,
							z = 5528,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 64,
							z = 5352,
							facing = 1,
						},
 						{
							name = "energygeo",
							x = 712,
							z = 4264,
							facing = 3,
						},
 						{
							name = "energyfusion",
							x = 64,
							z = 5192,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 1128,
							z = 4056,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 472,
							z = 5480,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 1320,
							z = 5224,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1208,
							z = 4712,
							facing = 1,
						},
 						{
							name = "factoryshield",
							x = 1352,
							z = 4736,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1208,
							z = 4616,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1528,
							z = 3448,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1528,
							z = 3544,
							facing = 1,
						},
 						{
							name = "factoryamph",
							x = 1656,
							z = 3528,
							facing = 1,
						},
 						{
							name = "factorycloak",
							x = 1440,
							z = 5848,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 600,
							z = 5560,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 600,
							z = 5368,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 648,
							z = 5736,
							facing = 1,
						},
 						{
							name = "turretaaflak",
							x = 312,
							z = 5384,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1256,
							z = 5832,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 1768,
							z = 5656,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 1832,
							z = 5496,
							facing = 1,
						},
 						{
							name = "turretaaclose",
							x = 1560,
							z = 5688,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 1784,
							z = 5048,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 1784,
							z = 4904,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 2624,
							z = 3760,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 2624,
							z = 4048,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 2536,
							z = 3912,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 2664,
							z = 3608,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 2680,
							z = 4184,
							facing = 1,
						},
 						{
							name = "turretaafar",
							x = 2240,
							z = 3936,
							facing = 1,
						},
 						{
							name = "turretaaclose",
							x = 1688,
							z = 3704,
							facing = 1,
						},
 						{
							name = "energygeo",
							x = 3464,
							z = 5480,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 3336,
							z = 5192,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 3256,
							z = 5640,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 3304,
							z = 5576,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 3384,
							z = 5288,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 3752,
							z = 5512,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 3712,
							z = 5184,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 3664,
							z = 5792,
							facing = 1,
						},
 						{
							name = "turretaaclose",
							x = 3464,
							z = 5688,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 3288,
							z = 5400,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 3184,
							z = 5184,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 3136,
							z = 5616,
							facing = 1,
						},
 						{
							name = "shieldraid",
							x = 3855,
							z = 3912,
							facing = 2,
						},
 						{
							name = "amphraid",
							x = 4870,
							z = 4960,
							facing = 1,
							patrolRoute = {
								{4848, 4974},
								{4904, 4943},
							},
						},
 						{
							name = "cloakraid",
							x = 4870,
							z = 4992,
							facing = 0,
							patrolRoute = {
								{4848, 4974},
								{4855, 5037},
							},
						},
 						{
							name = "shieldriot",
							x = 4618,
							z = 4211,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 3432,
							z = 3994,
							facing = 0,
						},
 						{
							name = "cloakcon",
							x = 3043,
							z = 4716,
							facing = 2,
						},
 						{
							name = "shieldskirm",
							x = 2826,
							z = 4767,
							facing = 1,
						},
 						{
							name = "shieldcon",
							x = 4021,
							z = 4282,
							facing = 3,
						},
 						{
							name = "cloakriot",
							x = 4582,
							z = 4215,
							facing = 1,
						},
 						{
							name = "shieldskirm",
							x = 4675,
							z = 4179,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 1328,
							z = 4528,
							facing = 1,
						},
 						{
							name = "staticstorage",
							x = 1528,
							z = 5144,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 3881,
							z = 2622,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 2504,
							z = 2952,
							facing = 1,
						},
 						{
							name = "cloakraid",
							x = 4839,
							z = 4984,
							facing = 2,
							patrolRoute = {
								{4785, 4985},
								{4848, 4974},
							},
						},
 						{
							name = "amphcon",
							x = 3032,
							z = 4175,
							facing = 3,
						},
 						{
							name = "shieldassault",
							x = 4656,
							z = 4211,
							facing = 3,
						},
 						{
							name = "cloakriot",
							x = 4695,
							z = 4200,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 1568,
							z = 5280,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 1721,
							z = 4699,
							facing = 1,
						},
 						{
							name = "shieldcon",
							x = 1813,
							z = 4771,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 2272,
							z = 3616,
							facing = 1,
						},
 						{
							name = "amphraid",
							x = 4834,
							z = 4937,
							facing = 0,
							patrolRoute = {
								{4826, 4913},
								{4848, 4974},
							},
						},
 						{
							name = "cloakskirm",
							x = 4668,
							z = 4161,
							facing = 1,
						},
 						{
							name = "shieldcon",
							x = 3407,
							z = 3615,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 2440,
							z = 2424,
							facing = 1,
						},
 						{
							name = "cloakraid",
							x = 3488,
							z = 3630,
							facing = 2,
						},
 						{
							name = "cloakriot",
							x = 4638,
							z = 4241,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 3620,
							z = 3035,
							facing = 2,
						},
 						{
							name = "shieldcon",
							x = 3962,
							z = 2661,
							facing = 1,
						},
 						{
							name = "amphfloater",
							x = 3505,
							z = 3401,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3403, 3417}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3352, 3456}, options = {"shift"}},
							},
						},
 						{
							name = "staticstorage",
							x = 1528,
							z = 4984,
							facing = 1,
						},
 						{
							name = "shieldcon",
							x = 2976,
							z = 4246,
							facing = 2,
						},
 						{
							name = "cloakcon",
							x = 3817,
							z = 4333,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 2312,
							z = 4152,
							facing = 1,
						},
 						{
							name = "cloakcon",
							x = 3735,
							z = 3983,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 3704,
							z = 4712,
							facing = 0,
						},
 						{
							name = "amphraid",
							x = 4813,
							z = 4977,
							facing = 0,
							patrolRoute = {
								{4848, 4974},
								{4798, 5014},
							},
						},
 						{
							name = "shieldraid",
							x = 3630,
							z = 3796,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 2824,
							z = 4904,
							facing = 0,
						},
 						{
							name = "amphfloater",
							x = 3451,
							z = 3415,
							facing = 3,
							patrolRoute = {
								{3405, 3481},
								{3403, 3417},
							},
						},
 						{
							name = "staticcon",
							x = 1304,
							z = 5848,
							facing = 1,
						},
 						{
							name = "amphfloater",
							x = 3488,
							z = 3436,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3403, 3417}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3412, 3480}, options = {"shift"}},
							},
						},
 						{
							name = "staticmex",
							x = 3352,
							z = 3816,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 3728,
							z = 4592,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 2720,
							z = 5136,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 2408,
							z = 3592,
							facing = 1,
						},
 						{
							name = "amphfloater",
							x = 3398,
							z = 3421,
							facing = 1,
							patrolRoute = {
								{3403, 3417},
								{3363, 3466},
							},
						},
 						{
							name = "turretlaser",
							x = 3216,
							z = 3776,
							facing = 1,
						},
 						{
							name = "shieldcon",
							x = 3392,
							z = 4217,
							facing = 2,
						},
 						{
							name = "cloakskirm",
							x = 3609,
							z = 4709,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 2520,
							z = 3464,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1328,
							z = 4944,
							facing = 1,
						},
 						{
							name = "shieldassault",
							x = 3341,
							z = 4821,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 2536,
							z = 3576,
							facing = 1,
						},
 						{
							name = "cloakraid",
							x = 3541,
							z = 3724,
							facing = 2,
						},
 						{
							name = "amphfloater",
							x = 3106,
							z = 3546,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3403, 3417}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3379, 3357}, options = {"shift"}},
							},
						},
 						{
							name = "energypylon",
							x = 3528,
							z = 4264,
							facing = 2,
						},
 						{
							name = "cloakskirm",
							x = 3024,
							z = 4786,
							facing = 2,
						},
 						{
							name = "shieldskirm",
							x = 2875,
							z = 4768,
							facing = 1,
						},
 						{
							name = "amphfloater",
							x = 2709,
							z = 3774,
							facing = 1,
						},
 						{
							name = "cloakskirm",
							x = 2744,
							z = 4874,
							facing = 2,
						},
 						{
							name = "shieldfelon",
							x = 1526,
							z = 4756,
							facing = 1,
						},
 						{
							name = "amphraid",
							x = 3116,
							z = 3677,
							facing = 0,
						},
 						{
							name = "cloakraid",
							x = 2650,
							z = 4900,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 1704,
							z = 4808,
							facing = 1,
						},
 						{
							name = "amphraid",
							x = 2538,
							z = 3648,
							facing = 1,
						},
 						{
							name = "cloakraid",
							x = 2288,
							z = 5401,
							facing = 1,
						},
 						{
							name = "cloakskirm",
							x = 1797,
							z = 5772,
							facing = 1,
						},
 						{
							name = "amphraid",
							x = 2065,
							z = 3551,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 2936,
							z = 4136,
							facing = 1,
						},
 						{
							name = "shieldskirm",
							x = 1364,
							z = 4736,
							facing = 1,
							buildProgress = 0.96109998,
						},
 						{
							name = "energysolar",
							x = 1832,
							z = 4664,
							facing = 1,
							buildProgress = 0.75950003,
						},
 						{
							name = "amphfloater",
							x = 1692,
							z = 3528,
							facing = 1,
							buildProgress = 0.1288,
						},
 						{
							name = "cloakskirm",
							x = 1449,
							z = 5848,
							facing = 1,
							buildProgress = 0.1629,
						},
					}
				},
			},
			defeatConditionConfig = {
				-- Indexed by allyTeam.
				[0] = { },
				[1] = {
					ignoreUnitLossDefeat = false,
					vitalCommanders = false,
					vitalUnitTypes = {
						"factoryshield",
						"factoryjump",
						"factoryspider",
						"factoryamph",
						"factorycloak",
					},
					loseAfterSeconds = false,
					allyTeamLossObjectiveID = 1,
				},
			},
			objectiveConfig = {
				-- This is just related to displaying objectives on the UI.
				[1] = {
					description = "Destroy all enemy Factories",
				},
				[2] = {
					description = "Protect your Commander",
				},
			},
			bonusObjectiveConfig = {
				[1] = {
					satisfyByTime = 12*60,
					comparisionType = planetUtilities.COMPARE.AT_MOST,
					targetNumber = 0,
					enemyUnitTypes = {
						"staticnuke",
					},
					image = planetUtilities.ICON_DIR .. "staticnuke.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.ATTACK,
					description = "Find and destroy the enemy Trinity before 12:00",
					experience = planetUtilities.BONUS_EXP,
				},
				[2] = {
					satisfyByTime = 12*60,
					comparisionType = planetUtilities.COMPARE.AT_MOST,
					targetNumber = 0,
					-- See bonusObjectiveID in units table
					image = planetUtilities.ICON_DIR .. "strike.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.ATTACK,
					description = "Destroy the enemy commander before 12:00",
					experience = planetUtilities.BONUS_EXP,
				},
				[3] = { -- Complete all bonus objectives
					completeAllBonusObjectives = true,
					image = planetUtilities.ICON_OVERLAY.ALL,
					description = "Complete all bonus objectives (in one battle).",
					experience = planetUtilities.BONUS_EXP,
				},
			}
		},
		completionReward = {
			experience = planetUtilities.MAIN_EXP,
			units = {
				"bomberheavy",
			},
			modules = {
				"module_battle_drone_LIMIT_B_2",
			},
			abilities = {
			},
			codexEntries = {
				"faction_lawless"
			}
		},
	}
	
	return planetData
end

return GetPlanet
