--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Planet config

local function GetPlanet(planetUtilities, planetID)
	
	local image = LUA_DIRNAME .. "images/planets/terran02.png"
	
	local planetData = {
		name = "Pendust",
		startingPlanet = false,
		mapDisplay = {
			x = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][1]) or 0.86,
			y = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][2]) or 0.64,
			image = image,
			size = planetUtilities.PLANET_SIZE_MAP,
		},
		infoDisplay = {
			image = image,
			size = planetUtilities.PLANET_SIZE_INFO,
			backgroundImage = planetUtilities.backgroundImages[math.floor(math.random()*#planetUtilities.backgroundImages) + 1],
			terrainType = "Coastal",
			radius = "7300 km",
			primary = "Narlapa",
			primaryType = "G7V",
			milRating = 1,
			feedbackLink = "http://zero-k.info/Forum/Thread/24594",
			text = "This was the capital of Haven. It must have been such a beautiful world in its prime. But war was closing, even there. Evacuation had started, and they were halfway done turning it into a fortress. Every industry retooled to build military hardware. Every air traffic system repurposed for war."
			.. "\n "
			.. "\nThen, just like that, everyone was gone."
			,
			extendedText = "I'm lucky that even half the fleet acknowledged those damn IFF codes. Now, to take control of the sea, then the enemy shoreline, with Shogun battleships. I'd better hurry - if they finish that Zenith meteor controller, things will become a lot more difficult..."
		},
		tips = {
			{
				image = "unitpics/shipheavyarty.png",
				text = [[The Shogun battleship is a straightforward unit; nine artillery cannons' worth of firepower lay waste to your enemies. As artillery units go the Shogun is fairly tough, but keep it away from submarines - it has no defense against underwater foes.]]
			},
			{
				image = "unitpics/conversion_partillery.png",
				text = [[If the terrain or enemy shields don't permit direct fire, Shoguns can be toggled to fire at a high angle instead. This firing mode is less accurate so use it only when necessary.]]
			},
			{
				image = "unitpics/zenith.png",
				text = [[The Zenith superweapon collects meteors from space and flings them across the map. The best counter to any superweapon is to destroy it before it is completed.]]
			},
		},
		gameConfig = {
			mapName = "Downs_of_Destruction_Fix",
			playerConfig = {
				startX = 5000,
				startZ = 1500,
				allyTeam = 0,
				commanderParameters = {
					facplop = true,
					defeatIfDestroyedObjectiveID = 2,
				},
				extraUnlocks = {
					"striderhub",
					"shipheavyarty",
				},
				startUnits = {
					{
						name = "shipheavyarty",
						x = 5450,
						z = 1200,
						facing = 0,
						buildProgress = 0.5,
					},
					-- flotilla
					{
						name = "shiparty",
						x = 4800,
						z = 1700,
						facing = 0,
					},
					{
						name = "shipheavyarty",
						x = 5000,
						z = 1700,
						facing = 0,
					},
					{
						name = "shiparty",
						x = 5200,
						z = 1700,
						facing = 0,
					},
					{
						name = "shipskirm",
						x = 4600,
						z = 1800,
						facing = 0,
					},
					{
						name = "shipriot",
						x = 4800,
						z = 1900,
						facing = 0,
					},
					{
						name = "shipassault",
						x = 5000,
						z = 2000,
						facing = 0,
					},
					{
						name = "shipriot",
						x = 5200,
						z = 1900,
						facing = 0,
					},
					{
						name = "shipskirm",
						x = 5400,
						z = 1800,
						facing = 0,
					},
					--
					{
						name = "pw_metal",
						x = 4950,
						z = 250,
						facing = 0,
					},
					{
						name = "factoryship",
						x = 5024,
						z = 1232,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 3336,
						z = 1592,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 4408,
						z = 952,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 5528,
						z = 2392,
						facing = 0,
					},
 					-- {
						-- name = "shipheavyarty",
						-- x = 5583,
						-- z = 1713,
						-- facing = 0,
					-- },
 					{
						name = "energywind",
						x = 4456,
						z = 904,
						facing = 2,
					},
 					{
						name = "staticmex",
						x = 4248,
						z = 1768,
						facing = 2,
					},
 					{
						name = "staticcon",
						x = 5176,
						z = 1160,
						facing = 0,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5176, 1160}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5151, 1185}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 5176,
						z = 1256,
						facing = 0,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5176, 1256}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5151, 1281}, options = {"shift"}},
						},
					},
 					{
						name = "striderhub",
						x = 5280,
						z = 1200,
						facing = 0,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5280, 1200}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5255, 1225}, options = {"shift"}},
						},
					},
 					{
						name = "energywind",
						x = 3384,
						z = 1592,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 3384,
						z = 1640,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 3336,
						z = 1640,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 3288,
						z = 1640,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 3288,
						z = 1592,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 3288,
						z = 1544,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 3336,
						z = 1544,
						facing = 2,
					},
 					{
						name = "energywind",
						x = 3384,
						z = 1544,
						facing = 2,
					},
 					{
						name = "energywind",
						x = 4456,
						z = 952,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 4456,
						z = 1000,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 4408,
						z = 1000,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 4360,
						z = 1000,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 4360,
						z = 952,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 4360,
						z = 904,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 4408,
						z = 904,
						facing = 2,
					},
 					{
						name = "energysolar",
						x = 4312,
						z = 1784,
						facing = 3,
					},
 					{
						name = "staticcon",
						x = 5176,
						z = 1352,
						facing = 0,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5176, 1352}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5151, 1377}, options = {"shift"}},
						},
					},
 					{
						name = "energysolar",
						x = 4184,
						z = 1752,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 5576,
						z = 2392,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 5576,
						z = 2440,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 5528,
						z = 2440,
						facing = 2,
					},
 					{
						name = "energywind",
						x = 5480,
						z = 2440,
						facing = 2,
					},
 					{
						name = "energywind",
						x = 5480,
						z = 2392,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 5480,
						z = 2344,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 5528,
						z = 2344,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 5576,
						z = 2344,
						facing = 0,
					},
				}
			},
			aiConfig = {
				{
					humanName = "Biobas",
					aiLib = "Circuit_difficulty_autofill_ally",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					allyTeam = 0,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energypylon",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turrettorp",
						"turretgauss",
						"turretheavylaser",
						"turretaalaser",
						"turretaaclose",
						"turretaaflak",
						"shieldshield",
						"staticradar",
						"staticheavyradar",
						"staticcon",
						"staticantinuke",
						"staticrearm",
						"factoryplane",
						"planecon",
						"planescout",
						"planefighter",
						"planeheavyfighter",
						"bomberprec",
						"bomberdisarm",
						"bomberheavy",
						"factoryamph",
						"amphcon",
						"amphraid",
						"amphimpulse",
						"amphfloater",
						"amphriot",
						"amphassault",
						"amphbomb",
						"amphaa",
						"factoryship",
						"shipcon",
						"shipaa",
						"shiparty",
						"shipassault",
						"shipriot",
						"shipscout",
						"shipskirm",
						"shiptorpraider",
						"subraider",
					},
					commander = false,
					startUnits = {
						{
							name = "staticmex",
							x = 2056,
							z = 504,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1432,
							z = 744,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 456,
							z = 936,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 248,
							z = 88,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1144,
							z = 1720,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2744,
							z = 264,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4072,
							z = 264,
							facing = 0,
						},
 						{
							name = "energyheavygeo",
							x = 1736,
							z = 1368,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 2640,
							z = 336,
							facing = 0,
						},
 						{
							name = "planecon",
							x = 4987,
							z = 3426,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 1256,
							z = 1224,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 520,
							z = 536,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 824,
							z = 872,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 904,
							z = 872,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 904,
							z = 952,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 824,
							z = 952,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 2088,
							z = 840,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 2888,
							z = 440,
							facing = 2,
						},
 						{
							name = "energyfusion",
							x = 440,
							z = 48,
							facing = 2,
						},
 						{
							name = "energyfusion",
							x = 616,
							z = 48,
							facing = 2,
						},
 						{
							name = "staticrearm",
							x = 1000,
							z = 1000,
							facing = 3,
						},
 						{
							name = "factoryplane",
							x = 1384,
							z = 992,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 1288,
							z = 824,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1368,
							z = 872,
							facing = 0,
						},
 						{
							name = "factoryship",
							x = 2800,
							z = 1888,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 2936,
							z = 1816,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 2936,
							z = 1896,
							facing = 0,
						},
 						{
							name = "factoryamph",
							x = 1656,
							z = 2184,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1752,
							z = 2056,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1656,
							z = 2056,
							facing = 0,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1656, 2220}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1656, 2056}, options = {"shift"}},
							},
						},
 						{
							name = "turrettorp",
							x = 1544,
							z = 2488,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 1704,
							z = 2488,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 584,
							z = 2280,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 424,
							z = 2280,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 304,
							z = 1872,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 720,
							z = 1904,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 1136,
							z = 1920,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 1552,
							z = 1904,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 1872,
							z = 1920,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 2272,
							z = 1872,
							facing = 0,
						},
 						{
							name = "staticheavyradar",
							x = 2128,
							z = 1408,
							facing = 0,
						},
 						{
							name = "pw_metal",
							x = 1184,
							z = 512,
							facing = 0,
						},
 						{
							name = "turretaafar",
							x = 1968,
							z = 1456,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 1864,
							z = 1480,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 2888,
							z = 2744,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 3080,
							z = 2680,
							facing = 0,
						},
 						{
							name = "shipassault",
							x = 3375,
							z = 3861,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 3643,
							z = 2114,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3880,
							z = 3128,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 1600,
							z = 3888,
							facing = 1,
						},
 						{
							name = "bomberheavy",
							x = 1647,
							z = 1491,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 2357,
							z = 4382,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 1032,
							z = 1736,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 2808,
							z = 1736,
							facing = 0,
						},
 						{
							name = "planeheavyfighter",
							x = 3314,
							z = 4916,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 1248,
							z = 2960,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 920,
							z = 1720,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 160,
							z = 4064,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1592,
							z = 2008,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1592, 2008}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1656, 2220}, options = {"shift"}},
							},
						},
 						{
							name = "staticradar",
							x = 3264,
							z = 2640,
							facing = 0,
						},
 						{
							name = "shipcon",
							x = 3736,
							z = 1558,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1640,
							z = 2008,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1640, 2008}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1656, 2220}, options = {"shift"}},
							},
						},
 						{
							name = "energywind",
							x = 4120,
							z = 888,
							facing = 0,
						},
 						{
							name = "amphimpulse",
							x = 1551,
							z = 3329,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1688,
							z = 2008,
							facing = 1,
						},
 						{
							name = "staticstorage",
							x = 1032,
							z = 1816,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 2784,
							z = 1313,
							facing = 2,
						},
 						{
							name = "shiptorpraider",
							x = 2663,
							z = 4400,
							facing = 3,
							patrolRoute = {
								{2641, 4417},
								{2686, 4372},
							},
						},
 						{
							name = "turretlaser",
							x = 2272,
							z = 3376,
							facing = 1,
						},
 						{
							name = "turrettorp",
							x = 3464,
							z = 1512,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 4200,
							z = 536,
							facing = 0,
						},
 						{
							name = "shipcon",
							x = 5204,
							z = 2625,
							facing = 3,
						},
 						{
							name = "amphfloater",
							x = 1041,
							z = 4591,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 1248,
							z = 1760,
							facing = 1,
						},
 						{
							name = "shipskirm",
							x = 3233,
							z = 3327,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 336,
							z = 816,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 3272,
							z = 2712,
							facing = 0,
						},
 						{
							name = "shipcon",
							x = 2265,
							z = 2305,
							facing = 3,
						},
 						{
							name = "amphfloater",
							x = 1082,
							z = 4594,
							facing = 0,
						},
 						{
							name = "shiparty",
							x = 3170,
							z = 3452,
							facing = 2,
						},
 						{
							name = "amphraid",
							x = 2397,
							z = 3896,
							facing = 1,
						},
 						{
							name = "turrettorp",
							x = 4424,
							z = 1096,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 3240,
							z = 2792,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2232,
							z = 3112,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 1542,
							z = 3902,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 1616,
							z = 624,
							facing = 0,
						},
 						{
							name = "amphfloater",
							x = 1125,
							z = 3724,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 4336,
							z = 1088,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 1808,
							z = 704,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 5195,
							z = 3413,
							facing = 3,
						},
 						{
							name = "amphaa",
							x = 1170,
							z = 4403,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2104,
							z = 3704,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 1312,
							z = 1200,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 3795,
							z = 3818,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 3496,
							z = 1608,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 1584,
							z = 1056,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 5368,
							z = 2392,
							facing = 0,
						},
 						{
							name = "shipcon",
							x = 3763,
							z = 1492,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 1208,
							z = 3096,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 1536,
							z = 3632,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 4440,
							z = 3096,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 1294,
							z = 2691,
							facing = 0,
						},
 						{
							name = "shipassault",
							x = 3836,
							z = 2527,
							facing = 1,
						},
 						{
							name = "amphraid",
							x = 2358,
							z = 3907,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 4328,
							z = 1368,
							facing = 0,
						},
 						{
							name = "amphaa",
							x = 1026,
							z = 4379,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 3688,
							z = 1480,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 4272,
							z = 3120,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 2760,
							z = 1736,
							facing = 0,
						},
 						{
							name = "amphraid",
							x = 2586,
							z = 3882,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 2856,
							z = 1736,
							facing = 0,
						},
 						{
							name = "amphaa",
							x = 1100,
							z = 4455,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 6864,
							z = 2784,
							facing = 3,
						},
 						{
							name = "subraider",
							x = 4854,
							z = 3691,
							facing = 0,
						},
 						{
							name = "shiparty",
							x = 1183,
							z = 3868,
							facing = 0,
						},
 						{
							name = "amphraid",
							x = 2551,
							z = 3870,
							facing = 1,
						},
 						{
							name = "amphraid",
							x = 2321,
							z = 3950,
							facing = 1,
						},
 						{
							name = "planeheavyfighter",
							x = 3604,
							z = 3874,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 4016,
							z = 160,
							facing = 0,
						},
 						{
							name = "amphraid",
							x = 2376,
							z = 3881,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 5456,
							z = 2160,
							facing = 0,
						},
 						{
							name = "amphaa",
							x = 1010,
							z = 4323,
							facing = 0,
						},
 						{
							name = "planeheavyfighter",
							x = 3241,
							z = 2470,
							facing = 3,
						},
 						{
							name = "amphraid",
							x = 2580,
							z = 3857,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 4048,
							z = 2736,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 5432,
							z = 2248,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 1456,
							z = 2992,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 672,
							z = 3177,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4040,
							z = 696,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 1728,
							z = 4176,
							facing = 1,
						},
 						{
							name = "amphimpulse",
							x = 3304,
							z = 4126,
							facing = 2,
						},
 						{
							name = "amphimpulse",
							x = 3342,
							z = 4145,
							facing = 2,
						},
 						{
							name = "shiptorpraider",
							x = 2752,
							z = 4365,
							facing = 3,
							patrolRoute = {
								{2675, 4364},
								{2645, 4416},
							},
						},
 						{
							name = "amphraid",
							x = 2476,
							z = 3877,
							facing = 1,
						},
 						{
							name = "shiptorpraider",
							x = 2592,
							z = 4391,
							facing = 2,
							patrolRoute = {
								{2581, 4439},
								{2641, 4417},
							},
						},
 						{
							name = "turretmissile",
							x = 1408,
							z = 3936,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 5376,
							z = 2320,
							facing = 0,
						},
 						{
							name = "amphfloater",
							x = 1606,
							z = 3378,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 2712,
							z = 1736,
							facing = 0,
						},
 						{
							name = "amphfloater",
							x = 1569,
							z = 3283,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4072,
							z = 792,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 1283,
							z = 3133,
							facing = 0,
						},
 						{
							name = "amphriot",
							x = 1616,
							z = 2471,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 3800,
							z = 1464,
							facing = 0,
						},
 						{
							name = "subraider",
							x = 3168,
							z = 2951,
							facing = 0,
						},
 						{
							name = "shiptorpraider",
							x = 2926,
							z = 2679,
							facing = 0,
						},
 						{
							name = "amphraid",
							x = 1795,
							z = 2984,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 3576,
							z = 1496,
							facing = 0,
						},
 						{
							name = "amphraid",
							x = 1723,
							z = 2448,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 3608,
							z = 1592,
							facing = 0,
						},
 						{
							name = "amphaa",
							x = 1625,
							z = 2243,
							facing = 3,
						},
 						{
							name = "shiparty",
							x = 2808,
							z = 1888,
							facing = 0,
							buildProgress = 0.23450001,
						},
					}
				},
				{
					humanName = "Star Shine",
					aiLib = "Circuit_difficulty_autofill_ally",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					allyTeam = 0,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energypylon",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turrettorp",
						"turretgauss",
						"turretheavylaser",
						"turretaalaser",
						"turretaaclose",
						"turretaaflak",
						"shieldshield",
						"staticradar",
						"staticheavyradar",
						"staticcon",
						"staticantinuke",
						"staticrearm",
						"factorygunship",
						"gunshipcon",
						"gunshipbomb",
						"gunshipemp",
						"gunshipaa",
						"gunshipassault",
						"gunshipheavyskirm",
						"gunshipskirm",
						"gunshipraid",
						"gunshipkrow",
						"factoryhover",
						"hovercon",
						"hoverraid",
						"hoverriot",
						"hoverskirm",
						"hoverassault",
						"hoverdepthcharge",
                        "hoverheavyraid",
						"hoverarty",
						"hoveraa",
						"factoryship",
						"shipcon",
						"shipaa",
						"shiparty",
						"shipassault",
						"shipriot",
						"shipscout",
						"shipskirm",
						"shiptorpraider",
						"subraider",
					},
					commander = false,
					startUnits = {
						{
							name = "staticmex",
							x = 5416,
							z = 168,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5656,
							z = 552,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5880,
							z = 184,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6200,
							z = 808,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6664,
							z = 680,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6600,
							z = 1224,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7288,
							z = 1208,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7624,
							z = 616,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7624,
							z = 104,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7128,
							z = 280,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7512,
							z = 1640,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7096,
							z = 1672,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6824,
							z = 2872,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7704,
							z = 3032,
							facing = 0,
						},
 						{
							name = "energyfusion",
							x = 8104,
							z = 64,
							facing = 2,
						},
 						{
							name = "energyfusion",
							x = 8104,
							z = 352,
							facing = 2,
						},
 						{
							name = "energyfusion",
							x = 8104,
							z = 640,
							facing = 2,
						},
 						{
							name = "energyfusion",
							x = 8104,
							z = 928,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 7576,
							z = 472,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 7304,
							z = 1352,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 6696,
							z = 904,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 5864,
							z = 440,
							facing = 2,
						},
 						{
							name = "factoryship",
							x = 6304,
							z = 2384,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 6440,
							z = 2328,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 6440,
							z = 2248,
							facing = 0,
						},
 						{
							name = "factoryhover",
							x = 7424,
							z = 2832,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 7384,
							z = 2664,
							facing = 0,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7384, 2664}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7424, 2796}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 7480,
							z = 2680,
							facing = 0,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7480, 2680}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7424, 2796}, options = {"shift"}},
							},
						},
 						{
							name = "turretheavylaser",
							x = 6776,
							z = 3192,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 6656,
							z = 2192,
							facing = 0,
						},
 						{
							name = "pw_metal",
							x = 7344,
							z = 112,
							facing = 0,
						},
 						{
							name = "turretaafar",
							x = 6960,
							z = 2160,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 6712,
							z = 2280,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 7368,
							z = 2472,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 7048,
							z = 2360,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 7512,
							z = 3192,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 7240,
							z = 3112,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 6408,
							z = 2984,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 6120,
							z = 3160,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 776,
							z = 3032,
							facing = 1,
							buildProgress = 0.1566,
						},
 						{
							name = "turrettorp",
							x = 5112,
							z = 3080,
							facing = 0,
						},
 						{
							name = "shipscout",
							x = 5698,
							z = 2649,
							facing = 3,
						},
 						{
							name = "hoverassault",
							x = 6106,
							z = 3066,
							facing = 3,
						},
 						{
							name = "hovercon",
							x = 5106,
							z = 3415,
							facing = 0,
						},
 						{
							name = "hoveraa",
							x = 5108,
							z = 4092,
							facing = 1,
						},
 						{
							name = "shipscout",
							x = 3263,
							z = 5088,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 6528,
							z = 2384,
							facing = 3,
						},
 						{
							name = "hoverassault",
							x = 4816,
							z = 4175,
							facing = 3,
						},
 						{
							name = "hoverassault",
							x = 4359,
							z = 4420,
							facing = 0,
						},
 						{
							name = "hoverriot",
							x = 7414,
							z = 2900,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7432,
							z = 2680,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7432, 2680}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7424, 2796}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 7512,
							z = 2632,
							facing = 3,
						},
 						{
							name = "staticstorage",
							x = 7000,
							z = 1688,
							facing = 3,
						},
 						{
							name = "hovercon",
							x = 766,
							z = 2920,
							facing = 0,
						},
 						{
							name = "hovercon",
							x = 1110,
							z = 3265,
							facing = 3,
						},
 						{
							name = "staticstorage",
							x = 7192,
							z = 1752,
							facing = 3,
						},
 						{
							name = "hoverarty",
							x = 5082,
							z = 3297,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7912,
							z = 3992,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 5544,
							z = 2536,
							facing = 0,
						},
 						{
							name = "hovercon",
							x = 6734,
							z = 2338,
							facing = 3,
						},
 						{
							name = "hoverraid",
							x = 4959,
							z = 3154,
							facing = 2,
						},
 						{
							name = "shipassault",
							x = 5272,
							z = 3475,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 7464,
							z = 2632,
							facing = 3,
						},
 						{
							name = "hovercon",
							x = 7024,
							z = 2055,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 5048,
							z = 3448,
							facing = 0,
							buildProgress = 0.67110002,
						},
 						{
							name = "hoverraid",
							x = 2997,
							z = 3158,
							facing = 2,
						},
 						{
							name = "hoverraid",
							x = 5358,
							z = 2354,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 7528,
							z = 2680,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7528, 2680}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7424, 2796}, options = {"shift"}},
							},
						},
 						{
							name = "shipassault",
							x = 4966,
							z = 3804,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5008, 3824}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4892, 3944}, options = {"shift"}},
							},
						},
 						{
							name = "energywind",
							x = 5336,
							z = 392,
							facing = 0,
						},
 						{
							name = "hoverskirm",
							x = 5161,
							z = 3744,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 6080,
							z = 2384,
							facing = 3,
						},
 						{
							name = "hoverassault",
							x = 4776,
							z = 4197,
							facing = 3,
						},
 						{
							name = "shipskirm",
							x = 5127,
							z = 3265,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 7312,
							z = 480,
							facing = 0,
						},
 						{
							name = "hoveraa",
							x = 5592,
							z = 4039,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 7952,
							z = 3936,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 3848,
							z = 264,
							facing = 0,
						},
 						{
							name = "shipriot",
							x = 5982,
							z = 2648,
							facing = 1,
						},
 						{
							name = "shipcon",
							x = 3240,
							z = 3142,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 7416,
							z = 2616,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 5600,
							z = 320,
							facing = 0,
						},
 						{
							name = "hoverassault",
							x = 4389,
							z = 4351,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 7240,
							z = 2152,
							facing = 3,
						},
 						{
							name = "hovercon",
							x = 5104,
							z = 3366,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 7368,
							z = 2616,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7368, 2616}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7424, 2796}, options = {"shift"}},
							},
						},
 						{
							name = "hoverarty",
							x = 7680,
							z = 2957,
							facing = 2,
						},
 						{
							name = "hoverraid",
							x = 3844,
							z = 2620,
							facing = 1,
						},
 						{
							name = "hoveraa",
							x = 6904,
							z = 2534,
							facing = 3,
						},
 						{
							name = "shipassault",
							x = 5333,
							z = 3476,
							facing = 1,
						},
 						{
							name = "shipcon",
							x = 5572,
							z = 3351,
							facing = 3,
						},
 						{
							name = "hovercon",
							x = 7005,
							z = 3153,
							facing = 3,
						},
 						{
							name = "hoverraid",
							x = 7221,
							z = 1561,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 4792,
							z = 344,
							facing = 0,
						},
 						{
							name = "hovercon",
							x = 7010,
							z = 2303,
							facing = 3,
						},
 						{
							name = "hovercon",
							x = 5670,
							z = 2683,
							facing = 1,
						},
 						{
							name = "shipcon",
							x = 3184,
							z = 4527,
							facing = 0,
						},
 						{
							name = "hoveraa",
							x = 5651,
							z = 3987,
							facing = 1,
						},
 						{
							name = "shipcon",
							x = 5050,
							z = 3820,
							facing = 0,
						},
 						{
							name = "hovercon",
							x = 4876,
							z = 3806,
							facing = 0,
						},
 						{
							name = "shipaa",
							x = 5346,
							z = 2702,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 2880,
							z = 304,
							facing = 0,
						},
 						{
							name = "hovercon",
							x = 5608,
							z = 2716,
							facing = 1,
						},
 						{
							name = "shipcon",
							x = 5667,
							z = 2623,
							facing = 0,
						},
 						{
							name = "shipscout",
							x = 4793,
							z = 2960,
							facing = 2,
						},
 						{
							name = "turretaalaser",
							x = 3016,
							z = 4600,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 7160,
							z = 2952,
							facing = 3,
						},
 						{
							name = "hovercon",
							x = 3292,
							z = 3318,
							facing = 0,
						},
 						{
							name = "hoveraa",
							x = 5669,
							z = 4080,
							facing = 1,
						},
 						{
							name = "shiparty",
							x = 6312,
							z = 2384,
							facing = 0,
							buildProgress = 0.1741,
						},
 						{
							name = "hoverraid",
							x = 7424,
							z = 2800,
							facing = 0,
							buildProgress = 0.74580002,
						},
					}
				},
				{
					startX = 6864,
					startZ = 7800,
					humanName = "Warbak",
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					commanderParameters = {
						facplop = false,
					},
					allyTeam = 1,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energypylon",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turrettorp",
						"turretgauss",
						"turretheavylaser",
						"turretaalaser",
						"turretaaclose",
						"turretaaflak",
						"shieldshield",
						"staticradar",
						"staticheavyradar",
						"staticantinuke",
						"staticrearm",
						"gunshipbomb",
						"gunshipemp",
						"gunshipaa",
						"gunshipassault",
						"gunshipheavyskirm",
						"gunshipskirm",
						"gunshipraid",
						"gunshipkrow",
					},
					commanderLevel = 6,
					commander = {
						name = "Mezzanin",
						chassis = "guardian",
						decorations = {
						},
						modules = {
							"module_ablative_armor",
							"module_ablative_armor",
							"module_ablative_armor",
							"commweapon_rocketlauncher",
							"commweapon_rocketlauncher",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_radarnet",
							"module_autorepair",
							"module_autorepair",
							"module_high_power_servos",
							"module_high_power_servos",
						}
					},
					startUnits = {
						{
							name = "zenith",
							x = 6864,
							z = 7328,
							facing = 0,
							buildProgress = 0.93,
							difficultyAtMost = 4,
							difficultyAtLeast = 4,
						},
						{
							name = "zenith",
							x = 6864,
							z = 7328,
							facing = 0,
							buildProgress = 0.88,
							difficultyAtMost = 3,
							difficultyAtLeast = 3,
						},
						{
							name = "zenith",
							x = 6864,
							z = 7328,
							facing = 0,
							buildProgress = 0.84,
							difficultyAtMost = 2,
							difficultyAtLeast = 2,
						},
						{
							name = "zenith",
							x = 6864,
							z = 7328,
							facing = 0,
							buildProgress = 0.80,
							difficultyAtMost = 1,
							difficultyAtLeast = 1,
						},
 						{
							name = "factorygunship",
							x = 6328,
							z = 7992,
							facing = 1,
						},
						{
							name = "staticcon",
							x = 6500,
							z = 7992,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 6712,
							z = 7464,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {6712, 7464}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {6489, 7125}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 6792,
							z = 7464,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 6872,
							z = 7464,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 6712,
							z = 7544,
							facing = 2,
						},
 						{
							name = "turretaaflak",
							x = 7016,
							z = 7272,
							facing = 2,
						},
 						{
							name = "turretaaflak",
							x = 6840,
							z = 7192,
							facing = 2,
						},
 						{
							name = "turretaaflak",
							x = 6728,
							z = 7320,
							facing = 2,
						},
 						{
							name = "pw_metal",
							x = 7440,
							z = 8032,
							facing = 0,
						},
 						{
							name = "gunshipskirm",
							x = 6221,
							z = 5300,
							facing = 2,
						},
 						{
							name = "gunshipaa",
							x = 6278,
							z = 3858,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 6392,
							z = 7480,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 6376,
							z = 7592,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 7088,
							z = 6640,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 6272,
							z = 7792,
							facing = 2,
						},
 						{
							name = "gunshipaa",
							x = 6273,
							z = 3875,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 5040,
							z = 7472,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 6128,
							z = 7936,
							facing = 2,
						},
					}
				},
				{
					humanName = "Fallacy",
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					allyTeam = 1,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energypylon",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turrettorp",
						"turretgauss",
						"turretheavylaser",
						"turretaalaser",
						"turretaaclose",
						"turretaaflak",
						"shieldshield",
						"staticradar",
						"staticheavyradar",
						"staticcon",
						"staticantinuke",
						"staticrearm",
						"factoryplane",
						"planecon",
						"planescout",
						"planefighter",
						"planeheavyfighter",
						"bomberprec",
						"bomberdisarm",
						"bomberheavy",
						"factoryamph",
						"amphcon",
						"amphraid",
						"amphimpulse",
						"amphfloater",
						"amphriot",
						"amphassault",
						"amphbomb",
						"amphaa",
						"factoryship",
						"shipcon",
						"shipaa",
						"shiparty",
						"shipassault",
						"shipriot",
						"shipscout",
						"shipskirm",
						"shiptorpraider",
						"subraider",
						"striderhub",
						"striderhub",
						"shipcarrier",
					},
					commander = false,
					startUnits = {
						{
							name = "staticmex",
							x = 744,
							z = 6936,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1112,
							z = 6712,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 696,
							z = 6408,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1336,
							z = 7416,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1768,
							z = 7608,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1976,
							z = 7976,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2344,
							z = 8152,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2648,
							z = 7816,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1768,
							z = 7176,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 632,
							z = 7672,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 744,
							z = 8104,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 200,
							z = 7848,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3592,
							z = 7176,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3720,
							z = 6440,
							facing = 0,
						},
 						{
							name = "energyfusion",
							x = 56,
							z = 8144,
							facing = 2,
						},
 						{
							name = "energyfusion",
							x = 264,
							z = 8144,
							facing = 2,
						},
 						{
							name = "energyfusion",
							x = 504,
							z = 8144,
							facing = 2,
						},
 						{
							name = "energyfusion",
							x = 56,
							z = 7952,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 888,
							z = 7704,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 1672,
							z = 7656,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 840,
							z = 6840,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 2376,
							z = 7912,
							facing = 2,
						},
 						{
							name = "staticrearm",
							x = 1176,
							z = 8088,
							facing = 2,
						},
 						{
							name = "factoryplane",
							x = 1344,
							z = 8104,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 1304,
							z = 7992,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 1384,
							z = 7992,
							facing = 2,
						},
 						{
							name = "factoryship",
							x = 2416,
							z = 6528,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 2296,
							z = 6632,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 2296,
							z = 6552,
							facing = 2,
						},
 						{
							name = "factoryamph",
							x = 584,
							z = 6152,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 552,
							z = 6296,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {552, 6296}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {584, 6116}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 632,
							z = 6296,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 1168,
							z = 5952,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 984,
							z = 5608,
							facing = 2,
						},
 						{
							name = "turretgauss",
							x = 1256,
							z = 5688,
							facing = 2,
						},
 						{
							name = "turretgauss",
							x = 1512,
							z = 5848,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 360,
							z = 5096,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 728,
							z = 5176,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 1032,
							z = 5240,
							facing = 2,
						},
 						{
							name = "pw_metal",
							x = 192,
							z = 7568,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4200,
							z = 6552,
							facing = 2,
						},
 						{
							name = "turretaalaser",
							x = 4760,
							z = 5032,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 1120,
							z = 5247,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 3048,
							z = 6200,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 3336,
							z = 6840,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 1752,
							z = 6264,
							facing = 2,
						},
 						{
							name = "turretaafar",
							x = 1360,
							z = 6048,
							facing = 2,
						},
 						{
							name = "shipcon",
							x = 2948,
							z = 5392,
							facing = 1,
						},
 						{
							name = "shipcon",
							x = 2996,
							z = 6066,
							facing = 1,
						},
 						{
							name = "shipskirm",
							x = 5776,
							z = 5855,
							facing = 3,
						},
 						{
							name = "shiparty",
							x = 757,
							z = 5744,
							facing = 2,
						},
 						{
							name = "shiparty",
							x = 6930,
							z = 4638,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 3177,
							z = 5337,
							facing = 2,
						},
 						{
							name = "bomberheavy",
							x = 1525,
							z = 7401,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 2616,
							z = 5832,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 680,
							z = 6280,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {680, 6280}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {584, 6116}, options = {"shift"}},
							},
						},
 						{
							name = "turrettorp",
							x = 2616,
							z = 5752,
							facing = 2,
						},
 						{
							name = "amphaa",
							x = 853,
							z = 5037,
							facing = 2,
						},
 						{
							name = "staticstorage",
							x = 1048,
							z = 6824,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 2221,
							z = 5815,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 2408,
							z = 6664,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 472,
							z = 4968,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 1128,
							z = 6792,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 5032,
							z = 6888,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 4027,
							z = 5664,
							facing = 1,
						},
 						{
							name = "turrettorp",
							x = 424,
							z = 4968,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 600,
							z = 6344,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {600, 6344}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {584, 6116}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 648,
							z = 6344,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {648, 6344}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {584, 6116}, options = {"shift"}},
							},
						},
 						{
							name = "shipskirm",
							x = 2960,
							z = 5898,
							facing = 2,
						},
 						{
							name = "turretaalaser",
							x = 1464,
							z = 5160,
							facing = 1,
						},
 						{
							name = "shipcon",
							x = 4421,
							z = 6194,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 2626,
							z = 6080,
							facing = 1,
						},
 						{
							name = "bomberheavy",
							x = 777,
							z = 8238,
							facing = 3,
						},
 						{
							name = "amphimpulse",
							x = 1566,
							z = 5575,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 4696,
							z = 5688,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 4696,
							z = 5576,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 5144,
							z = 6856,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 5032,
							z = 7096,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 4680,
							z = 6328,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 2632,
							z = 6024,
							facing = 2,
						},
 						{
							name = "shiptorpraider",
							x = 2539,
							z = 5618,
							facing = 2,
						},
 						{
							name = "shipassault",
							x = 1665,
							z = 5689,
							facing = 2,
						},
 						{
							name = "shipcon",
							x = 2273,
							z = 5911,
							facing = 3,
						},
 						{
							name = "amphriot",
							x = 1510,
							z = 5674,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 4696,
							z = 5800,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 2550,
							z = 5573,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 4888,
							z = 6936,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 552,
							z = 6344,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {552, 6344}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {584, 6116}, options = {"shift"}},
							},
						},
 						{
							name = "turretaalaser",
							x = 4696,
							z = 6280,
							facing = 2,
						},
 						{
							name = "amphraid",
							x = 1013,
							z = 5981,
							facing = 1,
						},
 						{
							name = "bomberprec",
							x = 1543,
							z = 7812,
							facing = 2,
						},
 						{
							name = "shipaa",
							x = 6577,
							z = 5186,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 1416,
							z = 4968,
							facing = 1,
						},
 						{
							name = "shiparty",
							x = 2465,
							z = 5678,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 3656,
							z = 6808,
							facing = 2,
						},
 						{
							name = "turretaalaser",
							x = 2712,
							z = 5736,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 1512,
							z = 5240,
							facing = 1,
						},
 						{
							name = "amphaa",
							x = 824,
							z = 4986,
							facing = 3,
						},
 						{
							name = "amphaa",
							x = 1063,
							z = 6067,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 5112,
							z = 7016,
							facing = 2,
						},
 						{
							name = "amphfloater",
							x = 1437,
							z = 5525,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 4712,
							z = 5096,
							facing = 2,
						},
 						{
							name = "amphfloater",
							x = 859,
							z = 4902,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 5192,
							z = 6984,
							facing = 2,
						},
 						{
							name = "shipskirm",
							x = 5269,
							z = 6048,
							facing = 3,
						},
 						{
							name = "amphaa",
							x = 1435,
							z = 5676,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 4872,
							z = 5176,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 5112,
							z = 7096,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 5160,
							z = 6744,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 5160,
							z = 6632,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 5112,
							z = 6536,
							facing = 2,
						},
 						{
							name = "turretaalaser",
							x = 4712,
							z = 4952,
							facing = 2,
						},
 						{
							name = "amphfloater",
							x = 905,
							z = 5870,
							facing = 2,
						},
 						{
							name = "turretaalaser",
							x = 520,
							z = 5064,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 2253,
							z = 6624,
							facing = 1,
						},
 						{
							name = "subraider",
							x = 2978,
							z = 6143,
							facing = 2,
						},
 						{
							name = "shiptorpraider",
							x = 4058,
							z = 5786,
							facing = 3,
						},
 						{
							name = "amphraid",
							x = 2625,
							z = 5284,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 4088,
							z = 6584,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 1873,
							z = 5768,
							facing = 1,
						},
 						{
							name = "shipskirm",
							x = 2789,
							z = 6003,
							facing = 3,
						},
 						{
							name = "amphraid",
							x = 2360,
							z = 5392,
							facing = 1,
						},
 						{
							name = "shipscout",
							x = 2985,
							z = 6105,
							facing = 1,
						},
 						{
							name = "amphaa",
							x = 761,
							z = 6010,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 2360,
							z = 6664,
							facing = 2,
							buildProgress = 0.50599998,
						},
 						{
							name = "subraider",
							x = 2408,
							z = 6527,
							facing = 2,
							buildProgress = 0.73830003,
						},
 						{
							name = "amphcon",
							x = 625,
							z = 6119,
							facing = 0,
						},
 						{
							name = "amphraid",
							x = 584,
							z = 6116,
							facing = 2,
							buildProgress = 0.26660001,
						},
					}
				},
				{
					humanName = "Ractyi",
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					allyTeam = 1,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energypylon",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turrettorp",
						"turretgauss",
						"turretheavylaser",
						"turretaalaser",
						"turretaaclose",
						"turretaaflak",
						"shieldshield",
						"staticradar",
						"staticheavyradar",
						"staticcon",
						"staticantinuke",
						"staticrearm",
						"factoryhover",
						"hovercon",
						"hoverraid",
						"hoverriot",
						"hoverskirm",
						"hoverassault",
						"hoverdepthcharge",
                        "hoverheavyraid",
						"hoverarty",
						"hoveraa",
						"factoryship",
						"shipcon",
						"shipaa",
						"shiparty",
						"shipassault",
						"shipriot",
						"shipscout",
						"shipskirm",
						"shiptorpraider",
						"subraider",
					},
					commander = false,
					midgameUnits = {
						{
							name = "shipheavyarty",
							x = 100,
							z = 4950,
							facing = 1,
							spawnRadius = 50,
							delay = 6*30*60,
							orbitalDrop = false,
						},
						{
							name = "shipcarrier",
							x = 100,
							z = 4950,
							facing = 1,
							spawnRadius = 50,
							delay = 9*30*60,
							orbitalDrop = false,
						},
						{
							name = "shipheavyarty",
							x = 100,
							z = 5000,
							facing = 1,
							spawnRadius = 50,
							delay = 9*30*60,
							orbitalDrop = false,
							difficultyAtLeast = 3,
						},
					},
					startUnits = {
						{
							name = "shipcarrier",
							x = 4100,
							z = 7000,
							facing = 0,
						},
						{
							name = "shipheavyarty",
							x = 3900,
							z = 7000,
							facing = 0,
							difficultyAtLeast = 4,
						},
						{
							name = "staticmex",
							x = 5032,
							z = 7608,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5752,
							z = 7944,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6328,
							z = 7512,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7528,
							z = 7256,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7944,
							z = 8024,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7112,
							z = 6424,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4008,
							z = 7864,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4728,
							z = 6328,
							facing = 0,
						},
 						{
							name = "energyheavygeo",
							x = 5416,
							z = 6904,
							facing = 0,
						},
 						{
							name = "staticarty",
							x = 6488,
							z = 6264,
							facing = 2,
						},
 						{
							name = "staticshield",
							x = 6512,
							z = 6496,
							facing = 2,
						},
 						{
							name = "turretaafar",
							x = 6624,
							z = 6464,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 6744,
							z = 6664,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 6648,
							z = 6312,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 6728,
							z = 6456,
							facing = 1,
						},
 						{
							name = "turretaaflak",
							x = 6648,
							z = 6584,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 6520,
							z = 6392,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 8136,
							z = 8144,
							facing = 2,
						},
 						{
							name = "energyfusion",
							x = 8024,
							z = 8144,
							facing = 2,
						},
 						{
							name = "energyfusion",
							x = 5736,
							z = 8064,
							facing = 2,
						},
 						{
							name = "energyfusion",
							x = 5720,
							z = 8160,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 7560,
							z = 7656,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 7048,
							z = 6904,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 6328,
							z = 6696,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 5960,
							z = 7512,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 5304,
							z = 7432,
							facing = 2,
						},
 						{
							name = "factoryhover",
							x = 5744,
							z = 6176,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 5704,
							z = 6344,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5768, 6392}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5704, 6344}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 5784,
							z = 6344,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5768, 6392}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5784, 6344}, options = {"shift"}},
							},
						},
 						{
							name = "factoryship",
							x = 4928,
							z = 6688,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 5048,
							z = 6776,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5048, 6776}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5023, 6751}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 5048,
							z = 6696,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5048, 6696}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5023, 6671}, options = {"shift"}},
							},
						},
 						{
							name = "pw_metal",
							x = 4992,
							z = 7984,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 2816,
							z = 5824,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 6936,
							z = 5720,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 6280,
							z = 5704,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 5464,
							z = 5688,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 4968,
							z = 5832,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 4344,
							z = 5832,
							facing = 2,
						},
 						{
							name = "turretmissile",
							x = 7248,
							z = 6112,
							facing = 2,
						},
 						{
							name = "turretmissile",
							x = 7536,
							z = 6032,
							facing = 2,
						},
 						{
							name = "turretmissile",
							x = 7936,
							z = 5984,
							facing = 2,
						},
 						{
							name = "turretmissile",
							x = 8112,
							z = 5984,
							facing = 2,
						},
 						{
							name = "shipcon",
							x = 4998,
							z = 5383,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 2728,
							z = 5816,
							facing = 2,
						},
 						{
							name = "hoverassault",
							x = 5828,
							z = 5468,
							facing = 3,
						},
 						{
							name = "shiparty",
							x = 3088,
							z = 5358,
							facing = 3,
						},
 						{
							name = "shipcon",
							x = 6804,
							z = 4743,
							facing = 2,
						},
 						{
							name = "hovercon",
							x = 2981,
							z = 5469,
							facing = 3,
						},
 						{
							name = "staticstorage",
							x = 6232,
							z = 7496,
							facing = 2,
						},
 						{
							name = "hoverarty",
							x = 4856,
							z = 5765,
							facing = 1,
						},
 						{
							name = "shipcon",
							x = 5823,
							z = 6040,
							facing = 2,
						},
 						{
							name = "hoverassault",
							x = 6950,
							z = 5462,
							facing = 3,
						},
 						{
							name = "shipassault",
							x = 3946,
							z = 5861,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 3624,
							z = 7064,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 4784,
							z = 5296,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 3552,
							z = 7056,
							facing = 2,
						},
 						{
							name = "hovercon",
							x = 5254,
							z = 5494,
							facing = 1,
						},
 						{
							name = "hovercon",
							x = 4577,
							z = 4659,
							facing = 1,
						},
 						{
							name = "shipcon",
							x = 5039,
							z = 5192,
							facing = 3,
						},
 						{
							name = "shipskirm",
							x = 4597,
							z = 6274,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 4776,
							z = 6280,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 4920,
							z = 6840,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4920, 6840}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4919, 6697}, options = {"shift"}},
							},
						},
 						{
							name = "turretlaser",
							x = 5952,
							z = 6208,
							facing = 2,
						},
 						{
							name = "hoverassault",
							x = 5871,
							z = 5461,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 2816,
							z = 5888,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 6192,
							z = 7536,
							facing = 2,
						},
 						{
							name = "shipcon",
							x = 1759,
							z = 5392,
							facing = 1,
						},
 						{
							name = "hoverriot",
							x = 5432,
							z = 5738,
							facing = 2,
						},
 						{
							name = "turretmissile",
							x = 528,
							z = 5136,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 4120,
							z = 4984,
							facing = 0,
						},
 						{
							name = "hoveraa",
							x = 5622,
							z = 5667,
							facing = 3,
						},
 						{
							name = "staticstorage",
							x = 6408,
							z = 7544,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 4880,
							z = 7536,
							facing = 2,
						},
 						{
							name = "shipskirm",
							x = 5537,
							z = 5538,
							facing = 1,
						},
 						{
							name = "turrettorp",
							x = 2712,
							z = 5896,
							facing = 2,
						},
 						{
							name = "turretmissile",
							x = 2416,
							z = 5952,
							facing = 2,
						},
 						{
							name = "shipcon",
							x = 3585,
							z = 5807,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 4776,
							z = 5160,
							facing = 2,
						},
 						{
							name = "shipaa",
							x = 6944,
							z = 4464,
							facing = 0,
						},
 						{
							name = "hoveraa",
							x = 5667,
							z = 5669,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 2616,
							z = 5880,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 4872,
							z = 6824,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4872, 6824}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4919, 6697}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 5672,
							z = 6392,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5672, 6392}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5768, 6392}, options = {"shift"}},
							},
						},
 						{
							name = "shiptorpraider",
							x = 4920,
							z = 6634,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 4760,
							z = 5096,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 4608,
							z = 6336,
							facing = 2,
						},
 						{
							name = "shipassault",
							x = 6415,
							z = 5371,
							facing = 1,
						},
 						{
							name = "turrettorp",
							x = 4696,
							z = 5192,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 4856,
							z = 6392,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4856, 6392}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4919, 6697}, options = {"shift"}},
							},
						},
 						{
							name = "turretheavylaser",
							x = 4680,
							z = 6120,
							facing = 2,
						},
 						{
							name = "hovercon",
							x = 7324,
							z = 5004,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 4824,
							z = 6824,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4824, 6824}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {4919, 6697}, options = {"shift"}},
							},
						},
 						{
							name = "staticradar",
							x = 4768,
							z = 6384,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 4744,
							z = 6200,
							facing = 2,
						},
 						{
							name = "hovercon",
							x = 5802,
							z = 6504,
							facing = 2,
						},
 						{
							name = "shipassault",
							x = 5588,
							z = 5598,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 4600,
							z = 6152,
							facing = 2,
						},
 						{
							name = "shipcon",
							x = 3060,
							z = 5727,
							facing = 2,
						},
 						{
							name = "hovercon",
							x = 5894,
							z = 6297,
							facing = 3,
						},
 						{
							name = "hoverarty",
							x = 7115,
							z = 5529,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 616,
							z = 5112,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 5720,
							z = 6392,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 5768,
							z = 6392,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5768, 6392}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5743, 6367}, options = {"shift"}},
							},
						},
 						{
							name = "shipskirm",
							x = 5963,
							z = 5522,
							facing = 1,
						},
 						{
							name = "shipcon",
							x = 5842,
							z = 5921,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 2712,
							z = 5976,
							facing = 2,
						},
 						{
							name = "shipassault",
							x = 4970,
							z = 6461,
							facing = 2,
						},
 						{
							name = "shipcon",
							x = 6432,
							z = 5315,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 5656,
							z = 6344,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5768, 6392}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5656, 6344}, options = {"shift"}},
							},
						},
 						{
							name = "staticradar",
							x = 352,
							z = 4992,
							facing = 1,
						},
 						{
							name = "shipaa",
							x = 3853,
							z = 5867,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 5504,
							z = 6208,
							facing = 2,
						},
 						{
							name = "shipscout",
							x = 4698,
							z = 4724,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 3904,
							z = 4992,
							facing = 2,
							buildProgress = 0.59249997,
						},
 						{
							name = "hoverraid",
							x = 5242,
							z = 5610,
							facing = 2,
						},
 						{
							name = "hovercon",
							x = 5820,
							z = 6278,
							facing = 3,
						},
					}
				},
			},
			defeatConditionConfig = {
				-- Indexed by allyTeam.
				[0] = { },
				[1] = {
					ignoreUnitLossDefeat = false,
					vitalCommanders = false,
					vitalUnitTypes = {
						"factoryplane",
						"factorygunship",
						"factoryamph",
						"factoryship",
						"factoryhover",
					},
					loseAfterSeconds = false,
					allyTeamLossObjectiveID = 1,
				},
			},
			objectiveConfig = {
				-- This is just related to displaying objectives on the UI.
				[1] = {
					description = "Destroy all enemy Factories",
				},
				[2] = {
					description = "Protect your Commander",
				},
			},
			bonusObjectiveConfig = {
				[1] = {
					satisfyOnce = true,
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 4,
					unitTypes = {
						"shipheavyarty",
					},
					image = planetUtilities.ICON_DIR .. "shipheavyarty.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.REPAIR,
					description = "Have 4 Shoguns",
					experience = planetUtilities.BONUS_EXP,
				},
				[2] = {
					victoryByTime = 20*60,
					image = planetUtilities.ICON_OVERLAY.CLOCK,
					description = "Win by 20:00",
					experience = planetUtilities.BONUS_EXP,
				},
			},
		},
		completionReward = {
			experience = planetUtilities.MAIN_EXP,
			units = {
				"striderhub",
				"shipheavyarty",
			},
			modules = {
				"commweapon_concussion",
			},
			abilities = {
			},
			codexEntries = {
				"location_pendust"
			},
		},
	}
	
	return planetData
end

return GetPlanet
