--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Planet config

local function GetPlanet(planetUtilities, planetID)
	
	local image = LUA_DIRNAME .. "images/planets/swamp03.png"
	
	local planetData = {
		name = "Mannia",
		startingPlanet = false,
		mapDisplay = {
			x = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][1]) or 0.895,
			y = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][2]) or 0.20,
			image = image,
			size = planetUtilities.PLANET_SIZE_MAP,
		},
		infoDisplay = {
			image = image,
			size = planetUtilities.PLANET_SIZE_INFO,
			backgroundImage = planetUtilities.backgroundImages[math.floor(math.random()*#planetUtilities.backgroundImages) + 1],
			terrainType = "Terran",
			radius = "6200 km",
			primary = "Wabloz Met",
			primaryType = "G8V",
			milRating = 1,
			feedbackLink = "http://zero-k.info/Forum/Thread/24642",
			text = "This was one of the last worlds to see its inhabitants disappear. Refugees from all the quadrant fled here, waiting for transit to the last bastion of humanity. Many seem to have accepted their fate, though, and built immense temporary cities, to be reclaimed by nature after their passing."
			.. "\n "
			.. "\nThe Empire would not, however. Even knowing how futile it was, they fortified this world with all they had."
			,
			extendedText = "The deep water channels and hills of this battleground present a challenging tactical landscape. The ultra-heavy amphibious Detriment strider is ideally suited to such mixed terrain."
			.. "\n "
			.. "\nHow ironic for those defiant armies, to stand immobile as everyone disappeared, and for countless more years, only to destroy themselves in such a futile way."
			.. "\n "
			.. "\nI wish I could have just continued my way, and left them rest in peace."
		},
		tips = {
			{
				image = "unitpics/striderdetriment.png",
				text = [[Detriments are the ultimate assault striders, armed with laser beams, ground-smoothing missiles, an anti-air battery, and multiple massive Gauss cannons on each arm. They are effective on land and sea and generally end battles very quickly.]]
			},
			{
				image = "unitpics/striderbantha.png",
				text = [[Insofar as the Detriment has a weakness at all, it is heavy hitters which can strike from outside the Detriment's range, like the Paladin and Shogun.]]
			},
		},
		gameConfig = {
			mapName = "Rage_v1",
			playerConfig = {
				startX = 5500,
				startZ = 750,
				allyTeam = 0,
				facplop = false,
				commanderParameters = {
					facplop = false,
					defeatIfDestroyedObjectiveID = 2,
				},
				extraUnlocks = {
					"striderdetriment",
				},
				startUnits = {
					{
						name = "striderdetriment",
						x = 5420,
						z = 1000,
						facing = 0,
					},
					{
						name = "staticmex",
						x = 5288,
						z = 856,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 5432,
						z = 552,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 5400,
						z = 200,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 5112,
						z = 3448,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 5208,
						z = 3016,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 5112,
						z = 2584,
						facing = 0,
					},
 					{
						name = "energysingu",
						x = 5016,
						z = 152,
						facing = 0,
					},
 					{
						name = "pw_metal",
						x = 5648,
						z = 160,
						facing = 0,
					},
 					{
						name = "energypylon",
						x = 5368,
						z = 568,
						facing = 0,
					},
 					{
						name = "energypylon",
						x = 5128,
						z = 1512,
						facing = 0,
					},
 					{
						name = "energypylon",
						x = 5176,
						z = 2504,
						facing = 0,
					},
 					{
						name = "energypylon",
						x = 4776,
						z = 3752,
						facing = 0,
					},
 					{
						name = "energypylon",
						x = 5240,
						z = 3352,
						facing = 0,
					},
 					{
						name = "staticcon",
						x = 5592,
						z = 792,
						facing = 0,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5592, 792}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5567, 817}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 5672,
						z = 792,
						facing = 0,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5672, 792}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5647, 817}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 5672,
						z = 872,
						facing = 0,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5672, 872}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5647, 897}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 5592,
						z = 872,
						facing = 0,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5592, 872}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5567, 897}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 5592,
						z = 952,
						facing = 0,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5592, 952}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5567, 977}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 5672,
						z = 952,
						facing = 0,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5672, 952}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5647, 977}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 5672,
						z = 1032,
						facing = 0,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5672, 1032}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5647, 1057}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 5592,
						z = 1032,
						facing = 0,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5592, 1032}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5567, 1057}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 5592,
						z = 1112,
						facing = 0,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5592, 1112}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5567, 1137}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 5672,
						z = 1112,
						facing = 0,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5672, 1112}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5647, 1137}, options = {"shift"}},
						},
					},
 					{
						name = "striderhub",
						x = 5488,
						z = 864,
						facing = 0,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5488, 864}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {5463, 889}, options = {"shift"}},
						},
					},
 					{
						name = "turretheavy",
						x = 4648,
						z = 4056,
						facing = 0,
					},
 					{
						name = "turretheavy",
						x = 5048,
						z = 3816,
						facing = 0,
					},
 					{
						name = "turretheavy",
						x = 5528,
						z = 3656,
						facing = 0,
					},
 					{
						name = "turretaafar",
						x = 4880,
						z = 3504,
						facing = 0,
					},
 					{
						name = "turretaafar",
						x = 4992,
						z = 928,
						facing = 0,
					},
				}
			},
			aiConfig = {
				{
					humanName = "Ally",
					aiLib = "Circuit_difficulty_autofill_ally",
					bitDependant = true,
					-- aiLib = "Null AI",
					-- bitDependant = false,
					allyTeam = 0,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energyheavygeo",
						"energysingu",
						"energypylon",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turrettorp",
						"turretgauss",
						"turretheavylaser",
						"turretaalaser",
						"turretaaclose",
						"turretaaflak",
						"shieldshield",
						"staticradar",
						"staticheavyradar",
						"staticcon",
						"staticantinuke",
						"staticrearm",
						"turretaafar",
						"turretheavy",
						"staticnuke",
						"staticheavyarty",
						"staticarty",
						"factoryship",
						"shipcon",
						"shipaa",
						"shiparty",
						"shipassault",
						"shipriot",
						"shipscout",
						"shipskirm",
						"shiptorpraider",
						"subraider",
						"factoryamph",
						"amphcon",
						"amphraid",
						"amphimpulse",
						"amphfloater",
						"amphriot",
						"amphassault",
						"amphbomb",
						"amphaa",
						"factoryhover",
						"hovercon",
						"hoverraid",
						"hoverriot",
						"hoverskirm",
						"hoverassault",
						"hoverdepthcharge",
                        "hoverheavyraid",
						"hoverarty",
						"hoveraa",
						"striderhub",
						"striderdante",
						"striderscorpion",
						"striderfunnelweb",
						"striderarty",
						"striderantiheavy",
						"factorycloak",
						"cloakcon",
						"cloakraid",
						"cloakriot",
						"cloakskirm",
						"cloakassault",
						"cloakaa",
						"cloakarty",
						"cloaksnipe",
						"cloakheavyraid",
						"cloakbomb",
						"factorygunship",
						"gunshipcon",
						"gunshipbomb",
						"gunshipemp",
						"gunshipaa",
						"gunshipassault",
						"gunshipheavyskirm",
						"gunshipskirm",
						"gunshipraid",
						"gunshipkrow",
						"factorytank",
						"tankcon",
						"tankassault",
						"tankheavyassault",
						"tankarty",
						"tankheavyarty",
						"tankaa",
						"tankriot",
					},
					commander = false,
					startUnits = {
						{
							name = "striderbantha",
							x = 778,
							z = 1538,
							facing = 0,
							difficultyAtMost = 3,
						},
						{
							name = "staticheavyarty",
							x = 2336,
							z = 752,
							facing = 0,
						},
						{
							name = "staticheavyarty",
							x = 8288,
							z = 880,
							facing = 0,
						},
						{
							name = "staticheavyradar",
							x = 2208,
							z = 2032,
							facing = 0,
						},
 						{
							name = "staticheavyradar",
							x = 8592,
							z = 2432,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3048,
							z = 1496,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6568,
							z = 3128,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3240,
							z = 1160,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3416,
							z = 1640,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7240,
							z = 3496,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6920,
							z = 3832,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3624,
							z = 696,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7432,
							z = 3944,
							facing = 0,
						},
 						{
							name = "tankarty",
							x = 3032,
							z = 4969,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4440,
							z = 1848,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8264,
							z = 4424,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8376,
							z = 3912,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8600,
							z = 3864,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3672,
							z = 3384,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3336,
							z = 3608,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8584,
							z = 3352,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3208,
							z = 3160,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8664,
							z = 2696,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2840,
							z = 3416,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2184,
							z = 3448,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8552,
							z = 1928,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8664,
							z = 1176,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1976,
							z = 2904,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8408,
							z = 1144,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1944,
							z = 2360,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8392,
							z = 440,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1864,
							z = 1560,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7464,
							z = 728,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7576,
							z = 1112,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1912,
							z = 904,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7208,
							z = 1064,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2232,
							z = 1000,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6952,
							z = 648,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2264,
							z = 296,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6248,
							z = 1896,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 984,
							z = 1000,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 776,
							z = 616,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 520,
							z = 1016,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 936,
							z = 1880,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9448,
							z = 1752,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 984,
							z = 3064,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9880,
							z = 1048,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 840,
							z = 3464,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9752,
							z = 648,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 664,
							z = 3816,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9352,
							z = 824,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1160,
							z = 3880,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9576,
							z = 3032,
							facing = 0,
						},
 						{
							name = "amphfloater",
							x = 7809,
							z = 5510,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 9560,
							z = 3576,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9736,
							z = 3976,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9272,
							z = 3928,
							facing = 0,
						},
 						{
							name = "energysingu",
							x = 8776,
							z = 136,
							facing = 0,
						},
 						{
							name = "energysingu",
							x = 1448,
							z = 136,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 312,
							z = 408,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 1032,
							z = 408,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 1752,
							z = 408,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 10008,
							z = 280,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 9288,
							z = 280,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 3192,
							z = 408,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 8568,
							z = 280,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 3192,
							z = 1128,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 7848,
							z = 280,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 2472,
							z = 1128,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 7128,
							z = 280,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 1752,
							z = 1128,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 7128,
							z = 1000,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 1032,
							z = 1128,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 7848,
							z = 1000,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 312,
							z = 1128,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 8568,
							z = 1000,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 312,
							z = 1848,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 9288,
							z = 1000,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 1032,
							z = 1848,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 10008,
							z = 1000,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 1752,
							z = 1848,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 9288,
							z = 1720,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 2472,
							z = 1848,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 8568,
							z = 1720,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 3192,
							z = 1848,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 7848,
							z = 1720,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 7128,
							z = 1720,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 2568,
							z = 248,
							facing = 0,
						},
 						{
							name = "factoryhover",
							x = 1104,
							z = 1472,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1064,
							z = 1288,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1144,
							z = 1288,
							facing = 0,
						},
 						{
							name = "factorytank",
							x = 3088,
							z = 3648,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3064,
							z = 3512,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3144,
							z = 3512,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3144,
							z = 3432,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3064,
							z = 3432,
							facing = 0,
						},
 						{
							name = "factoryamph",
							x = 7368,
							z = 3144,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 7336,
							z = 2936,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 7416,
							z = 2936,
							facing = 0,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7368, 3182}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7416, 2936}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 7416,
							z = 3016,
							facing = 0,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7368, 3182}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7416, 3016}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 7336,
							z = 3016,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1064,
							z = 1192,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1144,
							z = 1192,
							facing = 0,
						},
 						{
							name = "factorygunship",
							x = 9240,
							z = 1336,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 9208,
							z = 1144,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 9288,
							z = 1144,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 9288,
							z = 1224,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 9208,
							z = 1224,
							facing = 0,
						},
 						{
							name = "striderhub",
							x = 9072,
							z = 1216,
							facing = 2,
						},
 						{
							name = "striderhub",
							x = 1232,
							z = 1280,
							facing = 2,
						},
 						{
							name = "staticantinuke",
							x = 7112,
							z = 2640,
							facing = 2,
						},
 						{
							name = "staticantinuke",
							x = 2808,
							z = 2928,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 8264,
							z = 2520,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 8040,
							z = 3272,
							facing = 0,
						},
 						{
							name = "turretaaheavy",
							x = 1920,
							z = 1904,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 8200,
							z = 4104,
							facing = 0,
						},
 						{
							name = "turretaaheavy",
							x = 8448,
							z = 2096,
							facing = 0,
						},
 						{
							name = "turretaafar",
							x = 1968,
							z = 3824,
							facing = 0,
						},
 						{
							name = "turretaafar",
							x = 2224,
							z = 3824,
							facing = 0,
						},
 						{
							name = "turretaafar",
							x = 8368,
							z = 3584,
							facing = 0,
						},
 						{
							name = "turretaafar",
							x = 8576,
							z = 3568,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 2888,
							z = 2568,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 2680,
							z = 3464,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 3240,
							z = 3960,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2152,
							z = 4184,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1896,
							z = 3528,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 2152,
							z = 4296,
							facing = 2,
						},
 						{
							name = "turretheavy",
							x = 1880,
							z = 4680,
							facing = 0,
						},
 						{
							name = "turretheavy",
							x = 2376,
							z = 4728,
							facing = 0,
						},
 						{
							name = "staticshield",
							x = 2128,
							z = 4672,
							facing = 0,
						},
 						{
							name = "staticshield",
							x = 2128,
							z = 4736,
							facing = 0,
						},
 						{
							name = "turretheavy",
							x = 8424,
							z = 4600,
							facing = 0,
						},
 						{
							name = "turretheavy",
							x = 7992,
							z = 4568,
							facing = 0,
						},
 						{
							name = "staticshield",
							x = 8176,
							z = 4576,
							facing = 0,
						},
 						{
							name = "staticshield",
							x = 8240,
							z = 4576,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 8088,
							z = 4472,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 8392,
							z = 4472,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 1976,
							z = 4568,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 2280,
							z = 4616,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 7040,
							z = 3792,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 3292,
							z = 632,
							facing = 3,
						},
 						{
							name = "tankriot",
							x = 4791,
							z = 3632,
							facing = 1,
						},
 						{
							name = "striderfunnelweb",
							x = 4334,
							z = 3632,
							facing = 1,
						},
 						{
							name = "striderarty",
							x = 7271,
							z = 4946,
							facing = 0,
						},
 						{
							name = "gunshipheavyskirm",
							x = 9345,
							z = 5955,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 1336,
							z = 1448,
							facing = 1,
						},
 						{
							name = "hoverassault",
							x = 5454,
							z = 3357,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 912,
							z = 4048,
							facing = 1,
						},
 						{
							name = "amphassault",
							x = 8762,
							z = 5472,
							facing = 0,
						},
 						{
							name = "gunshipcon",
							x = 7930,
							z = 3754,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 7524,
							z = 4800,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 7232,
							z = 3872,
							facing = 3,
						},
 						{
							name = "hovercon",
							x = 1626,
							z = 2421,
							facing = 1,
						},
 						{
							name = "tankcon",
							x = 4186,
							z = 832,
							facing = 3,
						},
 						{
							name = "gunshipheavyskirm",
							x = 7499,
							z = 2936,
							facing = 0,
							patrolRoute = {
								{7528, 2904},
								{7404, 3038},
							},
						},
 						{
							name = "tankcon",
							x = 1658,
							z = 3628,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 7504,
							z = 1072,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 2912,
							z = 3360,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 4355,
							z = 2798,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 3200,
							z = 3264,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 8512,
							z = 3344,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 3137,
							z = 1063,
							facing = 3,
						},
 						{
							name = "tankcon",
							x = 1000,
							z = 3534,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 7152,
							z = 944,
							facing = 0,
						},
 						{
							name = "hovercon",
							x = 1499,
							z = 1386,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 5328,
							z = 688,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 3328,
							z = 1376,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 8352,
							z = 4064,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 1288,
							z = 1496,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 3240,
							z = 4600,
							facing = 0,
						},
 						{
							name = "hoverarty",
							x = 7028,
							z = 4403,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 8448,
							z = 384,
							facing = 0,
						},
 						{
							name = "tankassault",
							x = 4874,
							z = 3802,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 4105,
							z = 2519,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 9424,
							z = 1872,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 848,
							z = 1440,
							facing = 1,
						},
 						{
							name = "droneheavyslow",
							x = 4247,
							z = 3630,
							facing = 2,
						},
 						{
							name = "turretmissile",
							x = 800,
							z = 3632,
							facing = 1,
						},
 						{
							name = "gunshipheavyskirm",
							x = 5769,
							z = 4195,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5524, 4387}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5567, 4340}, options = {"shift"}},
							},
						},
 						{
							name = "turretlaser",
							x = 5040,
							z = 2880,
							facing = 0,
						},
 						{
							name = "tankcon",
							x = 1347,
							z = 3127,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 9296,
							z = 1680,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 4345,
							z = 1637,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 6216,
							z = 2024,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 9472,
							z = 3984,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 880,
							z = 3424,
							facing = 1,
							buildProgress = 0.50989997,
						},
 						{
							name = "turretlaser",
							x = 9568,
							z = 912,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 896,
							z = 1936,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1008,
							z = 3600,
							facing = 1,
						},
 						{
							name = "striderarty",
							x = 4716,
							z = 1079,
							facing = 0,
						},
 						{
							name = "striderarty",
							x = 7729,
							z = 4558,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 8104,
							z = 5032,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 6563,
							z = 1984,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 4960,
							z = 2704,
							facing = 0,
						},
 						{
							name = "amphaa",
							x = 8736,
							z = 4671,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 8616,
							z = 2744,
							facing = 3,
						},
 						{
							name = "dronelight",
							x = 4326,
							z = 3585,
							facing = 1,
						},
 						{
							name = "dronelight",
							x = 4269,
							z = 3558,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 7442,
							z = 4586,
							facing = 0,
						},
 						{
							name = "gunshipaa",
							x = 7477,
							z = 3187,
							facing = 1,
							patrolRoute = {
								{7544, 3144},
								{7342, 3275},
							},
						},
 						{
							name = "staticradar",
							x = 1040,
							z = 3792,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 2482,
							z = 1513,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 8168,
							z = 4936,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 9392,
							z = 3792,
							facing = 3,
						},
 						{
							name = "tankcon",
							x = 3090,
							z = 4471,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 7961,
							z = 1964,
							facing = 0,
						},
 						{
							name = "droneheavyslow",
							x = 4334,
							z = 3698,
							facing = 3,
						},
 						{
							name = "tankcon",
							x = 1175,
							z = 1347,
							facing = 1,
						},
 						{
							name = "striderscorpion",
							x = 9072,
							z = 1120,
							facing = 0,
							buildProgress = 0.1002,
						},
 						{
							name = "dronelight",
							x = 4325,
							z = 3636,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 1288,
							z = 1400,
							facing = 1,
						},
 						{
							name = "tankassault",
							x = 3580,
							z = 3686,
							facing = 1,
						},
 						{
							name = "dronelight",
							x = 4252,
							z = 3572,
							facing = 1,
						},
 						{
							name = "turrettorp",
							x = 8776,
							z = 2696,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 7361,
							z = 4633,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 6528,
							z = 3040,
							facing = 0,
						},
 						{
							name = "hovercon",
							x = 2106,
							z = 3448,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 832,
							z = 3840,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1952,
							z = 2864,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 9512,
							z = 5704,
							facing = 0,
						},
 						{
							name = "hovercon",
							x = 3112,
							z = 4223,
							facing = 2,
						},
 						{
							name = "dronelight",
							x = 4294,
							z = 3627,
							facing = 1,
						},
 						{
							name = "dronelight",
							x = 4415,
							z = 3632,
							facing = 1,
						},
 						{
							name = "amphraid",
							x = 9614,
							z = 7178,
							facing = 2,
						},
 						{
							name = "tankheavyassault",
							x = 3107,
							z = 4025,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 6120,
							z = 1816,
							facing = 0,
						},
 						{
							name = "tankcon",
							x = 1432,
							z = 3216,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 8743,
							z = 4411,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 9472,
							z = 5920,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 8154,
							z = 5088,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 4976,
							z = 2771,
							facing = 3,
						},
 						{
							name = "hovercon",
							x = 2503,
							z = 3822,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 632,
							z = 3768,
							facing = 1,
						},
 						{
							name = "turrettorp",
							x = 4520,
							z = 1832,
							facing = 0,
						},
 						{
							name = "amphraid",
							x = 9764,
							z = 7272,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 5280,
							z = 448,
							facing = 0,
						},
 						{
							name = "gunshipheavyskirm",
							x = 7236,
							z = 5047,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 2048,
							z = 4192,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1336,
							z = 1496,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 3688,
							z = 1416,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 2096,
							z = 3408,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 9440,
							z = 5728,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 4440,
							z = 1624,
							facing = 0,
						},
 						{
							name = "amphraid",
							x = 9628,
							z = 7250,
							facing = 2,
						},
 						{
							name = "amphfloater",
							x = 7735,
							z = 5270,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 8528,
							z = 1200,
							facing = 0,
						},
 						{
							name = "striderdante",
							x = 1615,
							z = 1041,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1384,
							z = 1448,
							facing = 1,
						},
 						{
							name = "amphfloater",
							x = 7738,
							z = 5422,
							facing = 0,
						},
 						{
							name = "striderdante",
							x = 9120,
							z = 1830,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 4392,
							z = 1832,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1288,
							z = 1448,
							facing = 1,
						},
 						{
							name = "tankcon",
							x = 3189,
							z = 4440,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 6559,
							z = 2996,
							facing = 2,
						},
 						{
							name = "hovercon",
							x = 1639,
							z = 2310,
							facing = 1,
						},
 						{
							name = "gunshipskirm",
							x = 5754,
							z = 4751,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5523, 4451}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5520, 4387}, options = {"shift"}},
							},
						},
 						{
							name = "energypylon",
							x = 4232,
							z = 1736,
							facing = 0,
						},
 						{
							name = "amphraid",
							x = 5830,
							z = 4074,
							facing = 3,
						},
 						{
							name = "tankcon",
							x = 3127,
							z = 4447,
							facing = 2,
						},
 						{
							name = "turretmissile",
							x = 7216,
							z = 3664,
							facing = 3,
						},
 						{
							name = "hovercon",
							x = 1472,
							z = 1419,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 8325,
							z = 3942,
							facing = 1,
						},
 						{
							name = "tankcon",
							x = 3119,
							z = 4370,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 1288,
							z = 1304,
							facing = 1,
						},
 						{
							name = "hovercon",
							x = 1598,
							z = 2318,
							facing = 1,
						},
 						{
							name = "amphraid",
							x = 5880,
							z = 4235,
							facing = 3,
						},
 						{
							name = "turretaalaser",
							x = 1048,
							z = 3864,
							facing = 1,
						},
 						{
							name = "hovercon",
							x = 1855,
							z = 3376,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1288,
							z = 1544,
							facing = 1,
						},
 						{
							name = "staticstorage",
							x = 4376,
							z = 1960,
							facing = 0,
						},
 						{
							name = "amphraid",
							x = 6361,
							z = 4282,
							facing = 1,
						},
 						{
							name = "tankassault",
							x = 4935,
							z = 3809,
							facing = 0,
						},
 						{
							name = "hovercon",
							x = 1214,
							z = 1533,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 4312,
							z = 1432,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 7424,
							z = 3563,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 5168,
							z = 2720,
							facing = 0,
						},
 						{
							name = "hovercon",
							x = 1488,
							z = 1446,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 7309,
							z = 3617,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 1336,
							z = 1544,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 4920,
							z = 2280,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 2072,
							z = 2328,
							facing = 1,
						},
 						{
							name = "hoveraa",
							x = 4721,
							z = 3164,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1336,
							z = 1352,
							facing = 1,
						},
 						{
							name = "gunshipaa",
							x = 8607,
							z = 3910,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 1384,
							z = 1496,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1336,
							z = 1304,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 5248,
							z = 2928,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4840,
							z = 2104,
							facing = 0,
						},
 						{
							name = "amphraid",
							x = 5909,
							z = 4231,
							facing = 0,
						},
 						{
							name = "hovercon",
							x = 2497,
							z = 3588,
							facing = 1,
						},
 						{
							name = "tankcon",
							x = 3077,
							z = 4365,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 1384,
							z = 1352,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 4760,
							z = 2024,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 7406,
							z = 4594,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1288,
							z = 1592,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1384,
							z = 1544,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 7056,
							z = 4000,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 3488,
							z = 1248,
							facing = 0,
						},
 						{
							name = "tankcon",
							x = 4420,
							z = 3383,
							facing = 1,
						},
 						{
							name = "hoverraid",
							x = 4451,
							z = 3286,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 1112,
							z = 3784,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 7391,
							z = 3423,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 4552,
							z = 1928,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1336,
							z = 1592,
							facing = 1,
						},
 						{
							name = "hoverraid",
							x = 4033,
							z = 3027,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1288,
							z = 1640,
							facing = 1,
						},
 						{
							name = "tankcon",
							x = 3048,
							z = 4537,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 4888,
							z = 2744,
							facing = 0,
							buildProgress = 0.5309,
						},
 						{
							name = "hoverraid",
							x = 3939,
							z = 2963,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 7395,
							z = 3625,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1432,
							z = 1432,
							facing = 1,
						},
 						{
							name = "gunshipcon",
							x = 8559,
							z = 2420,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1432,
							z = 1480,
							facing = 1,
						},
 						{
							name = "hovercon",
							x = 1198,
							z = 2902,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 7352,
							z = 3512,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 1432,
							z = 1384,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 3816,
							z = 1416,
							facing = 0,
						},
 						{
							name = "tankassault",
							x = 3198,
							z = 3766,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1384,
							z = 1400,
							facing = 1,
						},
 						{
							name = "hoverraid",
							x = 2698,
							z = 2540,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 6568,
							z = 2904,
							facing = 0,
							buildProgress = 0.7737,
						},
 						{
							name = "hoverraid",
							x = 2501,
							z = 2414,
							facing = 1,
						},
 						{
							name = "amphraid",
							x = 6683,
							z = 3554,
							facing = 3,
						},
 						{
							name = "hoverraid",
							x = 1960,
							z = 2232,
							facing = 1,
						},
 						{
							name = "gunshipaa",
							x = 9243,
							z = 1587,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1288,
							z = 1352,
							facing = 1,
						},
 						{
							name = "hoverraid",
							x = 1064,
							z = 2057,
							facing = 0,
						},
 						{
							name = "amphimpulse",
							x = 7366,
							z = 3193,
							facing = 0,
						},
 						{
							name = "striderantiheavy",
							x = 1232,
							z = 1200,
							facing = 0,
							buildProgress = 0.53860003,
						},
 						{
							name = "energypylon",
							x = 1720,
							z = 2360,
							facing = 1,
							buildProgress = 0.29159999,
						},
 						{
							name = "turretmissile",
							x = 8064,
							z = 5120,
							facing = 3,
							buildProgress = 0.3574,
						},
 						{
							name = "gunshipaa",
							x = 9240,
							z = 1337,
							facing = 2,
							buildProgress = 0.73949999,
						},
 						{
							name = "hoverraid",
							x = 1104,
							z = 1440,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1384,
							z = 1304,
							facing = 1,
							buildProgress = 0.77420002,
						},
 						{
							name = "tankcon",
							x = 3088,
							z = 3676,
							facing = 0,
							buildProgress = 0.1093,
						},
 						{
							name = "staticcon",
							x = 1336,
							z = 1400,
							facing = 1,
							buildProgress = 0.0556,
						},
 						{
							name = "turretmissile",
							x = 7408,
							z = 3744,
							facing = 3,
							buildProgress = 0.0874,
						},
 						{
							name = "turretlaser",
							x = 3264,
							z = 4544,
							facing = 1,
							buildProgress = 0.0305,
						},
					}
				},
				{
					startX = 4900,
					startZ = 8700,
					humanName = "Enemy",
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					-- aiLib = "Null AI",
					-- bitDependant = false,
					commanderParameters = {
						facplop = false,
					},
					allyTeam = 1,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energyheavygeo",
						"energysingu",
						"energypylon",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turrettorp",
						"turretgauss",
						"turretheavylaser",
						"turretaalaser",
						"turretaaclose",
						"turretaaflak",
						"shieldshield",
						"staticradar",
						"staticheavyradar",
						"staticcon",
						"staticantinuke",
						"staticrearm",
						"turretaafar",
						"turretheavy",
						"staticnuke",
						"staticheavyarty",
						"staticarty",
						"factoryship",
						"shipcon",
						"shipaa",
						"shiparty",
						"shipassault",
						"shipriot",
						"shipscout",
						"shipskirm",
						"shiptorpraider",
						"subraider",
						"factoryamph",
						"amphcon",
						"amphraid",
						"amphimpulse",
						"amphfloater",
						"amphriot",
						"amphassault",
						"amphbomb",
						"amphaa",
						"factoryhover",
						"hovercon",
						"hoverraid",
						"hoverriot",
						"hoverskirm",
						"hoverassault",
						"hoverdepthcharge",
                        "hoverheavyraid",
						"hoverarty",
						"hoveraa",
						"striderhub",
						"striderdante",
						"striderscorpion",
						"striderfunnelweb",
						"striderarty",
						"striderantiheavy",
						"striderbantha",
						"shipcarrier",
						"shipheavyarty",
						"factorycloak",
						"cloakcon",
						"cloakraid",
						"cloakriot",
						"cloakskirm",
						"cloakassault",
						"cloakaa",
						"cloakarty",
						"cloaksnipe",
						"cloakheavyraid",
						"cloakbomb",
						"factorygunship",
						"gunshipcon",
						"gunshipbomb",
						"gunshipemp",
						"gunshipaa",
						"gunshipassault",
						"gunshipheavyskirm",
						"gunshipskirm",
						"gunshipraid",
						"gunshipkrow",
						"factorytank",
						"tankcon",
						"tankassault",
						"tankheavyassault",
						"tankarty",
						"tankheavyarty",
						"tankaa",
						"tankriot",
					},
					commanderLevel = 7,
					commander = {
						name = "Yngas",
						chassis = "strike",
						modules = {
							"commweapon_beamlaser",
							"commweapon_beamlaser",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_autorepair",
							"module_autorepair",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_ablative_armor",
						}
					},
					midgameUnits = {
						{
							name = "striderbantha",
							x = 900,
							z = 9000,
							facing = 0,
							spawnRadius = 150,
							delay = 6*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 3,
						},
						{
							name = "striderfunnelweb",
							x = 9800,
							z = 9000,
							facing = 0,
							spawnRadius = 150,
							delay = 6*30*60,
							orbitalDrop = true,
						},
						{
							name = "striderfunnelweb",
							x = 9800,
							z = 9000,
							facing = 0,
							spawnRadius = 150,
							delay = 6*30*60,
							orbitalDrop = true,
						},
						{
							name = "striderfunnelweb",
							x = 9800,
							z = 9000,
							facing = 0,
							spawnRadius = 150,
							delay = 6*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 4,
						},
						{
							name = "striderbantha",
							x = 9800,
							z = 9000,
							facing = 0,
							spawnRadius = 150,
							delay = 12*30*60,
							orbitalDrop = true,
						},
						{
							name = "striderdante",
							x = 9800,
							z = 9000,
							facing = 0,
							spawnRadius = 150,
							delay = 12*30*60,
							orbitalDrop = true,
						},
						{
							name = "striderdante",
							x = 9800,
							z = 9000,
							facing = 0,
							spawnRadius = 150,
							delay = 12*30*60,
							orbitalDrop = true,
						},
						{
							name = "striderfunnelweb",
							x = 900,
							z = 9000,
							facing = 0,
							spawnRadius = 150,
							delay = 12*30*60,
							orbitalDrop = true,
						},
						{
							name = "striderfunnelweb",
							x = 900,
							z = 9000,
							facing = 0,
							spawnRadius = 150,
							delay = 12*30*60,
							orbitalDrop = true,
						},
						{
							name = "striderfunnelweb",
							x = 900,
							z = 9000,
							facing = 0,
							spawnRadius = 150,
							delay = 12*30*60,
							orbitalDrop = true,
						},
					},
					startUnits = {
						{
							name = "staticheavyarty",
							x = 4912,
							z = 8688,
							facing = 2,
						},
 						{
							name = "staticheavyarty",
							x = 5120,
							z = 8688,
							facing = 2,
						},
						{
							name = "energypylon",
							x = 4136,
							z = 9944,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4936,
							z = 9128,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5080,
							z = 8776,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2936,
							z = 8728,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3048,
							z = 9160,
							facing = 0,
						},
 						{
							name = "striderdante",
							x = 7797,
							z = 6434,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 3384,
							z = 8920,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3496,
							z = 9368,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6088,
							z = 8408,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4152,
							z = 8328,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6728,
							z = 9080,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7176,
							z = 9320,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7144,
							z = 9784,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7528,
							z = 9624,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2312,
							z = 9032,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2040,
							z = 9032,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8216,
							z = 9416,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8488,
							z = 9384,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2232,
							z = 8440,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8440,
							z = 9896,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2056,
							z = 7496,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9320,
							z = 9432,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9528,
							z = 9080,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2152,
							z = 6792,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9752,
							z = 9448,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2168,
							z = 6184,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2408,
							z = 6152,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 9768,
							z = 8168,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2184,
							z = 5736,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1256,
							z = 6040,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8376,
							z = 7800,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 696,
							z = 6072,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8376,
							z = 8584,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 936,
							z = 5544,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1032,
							z = 6872,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8328,
							z = 6984,
							facing = 0,
						},
 						{
							name = "gunshipassault",
							x = 2512,
							z = 8073,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 7992,
							z = 6200,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 952,
							z = 8648,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 9360,
							z = 9440,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 984,
							z = 9448,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 5016,
							z = 8648,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 840,
							z = 9864,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7224,
							z = 5624,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 440,
							z = 9528,
							facing = 0,
						},
 						{
							name = "shipcon",
							x = 6458,
							z = 5214,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 2264,
							z = 9752,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7336,
							z = 7080,
							facing = 0,
						},
 						{
							name = "shiparty",
							x = 6727,
							z = 8004,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 7216,
							z = 6208,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 5240,
							z = 6488,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3048,
							z = 6712,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5256,
							z = 5960,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3512,
							z = 6776,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3928,
							z = 6600,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3352,
							z = 6344,
							facing = 0,
						},
 						{
							name = "hoverarty",
							x = 9105,
							z = 7671,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 5216,
							z = 5584,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 6056,
							z = 5160,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 8256,
							z = 9648,
							facing = 2,
						},
 						{
							name = "shipskirm",
							x = 5552,
							z = 8123,
							facing = 2,
						},
 						{
							name = "pw_metal",
							x = 192,
							z = 8528,
							facing = 0,
						},
 						{
							name = "pw_metal",
							x = 2240,
							z = 10096,
							facing = 0,
						},
 						{
							name = "pw_metal",
							x = 8400,
							z = 10128,
							facing = 0,
						},
 						{
							name = "pw_metal",
							x = 10112,
							z = 8656,
							facing = 0,
						},
 						{
							name = "energysingu",
							x = 5720,
							z = 10120,
							facing = 0,
						},
 						{
							name = "energysingu",
							x = 4680,
							z = 10184,
							facing = 0,
						},
 						{
							name = "energysingu",
							x = 10168,
							z = 10152,
							facing = 0,
						},
 						{
							name = "energysingu",
							x = 88,
							z = 10120,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 9960,
							z = 10008,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 9240,
							z = 10008,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 7800,
							z = 10008,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 7080,
							z = 10008,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 6360,
							z = 10008,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 5640,
							z = 10008,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 3480,
							z = 10008,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 2760,
							z = 10008,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 2040,
							z = 10008,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 1320,
							z = 10008,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 600,
							z = 10008,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 600,
							z = 9288,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 1320,
							z = 9288,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 2760,
							z = 9288,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 3480,
							z = 9288,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 4200,
							z = 9288,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 4920,
							z = 9288,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 5640,
							z = 9288,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 6360,
							z = 9288,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 7080,
							z = 9288,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 7800,
							z = 9288,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 8520,
							z = 9288,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 9240,
							z = 9288,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 9960,
							z = 9288,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 9960,
							z = 8568,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 9240,
							z = 8568,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 8520,
							z = 8568,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 5640,
							z = 8568,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 4920,
							z = 8568,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 4200,
							z = 8568,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 3480,
							z = 8568,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 2760,
							z = 8568,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 2040,
							z = 8568,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 1320,
							z = 8568,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 600,
							z = 8568,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 4776,
							z = 9976,
							facing = 0,
						},
 						{
							name = "factoryship",
							x = 5840,
							z = 8608,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 5960,
							z = 8568,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5960, 8568}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5832, 8607}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 6040,
							z = 8568,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {6040, 8568}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5832, 8607}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 6040,
							z = 8648,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {6040, 8648}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5832, 8607}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 5960,
							z = 8648,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5960, 8648}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5832, 8607}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 5960,
							z = 8728,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5960, 8728}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5832, 8607}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 6040,
							z = 8728,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {6040, 8728}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5832, 8607}, options = {"shift"}},
							},
						},
 						{
							name = "striderhub",
							x = 4128,
							z = 8976,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 4024,
							z = 8840,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 3944,
							z = 8840,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 3944,
							z = 8920,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 4024,
							z = 8920,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 4024,
							z = 9000,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 3944,
							z = 9000,
							facing = 2,
						},
 						{
							name = "factorygunship",
							x = 1304,
							z = 9608,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 1272,
							z = 9736,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 1352,
							z = 9736,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 1352,
							z = 9816,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 1272,
							z = 9816,
							facing = 2,
						},
 						{
							name = "factoryamph",
							x = 3288,
							z = 7144,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 3256,
							z = 7288,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 3336,
							z = 7288,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 3336,
							z = 7368,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 3256,
							z = 7368,
							facing = 2,
						},
 						{
							name = "factorytank",
							x = 7120,
							z = 7392,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 7080,
							z = 7528,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 7160,
							z = 7528,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 7160,
							z = 7608,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 7080,
							z = 7608,
							facing = 2,
						},
 						{
							name = "factoryhover",
							x = 9552,
							z = 8752,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 9464,
							z = 8920,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 9544,
							z = 8920,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 9624,
							z = 8920,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 9704,
							z = 8920,
							facing = 2,
						},
 						{
							name = "striderhub",
							x = 1104,
							z = 9808,
							facing = 2,
						},
 						{
							name = "striderhub",
							x = 9760,
							z = 9040,
							facing = 2,
						},
 						{
							name = "staticantinuke",
							x = 8136,
							z = 7504,
							facing = 2,
						},
 						{
							name = "staticantinuke",
							x = 4936,
							z = 8864,
							facing = 2,
						},
 						{
							name = "staticantinuke",
							x = 1992,
							z = 7056,
							facing = 2,
						},
 						{
							name = "staticheavyradar",
							x = 2368,
							z = 8096,
							facing = 0,
						},
 						{
							name = "staticheavyradar",
							x = 8576,
							z = 8080,
							facing = 0,
						},
 						{
							name = "staticshield",
							x = 5008,
							z = 8752,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 5272,
							z = 8616,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 5048,
							z = 8520,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 4760,
							z = 8664,
							facing = 2,
						},
 						{
							name = "turretaaflak",
							x = 4792,
							z = 8856,
							facing = 2,
						},
 						{
							name = "turretaaflak",
							x = 5256,
							z = 8856,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 2712,
							z = 6008,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 3000,
							z = 6152,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 3224,
							z = 6200,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 3528,
							z = 6136,
							facing = 2,
						},
 						{
							name = "turretaalaser",
							x = 3400,
							z = 6232,
							facing = 2,
						},
 						{
							name = "turretaalaser",
							x = 2824,
							z = 6152,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 4872,
							z = 5752,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 5112,
							z = 5784,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 5336,
							z = 5752,
							facing = 2,
						},
 						{
							name = "turretaalaser",
							x = 4984,
							z = 5832,
							facing = 2,
						},
 						{
							name = "turretaalaser",
							x = 5224,
							z = 5832,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 6840,
							z = 5912,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 7112,
							z = 6008,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 7352,
							z = 6040,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 7608,
							z = 5976,
							facing = 2,
						},
 						{
							name = "turretaalaser",
							x = 7496,
							z = 6040,
							facing = 2,
						},
 						{
							name = "turretaalaser",
							x = 6952,
							z = 6008,
							facing = 2,
						},
 						{
							name = "staticshield",
							x = 6896,
							z = 6128,
							facing = 2,
						},
 						{
							name = "staticshield",
							x = 7504,
							z = 6192,
							facing = 2,
						},
 						{
							name = "staticshield",
							x = 3424,
							z = 6384,
							facing = 2,
						},
 						{
							name = "staticshield",
							x = 2752,
							z = 6240,
							facing = 2,
						},
 						{
							name = "staticshield",
							x = 5104,
							z = 5856,
							facing = 2,
						},
 						{
							name = "shipcon",
							x = 5883,
							z = 7339,
							facing = 2,
						},
 						{
							name = "staticstorage",
							x = 5016,
							z = 8792,
							facing = 2,
						},
 						{
							name = "striderdante",
							x = 6377,
							z = 6466,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 7184,
							z = 9600,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 6152,
							z = 5032,
							facing = 3,
						},
 						{
							name = "striderbantha",
							x = 1104,
							z = 9712,
							facing = 0,
							buildProgress = 0.85110003,
						},
 						{
							name = "staticstorage",
							x = 5064,
							z = 8728,
							facing = 2,
						},
 						{
							name = "striderbantha",
							x = 9799,
							z = 8953,
							facing = 1,
						},
 						{
							name = "turrettorp",
							x = 8328,
							z = 7896,
							facing = 3,
						},
 						{
							name = "hoverraid",
							x = 5455,
							z = 5036,
							facing = 3,
						},
 						{
							name = "shiparty",
							x = 4317,
							z = 5107,
							facing = 2,
						},
 						{
							name = "hovercon",
							x = 7965,
							z = 9159,
							facing = 2,
						},
 						{
							name = "amphraid",
							x = 5573,
							z = 5023,
							facing = 3,
						},
 						{
							name = "shipcon",
							x = 4897,
							z = 7679,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 5992,
							z = 8920,
							facing = 2,
						},
 						{
							name = "amphassault",
							x = 6541,
							z = 5532,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 3856,
							z = 6816,
							facing = 2,
						},
 						{
							name = "shipcon",
							x = 5714,
							z = 4971,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 5144,
							z = 8776,
							facing = 2,
						},
 						{
							name = "gunshipheavyskirm",
							x = 5746,
							z = 5592,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 6080,
							z = 8592,
							facing = 2,
						},
 						{
							name = "shipassault",
							x = 5494,
							z = 7252,
							facing = 2,
						},
 						{
							name = "hovercon",
							x = 7964,
							z = 6882,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 8416,
							z = 6912,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 7328,
							z = 9456,
							facing = 2,
						},
 						{
							name = "amphraid",
							x = 5616,
							z = 4616,
							facing = 0,
						},
 						{
							name = "hoverarty",
							x = 6180,
							z = 6498,
							facing = 1,
						},
 						{
							name = "turrettorp",
							x = 4088,
							z = 8280,
							facing = 2,
						},
 						{
							name = "staticstorage",
							x = 5208,
							z = 8744,
							facing = 2,
						},
 						{
							name = "tankarty",
							x = 8487,
							z = 6633,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 2160,
							z = 6880,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 1872,
							z = 5499,
							facing = 2,
						},
 						{
							name = "shipcon",
							x = 5848,
							z = 8831,
							facing = 0,
						},
 						{
							name = "striderbantha",
							x = 4889,
							z = 7349,
							facing = 2,
						},
 						{
							name = "hoverraid",
							x = 5119,
							z = 5086,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 4192,
							z = 8368,
							facing = 2,
						},
 						{
							name = "amphfloater",
							x = 5126,
							z = 7315,
							facing = 1,
						},
 						{
							name = "shipassault",
							x = 5435,
							z = 7328,
							facing = 2,
						},
 						{
							name = "gunshipcon",
							x = 2711,
							z = 8108,
							facing = 1,
						},
 						{
							name = "tankcon",
							x = 7213,
							z = 5921,
							facing = 2,
						},
 						{
							name = "tankassault",
							x = 8558,
							z = 6184,
							facing = 1,
						},
 						{
							name = "staticstorage",
							x = 5064,
							z = 8680,
							facing = 2,
						},
 						{
							name = "amphaa",
							x = 3416,
							z = 6035,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 7184,
							z = 6896,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 8416,
							z = 8688,
							facing = 2,
						},
 						{
							name = "hovercon",
							x = 9618,
							z = 7584,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 4278,
							z = 6473,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 2008,
							z = 7448,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 2208,
							z = 6064,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 1179,
							z = 6612,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 7008,
							z = 7024,
							facing = 3,
						},
 						{
							name = "tankcon",
							x = 7153,
							z = 5636,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 848,
							z = 9504,
							facing = 2,
						},
 						{
							name = "shipcon",
							x = 4423,
							z = 6184,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 8152,
							z = 7592,
							facing = 3,
						},
 						{
							name = "staticstorage",
							x = 5160,
							z = 8712,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 2224,
							z = 7632,
							facing = 1,
						},
 						{
							name = "tankheavyarty",
							x = 7631,
							z = 6361,
							facing = 1,
						},
 						{
							name = "hoverraid",
							x = 6071,
							z = 6331,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 3486,
							z = 5750,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 2040,
							z = 9336,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 2352,
							z = 6208,
							facing = 1,
						},
 						{
							name = "shipcon",
							x = 5973,
							z = 5181,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 9408,
							z = 9232,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 928,
							z = 9680,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 1832,
							z = 7496,
							facing = 1,
						},
 						{
							name = "shipcon",
							x = 5758,
							z = 6880,
							facing = 1,
						},
 						{
							name = "gunshipheavyskirm",
							x = 7495,
							z = 7495,
							facing = 1,
							patrolRoute = {
								{7496, 7496},
								{7365, 7365},
							},
						},
 						{
							name = "turrettorp",
							x = 5976,
							z = 8280,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 5120,
							z = 9040,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 6025,
							z = 5220,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 1024,
							z = 8560,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 5568,
							z = 8592,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 8312,
							z = 7816,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 6032,
							z = 8384,
							facing = 2,
						},
 						{
							name = "shipcon",
							x = 5728,
							z = 6777,
							facing = 2,
						},
 						{
							name = "tankcon",
							x = 7176,
							z = 5943,
							facing = 2,
						},
 						{
							name = "shipcon",
							x = 5397,
							z = 7537,
							facing = 1,
						},
 						{
							name = "hovercon",
							x = 9685,
							z = 7503,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 5810,
							z = 6568,
							facing = 1,
						},
 						{
							name = "tankcon",
							x = 6880,
							z = 6957,
							facing = 0,
						},
 						{
							name = "shipcon",
							x = 5067,
							z = 4888,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 2040,
							z = 9144,
							facing = 2,
						},
 						{
							name = "hoveraa",
							x = 8613,
							z = 6041,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 8224,
							z = 6832,
							facing = 3,
						},
 						{
							name = "gunshipaa",
							x = 7535,
							z = 7122,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 1792,
							z = 5676,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 9824,
							z = 8256,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 3824,
							z = 6624,
							facing = 2,
						},
 						{
							name = "shipaa",
							x = 4986,
							z = 7516,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 8344,
							z = 8072,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 8048,
							z = 6272,
							facing = 3,
						},
 						{
							name = "tankassault",
							x = 7929,
							z = 6271,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 2040,
							z = 9464,
							facing = 2,
						},
 						{
							name = "amphaa",
							x = 3423,
							z = 6077,
							facing = 2,
						},
 						{
							name = "amphimpulse",
							x = 6264,
							z = 6458,
							facing = 1,
						},
 						{
							name = "gunshipaa",
							x = 8319,
							z = 6762,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 928,
							z = 5824,
							facing = 1,
						},
 						{
							name = "hoverraid",
							x = 5295,
							z = 5063,
							facing = 3,
						},
 						{
							name = "shiparty",
							x = 6643,
							z = 8052,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 7920,
							z = 6464,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 2144,
							z = 9808,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 3216,
							z = 8800,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 6904,
							z = 7112,
							facing = 0,
							buildProgress = 0.2299,
						},
 						{
							name = "tankcon",
							x = 6349,
							z = 6880,
							facing = 3,
						},
 						{
							name = "amphraid",
							x = 5509,
							z = 4681,
							facing = 1,
						},
 						{
							name = "gunshipcon",
							x = 5638,
							z = 5175,
							facing = 2,
						},
 						{
							name = "tankcon",
							x = 5557,
							z = 6846,
							facing = 0,
						},
 						{
							name = "shipskirm",
							x = 5559,
							z = 7063,
							facing = 2,
						},
 						{
							name = "amphraid",
							x = 5621,
							z = 4640,
							facing = 1,
						},
 						{
							name = "hoverassault",
							x = 8202,
							z = 7769,
							facing = 3,
						},
 						{
							name = "shiptorpraider",
							x = 4685,
							z = 7082,
							facing = 2,
						},
 						{
							name = "amphraid",
							x = 5554,
							z = 4700,
							facing = 1,
						},
 						{
							name = "amphraid",
							x = 5620,
							z = 4668,
							facing = 1,
						},
 						{
							name = "gunshipassault",
							x = 4077,
							z = 6983,
							facing = 2,
						},
 						{
							name = "amphraid",
							x = 5644,
							z = 4614,
							facing = 1,
						},
 						{
							name = "tankcon",
							x = 8180,
							z = 6245,
							facing = 1,
						},
 						{
							name = "shipcon",
							x = 4511,
							z = 6007,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5176,
							z = 5576,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 1755,
							z = 5697,
							facing = 2,
						},
 						{
							name = "tankassault",
							x = 8899,
							z = 5975,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 7968,
							z = 6080,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 8328,
							z = 6760,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 7328,
							z = 5648,
							facing = 3,
						},
 						{
							name = "shipcon",
							x = 5754,
							z = 7250,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 2192,
							z = 8816,
							facing = 2,
						},
 						{
							name = "striderscorpion",
							x = 4564,
							z = 8736,
							facing = 1,
						},
 						{
							name = "amphraid",
							x = 5249,
							z = 5264,
							facing = 3,
						},
 						{
							name = "hoverraid",
							x = 5812,
							z = 6349,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 5408,
							z = 5968,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 6032,
							z = 5392,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 4495,
							z = 5759,
							facing = 1,
						},
 						{
							name = "shipcon",
							x = 5929,
							z = 7367,
							facing = 2,
						},
 						{
							name = "tankassault",
							x = 8226,
							z = 6204,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 8240,
							z = 7040,
							facing = 3,
						},
 						{
							name = "shipskirm",
							x = 6544,
							z = 8009,
							facing = 3,
						},
 						{
							name = "hovercon",
							x = 8120,
							z = 9252,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 9768,
							z = 9176,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {9792, 8943}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {9768, 9176}, options = {"shift"}},
							},
						},
 						{
							name = "amphcon",
							x = 2951,
							z = 8020,
							facing = 0,
						},
 						{
							name = "shipcarrier",
							x = 4160,
							z = 8832,
							facing = 0,
							buildProgress = 0.69440001,
						},
 						{
							name = "shipassault",
							x = 5245,
							z = 7680,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 3320,
							z = 6114,
							facing = 2,
						},
 						{
							name = "hovercon",
							x = 9495,
							z = 7113,
							facing = 2,
						},
 						{
							name = "tankaa",
							x = 7728,
							z = 6522,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 6016,
							z = 5184,
							facing = 3,
						},
 						{
							name = "amphaa",
							x = 3456,
							z = 6284,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 976,
							z = 6896,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 7112,
							z = 5784,
							facing = 3,
							buildProgress = 0.88029999,
						},
 						{
							name = "amphcon",
							x = 3051,
							z = 7705,
							facing = 0,
						},
 						{
							name = "hoveraa",
							x = 9632,
							z = 8389,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 1928,
							z = 7912,
							facing = 1,
						},
 						{
							name = "amphaa",
							x = 3272,
							z = 6641,
							facing = 2,
						},
 						{
							name = "striderdante",
							x = 3383,
							z = 6623,
							facing = 1,
						},
 						{
							name = "gunshipaa",
							x = 1477,
							z = 9408,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 1944,
							z = 5416,
							facing = 1,
							buildProgress = 0.69999999,
						},
 						{
							name = "tankaa",
							x = 7120,
							z = 7364,
							facing = 2,
							buildProgress = 0.63270003,
						},
 						{
							name = "staticcon",
							x = 5944,
							z = 5288,
							facing = 3,
							buildProgress = 0.33399999,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5944, 5288}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5919, 5263}, options = {"shift"}},
							},
						},
 						{
							name = "staticmex",
							x = 8248,
							z = 6152,
							facing = 0,
							buildProgress = 0.87330002,
						},
 						{
							name = "gunshipaa",
							x = 1304,
							z = 9607,
							facing = 0,
							buildProgress = 0.1567,
						},
 						{
							name = "shipskirm",
							x = 5832,
							z = 8607,
							facing = 2,
						},
 						{
							name = "hoveraa",
							x = 9551,
							z = 8784,
							facing = 2,
							buildProgress = 0.27990001,
						},
 						{
							name = "amphaa",
							x = 3288,
							z = 7108,
							facing = 2,
							buildProgress = 0.37220001,
						},
					}
				},
			},
			defeatConditionConfig = {
				[0] = { },
				[1] = {
					ignoreUnitLossDefeat = false,
					vitalCommanders = false,
					vitalUnitTypes = {
						"energysingu",
						"pw_metal",
					},
					loseAfterSeconds = false,
					allyTeamLossObjectiveID = 1,
				},
			},
			objectiveConfig = {
				-- This is just related to displaying objectives on the UI.
				[1] = {
					description = "Destroy all enemy Singularity Reactors and Ancient Fabricators",
				},
				[2] = {
					description = "Protect your Commander",
				},
			},
			bonusObjectiveConfig = {
				[1] = {
					satisfyForever = true,
					failOnUnitLoss = true,
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 0,
					unitTypes = {
						"striderdetriment",
					},
					image = planetUtilities.ICON_DIR .. "striderdetriment.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.GUARD,
					description = "Don't lose any Detriments",
					experience = planetUtilities.BONUS_EXP,
				},
				[2] = {
					victoryByTime = 30*60,
					image = planetUtilities.ICON_OVERLAY.CLOCK,
					description = "Win by 30:00",
					experience = planetUtilities.BONUS_EXP,
				},
			}
		},
		completionReward = {
			experience = planetUtilities.MAIN_EXP,
			units = {
				"striderdetriment",
			},
			modules = {
				
			},
			abilities = {
			},
			codexEntries = {
				"location_mannia"
			},
		},
	}
	
	return planetData
end

return GetPlanet
