--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Planet config

local function GetPlanet(planetUtilities, planetID)
	
	local image = LUA_DIRNAME .. "images/planets/swamp01.png"
	
	local planetData = {
		name = "Romolis",
		startingPlanet = false,
		mapDisplay = {
			x = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][1]) or 0.615,
			y = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][2]) or 0.375,
			image = image,
			size = planetUtilities.PLANET_SIZE_MAP,
		},
		infoDisplay = {
			image = image,
			size = planetUtilities.PLANET_SIZE_INFO,
			backgroundImage = planetUtilities.backgroundImages[math.floor(math.random()*#planetUtilities.backgroundImages) + 1],
			terrainType = "Terran",
			radius = "6880 km",
			primary = "Kaoloria",
			primaryType = "G4V",
			milRating = 1,
			feedbackLink = "http://zero-k.info/Forum/Thread/24530",
			text = "There are armies down there, that have been constantly fighting since everyone disappeared. Everywhere else with a stalemate, they would have gone dormant, awaiting external change to resume combat. But not here. This was set up deliberately, to continue long after there was anyone left."
			.. "\n "
			.. "\nWas it a statement? A final act of defiance, before going into the night?"
			,
			extendedText = "This side's Dantes are struggling in the hills against enemy Scorpions and Merlins. But I have Fleas and Widows to decloak, stun and destroy them."
			.. "\n "
			.. "\nTime to break the stalemate."
		},
		tips = {
			{
				image = "unitpics/spiderscout.png",
				text = [[Fleas are exceptionally cheap scout units, good for drawing fire and decloaking enemies. They can burrow into the ground to avoid detection.]]
			},
			{
				image = "unitpics/spiderantiheavy.png",
				text = [[Widows are cloaked spiders with a very powerful but short range EMP gun. Sneak up to enemy heavies and disable them. Multiple Widows will be required for the biggest targets.]]
			},
			{
				image = "unitpics/striderarty.png",
				text = [[The enemy Merlins fire a massive barrage of missiles from long distance. They take a long time to reload so advance after each salvo. Bait them into advancing with a juicy target, then stun them with Widows.]]
			},
		},
		gameConfig = {
			mapName = "Sierra-v2",
			playerConfig = {
				startX = 3800,
				startZ = 600,
				allyTeam = 0,
				facplop = false,
				commanderParameters = {
					facplop = false,
					defeatIfDestroyedObjectiveID = 2,
				},
				extraUnlocks = {
					"factoryspider",
					"spidercon",
					"spiderriot",
					"spiderassault",
					"spiderscout",
					"spiderantiheavy",
				},
				startUnits = {
					{
						name = "staticmex",
						x = 4664,
						z = 792,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 4296,
						z = 808,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 3736,
						z = 216,
						facing = 0,
					},
 					{
						name = "energygeo",
						x = 3256,
						z = 936,
						facing = 2,
					},
 					{
						name = "energypylon",
						x = 3768,
						z = 728,
						facing = 2,
					},
 					{
						name = "energysolar",
						x = 3800,
						z = 232,
						facing = 1,
					},
 					{
						name = "energysolar",
						x = 3720,
						z = 280,
						facing = 0,
					},
 					{
						name = "energysolar",
						x = 3672,
						z = 200,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 3752,
						z = 152,
						facing = 2,
					},
 					{
						name = "energysolar",
						x = 4360,
						z = 824,
						facing = 1,
					},
 					{
						name = "energysolar",
						x = 4280,
						z = 872,
						facing = 0,
					},
 					{
						name = "energysolar",
						x = 4232,
						z = 792,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 4312,
						z = 744,
						facing = 2,
					},
 					{
						name = "energysolar",
						x = 4728,
						z = 808,
						facing = 1,
					},
 					{
						name = "energysolar",
						x = 4648,
						z = 856,
						facing = 0,
					},
 					{
						name = "energysolar",
						x = 4600,
						z = 776,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 4680,
						z = 728,
						facing = 2,
					},
 					{
						name = "energysolar",
						x = 4488,
						z = 872,
						facing = 2,
					},
 					{
						name = "turretheavylaser",
						x = 4488,
						z = 808,
						facing = 0,
					},
 					{
						name = "factoryspider",
						x = 4072,
						z = 344,
						facing = 0,
					},
 					{
						name = "staticcon",
						x = 4104,
						z = 232,
						facing = 0,
						selfPatrol = true,
					},
					{
						name = "staticcon",
						x = 4000,
						z = 232,
						facing = 0,
						selfPatrol = true,
					},
					{
						name = "staticcon",
						x = 3900,
						z = 232,
						facing = 0,
						selfPatrol = true,
					},
 					{
						name = "energyfusion",
						x = 3912,
						z = 32,
						facing = 0,
					},
 					{
						name = "spiderantiheavy",
						x = 4012,
						z = 461,
						facing = 0,
					},
 					{
						name = "spiderantiheavy",
						x = 4067,
						z = 459,
						facing = 0,
					},
 					{
						name = "spiderantiheavy",
						x = 4127,
						z = 455,
						facing = 0,
					},
 					{
						name = "spiderscout",
						x = 218,
						z = 3701,
						facing = 0,
					},
 					{
						name = "spiderscout",
						x = 854,
						z = 3052,
						facing = 0,
					},
 					{
						name = "spiderscout",
						x = 2738,
						z = 3452,
						facing = 0,
					},
 					{
						name = "spiderscout",
						x = 7128,
						z = 3821,
						facing = 0,
					},
 					{
						name = "spiderscout",
						x = 6555,
						z = 4047,
						facing = 0,
					},
 					{
						name = "spiderscout",
						x = 5538,
						z = 3323,
						facing = 0,
					},
 					{
						name = "spiderscout",
						x = 4397,
						z = 3659,
						facing = 0,
					},
				}
			},
			aiConfig = {
				{
					aiLib = "Circuit_difficulty_autofill_ally",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					humanName = "Julienne",
					commanderParameters = {
						facplop = false,
					},
					allyTeam = 0,
					unlocks = {
						"staticcon",
						"staticmex",
						"staticstorage",
						"energysolar",
						"energywind",
						"energygeo",
						--"turretlaser",
						"staticradar",
						"factoryveh",
						"vehcon",
						"vehraid",
						"vehsupport",
						"vehriot",
						"vehassault",
						"veharty",
						--"vehheavyarty", made things too easy
						"factorycloak",
						"cloakcon",
						"cloakraid",
						"cloakriot",
						"cloakskirm",
						"cloakarty",
						"cloakassault",
						"cloaksnipe",
						"cloakbomb",
						"cloakaa",
						"factoryspider",
						"spidercon",
						--"spiderscout",
						"spideremp",
						"spiderriot",
						"spiderskirm",
						"spiderassualt",
						"spidercrabe",
						"spideraa",
						"striderhub",
						"striderdante",
					},
					commander = false,
					startUnits = {
						{
							name = "staticantinuke",
							x = 1600,
							z = 1300,
							facing = 0,
						},
						{
							name = "staticantinuke",
							x = 5300,
							z = 1100,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1800,
							z = 968,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2120,
							z = 776,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6472,
							z = 760,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2744,
							z = 216,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6840,
							z = 600,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5752,
							z = 232,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1880,
							z = 1656,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6024,
							z = 1592,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 840,
							z = 1688,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 712,
							z = 888,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 328,
							z = 904,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 536,
							z = 200,
							facing = 0,
						},
 						{
							name = "energygeo",
							x = 5720,
							z = 1304,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 5160,
							z = 1080,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 5960,
							z = 728,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 6600,
							z = 712,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 6744,
							z = 680,
							facing = 0,
						},
 						{
							name = "energygeo",
							x = 1320,
							z = 1400,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 712,
							z = 1256,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 632,
							z = 664,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 600,
							z = 472,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 552,
							z = 312,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 1864,
							z = 1192,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 3704,
							z = 1288,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3704,
							z = 1416,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 2680,
							z = 712,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 5864,
							z = 1416,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 6024,
							z = 1496,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 6024,
							z = 232,
							facing = 0,
						},
 						{
							name = "factorycloak",
							x = 2424,
							z = 416,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 2536,
							z = 248,
							facing = 0,
						},
 						{
							name = "striderhub",
							x = 2624,
							z = 384,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 2424,
							z = 136,
							facing = 0,
						},
 						{
							name = "factoryspider",
							x = 6120,
							z = 440,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 6152,
							z = 328,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 472,
							z = 1144,
							facing = 0,
						},
 						{
							name = "factoryveh",
							x = 496,
							z = 1264,
							facing = 0,
						},
 						{
							name = "turretgauss",
							x = 2024,
							z = 2568,
							facing = 0,
						},
 						{
							name = "turretgauss",
							x = 1080,
							z = 2280,
							facing = 0,
						},
 						{
							name = "turretgauss",
							x = 1544,
							z = 2424,
							facing = 0,
						},
 						{
							name = "turretemp",
							x = 1808,
							z = 2496,
							facing = 0,
						},
 						{
							name = "turretemp",
							x = 1312,
							z = 2384,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 1368,
							z = 2232,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 1800,
							z = 2280,
							facing = 0,
						},
 						{
							name = "turretaafar",
							x = 4048,
							z = 1104,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 3952,
							z = 1136,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 4144,
							z = 1152,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 3176,
							z = 2280,
							facing = 0,
						},
 						{
							name = "turretgauss",
							x = 3096,
							z = 2136,
							facing = 0,
						},
 						{
							name = "turretemp",
							x = 3152,
							z = 1968,
							facing = 0,
						},
 						{
							name = "turretgauss",
							x = 2520,
							z = 1480,
							facing = 0,
						},
 						{
							name = "turretaalaser",
							x = 2680,
							z = 1624,
							facing = 0,
						},
 						{
							name = "turretaalaser",
							x = 2888,
							z = 1816,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 5000,
							z = 1928,
							facing = 0,
						},
 						{
							name = "turretgauss",
							x = 4264,
							z = 1864,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3000,
							z = 1832,
							facing = 0,
						},
 						{
							name = "turretemp",
							x = 4864,
							z = 1952,
							facing = 0,
						},
 						{
							name = "turretemp",
							x = 4384,
							z = 1904,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 4568,
							z = 1832,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 4680,
							z = 1800,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1640,
							z = 2280,
							facing = 0,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1640, 2280}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1756, 2669}, options = {"shift"}},
							},
						},
 						{
							name = "turretheavylaser",
							x = 5928,
							z = 2360,
							facing = 0,
						},
 						{
							name = "turretgauss",
							x = 7016,
							z = 1704,
							facing = 0,
						},
 						{
							name = "turretemp",
							x = 6848,
							z = 1664,
							facing = 0,
						},
 						{
							name = "turretemp",
							x = 6064,
							z = 2352,
							facing = 0,
						},
 						{
							name = "turretaalaser",
							x = 6216,
							z = 2136,
							facing = 0,
						},
 						{
							name = "turretaalaser",
							x = 6600,
							z = 1848,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 6088,
							z = 2200,
							facing = 0,
						},
 						{
							name = "turretgauss",
							x = 72,
							z = 1944,
							facing = 0,
						},
 						{
							name = "turretemp",
							x = 192,
							z = 1952,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 6000,
							z = 2336,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 4928,
							z = 1904,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 1184,
							z = 2288,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 3168,
							z = 2176,
							facing = 2,
						},
 						{
							name = "striderdante",
							x = 2372,
							z = 2658,
							facing = 2,
							patrolRoute = {
								{2459, 2724},
								{2320, 2592},
							},
						},
 						{
							name = "energywind",
							x = 3656,
							z = 1400,
							facing = 0,
						},
 						{
							name = "cloakcon",
							x = 6394,
							z = 3410,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 5712,
							z = 160,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 6088,
							z = 1592,
							facing = 3,
						},
 						{
							name = "cloakcon",
							x = 1550,
							z = 2360,
							facing = 1,
						},
 						{
							name = "vehassault",
							x = 5228,
							z = 4052,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 2016,
							z = 992,
							facing = 0,
						},
 						{
							name = "vehassault",
							x = 5187,
							z = 4034,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 5048,
							z = 2456,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 3016,
							z = 1944,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 6318,
							z = 3414,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6472,
							z = 2568,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 2840,
							z = 200,
							facing = 0,
						},
 						{
							name = "spideraa",
							x = 5083,
							z = 3490,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 520,
							z = 1112,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1736,
							z = 1080,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1704,
							z = 2376,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 6472,
							z = 3608,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 1736,
							z = 952,
							facing = 0,
						},
 						{
							name = "spidercrabe",
							x = 5209,
							z = 3663,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 6496,
							z = 3472,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 424,
							z = 1128,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 824,
							z = 1640,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 4776,
							z = 920,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 1656,
							z = 2376,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 1880,
							z = 3080,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4664,
							z = 1912,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 328,
							z = 856,
							facing = 1,
						},
 						{
							name = "vehassault",
							x = 1631,
							z = 3482,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 5192,
							z = 2584,
							facing = 0,
						},
 						{
							name = "striderdante",
							x = 2624,
							z = 480,
							facing = 0,
							buildProgress = 0.67210001,
						},
 						{
							name = "cloakraid",
							x = 3808,
							z = 2696,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 1944,
							z = 1640,
							facing = 0,
						},
 						{
							name = "vehcon",
							x = 2303,
							z = 2290,
							facing = 0,
						},
 						{
							name = "cloakassault",
							x = 3236,
							z = 3578,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 5024,
							z = 2384,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 568,
							z = 1128,
							facing = 1,
						},
 						{
							name = "vehassault",
							x = 1671,
							z = 3359,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 6584,
							z = 3288,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 840,
							z = 904,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 3632,
							z = 304,
							facing = 0,
						},
 						{
							name = "cloakcon",
							x = 2391,
							z = 2751,
							facing = 2,
						},
 						{
							name = "spidercon",
							x = 6075,
							z = 3049,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 776,
							z = 1736,
							facing = 1,
						},
 						{
							name = "vehriot",
							x = 1572,
							z = 3140,
							facing = 1,
						},
 						{
							name = "vehassault",
							x = 1598,
							z = 3455,
							facing = 1,
						},
 						{
							name = "cloakcon",
							x = 2341,
							z = 2476,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 5933,
							z = 3032,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 2168,
							z = 744,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 3848,
							z = 344,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 920,
							z = 1672,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 5800,
							z = 248,
							facing = 0,
						},
 						{
							name = "vehcon",
							x = 2313,
							z = 2567,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 2200,
							z = 840,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 5144,
							z = 2488,
							facing = 3,
						},
 						{
							name = "vehassault",
							x = 1602,
							z = 3315,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1832,
							z = 1640,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 472,
							z = 1096,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 472,
							z = 1048,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 2680,
							z = 264,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 648,
							z = 920,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 424,
							z = 1080,
							facing = 1,
						},
 						{
							name = "cloakskirm",
							x = 3437,
							z = 3373,
							facing = 3,
						},
 						{
							name = "vehassault",
							x = 1642,
							z = 3442,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6840,
							z = 2168,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 4586,
							z = 1231,
							facing = 3,
						},
 						{
							name = "vehcon",
							x = 1609,
							z = 1607,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 728,
							z = 952,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 5960,
							z = 1576,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 5944,
							z = 1496,
							facing = 3,
						},
 						{
							name = "cloakskirm",
							x = 3403,
							z = 3334,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 1736,
							z = 872,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 648,
							z = 840,
							facing = 1,
						},
 						{
							name = "spiderskirm",
							x = 5279,
							z = 2592,
							facing = 0,
						},
 						{
							name = "vehassault",
							x = 1646,
							z = 3391,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 6056,
							z = 1672,
							facing = 3,
						},
 						{
							name = "vehassault",
							x = 1581,
							z = 3494,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 1864,
							z = 968,
							facing = 0,
						},
 						{
							name = "vehassault",
							x = 1579,
							z = 3280,
							facing = 0,
						},
 						{
							name = "vehcon",
							x = 2593,
							z = 2707,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 6136,
							z = 1480,
							facing = 3,
						},
 						{
							name = "spiderskirm",
							x = 5345,
							z = 2526,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 728,
							z = 824,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 1848,
							z = 1048,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6536,
							z = 3560,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 2728,
							z = 152,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 6616,
							z = 3336,
							facing = 3,
						},
 						{
							name = "spiderskirm",
							x = 6120,
							z = 499,
							facing = 0,
						},
 						{
							name = "vehassault",
							x = 1499,
							z = 3188,
							facing = 0,
						},
 						{
							name = "cloakcon",
							x = 2879,
							z = 1469,
							facing = 0,
						},
 						{
							name = "vehcon",
							x = 2011,
							z = 2883,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 520,
							z = 1064,
							facing = 1,
						},
 						{
							name = "spiderskirm",
							x = 5747,
							z = 1088,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 6536,
							z = 2536,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 536,
							z = 840,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 2776,
							z = 296,
							facing = 0,
						},
 						{
							name = "cloakraid",
							x = 3067,
							z = 1964,
							facing = 0,
						},
 						{
							name = "cloakcon",
							x = 2424,
							z = 425,
							facing = 0,
							buildProgress = 0.62849998,
						},
 						{
							name = "vehassault",
							x = 604,
							z = 1415,
							facing = 1,
						},
					}
				},
				{
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					humanName = "X47350",
					allyTeam = 1,
					unlocks = {
						"staticcon",
						"staticmex",
						"staticstorage",
						"staticradar",
						"energysolar",
						"energywind",
						"energygeo",
						"factorycloak",
						"cloakcon",
						"cloakraid",
						"cloakriot",
						"cloakskirm",
						"cloakarty",
						"cloakassault",
						"cloaksnipe",
						"cloakaa",
						"factoryamph",
						"amphcon",
						"amphraid",
						"amphimpulse",
						"amphfloater",
						"amphriot",
						"amphaa",
						"amphassault",
						"factoryspider",
						"spidercon",
						--"spiderscout",
						"spideremp",
						"spiderriot",
						"spiderskirm",
						"spiderassault",
						"spidercrabe",
						"spideraa",
					},
					difficultyDependantUnlocks = {
						[3] = {"spiderantiheavy"},
						[4] = {"spiderantiheavy","amphbomb"},
					},
					commander = false,
					startUnits = {
						{
							name = "staticshield",
							x = 850,
							z = 5000,
							facing = 0,
							difficultyAtLeast = 3,
						},
						{
							name = "staticshield",
							x = 6800,
							z = 4850,
							facing = 0,
							difficultyAtLeast = 3,
						},
						{
							name = "energyfusion",
							x = 130,
							z = 6490,
							facing = 0,
							difficultyAtLeast = 3,
						},
						{
							name = "staticantinuke",
							x = 5700,
							z = 6100,
							facing = 0,
						},
						{
							name = "staticantinuke",
							x = 1800,
							z = 6000,
							facing = 0,
						},
						{
							name = "staticshield",
							x = 1970,
							z = 4700,
							facing = 0,
						},
						{
							name = "staticshield",
							x = 2450,
							z = 4860,
							facing = 0,
						},
						{
							name = "staticshield",
							x = 3930,
							z = 5030,
							facing = 0,
						},
						{
							name = "staticshield",
							x = 4230,
							z = 5500,
							facing = 0,
						},
						{
							name = "staticshield",
							x = 5420,
							z = 4770,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5096,
							z = 6312,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2456,
							z = 6248,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5464,
							z = 6088,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2840,
							z = 6248,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6632,
							z = 6024,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1656,
							z = 5304,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7016,
							z = 6024,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6600,
							z = 6872,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 632,
							z = 6280,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 280,
							z = 6440,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1336,
							z = 6824,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3416,
							z = 6984,
							facing = 2,
						},
 						{
							name = "energygeo",
							x = 1560,
							z = 5688,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 4600,
							z = 6984,
							facing = 2,
						},
 						{
							name = "energygeo",
							x = 5800,
							z = 5496,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 1624,
							z = 5448,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 6264,
							z = 5368,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 5240,
							z = 5384,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 1000,
							z = 6008,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 4184,
							z = 5240,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 504,
							z = 6344,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 376,
							z = 6392,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 1144,
							z = 6584,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 3288,
							z = 5256,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 1240,
							z = 6744,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 6360,
							z = 5800,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 6728,
							z = 6440,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 5304,
							z = 5864,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 2056,
							z = 6024,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 2568,
							z = 6264,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 4552,
							z = 6488,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 2712,
							z = 6248,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 3752,
							z = 5736,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 3336,
							z = 6456,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 3368,
							z = 5352,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 4104,
							z = 5320,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3384,
							z = 6312,
							facing = 0,
						},
 						{
							name = "factoryamph",
							x = 3368,
							z = 6200,
							facing = 2,
						},
 						{
							name = "factoryspider",
							x = 6616,
							z = 6168,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 728,
							z = 5272,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 728,
							z = 5944,
							facing = 2,
						},
 						{
							name = "factorycloak",
							x = 760,
							z = 5824,
							facing = 2,
						},
 						{
							name = "staticstorage",
							x = 3272,
							z = 6584,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 3992,
							z = 4952,
							facing = 2,
						},
 						{
							name = "turretgauss",
							x = 3832,
							z = 4728,
							facing = 2,
						},
 						{
							name = "turretemp",
							x = 4176,
							z = 4976,
							facing = 2,
						},
 						{
							name = "turretemp",
							x = 3808,
							z = 5024,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 2536,
							z = 4776,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 1944,
							z = 4584,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 856,
							z = 4920,
							facing = 2,
						},
 						{
							name = "turretemp",
							x = 1104,
							z = 4848,
							facing = 2,
						},
 						{
							name = "turretriot",
							x = 2696,
							z = 4840,
							facing = 2,
						},
 						{
							name = "turretemp",
							x = 640,
							z = 4848,
							facing = 2,
						},
 						{
							name = "turretgauss",
							x = 1688,
							z = 4520,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 6600,
							z = 6296,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 6792,
							z = 4952,
							facing = 0,
						},
 						{
							name = "turretemp",
							x = 7040,
							z = 4848,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 5304,
							z = 4856,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 6648,
							z = 4520,
							facing = 2,
						},
 						{
							name = "turretaaflak",
							x = 2360,
							z = 4760,
							facing = 2,
						},
 						{
							name = "turretaaflak",
							x = 2152,
							z = 4712,
							facing = 2,
						},
 						{
							name = "turretaaclose",
							x = 1000,
							z = 4936,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 4424,
							z = 5512,
							facing = 2,
						},
 						{
							name = "turretgauss",
							x = 4360,
							z = 5192,
							facing = 2,
						},
 						{
							name = "turretaaflak",
							x = 3976,
							z = 5192,
							facing = 2,
						},
 						{
							name = "turretaaflak",
							x = 4248,
							z = 5400,
							facing = 2,
						},
 						{
							name = "turretaaclose",
							x = 5160,
							z = 6568,
							facing = 2,
						},
 						{
							name = "turretaalaser",
							x = 4904,
							z = 6296,
							facing = 2,
						},
 						{
							name = "turretaalaser",
							x = 4760,
							z = 6824,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 5512,
							z = 4712,
							facing = 2,
						},
 						{
							name = "turretriot",
							x = 5352,
							z = 4520,
							facing = 2,
						},
 						{
							name = "turretaaflak",
							x = 5272,
							z = 4712,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 6776,
							z = 4696,
							facing = 2,
						},
 						{
							name = "turretaalaser",
							x = 7096,
							z = 5000,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 3296,
							z = 7072,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 3488,
							z = 7072,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 736,
							z = 4944,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 4064,
							z = 5040,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 6816,
							z = 4768,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 2608,
							z = 4848,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 2264,
							z = 4840,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3960,
							z = 5288,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 744,
							z = 4360,
							facing = 0,
						},
 						{
							name = "spideremp",
							x = 1019,
							z = 3481,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 2216,
							z = 4792,
							facing = 1,
						},
 						{
							name = "cloakraid",
							x = 2897,
							z = 3878,
							facing = 1,
						},
 						{
							name = "spiderskirm",
							x = 6508,
							z = 4480,
							facing = 2,
						},
 						{
							name = "spidercrabe",
							x = 977,
							z = 3510,
							facing = 1,
						},
 						{
							name = "amphfloater",
							x = 3922,
							z = 2812,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 4656,
							z = 3872,
							facing = 3,
						},
 						{
							name = "cloakcon",
							x = 793,
							z = 3871,
							facing = 1,
						},
 						{
							name = "amphfloater",
							x = 3960,
							z = 2839,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7064,
							z = 4312,
							facing = 0,
						},
 						{
							name = "amphfloater",
							x = 4067,
							z = 2976,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2264,
							z = 4632,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 1376,
							z = 6800,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 5192,
							z = 5384,
							facing = 2,
						},
 						{
							name = "spiderskirm",
							x = 5201,
							z = 4473,
							facing = 3,
						},
 						{
							name = "cloakcon",
							x = 4499,
							z = 3243,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 776,
							z = 4424,
							facing = 1,
						},
 						{
							name = "cloakcon",
							x = 148,
							z = 2835,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 3488,
							z = 6880,
							facing = 2,
						},
 						{
							name = "cloakcon",
							x = 1223,
							z = 4276,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 4246,
							z = 4114,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 2288,
							z = 4736,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 3760,
							z = 4057,
							facing = 1,
						},
 						{
							name = "cloakskirm",
							x = 1043,
							z = 3512,
							facing = 1,
						},
 						{
							name = "spidercrabe",
							x = 6150,
							z = 4477,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 856,
							z = 4344,
							facing = 1,
						},
 						{
							name = "cloaksnipe",
							x = 1867,
							z = 5619,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 784,
							z = 4352,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 2360,
							z = 4680,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 5283,
							z = 4334,
							facing = 0,
						},
 						{
							name = "cloakraid",
							x = 3074,
							z = 4128,
							facing = 1,
						},
 						{
							name = "cloakassault",
							x = 1493,
							z = 3737,
							facing = 2,
						},
 						{
							name = "spidercrabe",
							x = 6616,
							z = 6132,
							facing = 2,
							buildProgress = 0.43849999,
						},
 						{
							name = "amphcon",
							x = 3368,
							z = 6164,
							facing = 2,
							buildProgress = 0.31850001,
						},
 						{
							name = "cloakraid",
							x = 760,
							z = 5814,
							facing = 2,
							buildProgress = 0.94999999,
						},
					}
				},
				{
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					humanName = "Sorcerers",
					allyTeam = 1,
					unlocks = {
						"staticcon",
						"staticmex",
						"energysolar",
						"energygeo",
						"staticstorage",
						"staticradar",
						"turretmissile",
						"planecon",
						"planescout",
						"planeheavyfighter",
						"bomberdisarm",
						"striderhub",
						"striderarty",
						"striderscorpion",
					},
					startX = 4400,
					startZ = 7000,
					commanderLevel = 6,
					commanderParameters = {
						facplop = false,
					},
					commander = {
						name = "Blackwitch",
						chassis = "engineer",
						decorations = {
						  "skin_support_dark",
						},
						modules = {
							"commweapon_lparticlebeam",
							"commweapon_multistunner",
							"module_heavy_armor",
							"module_heavy_armor",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_adv_nano",
							"module_adv_nano",
							"module_adv_nano",
							"module_adv_nano",
							"module_companion_drone",
							"module_companion_drone",
							"module_companion_drone",
							"module_companion_drone",
						}
					},
					midgameUnits = {
						{
							name = "striderscorpion",
							x = 4500,
							z = 6600,
							facing = 0,
							spawnRadius = 150,
							delay = 2*30*60,
							orbitalDrop = true,
						},
						{
							name = "striderscorpion",
							x = 4000,
							z = 6600,
							facing = 0,
							spawnRadius = 150,
							delay = 4*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 4,
						},
						{
							name = "striderscorpion",
							x = 3000,
							z = 6600,
							facing = 0,
							spawnRadius = 150,
							delay = 6*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 2,
							difficultyAtMost = 3,
						},
						{
							name = "striderbantha",
							x = 2000,
							z = 6600,
							facing = 0,
							spawnRadius = 150,
							delay = 6*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 4,
						},
						{
							name = "striderscorpion",
							x = 2000,
							z = 6600,
							facing = 0,
							spawnRadius = 150,
							delay = 8*30*60,
							orbitalDrop = true,
						},
						{
							name = "striderscorpion",
							x = 5500,
							z = 6600,
							facing = 0,
							spawnRadius = 150,
							delay = 10*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 3,
						},
					},
					startUnits = {
						{
							name = "staticheavyarty",
							x = 3970,
							z = 6735,
							facing = 2,
							buildProgress = 0.85,
							difficultyAtLeast = 4,
						},
						{
							name = "staticcon",
							x = 3975,
							z = 7000,
							facing = 2,
							difficultyAtLeast = 4,
						},
						{
							name = "turretriot",
							x = 4050,
							z = 6735,
							facing = 2,
							difficultyAtLeast = 4,
						},
						{
							name = "turretriot",
							x = 3870,
							z = 6700,
							facing = 2,
							difficultyAtLeast = 4,
						},
						{
							name = "striderhub",
							x = 4928,
							z = 6688,
							facing = 2,
						},
						{
							name = "turretriot",
							x = 4800,
							z = 6688,
							facing = 2,
						},
						{
							name = "turretriot",
							x = 5100,
							z = 6688,
							facing = 2,
						},
						{
							name = "striderhub",
							x = 800,
							z = 6688,
							facing = 2,
						},
						{
							name = "turretriot",
							x = 700,
							z = 6688,
							facing = 2,
						},
						{
							name = "turretriot",
							x = 900,
							z = 6688,
							facing = 2,
						},
						{
							name = "turretgauss",
							x = 800,
							z = 6500,
							facing = 2,
						},
						{
							name = "turretgauss",
							x = 800,
							z = 6800,
							facing = 2,
						},
						{
							name = "turretaafar",
							x = 1000,
							z = 6900,
							facing = 2,
						},
						{
							name = "staticrearm",
							x = 4632,
							z = 6696,
							facing = 2,
						},
 						{
							name = "factoryplane",
							x = 4720,
							z = 6392,
							facing = 2,
						},
 						{
							name = "staticstorage",
							x = 4424,
							z = 6808,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 5000,
							z = 6904,
							facing = 2,
						},
 						{
							name = "energygeo",
							x = 3944,
							z = 6328,
							facing = 2,
						},
 						{
							name = "energyfusion",
							x = 3384,
							z = 7136,
							facing = 0,
						},
 						{
							name = "striderarty",
							x = 2281,
							z = 4563,
							facing = 0,
						},
 						{
							name = "striderarty",
							x = 4928,
							z = 6592,
							facing = 0,
							buildProgress = 0.64770001,
						},
 						{
							name = "staticcon",
							x = 4936,
							z = 6840,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 5120,
							z = 6208,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 4984,
							z = 6824,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 5400,
							z = 4616,
							facing = 0,
						},
 						{
							name = "striderscorpion",
							x = 4250,
							z = 4480,
							facing = 3,
						},
					}
				},
			},
			defeatConditionConfig = {
				-- Indexed by allyTeam.
				[0] = { },
				[1] = {
					ignoreUnitLossDefeat = false,
					vitalCommanders = false,
					vitalUnitTypes = {
						"striderhub",
						--"striderscorpion",
						"stridercatapult",
					},
					loseAfterSeconds = false,
					allyTeamLossObjectiveID = 1,
				},
			},
			objectiveConfig = {
				-- This is just related to displaying objectives on the UI.
				[1] = {
					description = "Destroy all enemy Merlins and Strider Hubs",
				},
				[2] = {
					description = "Protect your Commander",
				},
			},
			bonusObjectiveConfig = {
				[1] = { -- Make six Widows
					satisfyOnce = true,
					countRemovedUnits = true,
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 9,
					unitTypes = {
						"spiderantiheavy",
					},
					image = planetUtilities.ICON_DIR .. "spiderantiheavy.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.REPAIR,
					description = "Build 6 Widows",
					experience = planetUtilities.BONUS_EXP,
				},
				[2] = { -- Switch
					satisfyOnce = true,
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 1,
					unitTypes = {
						"factorycloak",
						"factoryshield",
						"factoryamph",
						"factorygunship",
						"factoryhover",
						"factoryjump",
						"factoryplane",
						"factoryship",
						"factorytank",
						"factoryveh",
					},
					image = planetUtilities.ICON_DIR .. "factorycloak.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.REPAIR,
					description = "Build a second Factory",
					experience = planetUtilities.BONUS_EXP,
				},
				[3] = { -- Win by 20:00
					victoryByTime = 18*60,
					image = planetUtilities.ICON_OVERLAY.CLOCK,
					description = "Win by 18:00",
					experience = planetUtilities.BONUS_EXP,
				},
			},
		},
		completionReward = {
			experience = planetUtilities.MAIN_EXP,
			units = {
				"spiderscout",
				"spiderantiheavy",
			},
			modules = {
				"module_autorepair_LIMIT_D_2",
			},
			abilities = {
			},
			codexEntries = {
				"faction_rebels",
				"faction_dynasty"
			},
		},
	}
	
	return planetData
end

return GetPlanet
