--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Planet config

local function GetPlanet(planetUtilities, planetID)
	
	--local image = planetUtilities.planetImages[math.floor(math.random()*#planetUtilities.planetImages) + 1]
	local image = LUA_DIRNAME .. "images/planets/swamp01.png"
	
	local planetData = {
		name = "Lovaza Jira",
		startingPlanet = false,
		mapDisplay = {
			x = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][1]) or 0.485,
			y = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][2]) or 0.60,
			image = image,
			size = planetUtilities.PLANET_SIZE_MAP,
		},
		infoDisplay = {
			image = image,
			size = planetUtilities.PLANET_SIZE_INFO,
			backgroundImage = planetUtilities.backgroundImages[math.floor(math.random()*#planetUtilities.backgroundImages) + 1],
			terrainType = "Terran",
			radius = "6800 km",
			primary = "Glava",
			primaryType = "G4V",
			milRating = 1,
			feedbackLink = "http://zero-k.info/Forum/Thread/24469",
			text = "There is something valuable enough for someone to have put, not one, but two armies to guard it. Were they wary of a Commander betraying and stealing it?"
			.. "\n "
			.. "\nWhatever it is, I will have to find a way past those two armies."
			,
			extendedText = "I managed to trick those two armies to fight each-other thanks to an IFF glitch, but they are bringing heavy units and striders into play. I will need the Halberd armoured assault hovercraft and Lance anti-heavy artillery to cross the battlefield and reach that Artefact."
		},
		tips = {
			{
				image = "unitpics/hoverarty.png",
				text = [[Lances fire an exceptionally powerful beam, capable of destroying even striders in only a few hits. Set Lances to hold-fire when it is particularly important to avoid wasting precious shots on low-value targets.]]
			},
			{
				image = "unitpics/hoverassault.png",
				text = [[Halberds can employ armor when not firing, reducing all incoming damage by a factor of four. Use this to scout for artillery targets or bypass static defenses.]]
			},
			{
				image = "LuaUI/Images/commands/Bold/reclaim.png",
				text = [[You don't have immediate access to many metal spots. Reclaim the wrecks left by the ongoing battle to finance your own army. ]]
			},
		},
		gameConfig = {
			mapName = "ScorpioBattleground",
			playerConfig = {
				startX = 7480,
				startZ = 1400,
				allyTeam = 0,
				commanderParameters = {
					facplop = false,
					defeatIfDestroyedObjectiveID = 2,
					victoryAtLocation = {
						x = 144,
						z = 8080,
						radius = 100,
						objectiveID = 1,
					},
				},
				extraUnlocks = {
					"factoryhover",
					"hovercon",
					"hoverraid",
					"hoverriot",
					"hoverskirm",
					"hoverassault",
                    "hoverheavyraid",
					"hoverarty",
					"energygeo",
					"energywind",
				},
				startUnits = {
					{
						name = "staticheavyradar",
						x = 7600,
						z = 300,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 7992,
						z = 376,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 7768,
						z = 184,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 6008,
						z = 648,
						facing = 1,
					},
 					{
						name = "staticmex",
						x = 6856,
						z = 1112,
						facing = 1,
					},
 					{
						name = "staticmex",
						x = 7624,
						z = 1976,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 7672,
						z = 2024,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 7688,
						z = 1928,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 7576,
						z = 1928,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 7544,
						z = 2008,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 6904,
						z = 1160,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 6920,
						z = 1080,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 6824,
						z = 1048,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 6792,
						z = 1144,
						facing = 1,
					},
 					{
						name = "energysolar",
						x = 6088,
						z = 680,
						facing = 1,
					},
 					{
						name = "energysolar",
						x = 6008,
						z = 552,
						facing = 1,
					},
 					{
						name = "energysolar",
						x = 5896,
						z = 648,
						facing = 1,
					},
 					{
						name = "staticstorage",
						x = 8024,
						z = 184,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 7800,
						z = 264,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 7896,
						z = 328,
						facing = 1,
					},
 					{
						name = "factoryhover",
						x = 7040,
						z = 816,
						facing = 0,
					},
 					{
						name = "staticcon",
						x = 6888,
						z = 776,
						facing = 0,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {6888, 776}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {6863, 801}, options = {"shift"}},
						},
					},
 					{
						name = "hoverarty",
						x = 7292,
						z = 1124,
						facing = 0,
					},
 					{
						name = "hoverarty",
						x = 7183,
						z = 1111,
						facing = 0,
					},
 					{
						name = "hoverassault",
						x = 7135,
						z = 1324,
						facing = 0,
					},
 					{
						name = "hoverassault",
						x = 7212,
						z = 1348,
						facing = 0,
					},
 					{
						name = "hoverassault",
						x = 7284,
						z = 1345,
						facing = 0,
					},
 					{
						name = "hoverassault",
						x = 7357,
						z = 1347,
						facing = 0,
					},
 					{
						name = "hoverassault",
						x = 7064,
						z = 1332,
						facing = 0,
					},
				}
			},
			aiConfig = {
				{
					--aiLib = "Null AI",
					--bitDependant = false,
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					humanName = "Damara",
					commanderParameters = {
						facplop = false,
					},
					allyTeam = 1,
					unlocks = { -- no radar is deliberate
						"staticmex",
						"energysolar",
						"energywind",
						"staticcon",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretaaclose",
						"turretriot",
						"turretheavylaser",
						"turretemp",
						"striderhub",
						"striderdante",
						"factoryshield",
						"shieldcon",
						"shieldraid",
						"shieldriot",
						"shieldskirm",
						"shieldassault",
						"shieldarty",
						"shieldfelon",
						"shieldaa",
						"factorytank",
						"tankcon",
						"tankriot",
						"tankassault",
						--"tankheavyassault",
						"factoryspider",
						"spidercon",
						"spiderscout",
						"spideremp",
						"spiderskirm",
						"spiderassault",
						"spidercrabe",
						"spideraa",
						"staticantinuke",
					},
					difficultyDependantUnlocks = {
						[2] = {"spiderantiheavy"},
						[3] = {"spiderantiheavy","shieldshield"},
						[4] = {"spiderantiheavy","shieldshield","striderscorpion"}
					},
					commander = false,
					startUnits = {
						{
							name = "turretheavylaser",
							x = 410,
							z = 7910,
							facing = 2,
							difficultyAtLeast = 4,
						},
						{
							name = "staticantinuke",
							x = 1110,
							z = 1990,
							facing = 2,
						},
						{
							name = "turretaafar",
							x = 3470,
							z = 2500,
							facing = 0,
						},
						{
							name = "staticstorage",
							x = 488,
							z = 488,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2008,
							z = 1608,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1880,
							z = 1176,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2392,
							z = 872,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2072,
							z = 488,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1336,
							z = 2136,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1000,
							z = 1128,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 296,
							z = 920,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 568,
							z = 2936,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 280,
							z = 3416,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 840,
							z = 3384,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 32,
							z = 40,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 520,
							z = 456,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 1008,
							z = 40,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 1512,
							z = 456,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 504,
							z = 1448,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 520,
							z = 2440,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 1480,
							z = 1448,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 2184,
							z = 1176,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 376,
							z = 3336,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 2136,
							z = 504,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 2056,
							z = 552,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 968,
							z = 3064,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 2008,
							z = 472,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 2088,
							z = 424,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 1496,
							z = 2376,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 128,
							z = 1960,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 112,
							z = 952,
							facing = 1,
						},
 						{
							name = "turretantiheavy",
							x = 1392,
							z = 1600,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2616,
							z = 1320,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 2664,
							z = 1224,
							facing = 1,
						},
 						{
							name = "staticshield",
							x = 2448,
							z = 1232,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 2600,
							z = 1432,
							facing = 0,
						},
 						{
							name = "turretemp",
							x = 1584,
							z = 2544,
							facing = 0,
						},
 						{
							name = "turretemp",
							x = 1888,
							z = 2352,
							facing = 0,
						},
 						{
							name = "turretemp",
							x = 2224,
							z = 2240,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 2384,
							z = 1968,
							facing = 1,
						},
 						{
							name = "staticshield",
							x = 2112,
							z = 2000,
							facing = 1,
						},
 						{
							name = "staticshield",
							x = 1632,
							z = 2272,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 2312,
							z = 2088,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 2056,
							z = 2248,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 1704,
							z = 2408,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 1304,
							z = 3224,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 488,
							z = 3576,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 824,
							z = 3224,
							facing = 0,
						},
 						{
							name = "factoryshield",
							x = 728,
							z = 2560,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 584,
							z = 2568,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {609, 2593}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {584, 2568}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 584,
							z = 2648,
							facing = 1,
						},
 						{
							name = "factorytank",
							x = 1040,
							z = 1552,
							facing = 1,
						},
 						{
							name = "striderhub",
							x = 1040,
							z = 1696,
							facing = 1,
						},
 						{
							name = "factoryspider",
							x = 1800,
							z = 856,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1768,
							z = 744,
							facing = 0,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1768, 744}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1793, 769}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 1832,
							z = 744,
							facing = 0,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1832, 744}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1857, 769}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 888,
							z = 1528,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 888,
							z = 1592,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 64,
							z = 7632,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 496,
							z = 8048,
							facing = 1,
						},
 						{
							name = "turretaaheavy",
							x = 48,
							z = 7840,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 216,
							z = 7736,
							facing = 2,
						},
 						{
							name = "turretaalaser",
							x = 520,
							z = 8152,
							facing = 1,
						},
 						{
							name = "turrettorp",
							x = 1368,
							z = 7704,
							facing = 1,
						},
 						{
							name = "turrettorp",
							x = 2584,
							z = 7720,
							facing = 1,
						},
 						{
							name = "turrettorp",
							x = 2104,
							z = 6776,
							facing = 1,
						},
 						{
							name = "turrettorp",
							x = 456,
							z = 6824,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 376,
							z = 5752,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 1160,
							z = 6216,
							facing = 2,
						},
 						{
							name = "turretaaflak",
							x = 2344,
							z = 1304,
							facing = 1,
						},
 						{
							name = "turretaafar",
							x = 448,
							z = 2000,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 536,
							z = 3192,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 1368,
							z = 6888,
							facing = 2,
						},
 						{
							name = "turretaafar",
							x = 1184,
							z = 704,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 1440,
							z = 3088,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 2528,
							z = 1392,
							facing = 2,
						},
 						{
							name = "tankassault",
							x = 1896,
							z = 2711,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3256,
							z = 3576,
							facing = 0,
						},
 						{
							name = "striderdante",
							x = 5396,
							z = 3001,
							facing = 3,
						},
 						{
							name = "spiderskirm",
							x = 4932,
							z = 3041,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 560,
							z = 2352,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 1000,
							z = 1064,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 984,
							z = 1176,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 944,
							z = 976,
							facing = 1,
						},
 						{
							name = "shieldassault",
							x = 2963,
							z = 4478,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 3393,
							z = 3269,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 3776,
							z = 1632,
							facing = 0,
						},
 						{
							name = "spiderantiheavy",
							x = 2997,
							z = 4458,
							facing = 0,
						},
 						{
							name = "tankcon",
							x = 5112,
							z = 2701,
							facing = 0,
						},
 						{
							name = "shieldshield",
							x = 778,
							z = 2497,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 1376,
							z = 2240,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 784,
							z = 2336,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1952,
							z = 1488,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 3888,
							z = 1456,
							facing = 0,
						},
 						{
							name = "shieldcon",
							x = 2168,
							z = 4095,
							facing = 0,
						},
 						{
							name = "shieldraid",
							x = 2079,
							z = 1307,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 1944,
							z = 4264,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 368,
							z = 3056,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 672,
							z = 3040,
							facing = 1,
						},
 						{
							name = "shieldskirm",
							x = 2293,
							z = 2591,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 448,
							z = 2560,
							facing = 1,
						},
 						{
							name = "tankcon",
							x = 4084,
							z = 4064,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 3176,
							z = 2872,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2088,
							z = 4120,
							facing = 0,
						},
 						{
							name = "shieldskirm",
							x = 2954,
							z = 4577,
							facing = 1,
						},
 						{
							name = "tankcon",
							x = 2737,
							z = 3163,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 4096,
							z = 1456,
							facing = 0,
						},
 						{
							name = "striderdante",
							x = 1705,
							z = 2568,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 2000,
							z = 4064,
							facing = 1,
						},
 						{
							name = "staticstorage",
							x = 1448,
							z = 2040,
							facing = 1,
						},
 						{
							name = "spiderskirm",
							x = 5502,
							z = 3170,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 5031,
							z = 2783,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 2512,
							z = 784,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 2736,
							z = 2928,
							facing = 1,
						},
 						{
							name = "tankassault",
							x = 2963,
							z = 4657,
							facing = 1,
						},
 						{
							name = "shieldraid",
							x = 3714,
							z = 3606,
							facing = 1,
						},
 						{
							name = "tankassault",
							x = 3020,
							z = 4641,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 704,
							z = 2800,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 2208,
							z = 4000,
							facing = 1,
						},
 						{
							name = "staticstorage",
							x = 1224,
							z = 2232,
							facing = 1,
						},
 						{
							name = "shieldraid",
							x = 3636,
							z = 3756,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 5000,
							z = 2696,
							facing = 0,
							terraformHeight = 39,
						},
 						{
							name = "tankassault",
							x = 3022,
							z = 4503,
							facing = 1,
						},
 						{
							name = "tankcon",
							x = 5336,
							z = 3169,
							facing = 1,
						},
 						{
							name = "shieldshield",
							x = 4852,
							z = 3188,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 3960,
							z = 1560,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 3312,
							z = 3632,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 3984,
							z = 1648,
							facing = 0,
						},
 						{
							name = "striderscorpion",
							x = 2676,
							z = 4589,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 4424,
							z = 1656,
							facing = 0,
						},
 						{
							name = "spiderantiheavy",
							x = 3008,
							z = 4552,
							facing = 2,
						},
 						{
							name = "tankassault",
							x = 2395,
							z = 1561,
							facing = 0,
						},
 						{
							name = "tankassault",
							x = 6139,
							z = 3861,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 3784,
							z = 1272,
							facing = 0,
						},
 						{
							name = "shieldskirm",
							x = 5081,
							z = 3047,
							facing = 2,
						},
 						{
							name = "turretriot",
							x = 1864,
							z = 4216,
							facing = 1,
						},
 						{
							name = "spiderassault",
							x = 3002,
							z = 4378,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 2144,
							z = 4208,
							facing = 1,
						},
 						{
							name = "spidercrabe",
							x = 5089,
							z = 3120,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 3912,
							z = 1240,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 2733,
							z = 2875,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 2632,
							z = 3256,
							facing = 0,
						},
 						{
							name = "spiderassault",
							x = 4990,
							z = 2989,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 5208,
							z = 2424,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 3896,
							z = 3688,
							facing = 0,
						},
 						{
							name = "spiderassault",
							x = 5006,
							z = 3034,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 4328,
							z = 3352,
							facing = 0,
						},
 						{
							name = "spiderassault",
							x = 2321,
							z = 1510,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4552,
							z = 2040,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 4680,
							z = 2040,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 2111,
							z = 3125,
							facing = 0,
						},
 						{
							name = "spiderskirm",
							x = 2976,
							z = 4524,
							facing = 1,
						},
 						{
							name = "spiderantiheavy",
							x = 2045,
							z = 2516,
							facing = 0,
						},
 						{
							name = "tankcon",
							x = 2508,
							z = 3066,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 2656,
							z = 2807,
							facing = 1,
						},
 						{
							name = "shieldshield",
							x = 2928,
							z = 4473,
							facing = 0,
						},
 						{
							name = "shieldraid",
							x = 3168,
							z = 4717,
							facing = 0,
						},
 						{
							name = "spiderassault",
							x = 3037,
							z = 2005,
							facing = 0,
						},
 						{
							name = "tankassault",
							x = 1310,
							z = 1762,
							facing = 0,
						},
 						{
							name = "striderhub",
							x = 1920,
							z = 2624,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 5128,
							z = 2856,
							facing = 0,
							buildProgress = 0.8118,
						},
 						{
							name = "spiderassault",
							x = 3031,
							z = 1935,
							facing = 0,
						},
 						{
							name = "tankassault",
							x = 1064,
							z = 1552,
							facing = 1,
							buildProgress = 0.1815,
						},
 						{
							name = "shieldraid",
							x = 789,
							z = 2562,
							facing = 1,
						},
 						{
							name = "shieldraid",
							x = 740,
							z = 2560,
							facing = 1,
							buildProgress = 0.0711,
						},
					}
				},
				{
					--aiLib = "Null AI",
					--bitDependant = false,
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					humanName = "Chukini",
					commanderParameters = {
						facplop = false,
					},
					allyTeam = 2,
					unlocks = { -- no radar is deliberate
						"staticmex",
						"energysolar",
						"energywind",
						"staticcon",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretaaclose",
						"turretriot",
						"turretheavylaser",
						"turretemp",
						"striderhub",
						"striderdante",
						"factoryshield",
						"shieldcon",
						"shieldraid",
						"shieldriot",
						"shieldskirm",
						"shieldassault",
						"shieldarty",
						"shieldfelon",
						"shieldaa",
						"factoryjump",
						"jumpcon",
						"jumparty",
						"jumpblackhole",
						"jumpbomb",
						"jumpsumo",
						"jumpaa",
						"factorytank",
						"tankcon",
						"tankriot",
						"tankassault",
						"staticantinuke",
						--"tankheavyassault",
					},
					difficultyDependantUnlocks = {
						[2] = {"jumpassault"},
						[3] = {"jumpassault","shieldshield"},
						[4] = {"jumpassault","shieldshield","striderscorpion"}
					},
					commander = false,
					startUnits = {
						{
							{
								name = "staticantinuke",
								x = 7500,
								z = 7100,
								facing = 2,
							},
							name = "turretaafar",
							x = 5050,
							z = 6100,
							facing = 2,
						},
						{
							name = "turretaafar",
							x = 4390,
							z = 5350,
							facing = 2,
						},
						{
							name = "turretheavyassault",
							x = 4880,
							z = 5600,
							facing = 2,
						},
						{
							name = "staticstorage",
							x = 7896,
							z = 7896,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7192,
							z = 6552,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6984,
							z = 7128,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6152,
							z = 6728,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6056,
							z = 7464,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7736,
							z = 7752,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7928,
							z = 5656,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7512,
							z = 5432,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7928,
							z = 4984,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6392,
							z = 7992,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 8160,
							z = 8152,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 5672,
							z = 7752,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 6056,
							z = 7048,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 8160,
							z = 6888,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 5528,
							z = 7016,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 8160,
							z = 5784,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 7088,
							z = 8152,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 7624,
							z = 7800,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 7640,
							z = 6824,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 6760,
							z = 7608,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 7720,
							z = 5864,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 6696,
							z = 6632,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 5960,
							z = 7128,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 7912,
							z = 5112,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 7224,
							z = 5704,
							facing = 1,
						},
 						{
							name = "turretheavy",
							x = 5528,
							z = 6904,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 7064,
							z = 5320,
							facing = 2,
						},
 						{
							name = "turretheavy",
							x = 6776,
							z = 7048,
							facing = 2,
						},
 						{
							name = "turretriot",
							x = 6952,
							z = 5784,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 6856,
							z = 6200,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 5432,
							z = 6968,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 5912,
							z = 6808,
							facing = 2,
						},
 						{
							name = "factoryjump",
							x = 6360,
							z = 7320,
							facing = 2,
						},
 						{
							name = "factorytank",
							x = 7392,
							z = 6800,
							facing = 3,
						},
 						{
							name = "striderhub",
							x = 7392,
							z = 6592,
							facing = 3,
						},
 						{
							name = "factoryshield",
							x = 7656,
							z = 5680,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7512,
							z = 6760,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7512,
							z = 6840,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7784,
							z = 5656,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7784,
							z = 5752,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 6328,
							z = 7448,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 6408,
							z = 7448,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 5608,
							z = 7432,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 5064,
							z = 8008,
							facing = 3,
						},
 						{
							name = "staticshield",
							x = 7088,
							z = 5616,
							facing = 0,
						},
 						{
							name = "staticshield",
							x = 5584,
							z = 7104,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 6216,
							z = 6584,
							facing = 3,
						},
 						{
							name = "turretgauss",
							x = 6280,
							z = 6408,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 6424,
							z = 6312,
							facing = 2,
						},
 						{
							name = "staticshield",
							x = 6432,
							z = 6544,
							facing = 2,
						},
 						{
							name = "turretaalaser",
							x = 7832,
							z = 5304,
							facing = 2,
						},
 						{
							name = "turretaafar",
							x = 7600,
							z = 6400,
							facing = 3,
						},
 						{
							name = "turretaafar",
							x = 6720,
							z = 7424,
							facing = 2,
						},
 						{
							name = "turretaaflak",
							x = 5608,
							z = 7000,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 5648,
							z = 6880,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 6848,
							z = 5536,
							facing = 2,
						},
 						{
							name = "jumpassault",
							x = 5401,
							z = 4030,
							facing = 0,
						},
 						{
							name = "tankassault",
							x = 6261,
							z = 5170,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 6352,
							z = 7600,
							facing = 2,
						},
 						{
							name = "turretmissile",
							x = 6400,
							z = 4864,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 3880,
							z = 5000,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 7576,
							z = 5464,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7560,
							z = 5352,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7464,
							z = 5512,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 6192,
							z = 5168,
							facing = 3,
						},
 						{
							name = "tankassault",
							x = 4965,
							z = 5531,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 7192,
							z = 6600,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 6128,
							z = 7296,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 7024,
							z = 6944,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 3104,
							z = 5760,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 8048,
							z = 5328,
							facing = 3,
						},
 						{
							name = "tankcon",
							x = 2842,
							z = 5582,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 5872,
							z = 7552,
							facing = 2,
						},
 						{
							name = "turretheavylaser",
							x = 6200,
							z = 4744,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 7696,
							z = 7760,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 6208,
							z = 4960,
							facing = 3,
						},
 						{
							name = "jumpcon",
							x = 5173,
							z = 4596,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 5824,
							z = 7008,
							facing = 2,
						},
 						{
							name = "tankcon",
							x = 6029,
							z = 5418,
							facing = 3,
						},
 						{
							name = "jumpassault",
							x = 6360,
							z = 7296,
							facing = 2,
							buildProgress = 0.7877,
						},
 						{
							name = "tankcon",
							x = 5519,
							z = 4014,
							facing = 1,
						},
 						{
							name = "jumparty",
							x = 4712,
							z = 4502,
							facing = 3,
						},
 						{
							name = "jumpcon",
							x = 2539,
							z = 5279,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6008,
							z = 5224,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5336,
							z = 5736,
							facing = 0,
						},
 						{
							name = "jumpassault",
							x = 5428,
							z = 3710,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 4392,
							z = 7048,
							facing = 0,
						},
 						{
							name = "shieldassault",
							x = 6224,
							z = 5047,
							facing = 0,
						},
 						{
							name = "jumpcon",
							x = 5563,
							z = 4012,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 5456,
							z = 5776,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 6016,
							z = 4848,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 2440,
							z = 5224,
							facing = 0,
							buildProgress = 0.6577,
						},
 						{
							name = "turretlaser",
							x = 4400,
							z = 7104,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 5112,
							z = 4888,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 5120,
							z = 4928,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 4272,
							z = 5152,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 3632,
							z = 6720,
							facing = 2,
						},
 						{
							name = "staticstorage",
							x = 7112,
							z = 6664,
							facing = 3,
						},
 						{
							name = "jumpcon",
							x = 2621,
							z = 5488,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 6352,
							z = 7088,
							facing = 2,
						},
 						{
							name = "shieldskirm",
							x = 5468,
							z = 4519,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3720,
							z = 6616,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 3872,
							z = 5264,
							facing = 2,
						},
 						{
							name = "shieldshield",
							x = 6600,
							z = 4686,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2904,
							z = 5784,
							facing = 0,
							terraformHeight = 41,
						},
 						{
							name = "staticmex",
							x = 4200,
							z = 5176,
							facing = 0,
						},
 						{
							name = "jumpassault",
							x = 6459,
							z = 4398,
							facing = 2,
						},
 						{
							name = "turretmissile",
							x = 4064,
							z = 5152,
							facing = 2,
						},
 						{
							name = "tankassault",
							x = 5451,
							z = 3644,
							facing = 1,
						},
 						{
							name = "shieldarty",
							x = 5421,
							z = 3736,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 4272,
							z = 5360,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 6144,
							z = 7504,
							facing = 2,
						},
 						{
							name = "shieldshield",
							x = 7644,
							z = 5680,
							facing = 3,
							buildProgress = 0.6911,
						},
 						{
							name = "jumpcon",
							x = 4095,
							z = 4557,
							facing = 3,
						},
 						{
							name = "shieldshield",
							x = 6591,
							z = 4710,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 4056,
							z = 5368,
							facing = 2,
						},
 						{
							name = "jumpassault",
							x = 5817,
							z = 4930,
							facing = 1,
						},
 						{
							name = "striderdante",
							x = 5743,
							z = 3984,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 5824,
							z = 4976,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6040,
							z = 4552,
							facing = 0,
						},
 						{
							name = "tankcon",
							x = 5296,
							z = 4780,
							facing = 2,
						},
 						{
							name = "turretmissile",
							x = 6016,
							z = 5056,
							facing = 3,
						},
 						{
							name = "shieldriot",
							x = 4489,
							z = 4197,
							facing = 2,
						},
 						{
							name = "shieldraid",
							x = 3504,
							z = 6182,
							facing = 0,
							patrolRoute = {
								{3512, 6126},
								{3506, 6190},
							},
						},
 						{
							name = "turretriot",
							x = 4456,
							z = 5240,
							facing = 2,
						},
 						{
							name = "striderscorpion",
							x = 4806,
							z = 5133,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 4144,
							z = 4960,
							facing = 2,
						},
 						{
							name = "jumparty",
							x = 5732,
							z = 6557,
							facing = 3,
						},
 						{
							name = "tankassault",
							x = 7111,
							z = 5846,
							facing = 1,
						},
 						{
							name = "striderhub",
							x = 6912,
							z = 5056,
							facing = 3,
						},
 						{
							name = "jumpcon",
							x = 4708,
							z = 4681,
							facing = 0,
						},
 						{
							name = "jumpcon",
							x = 4324,
							z = 5687,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 5816,
							z = 4760,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 2912,
							z = 5664,
							facing = 2,
						},
 						{
							name = "shieldraid",
							x = 3556,
							z = 6167,
							facing = 2,
							patrolRoute = {
								{3546, 6180},
								{3509, 6126},
							},
						},
 						{
							name = "striderdante",
							x = 7296,
							z = 6592,
							facing = 0,
							buildProgress = 0.5729,
						},
 						{
							name = "jumpcon",
							x = 3906,
							z = 4641,
							facing = 2,
						},
 						{
							name = "shieldcon",
							x = 5252,
							z = 4578,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5344, 4688}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5227, 4567}, options = {"shift"}},
							},
						},
 						{
							name = "tankcon",
							x = 5528,
							z = 4056,
							facing = 1,
						},
 						{
							name = "tankheavyassault",
							x = 7368,
							z = 6800,
							facing = 3,
							buildProgress = 0.0584,
						},
 						{
							name = "turretheavylaser",
							x = 2696,
							z = 5576,
							facing = 2,
							buildProgress = 0.37,
						},
					}
				},
			},
			neutralUnits = {
				{
					name = "pw_artefact",
					x = 144,
					z = 8080,
					facing = 0,
					invincible = true,
					ignoredByAI = true,
					mapMarker = {
						text = "Artefact",
						color = "green"
					},
				},
			},
			terraform = {
				 {
					 terraformShape = planetUtilities.TERRAFORM_SHAPE.RAMP,
					 position = {7800, 195, 500, 7500,-90, 1150},
					 width = 200
				 },
				 {
					 terraformShape = planetUtilities.TERRAFORM_SHAPE.RAMP,
					 position = {350, 195, 7800, 800, -90, 7000},
					 width = 200
				 },
			},
			defeatConditionConfig = {
				[0] = { },
				[1] = {
					ignoreUnitLossDefeat = true,
					loseAfterSeconds = false,
				},
				[2] = {
					ignoreUnitLossDefeat = true,
					loseAfterSeconds = false,
				},
			},
			objectiveConfig = {
				[1] = {
					description = "Bring your Commander to the Artefact",
				},
				[2] = {
					description = "Protect your Commander",
				},
			},
			bonusObjectiveConfig = {
				[1] = { -- Build five Lances
					satisfyOnce = true,
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 5,
					unitTypes = {
						"hoverarty",
					},
					image = planetUtilities.ICON_DIR .. "hoverarty.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.REPAIR,
					description = "Have 5 Lances",
					experience = planetUtilities.BONUS_EXP,
				},
				[2] = {
					victoryByTime = 1200,
					image = planetUtilities.ICON_OVERLAY.CLOCK,
					description = "Win by 20:00",
					experience = planetUtilities.BONUS_EXP,
				},
				[3] = { -- Build a geo
					satisfyOnce = true,
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 1,
					unitTypes = {
						"energygeo",
					},
					image = planetUtilities.ICON_DIR .. "energygeo.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.REPAIR,
					description = "Build a Geothermal Generator",
					experience = planetUtilities.BONUS_EXP,
				},
			}
		},
		completionReward = {
			experience = planetUtilities.MAIN_EXP,
			units = {
				"hoverassault",
				"hoverarty",
			},
			modules = {
				"module_adv_targeting_LIMIT_B_2",
			},
			abilities = {
			},
			codexEntries = {
				"faction_lawless",
				"anomaly_lovaza_jira",
			}
		},
	}
	
	return planetData
end

return GetPlanet
