--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Planet config

local function GetPlanet(planetUtilities, planetID)
	
	local image = LUA_DIRNAME .. "images/planets/terran04.png"
	
	local planetData = {
		name = "Rockbar",
		startingPlanet = false,
		mapDisplay = {
			x = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][1]) or 0.77,
			y = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][2]) or 0.78,
			image = image,
			size = planetUtilities.PLANET_SIZE_MAP,
		},
		infoDisplay = {
			image = image,
			size = planetUtilities.PLANET_SIZE_INFO,
			backgroundImage = planetUtilities.backgroundImages[math.floor(math.random()*#planetUtilities.backgroundImages) + 1],
			terrainType = "Coastal",
			radius = "6060 km",
			primary = "Eox Tallis",
			primaryType = "G4V",
			milRating = 1,
			feedbackLink = "http://zero-k.info/Forum/Thread/24594",
			text = "A major naval exercise was just starting down there, when it all stopped. No preparations, no warning, complete surprise... This has to be one of the first places where everyone disappeared."
			.. "\n "
			.. "\nWell, both sides are evenly matched - when I go down, the side I join should win pretty easily, right?"
			,
			extendedText = "This was evenly matched, but the Detriment the other side is about to deploy could change that in a hurry. If this is some kind of automated balance system, well, it's rather flattering."
		},
		tips = {
			{
				image = "unitpics/shipcarrier.png",
				text = [[The Reef is a versatile carrier ship which deploys drones, constructs disarming cruise missiles and rearms friendly bombers. The disarming missiles are especially effective against heavy targets like the Shogun battleship or Detriment strider.]]
			},
			{
				image = "unitpics/subtacmissile.png",
				text = [[The Scylla constructs and fires tactical missiles. Use these to destroy static targets which are elevated or far away. Remember that destroying Pylon connections will disable heavy defenses.]]
			},
			{
				image = "unitpics/weaponmod_standoff_rocket.png",
				text = [[The Scylla and Reef must stockpile missiles before firing them, which requires resources. Select stockpiling units and left or right-click the Stockpile button to increase or decrease the maximum stockpile number. Ctrl and Shift to add or subtract multiples from the stockpile.]]
			},
		},
		gameConfig = {
			mapName = "SailAway",
			playerConfig = {
				startX = 2520,
				startZ = 9400,
				allyTeam = 0,
				commanderParameters = {
					facplop = true,
					defeatIfDestroyedObjectiveID = 2,
				},
				extraUnlocks = {
					"striderhub",
					"subtacmissile",
					"shipcarrier",
				},
				startUnits = {
					{
						name = "staticantinuke",
						x = 1280,
						z = 8140,
						facing = 1,
					},
					{
						name = "striderhub",
						x = 2096,
						z = 9328,
						facing = 2,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {2096, 9328}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {2121, 9303}, options = {"shift"}},
						},
					},
					-- flotilla
					{
						name = "shipaa",
						x = 1800,
						z = 8900,
						facing = 2,
					},
					{
						name = "shipcarrier",
						x = 1900,
						z = 8900,
						facing = 2,
					},
					{
						name = "shipcarrier",
						x = 2100,
						z = 8900,
						facing = 2,
					},
					{
						name = "shipcarrier",
						x = 2300,
						z = 8900,
						facing = 2,
					},
					{
						name = "shipaa",
						x = 2400,
						z = 8900,
						facing = 2,
					},
					{
						name = "shipassault",
						x = 1800,
						z = 8700,
						facing = 2,
					},
					{
						name = "shiparty",
						x = 1900,
						z = 8630,
						facing = 2,
					},
					{
						name = "shipassault",
						x = 2100,
						z = 8630,
						facing = 2,
					},
					{
						name = "shiparty",
						x = 2300,
						z = 8630,
						facing = 2,
					},
					{
						name = "shipassault",
						x = 2400,
						z = 8700,
						facing = 2,
					},
					{
						name = "subtacmissile",
						x = 2600,
						z = 9300,
						facing = 2,
					},
					{
						name = "subraider",
						x = 2650,
						z = 9150,
						facing = 2,
					},
					{
						name = "subraider",
						x = 2550,
						z = 9150,
						facing = 2,
					},
					{
						name = "subraider",
						x = 2700,
						z = 9200,
						facing = 2,
					},
					{
						name = "subraider",
						x = 2500,
						z = 9200,
						facing = 2,
					},
					--
 					{
						name = "staticmex",
						x = 1448,
						z = 9464,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 3416,
						z = 9880,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 1336,
						z = 9656,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 3288,
						z = 10152,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 3752,
						z = 10104,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 824,
						z = 9976,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 3848,
						z = 9880,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 328,
						z = 10120,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 152,
						z = 9992,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 2632,
						z = 10072,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 776,
						z = 9304,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2264,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energypylon",
						x = 632,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1144,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1224,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1304,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1384,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1464,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1544,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1624,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1704,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1784,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1864,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1944,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2024,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2104,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2184,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2344,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2424,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2504,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2584,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2664,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2744,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2824,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2904,
						z = 10216,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2904,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2824,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2744,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2664,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2584,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2504,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2424,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2344,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2264,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2184,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2104,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2024,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1944,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1864,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1784,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1704,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1624,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1544,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1464,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1384,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energypylon",
						x = 3432,
						z = 10040,
						facing = 2,
					},
 					{
						name = "energywind",
						x = 1304,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1224,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1144,
						z = 10136,
						facing = 0,
					},
 					{
						name = "energypylon",
						x = 4232,
						z = 9992,
						facing = 2,
					},
 					{
						name = "energywind",
						x = 1144,
						z = 10056,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1224,
						z = 10056,
						facing = 0,
					},
 					{
						name = "factoryship",
						x = 1952,
						z = 9408,
						facing = 2,
					},
 					{
						name = "energywind",
						x = 1304,
						z = 10056,
						facing = 0,
					},
 					{
						name = "turretaafar",
						x = 1728,
						z = 9408,
						facing = 2,
					},
 					{
						name = "energywind",
						x = 1384,
						z = 10056,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1464,
						z = 10056,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1544,
						z = 10056,
						facing = 0,
					},
 					{
						name = "staticcon",
						x = 2088,
						z = 9416,
						facing = 2,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {2088, 9416}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {2113, 9391}, options = {"shift"}},
						},
					},
 					{
						name = "energywind",
						x = 1624,
						z = 10056,
						facing = 0,
					},
 					{
						name = "staticcon",
						x = 2168,
						z = 9416,
						facing = 2,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {2168, 9416}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {2193, 9391}, options = {"shift"}},
						},
					},
 					{
						name = "energywind",
						x = 1704,
						z = 10056,
						facing = 0,
					},
 					{
						name = "staticcon",
						x = 2168,
						z = 9496,
						facing = 2,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {2168, 9496}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {2193, 9471}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 2088,
						z = 9496,
						facing = 2,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {2088, 9496}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {2113, 9471}, options = {"shift"}},
						},
					},
 					{
						name = "energywind",
						x = 1784,
						z = 10056,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1864,
						z = 10056,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1944,
						z = 10056,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2024,
						z = 10056,
						facing = 0,
					},
 					{
						name = "staticcon",
						x = 2088,
						z = 9576,
						facing = 2,
					},
 					{
						name = "energywind",
						x = 2104,
						z = 10056,
						facing = 0,
					},
 					{
						name = "staticcon",
						x = 2168,
						z = 9576,
						facing = 2,
					},
 					{
						name = "energywind",
						x = 2184,
						z = 10056,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2264,
						z = 10056,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2344,
						z = 10056,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2424,
						z = 10056,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2504,
						z = 10056,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2584,
						z = 10056,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2744,
						z = 10056,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2824,
						z = 10056,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2904,
						z = 10056,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2904,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2824,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2744,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2664,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2584,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2504,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2424,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2344,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2264,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2184,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2104,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2024,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1944,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1864,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1784,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1704,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1624,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1544,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1464,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1384,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1304,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1224,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1144,
						z = 9976,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1144,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1224,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1304,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1384,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1464,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1544,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1624,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1704,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1784,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1864,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1944,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2024,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2104,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2184,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2264,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2344,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2424,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2504,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2584,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2664,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2744,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2824,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2904,
						z = 9896,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2904,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2824,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2744,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2664,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2584,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2504,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2424,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2344,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2264,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2184,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2104,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 2024,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1944,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1864,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1784,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1704,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1624,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1544,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1464,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1384,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1304,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1224,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1144,
						z = 9816,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1144,
						z = 9736,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1224,
						z = 9736,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1304,
						z = 9736,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1384,
						z = 9736,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1464,
						z = 9736,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1544,
						z = 9736,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1544,
						z = 9656,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1464,
						z = 9656,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1384,
						z = 9656,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1224,
						z = 9656,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1144,
						z = 9656,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1144,
						z = 9576,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1224,
						z = 9576,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1304,
						z = 9576,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1384,
						z = 9576,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1464,
						z = 9576,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1544,
						z = 9576,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1544,
						z = 9496,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1384,
						z = 9496,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1304,
						z = 9496,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1224,
						z = 9496,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1144,
						z = 9496,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1144,
						z = 9416,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1224,
						z = 9416,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1304,
						z = 9416,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1384,
						z = 9416,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1464,
						z = 9416,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 1544,
						z = 9416,
						facing = 0,
					},
 					{
						name = "turrettorp",
						x = 2392,
						z = 9672,
						facing = 2,
					},
 					{
						name = "turrettorp",
						x = 2600,
						z = 9672,
						facing = 2,
					},
 					{
						name = "turrettorp",
						x = 1144,
						z = 9288,
						facing = 2,
					},
 					{
						name = "turrettorp",
						x = 1336,
						z = 9288,
						facing = 2,
					},
 					{
						name = "turrettorp",
						x = 2808,
						z = 9672,
						facing = 2,
					},
 					{
						name = "turrettorp",
						x = 1528,
						z = 9288,
						facing = 2,
					},
 					{
						name = "turrettorp",
						x = 3000,
						z = 9672,
						facing = 2,
					},
				}
			},
			aiConfig = {
				{
					humanName = "Uba Rassa",
					aiLib = "Circuit_difficulty_autofill_ally",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					allyTeam = 0,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energypylon",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turrettorp",
						"turretgauss",
						"turretaalaser",
						"turretaaclose",
						"staticradar",
						"staticcon",
						"staticantinuke",
						"staticrearm",
						"factoryplane",
						"planecon",
						"planescout",
						"planefighter",
						"planeheavyfighter",
						"bomberprec",
						"bomberdisarm",
						"bomberheavy",
						"factoryship",
						"shipcon",
						"shipaa",
						"shiparty",
						"shipassault",
						"shipriot",
						"shipscout",
						"shipskirm",
						"shiptorpraider",
						"subraider",
						"factoryamph",
						"amphcon",
						"amphraid",
						"amphimpulse",
						"amphfloater",
						"amphriot",
						"amphassault",
						"amphbomb",
						"amphaa",
						"factoryhover",
						"hovercon",
						"hoverraid",
						"hoverriot",
						"hoverskirm",
						"hoverassault",
						"hoverdepthcharge",
                        "hoverheavyraid",
						"hoverarty",
						"hoveraa",
					},
					commander = false,
					startUnits = {
						{
							name = "staticantinuke",
							x = 3240,
							z = 6400,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 1544,
							z = 7032,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2584,
							z = 8120,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2408,
							z = 8040,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 968,
							z = 6856,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2328,
							z = 8312,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 856,
							z = 7160,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 648,
							z = 7608,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3208,
							z = 8824,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 360,
							z = 7480,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3432,
							z = 8616,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1016,
							z = 7864,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4120,
							z = 8456,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1416,
							z = 7864,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4360,
							z = 8728,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 184,
							z = 8280,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3832,
							z = 7720,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4600,
							z = 7992,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5032,
							z = 8248,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4920,
							z = 8808,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4136,
							z = 6152,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4296,
							z = 6600,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4472,
							z = 6360,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5000,
							z = 6328,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 1624,
							z = 9592,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 3432,
							z = 6328,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4792,
							z = 9688,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4936,
							z = 9816,
							facing = 0,
						},
 						{
							name = "energysingu",
							x = 4920,
							z = 10056,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 5048,
							z = 9944,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4968,
							z = 9944,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4888,
							z = 9944,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4808,
							z = 9944,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4728,
							z = 9944,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4648,
							z = 9944,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4648,
							z = 9864,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4728,
							z = 9864,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4808,
							z = 9864,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4888,
							z = 9864,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4968,
							z = 9864,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 5048,
							z = 9864,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 5048,
							z = 9784,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4888,
							z = 9784,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4808,
							z = 9784,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4728,
							z = 9784,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4648,
							z = 9784,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4648,
							z = 9704,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4728,
							z = 9704,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4888,
							z = 9704,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4968,
							z = 9704,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 5048,
							z = 9704,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 5048,
							z = 9624,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4520,
							z = 6744,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 4968,
							z = 9624,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4888,
							z = 9624,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4808,
							z = 9624,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4728,
							z = 9624,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4648,
							z = 9624,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4648,
							z = 9544,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4728,
							z = 9544,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4808,
							z = 9544,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4888,
							z = 9544,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4968,
							z = 9544,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 5048,
							z = 9544,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 5048,
							z = 9464,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4968,
							z = 9464,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4888,
							z = 9464,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4808,
							z = 9464,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4728,
							z = 9464,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4648,
							z = 9464,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4648,
							z = 9384,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4728,
							z = 9384,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4808,
							z = 9384,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4888,
							z = 9384,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 4968,
							z = 9384,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 5048,
							z = 9384,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 4168,
							z = 9512,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 4344,
							z = 9368,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 4520,
							z = 9224,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 4760,
							z = 8872,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 4520,
							z = 8152,
							facing = 2,
						},
 						{
							name = "factoryship",
							x = 3168,
							z = 8048,
							facing = 2,
						},
 						{
							name = "factoryhover",
							x = 3360,
							z = 8032,
							facing = 2,
						},
 						{
							name = "staticrearm",
							x = 4760,
							z = 7896,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 4216,
							z = 7368,
							facing = 2,
						},
 						{
							name = "factoryamph",
							x = 3000,
							z = 8040,
							facing = 2,
						},
 						{
							name = "factoryplane",
							x = 4928,
							z = 7880,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 2984,
							z = 8232,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 4888,
							z = 8040,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 3064,
							z = 8232,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 4984,
							z = 8040,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 3144,
							z = 8232,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3160, 8047}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3144, 8232}, options = {"shift"}},
							},
						},
 						{
							name = "energypylon",
							x = 4520,
							z = 6504,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 3224,
							z = 8232,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 3304,
							z = 8232,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 3384,
							z = 8232,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 3720,
							z = 5928,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 3064,
							z = 8312,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3359, 8064}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3064, 8312}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 3144,
							z = 8312,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 3224,
							z = 8312,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 3304,
							z = 8312,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3359, 8064}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3304, 8312}, options = {"shift"}},
							},
						},
 						{
							name = "energypylon",
							x = 648,
							z = 8904,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 264,
							z = 8040,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 776,
							z = 7208,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 1000,
							z = 8024,
							facing = 0,
						},
 						{
							name = "turretheavy",
							x = 1432,
							z = 8008,
							facing = 1,
						},
 						{
							name = "turretheavy",
							x = 1176,
							z = 7048,
							facing = 1,
						},
 						{
							name = "turretantiheavy",
							x = 3328,
							z = 5904,
							facing = 3,
						},
 						{
							name = "turretheavy",
							x = 824,
							z = 6792,
							facing = 2,
						},
 						{
							name = "turretaaflak",
							x = 3576,
							z = 5800,
							facing = 3,
						},
 						{
							name = "staticarty",
							x = 1080,
							z = 6824,
							facing = 2,
						},
 						{
							name = "turretaaflak",
							x = 3496,
							z = 6152,
							facing = 3,
						},
 						{
							name = "turretaaflak",
							x = 680,
							z = 7032,
							facing = 2,
						},
 						{
							name = "turretaaflak",
							x = 920,
							z = 7080,
							facing = 2,
						},
 						{
							name = "turretheavy",
							x = 4152,
							z = 6040,
							facing = 2,
						},
 						{
							name = "turretaaflak",
							x = 1096,
							z = 7288,
							facing = 2,
						},
 						{
							name = "turretheavy",
							x = 4664,
							z = 6264,
							facing = 2,
						},
 						{
							name = "turretriot",
							x = 4440,
							z = 6136,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 1960,
							z = 8216,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 2760,
							z = 8520,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 3352,
							z = 9048,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 3736,
							z = 8200,
							facing = 2,
						},
 						{
							name = "staticstorage",
							x = 3064,
							z = 8376,
							facing = 2,
						},
 						{
							name = "staticstorage",
							x = 3304,
							z = 8392,
							facing = 2,
						},
 						{
							name = "turretantiheavy",
							x = 4432,
							z = 7968,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 3400,
							z = 7432,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 3272,
							z = 7432,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 3144,
							z = 7432,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 1200,
							z = 7712,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 1736,
							z = 7528,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 1912,
							z = 7512,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 2072,
							z = 7512,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 2392,
							z = 6952,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 2536,
							z = 6952,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 2696,
							z = 6952,
							facing = 2,
						},
 						{
							name = "staticheavyradar",
							x = 944,
							z = 6736,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 4888,
							z = 8088,
							facing = 2,
						},
 						{
							name = "shipscout",
							x = 2046,
							z = 6704,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 880,
							z = 7296,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 1336,
							z = 7592,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 1384,
							z = 7672,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 2760,
							z = 6056,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 1248,
							z = 7920,
							facing = 2,
						},
 						{
							name = "hoverriot",
							x = 619,
							z = 6068,
							facing = 1,
						},
 						{
							name = "amphassault",
							x = 1456,
							z = 5715,
							facing = 1,
							patrolRoute = {
								{1423, 5729},
								{1481, 5702},
							},
						},
 						{
							name = "amphcon",
							x = 362,
							z = 6587,
							facing = 3,
						},
 						{
							name = "staticstorage",
							x = 4136,
							z = 8408,
							facing = 2,
						},
 						{
							name = "shipassault",
							x = 352,
							z = 6572,
							facing = 0,
							patrolRoute = {
								{337, 6552},
								{192, 6672},
							},
						},
 						{
							name = "amphcon",
							x = 3089,
							z = 5092,
							facing = 2,
						},
 						{
							name = "hovercon",
							x = 2023,
							z = 7726,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 2904,
							z = 8168,
							facing = 2,
						},
 						{
							name = "amphfloater",
							x = 1396,
							z = 5778,
							facing = 3,
							patrolRoute = {
								{1405, 5790},
								{1423, 5729},
							},
						},
 						{
							name = "hoverdepthcharge",
							x = 1080,
							z = 5973,
							facing = 1,
							patrolRoute = {
								{1144, 6152},
								{1265, 6027},
							},
						},
 						{
							name = "turretlaser",
							x = 3088,
							z = 7760,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 2126,
							z = 7118,
							facing = 3,
						},
 						{
							name = "hoverraid",
							x = 404,
							z = 5464,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 657,
							z = 6075,
							facing = 3,
						},
 						{
							name = "planecon",
							x = 536,
							z = 6122,
							facing = 1,
						},
 						{
							name = "shipaa",
							x = 2649,
							z = 6501,
							facing = 2,
						},
 						{
							name = "hoverdepthcharge",
							x = 1370,
							z = 5706,
							facing = 2,
							patrolRoute = {
								{1423, 5729},
								{1366, 5757},
							},
						},
 						{
							name = "shipskirm",
							x = 1813,
							z = 5887,
							facing = 0,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1447, 5670}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1423, 5729}, options = {"shift"}},
							},
						},
 						{
							name = "energywind",
							x = 3080,
							z = 9512,
							facing = 2,
						},
 						{
							name = "hoverarty",
							x = 3354,
							z = 8040,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 4936,
							z = 8024,
							facing = 2,
						},
 						{
							name = "hovercon",
							x = 631,
							z = 6283,
							facing = 0,
						},
 						{
							name = "hoverarty",
							x = 1320,
							z = 5705,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 3016,
							z = 9592,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 3880,
							z = 7816,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 2920,
							z = 9688,
							facing = 2,
						},
 						{
							name = "hovercon",
							x = 401,
							z = 6551,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 2968,
							z = 9752,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 4984,
							z = 8088,
							facing = 2,
						},
 						{
							name = "shipcon",
							x = 1863,
							z = 5757,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 2920,
							z = 9640,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 4256,
							z = 6560,
							facing = 3,
						},
 						{
							name = "hoverassault",
							x = 1555,
							z = 6223,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3576,
							z = 5592,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 4936,
							z = 8104,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 3000,
							z = 8184,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3160, 8047}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3000, 8184}, options = {"shift"}},
							},
						},
 						{
							name = "hoverassault",
							x = 1729,
							z = 6303,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 3904,
							z = 7936,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 3448,
							z = 8664,
							facing = 2,
						},
 						{
							name = "hoverarty",
							x = 1279,
							z = 5750,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 2936,
							z = 8216,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 2472,
							z = 8120,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 3680,
							z = 5984,
							facing = 3,
						},
 						{
							name = "turrettorp",
							x = 4808,
							z = 10024,
							facing = 2,
						},
 						{
							name = "amphfloater",
							x = 2898,
							z = 7412,
							facing = 2,
						},
 						{
							name = "turretriot",
							x = 3768,
							z = 5720,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 2952,
							z = 8168,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 4224,
							z = 8640,
							facing = 2,
						},
 						{
							name = "shipassault",
							x = 1393,
							z = 5752,
							facing = 1,
							patrolRoute = {
								{1360, 5738},
								{1423, 5729},
							},
						},
 						{
							name = "hovercon",
							x = 1167,
							z = 5994,
							facing = 3,
						},
 						{
							name = "hovercon",
							x = 548,
							z = 6274,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 2936,
							z = 8264,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3160, 8047}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {2936, 8264}, options = {"shift"}},
							},
						},
 						{
							name = "shipcon",
							x = 712,
							z = 6385,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 2984,
							z = 8280,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3160, 8047}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {2984, 8280}, options = {"shift"}},
							},
						},
 						{
							name = "hovercon",
							x = 1633,
							z = 7914,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 1672,
							z = 9016,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 3048,
							z = 8184,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 3184,
							z = 8320,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 400,
							z = 8016,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 2984,
							z = 10088,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 2533,
							z = 6885,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 1448,
							z = 6040,
							facing = 1,
							buildProgress = 0.1812,
						},
 						{
							name = "shipcon",
							x = 1579,
							z = 6297,
							facing = 2,
						},
 						{
							name = "hovercon",
							x = 1055,
							z = 6035,
							facing = 3,
						},
 						{
							name = "hoverraid",
							x = 180,
							z = 5157,
							facing = 2,
						},
 						{
							name = "shiparty",
							x = 1728,
							z = 5877,
							facing = 2,
						},
 						{
							name = "hovercon",
							x = 3874,
							z = 10087,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 3648,
							z = 9760,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 2888,
							z = 8216,
							facing = 2,
						},
 						{
							name = "shipassault",
							x = 1460,
							z = 5743,
							facing = 0,
							patrolRoute = {
								{1479, 5698},
								{1423, 5729},
							},
						},
 						{
							name = "shipcon",
							x = 2871,
							z = 6445,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1400,
							z = 6152,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 1208,
							z = 7272,
							facing = 2,
						},
 						{
							name = "hovercon",
							x = 4220,
							z = 5585,
							facing = 2,
						},
 						{
							name = "amphraid",
							x = 2193,
							z = 5174,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 536,
							z = 6424,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 2936,
							z = 8312,
							facing = 2,
						},
 						{
							name = "hoverskirm",
							x = 3065,
							z = 7588,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 3488,
							z = 6080,
							facing = 2,
						},
 						{
							name = "hovercon",
							x = 3470,
							z = 7288,
							facing = 2,
						},
 						{
							name = "amphfloater",
							x = 1435,
							z = 5672,
							facing = 0,
							patrolRoute = {
								{1436, 5666},
								{1423, 5729},
							},
						},
 						{
							name = "turretmissile",
							x = 640,
							z = 6192,
							facing = 1,
							buildProgress = 0.53659999,
						},
 						{
							name = "shipcon",
							x = 904,
							z = 5890,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 1544,
							z = 6084,
							facing = 3,
						},
 						{
							name = "amphassault",
							x = 1900,
							z = 6022,
							facing = 2,
						},
 						{
							name = "staticstorage",
							x = 2552,
							z = 8040,
							facing = 2,
						},
 						{
							name = "hovercon",
							x = 1495,
							z = 6048,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 1304,
							z = 7704,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 1544,
							z = 7688,
							facing = 2,
						},
 						{
							name = "shipcon",
							x = 1404,
							z = 5968,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 2652,
							z = 6892,
							facing = 2,
						},
 						{
							name = "hoveraa",
							x = 2781,
							z = 6622,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 520,
							z = 6376,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 136,
							z = 5256,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1608,
							z = 7784,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 2888,
							z = 8264,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3160, 8047}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {2888, 8264}, options = {"shift"}},
							},
						},
 						{
							name = "shiptorpraider",
							x = 1377,
							z = 5641,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 2901,
							z = 7702,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 3096,
							z = 8184,
							facing = 2,
						},
 						{
							name = "shiparty",
							x = 3160,
							z = 8047,
							facing = 2,
							buildProgress = 0.0486,
						},
 						{
							name = "turrettorp",
							x = 616,
							z = 6392,
							facing = 1,
						},
 						{
							name = "hovercon",
							x = 978,
							z = 8479,
							facing = 3,
						},
 						{
							name = "shipcon",
							x = 1895,
							z = 6497,
							facing = 2,
						},
 						{
							name = "amphcon",
							x = 3577,
							z = 6868,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 952,
							z = 5944,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 2984,
							z = 8328,
							facing = 2,
						},
 						{
							name = "shipassault",
							x = 2713,
							z = 7189,
							facing = 3,
						},
 						{
							name = "hoverassault",
							x = 2157,
							z = 6782,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 2888,
							z = 8312,
							facing = 2,
						},
 						{
							name = "amphraid",
							x = 1722,
							z = 6662,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 1408,
							z = 6208,
							facing = 1,
						},
 						{
							name = "amphaa",
							x = 2831,
							z = 7330,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 568,
							z = 6376,
							facing = 1,
						},
 						{
							name = "shipaa",
							x = 2730,
							z = 6895,
							facing = 2,
						},
 						{
							name = "shipaa",
							x = 3160,
							z = 7898,
							facing = 2,
						},
 						{
							name = "amphaa",
							x = 2976,
							z = 7569,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 1496,
							z = 5928,
							facing = 0,
							buildProgress = 0.82660002,
						},
 						{
							name = "amphraid",
							x = 2977,
							z = 7681,
							facing = 2,
						},
 						{
							name = "shipscout",
							x = 3102,
							z = 7402,
							facing = 2,
						},
 						{
							name = "amphassault",
							x = 3000,
							z = 8004,
							facing = 2,
							buildProgress = 0.233,
						},
 						{
							name = "shipscout",
							x = 3144,
							z = 7728,
							facing = 2,
						},
					}
				},
				{
					startX = 3300,
					startZ = 700,
					humanName = "Xill",
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					commanderParameters = {
						facplop = false,
					},
					allyTeam = 1,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turrettorp",
						"turretgauss",
						"turretaalaser",
						"turretaaclose",
						"staticradar",
						"staticcon",
						"staticantinuke",
						"staticrearm",
						"factoryplane",
						"planecon",
						"planescout",
						"planefighter",
						"planeheavyfighter",
						"bomberprec",
						"bomberdisarm",
						"bomberheavy",
						"factoryship",
						"shipcon",
						"shipaa",
						"shiparty",
						"shipassault",
						"shipriot",
						"shipscout",
						"shipskirm",
						"shiptorpraider",
						"subraider",
						"factoryamph",
						"striderhub",
						"shipcarrier",
						"shipheavyarty",
						"striderdetriment",
						"staticnuke",
					},
					commanderLevel = 6,
					commander = {
						name = "Ballast",
						chassis = "support",
						modules = {
							"commweapon_beamlaser",
							"commweapon_multistunner",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_autorepair",
							"module_autorepair",
							"module_autorepair",
							"module_adv_nano",
							"module_adv_nano",
							"module_adv_nano",
							"module_adv_nano",
							"module_adv_nano",
						}
					},
					midgameUnits = {
						{
							name = "shipheavyarty",
							x = 3200,
							z = 100,
							facing = 0,
							spawnRadius = 50,
							delay = 6*30*60,
							orbitalDrop = false,
						},
						{
							name = "shipcarrier",
							x = 3400,
							z = 100,
							facing = 0,
							spawnRadius = 50,
							delay = 6*30*60,
							difficultyAtLeast = 2,
							orbitalDrop = false,
						},
						{
							name = "shipheavyarty",
							x = 3600,
							z = 100,
							facing = 0,
							spawnRadius = 50,
							delay = 6*30*60,
							difficultyAtLeast = 3,
							orbitalDrop = false,
						},
						{
							name = "shipcarrier",
							x = 3800,
							z = 100,
							facing = 0,
							spawnRadius = 50,
							delay = 6*30*60,
							difficultyAtLeast = 4,
							orbitalDrop = false,
						},
						{
							name = "striderdetriment",
							x = 3200,
							z = 100,
							facing = 0,
							spawnRadius = 50,
							delay = 10*30*60,
							orbitalDrop = false,
						},
						{
							name = "striderdetriment",
							x = 3200,
							z = 300,
							facing = 0,
							spawnRadius = 50,
							delay = 10*30*60,
							difficultyAtLeast = 4,
							orbitalDrop = false,
						},
						{
							name = "shipheavyarty",
							x = 3200,
							z = 100,
							facing = 0,
							spawnRadius = 50,
							delay = 15*30*60,
							orbitalDrop = false,
						},
						{
							name = "shipcarrier",
							x = 3400,
							z = 100,
							facing = 0,
							spawnRadius = 50,
							delay = 15*30*60,
							difficultyAtLeast = 2,
							orbitalDrop = false,
						},
						{
							name = "shipheavyarty",
							x = 3600,
							z = 100,
							facing = 0,
							spawnRadius = 50,
							delay = 15*30*60,
							difficultyAtLeast = 3,
							orbitalDrop = false,
						},
						{
							name = "shipcarrier",
							x = 3800,
							z = 100,
							facing = 0,
							spawnRadius = 50,
							delay = 15*30*60,
							difficultyAtLeast = 4,
							orbitalDrop = false,
						},
					},
					startUnits = {
						{
							name = "striderdetriment",
							x = 1600,
							z = 1600,
							facing = 2,
						},
						{
							name = "striderdetriment",
							x = 1900,
							z = 1600,
							facing = 2,
							difficultyAtLeast = 4,
						},
						{
							name = "energysingu",
							x = 344,
							z = 1000,
							facing = 2,
						},
 						{
							name = "energysingu",
							x = 4952,
							z = 552,
							facing = 2,
						},
 						{
							name = "energysingu",
							x = 2888,
							z = 104,
							facing = 2,
						},
 						{
							name = "staticantinuke",
							x = 4344,
							z = 1888,
							facing = 2,
						},
 						{
							name = "staticantinuke",
							x = 1000,
							z = 1888,
							facing = 2,
						},
						{
							name = "staticnuke",
							x = 474,
							z = 2265,
							facing = 0,
							difficultyAtLeast = 3,
						},
 						{
							name = "staticmex",
							x = 2088,
							z = 1048,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2232,
							z = 904,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2056,
							z = 424,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4232,
							z = 1912,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2216,
							z = 56,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4216,
							z = 2344,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1464,
							z = 280,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1224,
							z = 104,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5064,
							z = 1992,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4888,
							z = 1400,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 440,
							z = 376,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5048,
							z = 1272,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 472,
							z = 536,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3960,
							z = 392,
							facing = 0,
						},
 						{
							name = "staticrearm",
							x = 2216,
							z = 184,
							facing = 2,
						},
 						{
							name = "factoryplane",
							x = 2144,
							z = 328,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 2008,
							z = 184,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 2008,
							z = 280,
							facing = 2,
						},
 						{
							name = "staticstorage",
							x = 1976,
							z = 24,
							facing = 2,
						},
 						{
							name = "staticstorage",
							x = 1848,
							z = 40,
							facing = 2,
						},
 						{
							name = "striderhub",
							x = 1040,
							z = 1232,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 1112,
							z = 1288,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 1192,
							z = 1320,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 984,
							z = 504,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 1832,
							z = 328,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 2504,
							z = 936,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 3240,
							z = 584,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 4200,
							z = 440,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 4776,
							z = 712,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 4824,
							z = 1688,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 4408,
							z = 2024,
							facing = 0,
						},
 						{
							name = "turretantiheavy",
							x = 4112,
							z = 1920,
							facing = 0,
						},
 						{
							name = "turretheavy",
							x = 4712,
							z = 2088,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 4392,
							z = 2264,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 4952,
							z = 2104,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 1416,
							z = 1480,
							facing = 0,
						},
 						{
							name = "turretaafar",
							x = 4496,
							z = 1824,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 1624,
							z = 1304,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 4712,
							z = 1720,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 1848,
							z = 1064,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 2312,
							z = 1448,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 2616,
							z = 1528,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 3112,
							z = 1352,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 3496,
							z = 1272,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 1608,
							z = 2408,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 2024,
							z = 2344,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 2264,
							z = 2312,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 1816,
							z = 3432,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 2264,
							z = 3368,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 2744,
							z = 3304,
							facing = 0,
						},
 						{
							name = "factoryship",
							x = 2864,
							z = 864,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3032,
							z = 856,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3128,
							z = 856,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3224,
							z = 856,
							facing = 0,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3199, 881}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3224, 856}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 3320,
							z = 856,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3416,
							z = 856,
							facing = 0,
						},
 						{
							name = "striderhub",
							x = 3232,
							z = 960,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 3064,
							z = 728,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 3400,
							z = 728,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 392,
							z = 376,
							facing = 0,
						},
 						{
							name = "bomberheavy",
							x = 1770,
							z = -184,
							facing = 2,
						},
 						{
							name = "shipcon",
							x = 514,
							z = 3565,
							facing = 3,
						},
 						{
							name = "planeheavyfighter",
							x = 1648,
							z = 3633,
							facing = 2,
						},
 						{
							name = "turrettorp",
							x = 2216,
							z = 1048,
							facing = 0,
						},
 						{
							name = "shipcon",
							x = 3301,
							z = 4417,
							facing = 1,
						},
 						{
							name = "shiparty",
							x = 352,
							z = 4189,
							facing = 0,
						},
 						{
							name = "shipaa",
							x = 2502,
							z = 4823,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 2912,
							z = 1664,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 2208,
							z = 560,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 2664,
							z = 2008,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 2840,
							z = 712,
							facing = 0,
						},
 						{
							name = "shiptorpraider",
							x = 3098,
							z = 1194,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 3528,
							z = 2600,
							facing = 0,
						},
 						{
							name = "shiparty",
							x = 894,
							z = 3509,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 4928,
							z = 1536,
							facing = 0,
						},
 						{
							name = "planecon",
							x = 3574,
							z = 3953,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 1344,
							z = 128,
							facing = 0,
						},
 						{
							name = "shipassault",
							x = 4486,
							z = 3631,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 1536,
							z = 352,
							facing = 0,
						},
 						{
							name = "planeheavyfighter",
							x = 1991,
							z = 3651,
							facing = 2,
						},
 						{
							name = "shiptorpraider",
							x = 1743,
							z = 2581,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 3776,
							z = 512,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 1496,
							z = 3304,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 504,
							z = 616,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 2384,
							z = 400,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 4024,
							z = 280,
							facing = 0,
						},
 						{
							name = "shipcon",
							x = 4537,
							z = 3460,
							facing = 0,
						},
 						{
							name = "planeheavyfighter",
							x = 1825,
							z = 6608,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 1696,
							z = 3104,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 1600,
							z = 3488,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 3664,
							z = 3632,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 4096,
							z = 2160,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 1576,
							z = 3288,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 1056,
							z = 1712,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 4960,
							z = 1744,
							facing = 0,
						},
 						{
							name = "bomberdisarm",
							x = 2147,
							z = 91,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 1512,
							z = 3080,
							facing = 0,
						},
 						{
							name = "shipriot",
							x = 4679,
							z = 4177,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 3592,
							z = 4472,
							facing = 3,
							buildProgress = 0.71929997,
						},
 						{
							name = "turretlaser",
							x = 160,
							z = 2272,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 192,
							z = 2080,
							facing = 0,
						},
 						{
							name = "shipcon",
							x = 4491,
							z = 3450,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 1624,
							z = 3208,
							facing = 0,
						},
 						{
							name = "turretaalaser",
							x = 1656,
							z = 3288,
							facing = 0,
						},
 						{
							name = "shipcon",
							x = 3133,
							z = 4603,
							facing = 0,
						},
 						{
							name = "shipscout",
							x = 2865,
							z = 1358,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 3584,
							z = 3456,
							facing = 0,
						},
 						{
							name = "shipskirm",
							x = 3391,
							z = 2941,
							facing = 0,
						},
 						{
							name = "subraider",
							x = 2776,
							z = 3581,
							facing = 0,
						},
 						{
							name = "shiptorpraider",
							x = 2871,
							z = 3628,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 3392,
							z = 3824,
							facing = 0,
						},
 						{
							name = "shiptorpraider",
							x = 2895,
							z = 2657,
							facing = 0,
						},
 						{
							name = "subraider",
							x = 3480,
							z = 2339,
							facing = 0,
						},
 						{
							name = "shipscout",
							x = 4157,
							z = 2698,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 4720,
							z = 3568,
							facing = 3,
						},
 						{
							name = "subraider",
							x = 2944,
							z = 1965,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 136,
							z = 4408,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 3632,
							z = 4064,
							facing = 0,
							buildProgress = 0.2888,
						},
 						{
							name = "shiparty",
							x = 2872,
							z = 864,
							facing = 0,
							buildProgress = 0.0905,
						},
 						{
							name = "staticmex",
							x = 3256,
							z = 4888,
							facing = 0,
							buildProgress = 0.1399,
						},
					}
				},
				{
					humanName = "Rapla IV",
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					allyTeam = 1,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turrettorp",
						"turretgauss",
						"turretaalaser",
						"turretaaclose",
						"staticradar",
						"staticcon",
						"staticantinuke",
						"factoryship",
						"shipcon",
						"shipaa",
						"shiparty",
						"shipassault",
						"shipriot",
						"shipscout",
						"shipskirm",
						"shiptorpraider",
						"subraider",
						"factoryamph",
						"amphcon",
						"amphraid",
						"amphimpulse",
						"amphfloater",
						"amphriot",
						"amphassault",
						"amphbomb",
						"amphaa",
						"factoryhover",
						"hovercon",
						"hoverraid",
						"hoverriot",
						"hoverskirm",
						"hoverassault",
						"hoverdepthcharge",
                        "hoverheavyraid",
						"hoverarty",
						"hoveraa",
					},
					commander = false,
					startUnits = {
						{
							name = "staticmex",
							x = 2792,
							z = 1736,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1672,
							z = 2952,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2552,
							z = 1896,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2776,
							z = 2024,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1384,
							z = 3592,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3336,
							z = 2712,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1512,
							z = 4136,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3608,
							z = 2632,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1496,
							z = 4584,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3512,
							z = 3368,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 712,
							z = 4520,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3208,
							z = 3688,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3864,
							z = 3512,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3864,
							z = 3720,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 168,
							z = 2392,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 3032,
							z = 2072,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 232,
							z = 2200,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 120,
							z = 2072,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 136,
							z = 1496,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1016,
							z = 1672,
							facing = 0,
						},
 						{
							name = "factoryship",
							x = 3296,
							z = 2256,
							facing = 0,
						},
 						{
							name = "factoryamph",
							x = 3480,
							z = 2168,
							facing = 0,
						},
 						{
							name = "factoryhover",
							x = 3088,
							z = 2224,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3080,
							z = 2040,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3160,
							z = 2040,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3240,
							z = 2040,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3320,
							z = 2040,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3400,
							z = 2040,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3480,
							z = 2040,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 200,
							z = 744,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 3144,
							z = 1896,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 3448,
							z = 1896,
							facing = 0,
						},
 						{
							name = "turretaafar",
							x = 3280,
							z = 1888,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 312,
							z = 1720,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 840,
							z = 1832,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 328,
							z = 2664,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 2600,
							z = 2248,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 2840,
							z = 2456,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 696,
							z = 3544,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 3064,
							z = 2728,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 872,
							z = 4360,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 1448,
							z = 4008,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 3896,
							z = 2504,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 3976,
							z = 2664,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 4088,
							z = 2696,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 3464,
							z = 3128,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 3768,
							z = 2936,
							facing = 0,
						},
 						{
							name = "turrettorp",
							x = 3864,
							z = 3000,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 3480,
							z = 3736,
							facing = 0,
						},
 						{
							name = "turretheavy",
							x = 792,
							z = 4680,
							facing = 0,
						},
 						{
							name = "turretheavy",
							x = 1720,
							z = 4408,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 1272,
							z = 4600,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 1592,
							z = 4664,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 984,
							z = 4488,
							facing = 0,
						},
 						{
							name = "turretantiheavy",
							x = 3104,
							z = 3856,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 1464,
							z = 4344,
							facing = 0,
						},
 						{
							name = "turretheavy",
							x = 3432,
							z = 4136,
							facing = 0,
						},
 						{
							name = "turretaafar",
							x = 3440,
							z = 3616,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 3208,
							z = 3528,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 3656,
							z = 3848,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 3816,
							z = 3912,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 3832,
							z = 3384,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 3960,
							z = 3656,
							facing = 1,
						},
 						{
							name = "turretheavy",
							x = 1208,
							z = 1880,
							facing = 1,
						},
 						{
							name = "turretheavy",
							x = 216,
							z = 2744,
							facing = 0,
						},
 						{
							name = "turretheavy",
							x = 728,
							z = 2584,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 296,
							z = 2504,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 664,
							z = 2248,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 456,
							z = 2616,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 904,
							z = 2440,
							facing = 0,
						},
 						{
							name = "staticheavyradar",
							x = 3248,
							z = 4048,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 560,
							z = 4512,
							facing = 2,
						},
 						{
							name = "shipassault",
							x = 2320,
							z = 2668,
							facing = 0,
							patrolRoute = {
								{2208, 2640},
								{2330, 2785},
							},
						},
 						{
							name = "energywind",
							x = 2680,
							z = 2088,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 2808,
							z = 1928,
							facing = 0,
						},
 						{
							name = "shipcon",
							x = 3200,
							z = 2724,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 2744,
							z = 2104,
							facing = 0,
						},
 						{
							name = "amphassault",
							x = 3792,
							z = 3747,
							facing = 0,
						},
 						{
							name = "hoverassault",
							x = 2426,
							z = 3694,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 3400,
							z = 2776,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 2760,
							z = 1960,
							facing = 0,
						},
 						{
							name = "energyfusion",
							x = 1192,
							z = 3248,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 2792,
							z = 2072,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 2824,
							z = 1976,
							facing = 0,
						},
 						{
							name = "shiparty",
							x = 388,
							z = 4074,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 3102,
							z = 2032,
							facing = 3,
						},
 						{
							name = "shiparty",
							x = 3081,
							z = 4662,
							facing = 0,
						},
 						{
							name = "hovercon",
							x = 980,
							z = 3284,
							facing = 0,
						},
 						{
							name = "amphimpulse",
							x = 2897,
							z = 4109,
							facing = 0,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {2961, 4176}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3024, 4165}, options = {"shift"}},
							},
						},
 						{
							name = "energywind",
							x = 2824,
							z = 2024,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 1504,
							z = 2912,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 2728,
							z = 2008,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 2712,
							z = 1960,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 2728,
							z = 2056,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 2840,
							z = 2072,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 2792,
							z = 2120,
							facing = 0,
						},
 						{
							name = "shipcon",
							x = 1411,
							z = 3268,
							facing = 0,
						},
 						{
							name = "hovercon",
							x = 2248,
							z = 2564,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 2840,
							z = 2120,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 2872,
							z = 1976,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 3520,
							z = 2416,
							facing = 0,
						},
 						{
							name = "hoverassault",
							x = 2276,
							z = 3745,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 2760,
							z = 1912,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 2872,
							z = 2024,
							facing = 0,
						},
 						{
							name = "shipskirm",
							x = 2998,
							z = 4193,
							facing = 1,
							patrolRoute = {
								{3012, 4215},
								{2962, 4178},
							},
						},
 						{
							name = "energywind",
							x = 2712,
							z = 1912,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 3288,
							z = 2776,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 3288,
							z = 2696,
							facing = 0,
						},
 						{
							name = "hoverraid",
							x = 4650,
							z = 4615,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 4442,
							z = 3450,
							facing = 1,
						},
 						{
							name = "hoverskirm",
							x = 2608,
							z = 3685,
							facing = 0,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {2961, 4176}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {2899, 4161}, options = {"shift"}},
							},
						},
 						{
							name = "energywind",
							x = 3336,
							z = 2664,
							facing = 0,
						},
 						{
							name = "hovercon",
							x = 1168,
							z = 3206,
							facing = 0,
						},
 						{
							name = "shipcon",
							x = 1424,
							z = 3221,
							facing = 0,
						},
 						{
							name = "energyfusion",
							x = 1400,
							z = 3040,
							facing = 0,
						},
 						{
							name = "hoverarty",
							x = 2673,
							z = 3566,
							facing = 0,
						},
 						{
							name = "subraider",
							x = 4673,
							z = 4630,
							facing = 2,
						},
 						{
							name = "turretlaser",
							x = 3120,
							z = 2496,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 2880,
							z = 2213,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 1312,
							z = 3168,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 1144,
							z = 3000,
							facing = 0,
						},
 						{
							name = "hovercon",
							x = 2078,
							z = 2385,
							facing = 3,
						},
 						{
							name = "energyfusion",
							x = 1384,
							z = 3536,
							facing = 0,
							buildProgress = 0.43399999,
						},
 						{
							name = "amphcon",
							x = 3363,
							z = 2219,
							facing = 1,
						},
 						{
							name = "hoveraa",
							x = 1523,
							z = 2961,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 3112,
							z = 1992,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3160,
							z = 1992,
							facing = 0,
						},
 						{
							name = "amphaa",
							x = 2895,
							z = 3079,
							facing = 3,
						},
 						{
							name = "staticstorage",
							x = 1720,
							z = 2904,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 2812,
							z = 2803,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 3208,
							z = 1992,
							facing = 0,
						},
 						{
							name = "shipaa",
							x = 3304,
							z = 2256,
							facing = 0,
							buildProgress = 0.61949998,
						},
 						{
							name = "turretriot",
							x = 968,
							z = 3400,
							facing = 0,
							buildProgress = 0.3136,
						},
 						{
							name = "hovercon",
							x = 2734,
							z = 2326,
							facing = 2,
						},
 						{
							name = "amphraid",
							x = 3621,
							z = 2998,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3016,
							z = 2024,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 3064,
							z = 1992,
							facing = 0,
						},
 						{
							name = "hoverraid",
							x = 4295,
							z = 3224,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 3463,
							z = 2220,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {2680, 3004}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {3480, 2204}, options = {"shift"}},
							},
						},
 						{
							name = "hovercon",
							x = 2959,
							z = 2324,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 2984,
							z = 2072,
							facing = 0,
							buildProgress = 0.85030001,
						},
 						{
							name = "hoverarty",
							x = 3088,
							z = 2192,
							facing = 0,
							buildProgress = 0.0396,
						},
					}
				},
			},
			defeatConditionConfig = {
				-- Indexed by allyTeam.
				[0] = { },
				[1] = {
					ignoreUnitLossDefeat = false,
					vitalCommanders = false,
					vitalUnitTypes = {
						"striderhub",
						"striderdetriment"
					},
					loseAfterSeconds = false,
					allyTeamLossObjectiveID = 1,
				},
			},
			objectiveConfig = {
				-- This is just related to displaying objectives on the UI.
				[1] = {
					description = "Destroy all enemy Strider Hubs and Detriments",
				},
				[2] = {
					description = "Protect your Commander",
				},
			},
			bonusObjectiveConfig = {
				[1] = {
					satisfyOnce = true,
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 8,
					unitTypes = {
						"shipcarrier",
					},
					image = planetUtilities.ICON_DIR .. "shipcarrier.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.REPAIR,
					description = "Have 8 Reefs",
					experience = planetUtilities.BONUS_EXP,
				},
				[2] = {
					victoryByTime = 25*60,
					image = planetUtilities.ICON_OVERLAY.CLOCK,
					description = "Win by 25:00",
					experience = planetUtilities.BONUS_EXP,
				},
				[3] = {
					onlyCountRemovedUnits = true,
					satisfyByTime = 16*60,
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 1,
					enemyUnitTypes = {
						"energysingu",
					},
					image = planetUtilities.ICON_DIR .. "energysingu.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.ATTACK,
					description = "Destroy an enemy Singularity Reactor before 16:00",
					experience = planetUtilities.BONUS_EXP,
				},
			},
		},
		completionReward = {
			experience = planetUtilities.MAIN_EXP,
			units = {
				"striderhub",
				"subtacmissile",
				"shipcarrier",
			},
			modules = {
				"commweapon_disruptorbomb",
			},
			abilities = {
			},
			codexEntries = {
				"location_rockbar"
			},
		},
	}
	
	return planetData
end

return GetPlanet
