--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Planet config

local function GetPlanet(planetUtilities, planetID)
	
	local image = LUA_DIRNAME .. "images/planets/terran04.png"
	
	local planetData = {
		name = "Karuwal",
		startingPlanet = false,
		mapDisplay = {
			x = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][1]) or 0.685,
			y = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][2]) or 0.42,
			image = image,
			size = planetUtilities.PLANET_SIZE_MAP,
		},
		infoDisplay = {
			image = image,
			size = planetUtilities.PLANET_SIZE_INFO,
			backgroundImage = planetUtilities.backgroundImages[math.floor(math.random()*#planetUtilities.backgroundImages) + 1],
			terrainType = "Alpine",
			radius = "6310 km",
			primary = "Ilvasia",
			primaryType = "G7V",
			milRating = 1,
			feedbackLink = "http://zero-k.info/Forum/Thread/24566",
			text = "This is the closest point the Rebel military ever came to threaten the Empire's heartland. But overconfidence was their downfall: instead of keeping with ambush and clever strategic play, they met the Empire on its own terms in a single, decisive engagement."
			.. "\n "
			.. "\nThis defeat broke the momentum of the Rebel forces, from which they would never recover."
			,
			extendedText = "Once bitten, twice shy: the Empire stationed an impressive collection of heavy units here, including large Paladin striders. I managed to take control of a few Scorpions - which was surprisingly easy - and mountains are a good place for ambush, to destroy those heavies."
		},
		tips = {
			{
				image = "unitpics/striderscorpion.png",
				text = [[Scorpions are cloaked all-terrain striders effective against enemy heavies. Most of their weapons only fire forwards so make sure they are not decloaked and flanked.]]
			},
			{
				image = "unitpics/striderbantha.png",
				text = [[Get close to a Paladin with two or three Scorpions then use their multistunners (default hotkey D) to stunlock the Paladin. One Scorpion on its own will be insufficient against anything but a highly damaged Paladin.]]
			},
			{
				image = "unitpics/staticnuke.png",
				text = [[Your ally has constructed a Trinity nuclear silo but the enemy is well protected by Antinukes. Destroy the Antinukes to give your team the upper hand.]]
			},
		},
		gameConfig = {
			mapName = "Craterv01",
			playerConfig = {
				startX = 1411,
				startZ = 4100,
				allyTeam = 0,
				commanderParameters = {
					facplop = true,
					defeatIfDestroyedObjectiveID = 2,
				},
				extraUnlocks = {
					"striderhub",
					"striderscorpion",
					
				},
				startUnits = {
					{
						name = "striderscorpion",
						x = 1300,
						z = 3800,
						facing = 1,
					},
					{
						name = "striderscorpion",
						x = 1300,
						z = 4000,
						facing = 1,
					},
					{
						name = "striderscorpion",
						x = 1500,
						z = 3900,
						facing = 1,
					},
					{
						name = "energyfusion",
						x = 630,
						z = 4260,
						facing = 0,
					},
					{
						name = "energyfusion",
						x = 800,
						z = 4420,
						facing = 0,
					},
					{
						name = "staticmex",
						x = 920,
						z = 4296,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 1304,
						z = 4104,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 904,
						z = 3864,
						facing = 0,
					},
 					{
						name = "energywind",
						x = 856,
						z = 4232,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 856,
						z = 4152,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 840,
						z = 4072,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 840,
						z = 3992,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 840,
						z = 3912,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 1000,
						z = 4328,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 1080,
						z = 4280,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 1160,
						z = 4232,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 1240,
						z = 4200,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 1320,
						z = 4152,
						facing = 1,
					},
 					{
						name = "staticheavyradar",
						x = 1792,
						z = 4160,
						facing = 1,
						terraformHeight = 364,
					},
 					{
						name = "staticcon",
						x = 1192,
						z = 3816,
						facing = 1,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {1192, 3816}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {1217, 3791}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 1192,
						z = 3992,
						facing = 1,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {1192, 3992}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {1217, 3967}, options = {"shift"}},
						},
					},
 					{
						name = "striderhub",
						x = 1184,
						z = 3904,
						facing = 1,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {1184, 3904}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {1209, 3879}, options = {"shift"}},
						},
					},
 					{
						name = "staticstorage",
						x = 1048,
						z = 4072,
						facing = 1,
					},
 					{
						name = "staticstorage",
						x = 968,
						z = 4072,
						facing = 1,
					},
 					{
						name = "energywind",
						x = 1064,
						z = 4376,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 1144,
						z = 4328,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 1224,
						z = 4296,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 1304,
						z = 4248,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 776,
						z = 3960,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 776,
						z = 4040,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 776,
						z = 4120,
						facing = 3,
					},
 					{
						name = "energywind",
						x = 776,
						z = 4200,
						facing = 3,
					},
				}
			},
			aiConfig = {
				{
					humanName = "Ally #1",
					aiLib = "Circuit_difficulty_autofill_ally",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					allyTeam = 0,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energypylon",
						"staticstorage",
						"turretmissile",
						"staticradar",
						"staticcon",
						"staticrearm",
						"factoryjump",
						"jumpcon",
						"jumpraid",
						"jumpskirm",
						"jumpassault",
						"jumpsumo",
						"jumpaa",
						"factorytank",
						"tankassault",
						"tankarty",
						"tankheavyarty",
						"tankaa",
						"tankriot",
						"striderhub",
						"striderdante",
						"striderarty",
						"factoryplane",
						"planecon",
						"planescout",
						"planefighter",
						"planeheavyfighter",
						"bomberprec",
						"bomberheavy",
						"bomberdisarm",
					},
					commander = false,
					startUnits = {
						{
							name = "staticnuke",
							x = 496,
							z = 1776,
							facing = 1,
						},
						{
							name = "staticstorage",
							x = 536,
							z = 1496,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 600,
							z = 1992,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 456,
							z = 1496,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 504,
							z = 2392,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 952,
							z = 2536,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 2616,
							z = 3432,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 648,
							z = 2856,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1416,
							z = 2392,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 2584,
							z = 3800,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 1672,
							z = 2856,
							facing = 0,
						},
 						{
							name = "turretaalaser",
							x = 2248,
							z = 3480,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 2040,
							z = 2504,
							facing = 0,
						},
 						{
							name = "turretaalaser",
							x = 2296,
							z = 3816,
							facing = 1,
						},
 						{
							name = "energyfusion",
							x = 240,
							z = 1560,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 840,
							z = 1544,
							facing = 0,
						},
 						{
							name = "energyfusion",
							x = 240,
							z = 1416,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 520,
							z = 1240,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 3048,
							z = 3576,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 1048,
							z = 888,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 2952,
							z = 2744,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 1240,
							z = 568,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1688,
							z = 888,
							facing = 0,
						},
 						{
							name = "turretaafar",
							x = 1664,
							z = 3536,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1680,
							z = 3440,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1712,
							z = 3632,
							facing = 1,
						},
 						{
							name = "turretaafar",
							x = 2032,
							z = 2032,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 2104,
							z = 1832,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 2024,
							z = 1592,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 1688,
							z = 1672,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 1752,
							z = 2024,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 2200,
							z = 600,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 2280,
							z = 760,
							facing = 1,
						},
 						{
							name = "energyheavygeo",
							x = 1848,
							z = 1784,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 1720,
							z = 2392,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 776,
							z = 2440,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 712,
							z = 1544,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 584,
							z = 2600,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 1512,
							z = 1288,
							facing = 3,
						},
 						{
							name = "factoryplane",
							x = 456,
							z = 2576,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 1144,
							z = 888,
							facing = 3,
						},
 						{
							name = "staticrearm",
							x = 504,
							z = 2776,
							facing = 1,
						},
 						{
							name = "staticrearm",
							x = 296,
							z = 2664,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 1160,
							z = 664,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 1144,
							z = 776,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 1160,
							z = 552,
							facing = 1,
						},
 						{
							name = "staticantinuke",
							x = 1296,
							z = 1608,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 728,
							z = 1720,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 728,
							z = 1800,
							facing = 1,
						},
 						{
							name = "factorytank",
							x = 864,
							z = 1744,
							facing = 1,
						},
 						{
							name = "striderhub",
							x = 768,
							z = 2720,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 648,
							z = 2696,
							facing = 1,
						},
 						{
							name = "turretgauss",
							x = 2648,
							z = 1096,
							facing = 1,
						},
 						{
							name = "turretgauss",
							x = 2696,
							z = 1464,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1448,
							z = 760,
							facing = 0,
						},
 						{
							name = "factoryjump",
							x = 1448,
							z = 920,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 2328,
							z = 472,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 3016,
							z = 2072,
							facing = 1,
						},
 						{
							name = "turretaaflak",
							x = 2008,
							z = 520,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 2616,
							z = 2440,
							facing = 3,
						},
 						{
							name = "striderdante",
							x = 4578,
							z = 2082,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 2184,
							z = 4968,
							facing = 1,
						},
 						{
							name = "striderarty",
							x = 864,
							z = 2720,
							facing = 0,
							buildProgress = 0.98250002,
						},
 						{
							name = "staticradar",
							x = 2688,
							z = 816,
							facing = 0,
						},
 						{
							name = "tankaa",
							x = 1683,
							z = 2922,
							facing = 1,
						},
 						{
							name = "tankriot",
							x = 1416,
							z = 2624,
							facing = 0,
						},
 						{
							name = "jumpcon",
							x = 3447,
							z = 1856,
							facing = 1,
						},
 						{
							name = "jumpassault",
							x = 2026,
							z = 3109,
							facing = 0,
						},
 						{
							name = "bomberheavy",
							x = 704,
							z = 2796,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 2728,
							z = 744,
							facing = 0,
						},
 						{
							name = "tankassault",
							x = 4201,
							z = 1590,
							facing = 3,
						},
 						{
							name = "jumpcon",
							x = 4300,
							z = 1979,
							facing = 1,
						},
 						{
							name = "tankriot",
							x = 4210,
							z = 1721,
							facing = 0,
						},
 						{
							name = "tankassault",
							x = 2096,
							z = 2933,
							facing = 0,
						},
 						{
							name = "tankassault",
							x = 1821,
							z = 3009,
							facing = 1,
						},
 						{
							name = "jumpcon",
							x = 2732,
							z = 1007,
							facing = 1,
						},
 						{
							name = "jumpraid",
							x = 2597,
							z = 5534,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 752,
							z = 2224,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 2632,
							z = 744,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 2712,
							z = 6744,
							facing = 2,
						},
 						{
							name = "striderdante",
							x = 4935,
							z = 1810,
							facing = 2,
						},
 						{
							name = "planescout",
							x = 2439,
							z = 760,
							facing = 0,
						},
 						{
							name = "jumpskirm",
							x = 4028,
							z = 1808,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 1784,
							z = 5992,
							facing = 1,
						},
 						{
							name = "jumpraid",
							x = 1448,
							z = 944,
							facing = 0,
							buildProgress = 0.0424,
						},
 						{
							name = "jumpcon",
							x = 4901,
							z = 1973,
							facing = 2,
						},
 						{
							name = "tankassault",
							x = 4938,
							z = 1650,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 2008,
							z = 5496,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 2872,
							z = 4872,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 2768,
							z = 656,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 2480,
							z = 4288,
							facing = 1,
						},
 						{
							name = "tankaa",
							x = 1692,
							z = 2965,
							facing = 1,
						},
 						{
							name = "tankaa",
							x = 892,
							z = 1744,
							facing = 1,
							buildProgress = 0.59509999,
						},
 						{
							name = "tankaa",
							x = 980,
							z = 2714,
							facing = 3,
							patrolRoute = {
								{1002, 2708},
								{776, 2664},
							},
						},
 						{
							name = "bomberprec",
							x = 1674,
							z = 2804,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 2248,
							z = 4824,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 2560,
							z = 800,
							facing = 0,
						},
 						{
							name = "planecon",
							x = 2890,
							z = 2344,
							facing = 1,
						},
 						{
							name = "jumpcon",
							x = 4418,
							z = 2126,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 2848,
							z = 832,
							facing = 0,
						},
 						{
							name = "jumpcon",
							x = 4027,
							z = 1678,
							facing = 1,
						},
 						{
							name = "jumpcon",
							x = 1759,
							z = 897,
							facing = 1,
						},
					}
				},
				{
					humanName = "Ally #2",
					aiLib = "Circuit_difficulty_autofill", -- Intentially not _ally.
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					allyTeam = 0,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energypylon",
						"staticstorage",
						"turretmissile",
						"staticradar",
						"staticcon",
						"staticrearm",
						"factoryshield",
						"shieldcon",
						"shieldraid",
						"shieldassault",
						"shieldriot",
						"shieldskirm",
						"shieldbomb",
						"shieldaa",
						"shieldfelon",
						"shieldshield",
						"factoryamph",
						"amphcon",
						"amphraid",
						"amphimpulse",
						"amphfloater",
						"amphriot",
						"amphassault",
						"amphaa",
						"factoryspider",
						"spidercon",
						"spiderscout",
						"spiderriot",
						"spideremp",
						"spiderskirm",
						"spiderassault",
						"spidercrabe",
						"spideraa",
						"striderhub",
						"striderdante",
						"striderarty",
					},
					commander = false,
					startUnits = {
						{
							name = "staticcon",
							x = 472,
							z = 3736,
							facing = 0,
						},
 						{
							name = "factoryspider",
							x = 488,
							z = 3864,
							facing = 0,
						},
 						{
							name = "striderhub",
							x = 1136,
							z = 6064,
							facing = 1,
						},
 						{
							name = "turretaafar",
							x = 1680,
							z = 6128,
							facing = 1,
						},
 						{
							name = "turretaafar",
							x = 1680,
							z = 4784,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 1760,
							z = 4704,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 712,
							z = 5480,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 1760,
							z = 4848,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 776,
							z = 5864,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 3016,
							z = 6552,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 3080,
							z = 6840,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 600,
							z = 6312,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 3096,
							z = 5400,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 1320,
							z = 6376,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 2984,
							z = 4408,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 1512,
							z = 6008,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1272,
							z = 5576,
							facing = 0,
						},
 						{
							name = "energyfusion",
							x = 432,
							z = 5736,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 2056,
							z = 5496,
							facing = 0,
						},
 						{
							name = "turretaalaser",
							x = 2584,
							z = 4856,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 1768,
							z = 6552,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 632,
							z = 6056,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 1576,
							z = 6872,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 712,
							z = 6056,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 2760,
							z = 6744,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2456,
							z = 4536,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2664,
							z = 4216,
							facing = 0,
						},
 						{
							name = "energyheavygeo",
							x = 2760,
							z = 6136,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 2456,
							z = 6136,
							facing = 3,
						},
 						{
							name = "turretheavy",
							x = 2888,
							z = 6184,
							facing = 1,
						},
 						{
							name = "turretheavy",
							x = 2808,
							z = 5928,
							facing = 1,
						},
 						{
							name = "turretaafar",
							x = 2320,
							z = 6032,
							facing = 1,
						},
 						{
							name = "staticantinuke",
							x = 1488,
							z = 5688,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 1544,
							z = 6504,
							facing = 3,
						},
 						{
							name = "turretaalaser",
							x = 2392,
							z = 6280,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 920,
							z = 5928,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 2680,
							z = 5480,
							facing = 1,
						},
 						{
							name = "factoryshield",
							x = 2808,
							z = 5488,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1144,
							z = 6184,
							facing = 1,
						},
 						{
							name = "factoryamph",
							x = 1288,
							z = 6136,
							facing = 1,
						},
 						{
							name = "turretaalaser",
							x = 2424,
							z = 5832,
							facing = 3,
						},
 						{
							name = "energyfusion",
							x = 432,
							z = 5944,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 3000,
							z = 6712,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 968,
							z = 4024,
							facing = 1,
						},
 						{
							name = "striderdante",
							x = 3669,
							z = 2843,
							facing = 1,
							patrolRoute = {
								{3706, 2866},
								{3568, 2736},
							},
						},
 						{
							name = "amphriot",
							x = 4734,
							z = 5612,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 1776,
							z = 2544,
							facing = 1,
						},
 						{
							name = "striderarty",
							x = 1232,
							z = 6016,
							facing = 0,
							buildProgress = 0.9102,
						},
 						{
							name = "spidercon",
							x = 1279,
							z = 3768,
							facing = 1,
						},
 						{
							name = "amphcon",
							x = 3149,
							z = 4560,
							facing = 2,
						},
 						{
							name = "energywind",
							x = 1800,
							z = 4056,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 1928,
							z = 4168,
							facing = 1,
						},
 						{
							name = "spiderassault",
							x = 1894,
							z = 5791,
							facing = 2,
						},
 						{
							name = "spidercon",
							x = 1316,
							z = 3275,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 2704,
							z = 6640,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 2280,
							z = 2440,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 2440,
							z = 4296,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 3797,
							z = 2814,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 2983,
							z = 1521,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 3786,
							z = 2856,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 1528,
							z = 4120,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 1352,
							z = 3144,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1112,
							z = 6120,
							facing = 1,
						},
 						{
							name = "spiderassault",
							x = 3841,
							z = 6372,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 1672,
							z = 4120,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 1912,
							z = 4040,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 1072,
							z = 4192,
							facing = 1,
						},
 						{
							name = "amphfloater",
							x = 3743,
							z = 6368,
							facing = 1,
						},
 						{
							name = "shieldskirm",
							x = 3005,
							z = 4553,
							facing = 2,
						},
 						{
							name = "shieldassault",
							x = 2964,
							z = 4602,
							facing = 2,
						},
 						{
							name = "shieldcon",
							x = 2687,
							z = 4495,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 3080,
							z = 2568,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1064,
							z = 6120,
							facing = 1,
						},
 						{
							name = "shieldfelon",
							x = 3186,
							z = 5271,
							facing = 3,
						},
 						{
							name = "striderdante",
							x = 4659,
							z = 5740,
							facing = 0,
						},
 						{
							name = "shieldshield",
							x = 3625,
							z = 6371,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 3444,
							z = 2943,
							facing = 1,
						},
 						{
							name = "shieldskirm",
							x = 2210,
							z = 6370,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 2968,
							z = 1048,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1080,
							z = 6072,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 2472,
							z = 2456,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 2632,
							z = 2536,
							facing = 1,
						},
 						{
							name = "shieldshield",
							x = 2883,
							z = 5289,
							facing = 3,
						},
 						{
							name = "amphraid",
							x = 2624,
							z = 5544,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 1096,
							z = 6168,
							facing = 1,
						},
 						{
							name = "amphraid",
							x = 2536,
							z = 5705,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 3160,
							z = 4515,
							facing = 0,
						},
 						{
							name = "amphraid",
							x = 2538,
							z = 5736,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 1656,
							z = 5263,
							facing = 2,
						},
 						{
							name = "spiderscout",
							x = 4201,
							z = 2852,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 416,
							z = 3632,
							facing = 1,
						},
 						{
							name = "striderarty",
							x = 2922,
							z = 4680,
							facing = 2,
							difficultyAtLeast = 2,
						},
 						{
							name = "spidercon",
							x = 488,
							z = 3900,
							facing = 0,
							buildProgress = 0.80159998,
						},
 						{
							name = "shieldaa",
							x = 2586,
							z = 5652,
							facing = 0,
						},
 						{
							name = "amphaa",
							x = 1515,
							z = 6161,
							facing = 2,
						},
					}
				},
				{
					humanName = "Enemy #1",
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					allyTeam = 1,
					
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energypylon",
						"staticstorage",
						--"turretmissile",
						"staticradar",
						"staticcon",
						"staticrearm",
						"factoryjump",
						"jumpcon",
						"jumpraid",
						"jumpskirm",
						"jumpassault",
						"jumpsumo",
						"jumpaa",
						"factorycloak",
						"cloakcon",
						"cloakraid",
						"cloakriot",
						"cloakskirm",
						"cloakassault",
						"cloakaa",
						"cloakarty",
						"cloaksnipe",
						"cloakheavyraid",
						"cloakbomb",
						"factoryplane",
						"planecon",
						"planescout",
						"planefighter",
						"planeheavyfighter",
						"bomberprec",
						--"bomberheavy",
						"bomberdisarm",
					},
					difficultyDependantUnlocks = {
						[4] = {"bomberheavy"},
					},
					commander = false,
					startUnits = {
						{
							name = "staticheavyarty",
							x = 7440,
							z = 3008,
							facing = 3,
							buildProgress = 0.2,
							difficultyAtLeast = 1,
							difficultyAtMost = 1,
							terraformHeight = 340,
						},
						{
							name = "staticheavyarty",
							x = 7440,
							z = 3008,
							facing = 3,
							buildProgress = 0.4,
							difficultyAtLeast = 2,
							difficultyAtMost = 2,
							terraformHeight = 340,
						},
						{
							name = "staticheavyarty",
							x = 7440,
							z = 3008,
							facing = 3,
							buildProgress = 0.6,
							difficultyAtLeast = 3,
							difficultyAtMost = 3,
							terraformHeight = 340,
						},
						{
							name = "staticheavyarty",
							x = 7440,
							z = 3008,
							facing = 3,
							buildProgress = 0.8,
							difficultyAtLeast = 4,
							difficultyAtMost = 4,
							terraformHeight = 340,
						},
						{
							name = "staticstorage",
							x = 8392,
							z = 696,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 7704,
							z = 328,
							facing = 0,
						},
 						{
							name = "turretaalaser",
							x = 5928,
							z = 568,
							facing = 3,
						},
 						{
							name = "turretaalaser",
							x = 6152,
							z = 1592,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 5432,
							z = 1400,
							facing = 3,
						},
 						{
							name = "staticrearm",
							x = 8872,
							z = 3112,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 8568,
							z = 1720,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8504,
							z = 1336,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 7528,
							z = 424,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 8696,
							z = 888,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 7600,
							z = 272,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 8392,
							z = 3336,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 7960,
							z = 824,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 7632,
							z = 656,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 7768,
							z = 1192,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 7872,
							z = 640,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 7992,
							z = 3096,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 8024,
							z = 1624,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 7888,
							z = 352,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 7224,
							z = 1704,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 6848,
							z = 3520,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 7528,
							z = 648,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 6944,
							z = 3856,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6616,
							z = 440,
							facing = 1,
						},
 						{
							name = "factoryjump",
							x = 7576,
							z = 888,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 5304,
							z = 504,
							facing = 3,
						},
 						{
							name = "athena",
							x = 6112,
							z = 5535,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 6336,
							z = 1024,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 8360,
							z = 2904,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 6336,
							z = 1088,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 6384,
							z = 1328,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 6480,
							z = 1360,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7720,
							z = 952,
							facing = 3,
						},
 						{
							name = "energyheavygeo",
							x = 6440,
							z = 1080,
							facing = 1,
						},
 						{
							name = "turretantiheavy",
							x = 6336,
							z = 1184,
							facing = 3,
						},
 						{
							name = "staticheavyradar",
							x = 6448,
							z = 1264,
							facing = 3,
						},
 						{
							name = "factorycloak",
							x = 7696,
							z = 1560,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8408,
							z = 2968,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7864,
							z = 1528,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7864, 1528}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7684, 1560}, options = {"shift"}},
							},
						},
 						{
							name = "energywind",
							x = 8488,
							z = 2968,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8488,
							z = 3048,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8408,
							z = 3048,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8408,
							z = 3128,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8488,
							z = 3128,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8488,
							z = 3208,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8408,
							z = 3208,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8408,
							z = 3288,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8488,
							z = 3288,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8328,
							z = 3080,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8248,
							z = 3080,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 7064,
							z = 1032,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8168,
							z = 3080,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8088,
							z = 3080,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8088,
							z = 3160,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8168,
							z = 3160,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8248,
							z = 3160,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8328,
							z = 3160,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 7912,
							z = 728,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 8360,
							z = 1256,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 6328,
							z = 2984,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 6376,
							z = 3720,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 8456,
							z = 3832,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 5336,
							z = 920,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 7848,
							z = 3192,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 8168,
							z = 2424,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 5624,
							z = 1800,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6632,
							z = 2952,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6776,
							z = 2568,
							facing = 0,
						},
 						{
							name = "energysingu",
							x = 8968,
							z = 3560,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8296,
							z = 1784,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8280,
							z = 1864,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 8264,
							z = 1944,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 7528,
							z = 2712,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 7496,
							z = 3224,
							facing = 3,
						},
 						{
							name = "turretaafar",
							x = 7696,
							z = 2864,
							facing = 3,
						},
 						{
							name = "turretaaflak",
							x = 7288,
							z = 3176,
							facing = 3,
						},
 						{
							name = "turretaaflak",
							x = 7288,
							z = 2824,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 7240,
							z = 2680,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 7224,
							z = 3320,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 7200,
							z = 2992,
							facing = 3,
						},
 						{
							name = "staticshield",
							x = 7584,
							z = 2992,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7768,
							z = 3032,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7768,
							z = 3112,
							facing = 3,
						},
 						{
							name = "staticantinuke",
							x = 8272,
							z = 2648,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 8072,
							z = 2632,
							facing = 2,
						},
 						{
							name = "turretriot",
							x = 8440,
							z = 2600,
							facing = 2,
						},
 						{
							name = "turretaaheavy",
							x = 8128,
							z = 1392,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 8064,
							z = 1312,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 8064,
							z = 1472,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 8760,
							z = 3256,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 8224,
							z = 1392,
							facing = 3,
						},
 						{
							name = "staticantinuke",
							x = 7696,
							z = 488,
							facing = 1,
						},
 						{
							name = "factoryplane",
							x = 8632,
							z = 3280,
							facing = 3,
						},
 						{
							name = "staticrearm",
							x = 8680,
							z = 3096,
							facing = 3,
						},
 						{
							name = "staticstorage",
							x = 8232,
							z = 2952,
							facing = 3,
						},
 						{
							name = "jumpassault",
							x = 4363,
							z = 1609,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 5696,
							z = 2912,
							facing = 3,
						},
 						{
							name = "cloaksnipe",
							x = 5948,
							z = 2680,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 8784,
							z = 4960,
							facing = 3,
						},
 						{
							name = "bomberheavy",
							x = 8641,
							z = 3057,
							facing = 1,
						},
 						{
							name = "jumpassault",
							x = 4436,
							z = 1569,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 8336,
							z = 1696,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 6024,
							z = 2808,
							facing = 3,
						},
 						{
							name = "cloakraid",
							x = 4104,
							z = 4465,
							facing = 0,
						},
 						{
							name = "cloakcon",
							x = 4700,
							z = 6059,
							facing = 3,
						},
 						{
							name = "jumpraid",
							x = 3912,
							z = 5893,
							facing = 3,
						},
 						{
							name = "cloakraid",
							x = 3742,
							z = 4960,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 6800,
							z = 2672,
							facing = 3,
						},
 						{
							name = "cloakaa",
							x = 5792,
							z = 2824,
							facing = 0,
						},
 						{
							name = "cloakassault",
							x = 4857,
							z = 2958,
							facing = 2,
						},
 						{
							name = "cloakcon",
							x = 5583,
							z = 3484,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 8808,
							z = 3272,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 6024,
							z = 1608,
							facing = 0,
						},
 						{
							name = "cloakskirm",
							x = 5858,
							z = 2604,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 8776,
							z = 3320,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 6600,
							z = 2728,
							facing = 3,
						},
 						{
							name = "bomberheavy",
							x = 6233,
							z = 2397,
							facing = 3,
							difficultyAtLeast = 2,
						},
 						{
							name = "cloakaa",
							x = 5774,
							z = 3035,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 4792,
							z = 664,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 8776,
							z = 3368,
							facing = 3,
						},
 						{
							name = "jumpassault",
							x = 7394,
							z = 854,
							facing = 2,
							patrolRoute = {
								{7397, 914},
								{7456, 720},
							},
						},
 						{
							name = "staticradar",
							x = 4880,
							z = 672,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 7816,
							z = 1688,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 8824,
							z = 3320,
							facing = 3,
						},
 						{
							name = "cloakraid",
							x = 4000,
							z = 4622,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 7928,
							z = 1608,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7928, 1608}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7684, 1560}, options = {"shift"}},
							},
						},
 						{
							name = "jumpassault",
							x = 4839,
							z = 2925,
							facing = 2,
						},
 						{
							name = "cloakraid",
							x = 4095,
							z = 4487,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 5616,
							z = 5856,
							facing = 2,
						},
 						{
							name = "bomberheavy",
							x = 5671,
							z = 2320,
							facing = 1,
							difficultyAtLeast = 2,
						},
 						{
							name = "cloakskirm",
							x = 6601,
							z = 1509,
							facing = 1,
						},
 						{
							name = "turretmissile",
							x = 5744,
							z = 5728,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 8600,
							z = 5752,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 6496,
							z = 6400,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 6616,
							z = 216,
							facing = 0,
						},
 						{
							name = "jumpcon",
							x = 6607,
							z = 2872,
							facing = 3,
						},
 						{
							name = "cloakcon",
							x = 5556,
							z = 3589,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 5608,
							z = 2856,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5880, 2840}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5608, 2856}, options = {"shift"}},
							},
						},
 						{
							name = "cloakheavyraid",
							x = 7800,
							z = 1864,
							facing = 0,
						},
 						{
							name = "cloakcon",
							x = 5674,
							z = 2944,
							facing = 3,
						},
 						{
							name = "cloakcon",
							x = 5210,
							z = 4256,
							facing = 2,
						},
 						{
							name = "turretmissile",
							x = 7552,
							z = 1088,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 5936,
							z = 4928,
							facing = 3,
						},
 						{
							name = "jumpaa",
							x = 7487,
							z = 1309,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 6784,
							z = 608,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 8016,
							z = 6240,
							facing = 3,
						},
 						{
							name = "cloakcon",
							x = 5450,
							z = 3655,
							facing = 2,
						},
 						{
							name = "cloakarty",
							x = 5018,
							z = 793,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7816,
							z = 1544,
							facing = 3,
						},
 						{
							name = "jumpassault",
							x = 4399,
							z = 1600,
							facing = 3,
						},
 						{
							name = "striderdante",
							x = 4895,
							z = 3003,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 8856,
							z = 3272,
							facing = 3,
						},
 						{
							name = "planecon",
							x = 5443,
							z = 3717,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 6024,
							z = 4504,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {6024, 4504}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5588, 4487}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 7816,
							z = 1496,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7816, 1496}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7684, 1560}, options = {"shift"}},
							},
						},
 						{
							name = "jumpcon",
							x = 5471,
							z = 3659,
							facing = 3,
						},
 						{
							name = "cloakriot",
							x = 7631,
							z = 1434,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 6200,
							z = 824,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 5712,
							z = 5552,
							facing = 2,
						},
 						{
							name = "jumpraid",
							x = 4599,
							z = 3976,
							facing = 3,
						},
 						{
							name = "cloakcon",
							x = 6873,
							z = 1725,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7816,
							z = 1640,
							facing = 3,
						},
 						{
							name = "cloakheavyraid",
							x = 5562,
							z = 5189,
							facing = 3,
							patrolRoute = {
								{5574, 5139},
								{5550, 5201},
							},
						},
 						{
							name = "staticcon",
							x = 7880,
							z = 1592,
							facing = 3,
						},
 						{
							name = "cloakcon",
							x = 5380,
							z = 3583,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 7736,
							z = 856,
							facing = 3,
						},
 						{
							name = "cloakcon",
							x = 5718,
							z = 2808,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 5784,
							z = 5800,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 6048,
							z = 4624,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 5768,
							z = 5176,
							facing = 2,
						},
 						{
							name = "cloakcon",
							x = 5432,
							z = 6199,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 5864,
							z = 5608,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5864, 5608}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {5784, 5800}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 8872,
							z = 3320,
							facing = 3,
						},
 						{
							name = "cloaksnipe",
							x = 6721,
							z = 2238,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7832,
							z = 1448,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 6240,
							z = 4752,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 8824,
							z = 3368,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 5840,
							z = 5888,
							facing = 2,
						},
 						{
							name = "staticstorage",
							x = 8280,
							z = 2920,
							facing = 3,
						},
 						{
							name = "cloakheavyraid",
							x = 7686,
							z = 1560,
							facing = 3,
							buildProgress = 0.6613,
						},
 						{
							name = "staticcon",
							x = 7864,
							z = 1640,
							facing = 3,
						},
 						{
							name = "cloakcon",
							x = 6651,
							z = 2828,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7832,
							z = 1592,
							facing = 3,
						},
 						{
							name = "cloakcon",
							x = 6322,
							z = 3375,
							facing = 3,
						},
 						{
							name = "cloakraid",
							x = 7582,
							z = 1686,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 6248,
							z = 4664,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 5688,
							z = 5784,
							facing = 2,
							terraformHeight = 91,
						},
 						{
							name = "cloakheavyraid",
							x = 5503,
							z = 5201,
							facing = 3,
							patrolRoute = {
								{5552, 5199},
								{5488, 5193},
							},
						},
 						{
							name = "jumpcon",
							x = 6785,
							z = 2713,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 5880,
							z = 2840,
							facing = 3,
						},
 						{
							name = "cloakaa",
							x = 7054,
							z = 1905,
							facing = 0,
						},
 						{
							name = "jumpassault",
							x = 7552,
							z = 888,
							facing = 3,
							buildProgress = 0.27110001,
						},
					}
				},
				{
					humanName = "Chevalier",
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					allyTeam = 1,
					midgameUnits = {
						{
							name = "striderbantha",
							x = 8700,
							z = 1500,
							facing = 2,
							spawnRadius = 50,
							delay = 6*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 3,
						},
						{
							name = "striderbantha",
							x = 8700,
							z = 1500,
							facing = 2,
							spawnRadius = 50,
							delay = 13*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 2,
						},
						{
							name = "striderbantha",
							x = 8700,
							z = 1500,
							facing = 2,
							spawnRadius = 50,
							delay = 19*30*60,
							orbitalDrop = true,
						},
						{
							name = "striderbantha",
							x = 8700,
							z = 1500,
							facing = 2,
							spawnRadius = 50,
							delay = 19*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 4,
						},
						{
							name = "striderarty",
							x = 8700,
							z = 1500,
							facing = 2,
							spawnRadius = 50,
							delay = 5*30*60,
							orbitalDrop = true,
						},
						{
							name = "tankheavyassault",
							x = 8700,
							z = 1500,
							facing = 2,
							spawnRadius = 50,
							delay = 4*30*60,
							orbitalDrop = true,
							difficultyAtLeast = 3,
						},
						{
							name = "tankheavyassault",
							x = 8700,
							z = 1500,
							facing = 2,
							spawnRadius = 50,
							delay = 8*30*60,
							orbitalDrop = true,
						},
						{
							name = "tankheavyassault",
							x = 8700,
							z = 1500,
							facing = 2,
							spawnRadius = 50,
							delay = 12*30*60,
							orbitalDrop = true,
						},
					},
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energypylon",
						"staticstorage",
						--"turretmissile",
						"staticradar",
						"staticcon",
						"staticrearm",
						"factoryspider",
						"spidercon",
						"spiderscout",
						"spiderriot",
						"spideremp",
						"spiderskirm",
						"spiderassault",
						"spidercrabe",
						"spideraa",
						"factoryamph",
						"amphcon",
						"amphraid",
						"amphimpulse",
						"amphfloater",
						"amphriot",
						"amphassault",
						"amphaa",
						"factorytank",
						"tankassault",
						"tankarty",
						"tankheavyarty",
						"tankaa",
						"tankriot",
						--"striderhub",
						"striderdante",
						--"striderarty",
						--"striderbantha",
					},
					difficultyDependantUnlocks = {
						[4] = {"striderhub",}
					},
					commander = false,
					startUnits = {
						{
							name = "striderhub",
							x = 8432,
							z = 5936,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {8432, 5936}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {8407, 5911}, options = {"shift"}},
							},
						},
						{
							name = "staticcon",
							x = 8440,
							z = 5848,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {8440, 5848}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {8415, 5823}, options = {"shift"}},
							},
						},
 						{
							name = "staticcon",
							x = 8440,
							z = 6024,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {8440, 6024}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {8415, 5999}, options = {"shift"}},
							},
						},
						{
							name = "striderbantha",
							x = 8340,
							z = 6024,
							facing = 3,
							buildProgress = 0.1,
							difficultyAtLeast = 1,
							difficultyAtMost = 1,
						},
						{
							name = "striderbantha",
							x = 8340,
							z = 6024,
							facing = 3,
							buildProgress = 0.2,
							difficultyAtLeast = 2,
							difficultyAtMost = 2,
						},
						{
							name = "striderbantha",
							x = 8340,
							z = 6024,
							facing = 3,
							buildProgress = 0.3,
							difficultyAtLeast = 3,
							difficultyAtMost = 3,
						},
						{
							name = "striderbantha",
							x = 8340,
							z = 6024,
							facing = 3,
							buildProgress = 0.4,
							difficultyAtLeast = 4,
							difficultyAtMost = 4,
						},
						{
							name = "striderbantha",
							x = 8600,
							z = 6024,
							facing = 3,
							difficultyAtLeast = 2,
						},
						{
							name = "turretaaheavy",
							x = 8600,
							z = 6200,
							facing = 3,
						},
						{
							name = "staticstorage",
							x = 5600,
							z = 6300,
							facing = 1,
						},
						{
							name = "striderhub",
							x = 7888,
							z = 1200,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 7992,
							z = 1192,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 7064,
							z = 3688,
							facing = 3,
						},
 						{
							name = "factoryspider",
							x = 6936,
							z = 3688,
							facing = 3,
						},
 						{
							name = "staticstorage",
							x = 8088,
							z = 3400,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 6360,
							z = 5320,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 6232,
							z = 6456,
							facing = 3,
						},
 						{
							name = "turretaaflak",
							x = 6424,
							z = 6792,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 8696,
							z = 5208,
							facing = 0,
						},
 						{
							name = "turretgauss",
							x = 7640,
							z = 6184,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 8776,
							z = 4808,
							facing = 0,
						},
 						{
							name = "turretgauss",
							x = 7640,
							z = 6008,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 8344,
							z = 4664,
							facing = 0,
						},
 						{
							name = "turretaaclose",
							x = 7784,
							z = 5944,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 8632,
							z = 4344,
							facing = 0,
						},
 						{
							name = "turretaaclose",
							x = 7768,
							z = 6232,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 6528,
							z = 6096,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 7864,
							z = 4808,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 6528,
							z = 5856,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 7608,
							z = 4344,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 6344,
							z = 4360,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 6200,
							z = 6584,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 7240,
							z = 4696,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8760,
							z = 5960,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8440,
							z = 5656,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 6808,
							z = 5208,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 8232,
							z = 6312,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 7048,
							z = 6008,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 8040,
							z = 6632,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7592,
							z = 6312,
							facing = 0,
						},
 						{
							name = "turretantiheavy",
							x = 6592,
							z = 5968,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 8536,
							z = 4712,
							facing = 1,
						},
 						{
							name = "energyheavygeo",
							x = 7608,
							z = 5720,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 7976,
							z = 6216,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 8184,
							z = 5464,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 7704,
							z = 5032,
							facing = 3,
						},
 						{
							name = "turretheavy",
							x = 7432,
							z = 4216,
							facing = 3,
						},
 						{
							name = "staticheavyradar",
							x = 7008,
							z = 6240,
							facing = 3,
						},
 						{
							name = "staticantinuke",
							x = 7760,
							z = 6088,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 7640,
							z = 4696,
							facing = 3,
						},
 						{
							name = "factoryamph",
							x = 7560,
							z = 5000,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7288,
							z = 5896,
							facing = 3,
						},
 						{
							name = "staticantinuke",
							x = 8384,
							z = 4152,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 8200,
							z = 4136,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 8448,
							z = 4304,
							facing = 3,
						},
 						{
							name = "turretaalaser",
							x = 8472,
							z = 4008,
							facing = 3,
						},
 						{
							name = "factorytank",
							x = 7120,
							z = 5872,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 6168,
							z = 6728,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 5696,
							z = 3658,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 6701,
							z = 4528,
							facing = 3,
						},
 						{
							name = "tankriot",
							x = 5388,
							z = 3929,
							facing = 3,
						},
 						{
							name = "tankassault",
							x = 5391,
							z = 4058,
							facing = 1,
							difficultyAtLeast = 2,
						},
 						{
							name = "tankassault",
							x = 5727,
							z = 5408,
							facing = 2,
							patrolRoute = {
								{5706, 5413},
								{5761, 5446},
							},
						},
 						{
							name = "amphcon",
							x = 5979,
							z = 4969,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 6613,
							z = 3644,
							facing = 3,
						},
 						{
							name = "tankassault",
							x = 6328,
							z = 2821,
							facing = 0,
						},
 						{
							name = "amphcon",
							x = 5695,
							z = 4617,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 5352,
							z = 1128,
							facing = 0,
						},
 						{
							name = "spiderscout",
							x = 4307,
							z = 4195,
							facing = 0,
						},
 						{
							name = "tankassault",
							x = 6840,
							z = 5779,
							facing = 3,
						},
 						{
							name = "striderarty",
							x = 6437,
							z = 2211,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7240,
							z = 5848,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 5544,
							z = 2280,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 7240,
							z = 5944,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7240, 5944}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7092, 5872}, options = {"shift"}},
							},
						},
 						{
							name = "tankassault",
							x = 6773,
							z = 2627,
							facing = 3,
						},
 						{
							name = "tankassault",
							x = 3919,
							z = 5072,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 4712,
							z = 1128,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 4489,
							z = 4719,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 6080,
							z = 4848,
							facing = 3,
						},
 						{
							name = "spiderassault",
							x = 5646,
							z = 4154,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 4712,
							z = 1352,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5736,
							z = 5784,
							facing = 0,
							terraformHeight = 91,
						},
 						{
							name = "amphaa",
							x = 3930,
							z = 5747,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 7240,
							z = 5800,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7240, 5800}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7092, 5872}, options = {"shift"}},
							},
						},
 						{
							name = "amphraid",
							x = 4345,
							z = 4151,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 4744,
							z = 664,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6040,
							z = 4728,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 7912,
							z = 4856,
							facing = 3,
						},
 						{
							name = "spiderskirm",
							x = 5887,
							z = 4253,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 7304,
							z = 3000,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 5371,
							z = 4322,
							facing = 0,
						},
 						{
							name = "spiderscout",
							x = 4929,
							z = 3632,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 6296,
							z = 5464,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 7192,
							z = 2872,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 7064,
							z = 2840,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 5816,
							z = 2120,
							facing = 0,
						},
 						{
							name = "energywind",
							x = 6168,
							z = 5528,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 7792,
							z = 1248,
							facing = 3,
						},
 						{
							name = "tankassault",
							x = 5664,
							z = 5424,
							facing = 1,
							patrolRoute = {
								{5645, 5432},
								{5706, 5413},
							},
						},
 						{
							name = "amphraid",
							x = 4417,
							z = 4433,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 6392,
							z = 6584,
							facing = 0,
						},
 						{
							name = "staticstorage",
							x = 7848,
							z = 4856,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 5880,
							z = 2776,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 7192,
							z = 1480,
							facing = 3,
						},
 						{
							name = "spideraa",
							x = 5597,
							z = 3125,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 6200,
							z = 4760,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 6152,
							z = 2840,
							facing = 3,
						},
 						{
							name = "tankaa",
							x = 5430,
							z = 4099,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 6344,
							z = 6584,
							facing = 2,
						},
 						{
							name = "spiderscout",
							x = 4618,
							z = 3852,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 5285,
							z = 4604,
							facing = 3,
						},
 						{
							name = "spidercrabe",
							x = 5346,
							z = 3964,
							facing = 2,
						},
 						{
							name = "energypylon",
							x = 5976,
							z = 1608,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 7240,
							z = 5896,
							facing = 3,
						},
 						{
							name = "tankheavyassault",
							x = 3622,
							z = 5303,
							facing = 1,
						},
 						{
							name = "energywind",
							x = 6024,
							z = 6184,
							facing = 2,
						},
 						{
							name = "staticmex",
							x = 4728,
							z = 1256,
							facing = 0,
						},
 						{
							name = "staticcon",
							x = 7288,
							z = 5848,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 5592,
							z = 2152,
							facing = 0,
						},
 						{
							name = "tankassault",
							x = 4054,
							z = 5265,
							facing = 2,
							difficultyAtLeast = 2,
						},
 						{
							name = "spiderscout",
							x = 4427,
							z = 3933,
							facing = 3,
						},
 						{
							name = "staticradar",
							x = 4992,
							z = 1072,
							facing = 0,
						},
 						{
							name = "spidercrabe",
							x = 3672,
							z = 5537,
							facing = 3,
						},
 						{
							name = "amphraid",
							x = 4387,
							z = 3992,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 5056,
							z = 1232,
							facing = 0,
						},
 						{
							name = "tankassault",
							x = 3831,
							z = 5390,
							facing = 1,
							difficultyAtLeast = 2,
						},
 						{
							name = "amphcon",
							x = 7234,
							z = 4810,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 4824,
							z = 1080,
							facing = 0,
						},
 						{
							name = "amphraid",
							x = 4334,
							z = 4097,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 6632,
							z = 1576,
							facing = 3,
						},
 						{
							name = "energywind",
							x = 6504,
							z = 1576,
							facing = 0,
						},
 						{
							name = "spidercon",
							x = 5453,
							z = 3459,
							facing = 3,
						},
 						{
							name = "turretmissile",
							x = 4768,
							z = 1296,
							facing = 0,
						},
 						{
							name = "tankassault",
							x = 5776,
							z = 5373,
							facing = 0,
							patrolRoute = {
								{5743, 5361},
								{5704, 5414},
							},
						},
 						{
							name = "amphraid",
							x = 4329,
							z = 4232,
							facing = 3,
						},
 						{
							name = "tankassault",
							x = 5759,
							z = 5457,
							facing = 3,
							patrolRoute = {
								{5755, 5454},
								{5706, 5413},
							},
						},
 						{
							name = "amphcon",
							x = 6262,
							z = 4154,
							facing = 3,
						},
 						{
							name = "tankassault",
							x = 5847,
							z = 5547,
							facing = 3,
							difficultyAtLeast = 2,
						},
 						{
							name = "spiderscout",
							x = 4352,
							z = 4109,
							facing = 3,
						},
 						{
							name = "amphcon",
							x = 7524,
							z = 5000,
							facing = 3,
							buildProgress = 0.56290001,
						},
 						{
							name = "spidercon",
							x = 6900,
							z = 3688,
							facing = 3,
							buildProgress = 0.3599,
						},
 						{
							name = "tankassault",
							x = 7092,
							z = 5872,
							facing = 3,
							buildProgress = 0.2211,
						},
					}
				},
				{
					startX = 8580,
					startZ = 5800,
					humanName = "Enemy #3",
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					--aiLib = "Null AI",
					--bitDependant = false,
					commanderParameters = {
						facplop = false,
					},
					allyTeam = 1,
					commanderLevel = 6,
					commander = {
						name = "Blinder",
						chassis = "strike",
						modules = {
							"commweapon_heavymachinegun",
							"commweapon_multistunner",
							"module_autorepair",
							"module_autorepair",
							"module_autorepair",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_high_power_servos",
						},
					},
					startUnits = {
					}
				},
			},
			terraform = {
				{
					terraformShape = planetUtilities.TERRAFORM_SHAPE.RAMP,
					position = {1572, 273, 3906, 1876, 169, 3700},
					width = 250,
				},
			},
			defeatConditionConfig = {
				-- Indexed by allyTeam.
				[0] = { },
				[1] = {
					ignoreUnitLossDefeat = false,
					vitalCommanders = true,
					vitalUnitTypes = {
						"striderhub",
						"staticheavyarty",
						"striderbantha"
					},
					loseAfterSeconds = false,
					allyTeamLossObjectiveID = 1,
				},
			},
			objectiveConfig = {
				-- This is just related to displaying objectives on the UI.
				[1] = {
					description = "Destroy all enemy Paladins, Big Berthas and Strider Hubs",
				},
				[2] = {
					description = "Protect your Commander",
				},
			},
			bonusObjectiveConfig = {
				[1] = {
					satisfyOnce = true,
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 6,
					unitTypes = {
						"striderscorpion",
					},
					image = planetUtilities.ICON_DIR .. "striderscorpion.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.REPAIR,
					description = "Have 6 Scorpions",
					experience = planetUtilities.BONUS_EXP,
				},
				[2] = {
					victoryByTime = 25*60,
					image = planetUtilities.ICON_OVERLAY.CLOCK,
					description = "Win by 25:00",
					experience = planetUtilities.BONUS_EXP,
				},
				[3] = {
					satisfyOnce = true,
					comparisionType = planetUtilities.COMPARE.AT_MOST,
					targetNumber = 0,
					enemyUnitTypes = {
						"staticantinuke",
					},
					image = planetUtilities.ICON_DIR .. "staticantinuke.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.ATTACK,
					description = "Find and destroy all four enemy Antinukes",
					experience = planetUtilities.BONUS_EXP,
				},
			}
		},
		completionReward = {
			experience = planetUtilities.MAIN_EXP,
			units = {
				"striderhub",
				"striderscorpion",
			},
			modules = {
				"commweapon_multistunner",
			},
			abilities = {
			},
			codexEntries = {
				"faction_rebels",
				"location_karuwal"
			}
		},
	}
	
	return planetData
end

return GetPlanet
