--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Planet config

local function GetPlanet(planetUtilities, planetID)
	
	--local image = planetUtilities.planetImages[math.floor(math.random()*#planetUtilities.planetImages) + 1]
	local image = LUA_DIRNAME .. "images/planets/terran01.png"
	
	local planetData = {
		name = "Thibella",
		startingPlanet = false,
		mapDisplay = {
			x = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][1]) or 0.29,
			y = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][2]) or 0.65,
			image = image,
			size = planetUtilities.PLANET_SIZE_MAP,
		},
		infoDisplay = {
			image = image,
			size = planetUtilities.PLANET_SIZE_INFO,
			backgroundImage = planetUtilities.backgroundImages[math.floor(math.random()*#planetUtilities.backgroundImages) + 1],
			terrainType = "Terran",
			radius = "7200 km",
			primary = "Thibella",
			primaryType = "G3V",
			milRating = 2,
			feedbackLink = "http://zero-k.info/Forum/Thread/24429",
			text = "There is a battle raging for the control of this world, but without direction, it seems to have reached stalemate a long time ago."
			.. "\n "
			.. "\nOne side has recognized my IFF signal as friendly, strangely enough. If I can tip the fight in their favor, this should let me find out what is going on here."
			,
			extendedText = "If I can destroy this Big Bertha cannon here, it should open things up for my allies. The best method for eliminating may be those Scythes."
			.. "\n "
			.. "\nThis should be enough to tip the battle and give them control of this world."
		},
		tips = {
			{
				image = "unitpics/cloakheavyraid.png",
				text = [[Scythes are very good for picking off poorly defended high-value targets behind enemy lines. The Scythes will be decloaked if they attack, if they are damaged, or if they get too close to enemy units.]]
			},
			{
				image = "unitpics/staticheavyarty.png",
				text = [[The Big Bertha cannon wins battles by attrition. It's too inaccurate to hit a single target reliably, but in a large battle it will probably hit something with each shot. Watch the shell trajectory to work out where the Bertha is.]]
			},
			{
				image = "unitpics/turretsunlance.png",
				text = [[Sunlances are special turrets which cannot be built in a normal game. They fire a high-power disruptor beam which slows whatever they hit.]]
			},
		},
		gameConfig = {
			mapName = "Tabula-v6.1",
			playerConfig = {
				startX = 7500,
				startZ = 6500,
				allyTeam = 0,
				commanderParameters = {
					facplop = false,
					defeatIfDestroyedObjectiveID = 2,
				},
				extraUnlocks = {
					"cloakheavyraid",
				},
				startUnits = {
					{
						name = "staticmex",
						x = 7320,
						z = 6456,
						facing = 3,
					},
					{
						name = "staticmex",
						x = 7336,
						z = 6808,
						facing = 3,
					},
					{
						name = "staticmex",
						x = 7752,
						z = 6600,
						facing = 3,
					},
					{
						name = "energysolar",
						x = 7384,
						z = 6472,
						facing = 2,
					},
					{
						name = "energysolar",
						x = 7304,
						z = 6520,
						facing = 1,
					},
					{
						name = "energysolar",
						x = 7256,
						z = 6440,
						facing = 0,
					},
					{
						name = "energysolar",
						x = 7336,
						z = 6392,
						facing = 3,
					},
					{
						name = "energysolar",
						x = 7400,
						z = 6824,
						facing = 2,
					},
					{
						name = "energysolar",
						x = 7320,
						z = 6872,
						facing = 1,
					},
					{
						name = "energysolar",
						x = 7272,
						z = 6792,
						facing = 0,
					},
					{
						name = "energysolar",
						x = 7352,
						z = 6744,
						facing = 3,
					},
					{
						name = "energysolar",
						x = 7816,
						z = 6616,
						facing = 2,
					},
					{
						name = "energysolar",
						x = 7736,
						z = 6664,
						facing = 1,
					},
					{
						name = "energysolar",
						x = 7688,
						z = 6584,
						facing = 0,
					},
					{
						name = "energysolar",
						x = 7768,
						z = 6536,
						facing = 3,
					},
					{
						name = "factorycloak",
						x = 7848,
						z = 6328,
						facing = 2,
					},
					{
						name = "cloakheavyraid",
						x = 7848,
						z = 6128,
						facing = 2,
					},
					{
						name = "cloakheavyraid",
						x = 7648,
						z = 6128,
						facing = 2,
					},
					{
						name = "cloakheavyraid",
						x = 8048,
						z = 6128,
						facing = 2,
					},
					{
						name = "cloakheavyraid",
						x = 7848,
						z = 5928,
						facing = 2,
					},
					{
						name = "cloakheavyraid",
						x = 7648,
						z = 5928,
						facing = 2,
					},
					{
						name = "cloakheavyraid",
						x = 8048,
						z = 5928,
						facing = 2,
					},
				}
			},
			aiConfig = {
				{
					startX = 7700,
					startZ = 1200,
					aiLib = "Circuit_difficulty_autofill_ally",
					humanName = "Ally",
					bitDependant = true, -- Whether the AI name needs to be appended with 32bit or 64bit by the handler
					allyTeam = 0,
					unlocks = {
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turretheavylaser",
						"turretaalaser",
						"staticradar",
						"staticmex",
						"staticcon",
						"staticstorage",
						"energypylon",
						"energysolar",
						"factorygunship",
						"gunshipcon",
						"gunshipbomb",
						"gunshipemp",
						"gunshipheavyskirm",
						"gunshipraid",
						"gunshipassault",
						"gunshipaa",
						"gunshipskirm",
						"factoryveh",
						"vehcon",
						"vehscout",
						"vehraid",
						"vehassault",
						"vehriot",
						"vehsupport",
						"veharty",
						--"vehheavyarty", might destroy a Sunlance
						"vehaa",
						"factoryhover",
						"hovercon",
						"hoverraid",
						"hoverriot",
						"hoverskirm",
						"hoverassault",
						"hoverarty", -- probably won't destroy a Sunlance
                        "hoverheavyraid",
						"hoveraa",
						"factoryspider",
						"spidercon",
						"spiderscout",
						"spiderskirm",
						"spideremp",
						"spiderriot",
						"spiderassault",
						"spidercrabe",
						"spideraa",
					},
					commander = false,
					startUnits = {
						{
							name = "staticstorage",
							x = 8100,
							z = 1000,
							facing = 0,
						},
						{
							name = "staticstorage",
							x = 8100,
							z = 4500,
							facing = 0,
						},
						{
							name = "staticstorage",
							x = 8100,
							z = 2400,
							facing = 0,
							
						},
						{
							name = "energypylon",
							x = 5880,
							z = 3176,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 5416,
							z = 3960,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 6280,
							z = 4100,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 6500,
							z = 3200,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 7000,
							z = 4000,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 7360,
							z = 3200,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 7930,
							z = 3520,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 5748,
							z = 6760,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 4936,
							z = 6504,
							facing = 0,
						},
						{
							name = "energygeo",
							x = 5600,
							z = 7028,
							facing = 0,
						},
						{
							name = "energyfusion",
							x = 6200,
							z = 7000,
							facing = 0,
						},
						{
							name = "energyfusion",
							x = 8120,
							z = 3300,
							facing = 0,
						},
						{
							name = "energyfusion",
							x = 8120,
							z = 3550,
							facing = 0,
						},
						{
							name = "energyfusion",
							x = 8120,
							z = 3800,
							facing = 0,
						},
						{
							name = "turretheavy",
							x = 4616,
							z = 6280,
							facing = 0,
						},
						{
							name = "turretsunlance",
							x = 4950,
							z = 4100,
							facing = 0,
						},
						{
							name = "turretsunlance",
							x = 5536,
							z = 2832,
							facing = 0,
						},
						{
							name = "turretantiheavy",
							x = 5584,
							z = 3552,
							facing = 0,
						},
						{	-- corresponds to Team 1
							name = "staticmex",
							x = 7816,
							z = 1032,
							facing = 0,
						},
						{
							name = "factorygunship",
							x = 7816,
							z = 1288,
							facing = 1,
						},
						{
							name = "gunshipskirm",
							x = 5216,
							z = 1908,
							facing = 3,
						},
						{
							name = "staticmex",
							x = 7496,
							z = 808,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 7480,
							z = 872,
							facing = 3,
						},
						{
							name = "gunshipcon",
							x = 7193,
							z = 5477,
							facing = 0,
						},
						{
							name = "turretlaser",
							x = 7728,
							z = 736,
							facing = 3,
						},
						{
							name = "staticmex",
							x = 7736,
							z = 520,
							facing = 0,
						},
						{
							name = "staticradar",
							x = 7680,
							z = 912,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 7680,
							z = 1344,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 5288,
							z = 680,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 7816,
							z = 968,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 7632,
							z = 2576,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 7880,
							z = 1064,
							facing = 3,
						},
						{
							name = "staticmex",
							x = 6312,
							z = 2808,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 7800,
							z = 1096,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 7680,
							z = 1216,
							facing = 3,
						},
						{
							name = "staticcon",
							x = 7672,
							z = 1304,
							facing = 3,
						},
						{
							name = "staticmex",
							x = 5960,
							z = 760,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 5224,
							z = 696,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 5256,
							z = 760,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 5160,
							z = 648,
							facing = 0,
						},
						{
							name = "gunshipcon",
							x = 6590,
							z = 3613,
							facing = 2,
						},
						{
							name = "turretlaser",
							x = 6752,
							z = 1824,
							facing = 3,
						},
						{
							name = "staticradar",
							x = 6032,
							z = 864,
							facing = 0,
						},
						{
							name = "gunshipaa",
							x = 5154,
							z = 806,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 6680,
							z = 1544,
							facing = 3,
						},
						{
							name = "gunshipaa",
							x = 4428,
							z = 4410,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 5904,
							z = 800,
							facing = 0,
						},
						{
							name = "gunshipassault",
							x = 5784,
							z = 2812,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 4904,
							z = 1528,
							facing = 0,
						},
						{
							name = "turretmissile",
							x = 7536,
							z = 1904,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 5984,
							z = 2704,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 6376,
							z = 2936,
							facing = 3,
						},
						{
							name = "staticmex",
							x = 5304,
							z = 3224,
							facing = 0,
						},
						{
							name = "staticcon",
							x = 7672,
							z = 1256,
							facing = 3,
						},
						{
							name = "gunshipskirm",
							x = 4133,
							z = 35,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 5272,
							z = 3160,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 7064,
							z = 2152,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 5240,
							z = 3240,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 7896,
							z = 984,
							facing = 3,
						},
						{
							name = "gunshipaa",
							x = 5156,
							z = 885,
							facing = 3,
						},
						{
							name = "turretmissile",
							x = 7824,
							z = 1840,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 6032,
							z = 4032,
							facing = 3,
						},
						{
							name = "gunshipaa",
							x = 5155,
							z = 873,
							facing = 3,
						},
						{
							name = "gunshipaa",
							x = 5153,
							z = 841,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 5088,
							z = 4688,
							facing = 2,
						},
						{
							name = "turretmissile",
							x = 7600,
							z = 1760,
							facing = 3,
						},
						{
							name = "turretmissile",
							x = 7664,
							z = 1856,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 5296,
							z = 5520,
							facing = 2,
						},
						{
							name = "turretmissile",
							x = 7744,
							z = 1760,
							facing = 3,
						},
						{
							name = "turretmissile",
							x = 7488,
							z = 1760,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 5984,
							z = 6096,
							facing = 2,
						},
						{
							name = "turretmissile",
							x = 7424,
							z = 1888,
							facing = 3,
						},
						{
							name = "turretmissile",
							x = 7632,
							z = 1968,
							facing = 3,
						},
						{
							name = "staticcon",
							x = 4744,
							z = 5896,
							facing = 2,
							buildProgress = 0.20900001,
						},
						{
							name = "turretmissile",
							x = 7520,
							z = 2016,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 7456,
							z = 4464,
							facing = 3,
						},
						{
							name = "turretmissile",
							x = 7744,
							z = 1936,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 6944,
							z = 4816,
							facing = 3,
						},
						{
							name = "turretmissile",
							x = 7552,
							z = 1648,
							facing = 3,
						},
						{
							name = "turretmissile",
							x = 7680,
							z = 1664,
							facing = 3,
						},
						{
							name = "turretmissile",
							x = 7408,
							z = 2000,
							facing = 3,
							buildProgress = 0.108,
						},
						{	-- corresponds to Team 2
							name = "staticmex",
							x = 7912,
							z = 2840,
							facing = 0,
						},
						{
							name = "factoryveh",
							x = 7752,
							z = 2728,
							facing = 3,
						},
						{
							name = "staticmex",
							x = 7512,
							z = 2952,
							facing = 0,
						},
						{
							name = "vehassault",
							x = 4586,
							z = 2160,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 7448,
							z = 2968,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 7744,
							z = 2576,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 7032,
							z = 2024,
							facing = 3,
						},
						{
							name = "staticmex",
							x = 7544,
							z = 2424,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 6696,
							z = 1608,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 6984,
							z = 2120,
							facing = 3,
						},
						{
							name = "vehcon",
							x = 6612,
							z = 3291,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 7608,
							z = 2456,
							facing = 3,
						},
						{
							name = "vehriot",
							x = 6635,
							z = 2414,
							facing = 3,
						},
						{
							name = "staticmex",
							x = 7048,
							z = 2088,
							facing = 0,
						},
						{
							name = "vehcon",
							x = 6919,
							z = 2739,
							facing = 3,
						},
						{
							name = "vehscout",
							x = 3847,
							z = 5510,
							facing = 3,
						},
						{
							name = "staticradar",
							x = 7856,
							z = 2720,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 4104,
							z = 152,
							facing = 0,
						},
						{
							name = "turretlaser",
							x = 7744,
							z = 2880,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 6952,
							z = 2040,
							facing = 3,
						},
						{
							name = "vehaa",
							x = 6866,
							z = 3427,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 6744,
							z = 1672,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 6760,
							z = 1592,
							facing = 3,
						},
						{
							name = "staticmex",
							x = 5736,
							z = 2536,
							facing = 0,
						},
						{
							name = "staticcon",
							x = 7928,
							z = 2744,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 5048,
							z = 2360,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 7112,
							z = 2040,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 5752,
							z = 2600,
							facing = 3,
						},
						{
							name = "vehcon",
							x = 6520,
							z = 2822,
							facing = 3,
						},
						{
							name = "vehcon",
							x = 6711,
							z = 3146,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 6376,
							z = 2856,
							facing = 3,
						},
						{
							name = "vehcon",
							x = 4249,
							z = 4363,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 7464,
							z = 3048,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 4968,
							z = 2376,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 7528,
							z = 2488,
							facing = 3,
						},
						{
							name = "vehaa",
							x = 4769,
							z = 2171,
							facing = 1,
						},
						{
							name = "vehcon",
							x = 5320,
							z = 3991,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 6296,
							z = 2872,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 6280,
							z = 2744,
							facing = 3,
						},
						{
							name = "staticcon",
							x = 7880,
							z = 2792,
							facing = 3,
						},
						{
							name = "staticcon",
							x = 7928,
							z = 2696,
							facing = 3,
						},
						{
							name = "veharty",
							x = 5833,
							z = 2871,
							facing = 1,
						},
						{
							name = "vehriot",
							x = 6429,
							z = 2973,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 4888,
							z = 2232,
							facing = 0,
						},
						{
							name = "vehcon",
							x = 5234,
							z = 4121,
							facing = 3,
						},
						{
							name = "vehassault",
							x = 5517,
							z = 2125,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 6360,
							z = 2696,
							facing = 3,
						},
						{
							name = "vehcon",
							x = 6068,
							z = 2626,
							facing = 3,
						},
						{
							name = "vehscout",
							x = 3144,
							z = 6342,
							facing = 0,
						},
						{
							name = "vehcon",
							x = 5062,
							z = 4401,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 6216,
							z = 2856,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 4432,
							z = 4416,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 6376,
							z = 2776,
							facing = 3,
						},
						{
							name = "turretaalaser",
							x = 4136,
							z = 4344,
							facing = 2,
						},
						{
							name = "vehriot",
							x = 6430,
							z = 2574,
							facing = 2,
						},
						{
							name = "vehraid",
							x = 7567,
							z = 2526,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 7544,
							z = 3016,
							facing = 3,
						},
						{
							name = "wolverine_mine",
							x = 4408,
							z = 3448,
							facing = 0,
						},
						{
							name = "vehscout",
							x = 6159,
							z = 1952,
							facing = 3,
						},
						{
							name = "vehcon",
							x = 7671,
							z = 3055,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 5272,
							z = 3848,
							facing = 3,
							buildProgress = 0.79280001,
						},
						{
							name = "vehriot",
							x = 7724,
							z = 2728,
							facing = 3,
							buildProgress = 0.87300003,
						},
						{
							name = "turretlaser",
							x = 4128,
							z = 4464,
							facing = 2,
							buildProgress = 0.1166,
						},
						{	-- corresponds to Team 3
							name = "staticmex",
							x = 7880,
							z = 4568,
							facing = 0,
						},
						{
							name = "factoryhover",
							x = 7696,
							z = 4560,
							facing = 3,
						},
						{
							name = "hoveraa",
							x = 3636,
							z = 5276,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 7512,
							z = 4856,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 7448,
							z = 4840,
							facing = 3,
						},
						{
							name = "hoverraid",
							x = 4769,
							z = 5557,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 7576,
							z = 4200,
							facing = 0,
						},
						{
							name = "staticradar",
							x = 7808,
							z = 4592,
							facing = 3,
						},
						{
							name = "turretlaser",
							x = 7696,
							z = 4400,
							facing = 3,
						},
						{
							name = "hovercon",
							x = 4806,
							z = 4770,
							facing = 2,
						},
						{
							name = "staticmex",
							x = 6904,
							z = 4888,
							facing = 0,
						},
						{
							name = "hoverskirm",
							x = 4643,
							z = 4517,
							facing = 2,
						},
						{
							name = "staticmex",
							x = 6104,
							z = 4024,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 7560,
							z = 4264,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 7512,
							z = 4184,
							facing = 3,
						},
						{
							name = "staticmex",
							x = 5464,
							z = 4440,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 5704,
							z = 5304,
							facing = 0,
						},
						{
							name = "staticradar",
							x = 6176,
							z = 4064,
							facing = 3,
						},
						{
							name = "staticcon",
							x = 5480,
							z = 4760,
							facing = 3,
							buildProgress = 0.81209999,
						},
						{
							name = "energysolar",
							x = 6120,
							z = 3960,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 6040,
							z = 3976,
							facing = 3,
						},
						{
							name = "hoverskirm",
							x = 3527,
							z = 5014,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 6120,
							z = 3880,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 6088,
							z = 4088,
							facing = 3,
						},
						{
							name = "staticmex",
							x = 4872,
							z = 4760,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 6200,
							z = 3960,
							facing = 3,
						},
						{
							name = "hovercon",
							x = 5416,
							z = 4621,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 5208,
							z = 3800,
							facing = 0,
						},
						{
							name = "turretlaser",
							x = 7696,
							z = 4720,
							facing = 3,
						},
						{
							name = "hoverskirm",
							x = 3860,
							z = 4645,
							facing = 2,
						},
						{
							name = "staticcon",
							x = 7880,
							z = 4616,
							facing = 3,
						},
						{
							name = "staticmex",
							x = 4904,
							z = 2328,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 4888,
							z = 2392,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 7816,
							z = 4504,
							facing = 3,
						},
						{
							name = "hovercon",
							x = 3632,
							z = 4805,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 7944,
							z = 4552,
							facing = 3,
						},
						{
							name = "hovercon",
							x = 5162,
							z = 2533,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 7896,
							z = 4472,
							facing = 3,
						},
						{
							name = "staticcon",
							x = 7832,
							z = 4664,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 4968,
							z = 2296,
							facing = 0,
						},
						{
							name = "hoverskirm",
							x = 4797,
							z = 4853,
							facing = 2,
						},
						{
							name = "hoverraid",
							x = 6119,
							z = 3511,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 7560,
							z = 4744,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 7976,
							z = 4472,
							facing = 3,
						},
						{
							name = "hoverriot",
							x = 5636,
							z = 3383,
							facing = 0,
						},
						{
							name = "hoverriot",
							x = 6343,
							z = 3669,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 4840,
							z = 2312,
							facing = 0,
						},
						{
							name = "hovercon",
							x = 5453,
							z = 4643,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 7576,
							z = 4824,
							facing = 3,
						},
						{
							name = "hovercon",
							x = 6819,
							z = 3979,
							facing = 3,
						},
						{
							name = "hoverskirm",
							x = 3453,
							z = 4855,
							facing = 2,
						},
						{
							name = "hovercon",
							x = 5358,
							z = 4686,
							facing = 1,
						},
						{
							name = "factoryhover",
							x = 5344,
							z = 4784,
							facing = 3,
						},
						{
							name = "hoverriot",
							x = 6359,
							z = 3629,
							facing = 3,
						},
						{
							name = "hoveraa",
							x = 3366,
							z = 4850,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 4344,
							z = 5896,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 7640,
							z = 4184,
							facing = 3,
						},
						{
							name = "hovercon",
							x = 4291,
							z = 4231,
							facing = 3,
						},
						{
							name = "hoverraid",
							x = 3484,
							z = 6234,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 5024,
							z = 2416,
							facing = 0,
						},
						{
							name = "hoverraid",
							x = 5378,
							z = 3156,
							facing = 2,
						},
						{
							name = "turretmissile",
							x = 5184,
							z = 2688,
							facing = 0,
						},
						{
							name = "hovercon",
							x = 7168,
							z = 4299,
							facing = 3,
						},
						{
							name = "hoveraa",
							x = 7696,
							z = 4560,
							facing = 3,
							buildProgress = 0.75709999,
						},
						{
							name = "hoveraa",
							x = 5344,
							z = 4784,
							facing = 3,
							buildProgress = 0.13330001,
						},
						{
							name = "staticcon",
							x = 5128,
							z = 2408,
							facing = 0,
							buildProgress = 0.0333,
						},
						{	-- corresponds to Team 4
							name = "staticmex",
							x = 5880,
							z = 6200,
							facing = 0,
						},
						{
							name = "factoryspider",
							x = 5992,
							z = 5944,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 5928,
							z = 6136,
							facing = 2,
						},
						{
							name = "staticmex",
							x = 6088,
							z = 6936,
							facing = 0,
						},
						{
							name = "turretlaser",
							x = 5856,
							z = 5888,
							facing = 2,
						},
						{
							name = "staticmex",
							x = 5128,
							z = 5624,
							facing = 0,
						},
						{
							name = "spiderriot",
							x = 5073,
							z = 5180,
							facing = 3,
						},
						{
							name = "staticradar",
							x = 5840,
							z = 6176,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 5816,
							z = 6264,
							facing = 2,
						},
						{
							name = "staticmex",
							x = 4168,
							z = 7000,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 5896,
							z = 6264,
							facing = 2,
						},
						{
							name = "spidercon",
							x = 4110,
							z = 4511,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 6008,
							z = 6152,
							facing = 2,
						},
						{
							name = "spidercon",
							x = 4501,
							z = 5984,
							facing = 3,
						},
						{
							name = "staticheavyradar",
							x = 6144,
							z = 4784,
							facing = 0,
						},
						{
							name = "spiderskirm",
							x = 3857,
							z = 4190,
							facing = 1,
						},
						{
							name = "spiderskirm",
							x = 3980,
							z = 4518,
							facing = 3,
						},
						{
							name = "staticmex",
							x = 4840,
							z = 6280,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 4232,
							z = 5976,
							facing = 2,
						},
						{
							name = "staticcon",
							x = 5832,
							z = 5928,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 5752,
							z = 6184,
							facing = 2,
						},
						{
							name = "staticmex",
							x = 3304,
							z = 5656,
							facing = 0,
						},
						{
							name = "spideraa",
							x = 3802,
							z = 4895,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 4216,
							z = 5896,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 5976,
							z = 6232,
							facing = 2,
						},
						{
							name = "turretlaser",
							x = 5984,
							z = 5792,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 4792,
							z = 6392,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 4888,
							z = 4696,
							facing = 2,
						},
						{
							name = "staticcon",
							x = 5880,
							z = 5944,
							facing = 2,
						},
						{
							name = "spiderskirm",
							x = 4204,
							z = 4295,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 5192,
							z = 5624,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 4152,
							z = 5976,
							facing = 2,
						},
						{
							name = "spiderscout",
							x = 3824,
							z = 4905,
							facing = 2,
						},
						{
							name = "spiderscout",
							x = 4616,
							z = 3378,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 4776,
							z = 6312,
							facing = 2,
						},
						{
							name = "spiderscout",
							x = 4229,
							z = 1564,
							facing = 1,
						},
						{
							name = "spidercon",
							x = 6415,
							z = 5647,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 4312,
							z = 5976,
							facing = 2,
						},
						{
							name = "staticcon",
							x = 5896,
							z = 5896,
							facing = 2,
						},
						{
							name = "spideraa",
							x = 3472,
							z = 5508,
							facing = 2,
						},
						{
							name = "spiderscout",
							x = 3770,
							z = 710,
							facing = 3,
						},
						{
							name = "staticradar",
							x = 4352,
							z = 6880,
							facing = 2,
						},
						{
							name = "spiderscout",
							x = 3969,
							z = 1507,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 3368,
							z = 5624,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 5848,
							z = 6088,
							facing = 2,
						},
						{
							name = "spiderassault",
							x = 3276,
							z = 5142,
							facing = 3,
						},
						{
							name = "spidercon",
							x = 2599,
							z = 5477,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 5736,
							z = 6264,
							facing = 2,
						},
						{
							name = "spiderskirm",
							x = 4519,
							z = 4708,
							facing = 3,
						},
						{
							name = "spidercon",
							x = 3840,
							z = 4883,
							facing = 1,
						},
						{
							name = "staticradar",
							x = 7488,
							z = 6576,
							facing = 3,
						},
						{
							name = "spideraa",
							x = 4916,
							z = 5761,
							facing = 3,
						},
						{
							name = "spideraa",
							x = 3457,
							z = 5570,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 4200,
							z = 6936,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 4904,
							z = 6312,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 5784,
							z = 6392,
							facing = 2,
						},
						{
							name = "spiderscout",
							x = 4127,
							z = 1556,
							facing = 0,
						},
						{
							name = "spiderscout",
							x = 4119,
							z = 1622,
							facing = 0,
						},
						{
							name = "spiderscout",
							x = 4120,
							z = 1282,
							facing = 0,
						},
						{
							name = "spiderscout",
							x = 3975,
							z = 905,
							facing = 2,
						},
						{
							name = "spiderscout",
							x = 4111,
							z = 1675,
							facing = 0,
						},
						{
							name = "factoryspider",
							x = 4280,
							z = 4584,
							facing = 2,
						},
						{
							name = "spiderscout",
							x = 3984,
							z = 934,
							facing = 3,
						},
						{
							name = "spidercon",
							x = 5269,
							z = 4518,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 4840,
							z = 6216,
							facing = 2,
						},
						{
							name = "spidercon",
							x = 6051,
							z = 6072,
							facing = 2,
						},
						{
							name = "spiderskirm",
							x = 5883,
							z = 6007,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 5976,
							z = 6312,
							facing = 2,
						},
						{
							name = "spidercon",
							x = 6028,
							z = 5944,
							facing = 1,
							buildProgress = 0.59630001,
						},
						{
							name = "spidercon",
							x = 4280,
							z = 4548,
							facing = 2,
							buildProgress = 0.0983,
						},
					},
				},
				{
					startX = 1200,
					startZ = 1200,
					aiLib = "Circuit_difficulty_autofill",
					humanName = "Enemy",
					bitDependant = true, -- Whether the AI name needs to be appended with 32bit or 64bit by the handler
					commanderParameters = {
						facplop = false,
					},
					allyTeam = 1,
					unlocks = {
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turretheavylaser",
						"turretaalaser",
						"staticradar",
						"staticmex",
						"staticcon",
						"staticstorage",
						"energypylon",
						"energysolar",
						"factorygunship",
						"gunshipcon",
						"gunshipbomb",
						"gunshipemp",
						"gunshipheavyskirm",
						"gunshipraid",
						"gunshipassault",
						"gunshipaa",
						"gunshipskirm",
						"factoryveh",
						"vehcon",
						"vehscout",
						"vehraid",
						"vehassault",
						"vehriot",
						"vehsupport",
						"veharty",
						"vehheavyarty",
						"vehaa",
						"factoryshield",
						"shieldcon",
						"shieldraid",
						"shieldassault",
						"shieldskirm",
						"shieldarty",
						"shieldfelon",
						"shieldaa",
						"factorytank",
						"tankcon",
						"tankraid",
						"tankheavyraid",
						"tankriot",
						"tankassault",
						"tankheavyassault",
						"tankarty",
						"tankaa"
					},
					difficultyDependantUnlocks = {
						[2] = {"shieldriot"},
						[3] = {"shieldriot","shieldbomb"},
						[4] = {"shieldriot","shieldbomb"},
					},
					commanderLevel = 1,
					commander = {
						name = "Labrador",
						chassis = "engineer",
						decorations = {},
						modules = {
						  {
							"commweapon_shotgun",
							"module_radarnet"
						  },
						},
					},
					startUnits = {
						{
							name = "staticantinuke",
							x = 730,
							z = 1535,
							facing = 0,
						},
						{
							name = "staticheavyradar",
							x = 2208,
							z = 2192,
							facing = 0,
						},
						{
							name = "staticheavyarty",
							x = 2064,
							z = 2336,
							facing = 0,
						},
						{
							name = "turretlaser",
							x = 1964,
							z = 2236,
							facing = 2,
							difficultyAtMost = 1,
							difficultyAtLeast = 1,
						},
						{
							name = "turretlaser",
							x = 2164,
							z = 2136,
							facing = 2,
							difficultyAtMost = 2,
							difficultyAtLeast = 2,
						},
						{
							name = "turretlaser",
							x = 1964,
							z = 2336,
							facing = 2,
							difficultyAtMost = 3,
							difficultyAtLeast = 2,
						},
						{
							name = "turretriot",
							x = 2164,
							z = 2136,
							facing = 2,
							difficultyAtLeast = 3,
						},
						{
							name = "turretriot",
							x = 1964,
							z = 2336,
							facing = 2,
							difficultyAtLeast = 4,
						},
						{
							name = "staticstorage",
							x = 100,
							z = 6300,
							facing = 0,
						},
						{
							name = "staticstorage",
							x = 100,
							z = 4500,
							facing = 0,
						},
						{
							name = "staticstorage",
							x = 100,
							z = 3000,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 2920,
							z = 2680,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 2500,
							z = 3160,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 2400,
							z = 3750,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 2000,
							z = 2600,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 1100,
							z = 2600,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 400,
							z = 2400,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 1900,
							z = 4000,
							facing = 0,
						},
						{
							name = "energypylon",
							x = 1500,
							z = 4700,
							facing = 0,
						},
						{
							name = "energyfusion",
							x = 1700,
							z = 4800,
							facing = 0,
						},
						{
							name = "energyfusion",
							x = 1440,
							z = 5100,
							facing = 0,
						},
						{
							name = "energyfusion",
							x = 120,
							z = 2600,
							facing = 0,
						},
						{
							name = "energyfusion",
							x = 120,
							z = 2750,
							facing = 0,
						},
						{
							name = "turretsunlance",
							x = 3376,
							z = 2848,
							facing = 0,
							--bonusObjectiveID = 3,
						},
						{
							name = "turretsunlance",
							x = 2688,
							z = 4160,
							facing = 0,
							--bonusObjectiveID = 3,
						},
						{	-- corresponds to Team 5
							name = "factorygunship",
							x = 1240,
							z = 6936,
							facing = 0,
						},
						{
							name = "gunshipaa",
							x = 4755,
							z = 2965,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 472,
							z = 6664,
							facing = 0,
						},
						{
							name = "gunshipaa",
							x = 2282,
							z = 6426,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 408,
							z = 6696,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 456,
							z = 6600,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 712,
							z = 6376,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 392,
							z = 6152,
							facing = 0,
						},
						{
							name = "turretlaser",
							x = 1104,
							z = 6880,
							facing = 2,
						},
						{
							name = "gunshipskirm",
							x = 2237,
							z = 5386,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 1344,
							z = 5328,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 2248,
							z = 6424,
							facing = 0,
						},
						{
							name = "staticradar",
							x = 1344,
							z = 5504,
							facing = 1,
						},
						{
							name = "gunshipaa",
							x = 2185,
							z = 6143,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 728,
							z = 6440,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 808,
							z = 6408,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 760,
							z = 6248,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 648,
							z = 6424,
							facing = 1,
						},
						{
							name = "gunshipskirm",
							x = 2161,
							z = 5216,
							facing = 0,
						},
						{
							name = "turretlaser",
							x = 1232,
							z = 6784,
							facing = 2,
						},
						{
							name = "turretlaser",
							x = 2928,
							z = 6528,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 2808,
							z = 2712,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 648,
							z = 6344,
							facing = 1,
						},
						{
							name = "staticcon",
							x = 1160,
							z = 6744,
							facing = 2,
						},
						{
							name = "gunshipskirm",
							x = 2215,
							z = 4925,
							facing = 0,
						},
						{
							name = "turretlaser",
							x = 416,
							z = 4448,
							facing = 1,
						},
						{
							name = "gunshipcon",
							x = 2762,
							z = 1841,
							facing = 2,
						},
						{
							name = "gunshipcon",
							x = 1196,
							z = 5911,
							facing = 2,
						},
						{
							name = "staticradar",
							x = 2752,
							z = 6528,
							facing = 2,
						},
						{
							name = "gunshipaa",
							x = 2210,
							z = 6225,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 2984,
							z = 6552,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 2968,
							z = 6424,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 776,
							z = 6328,
							facing = 1,
						},
						{
							name = "gunshipaa",
							x = 2089,
							z = 6259,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 312,
							z = 4280,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 2872,
							z = 6520,
							facing = 2,
						},
						{
							name = "staticmex",
							x = 2984,
							z = 6488,
							facing = 0,
						},
						{
							name = "turretlaser",
							x = 736,
							z = 2528,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 1280,
							z = 2352,
							facing = 1,
						},
						{
							name = "staticcon",
							x = 1416,
							z = 6888,
							facing = 2,
						},
						{
							name = "turretmissile",
							x = 1744,
							z = 6496,
							facing = 2,
						},
						{
							name = "turretlaser",
							x = 3152,
							z = 2624,
							facing = 0,
						},
						{
							name = "turretmissile",
							x = 1744,
							z = 6384,
							facing = 2,
						},
						{
							name = "turretlaser",
							x = 2736,
							z = 1712,
							facing = 0,
							buildProgress = 0.0361,
						},
						{	-- corresponds to Team 6
							name = "staticmex",
							x = 664,
							z = 4760,
							facing = 0,
						},
						{
							name = "factoryveh",
							x = 600,
							z = 4568,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 696,
							z = 4232,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 744,
							z = 4136,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 1224,
							z = 5048,
							facing = 1,
						},
						{
							name = "vehcon",
							x = 4247,
							z = 1779,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 600,
							z = 4808,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 728,
							z = 4744,
							facing = 1,
						},
						{
							name = "vehcon",
							x = 3721,
							z = 2369,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 1160,
							z = 5096,
							facing = 0,
						},
						{
							name = "vehassault",
							x = 3611,
							z = 2861,
							facing = 3,
						},
						{
							name = "vehassault",
							x = 3707,
							z = 3473,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 528,
							z = 4432,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 1512,
							z = 5576,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 1544,
							z = 5640,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 1144,
							z = 5160,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 1896,
							z = 4376,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 808,
							z = 4744,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 2472,
							z = 4648,
							facing = 0,
						},
						{
							name = "vehcon",
							x = 2958,
							z = 4663,
							facing = 1,
						},
						{
							name = "staticcon",
							x = 488,
							z = 4552,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 760,
							z = 4216,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 2472,
							z = 4584,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 448,
							z = 4560,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 712,
							z = 4824,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 1096,
							z = 5080,
							facing = 1,
						},
						{
							name = "vehaa",
							x = 3208,
							z = 5321,
							facing = 3,
						},
						{
							name = "staticcon",
							x = 456,
							z = 4600,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 376,
							z = 6088,
							facing = 1,
						},
						{
							name = "veharty",
							x = 2906,
							z = 4507,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 2048,
							z = 3088,
							facing = 1,
						},
						{
							name = "turretmissile",
							x = 2880,
							z = 3744,
							facing = 1,
						},
						{
							name = "vehaa",
							x = 3354,
							z = 5219,
							facing = 2,
						},
						{
							name = "vehraid",
							x = 843,
							z = 4423,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 456,
							z = 6088,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 2856,
							z = 3896,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 456,
							z = 6168,
							facing = 1,
						},
						{
							name = "vehaa",
							x = 1016,
							z = 4576,
							facing = 3,
						},
						{
							name = "staticcon",
							x = 440,
							z = 4520,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 336,
							z = 6272,
							facing = 1,
						},
						{
							name = "staticcon",
							x = 2712,
							z = 3592,
							facing = 1,
						},
						{
							name = "staticradar",
							x = 432,
							z = 6336,
							facing = 1,
						},
						{
							name = "vehassault",
							x = 2397,
							z = 4280,
							facing = 1,
						},
						{
							name = "turretmissile",
							x = 2768,
							z = 3760,
							facing = 1,
						},
						{
							name = "wolverine_mine",
							x = 3896,
							z = 5016,
							facing = 0,
						},
						{
							name = "vehassault",
							x = 4283,
							z = 2394,
							facing = 3,
						},
						{
							name = "turretmissile",
							x = 2832,
							z = 3568,
							facing = 1,
						},
						{
							name = "turretriot",
							x = 3048,
							z = 3544,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 3016,
							z = 3448,
							facing = 1,
						},
						{
							name = "wolverine_mine",
							x = 3224,
							z = 4056,
							facing = 0,
						},
						{
							name = "wolverine_mine",
							x = 3432,
							z = 3752,
							facing = 0,
						},
						{
							name = "vehriot",
							x = 2553,
							z = 4542,
							facing = 1,
						},
						{
							name = "vehcon",
							x = 763,
							z = 3956,
							facing = 2,
						},
						{
							name = "vehcon",
							x = 937,
							z = 4577,
							facing = 1,
						},
						{
							name = "vehscout",
							x = 2489,
							z = 4930,
							facing = 0,
						},
						{
							name = "vehassault",
							x = 626,
							z = 4568,
							facing = 1,
							buildProgress = 0.65460002,
						},
						{	-- Corresponds to Team 7
							name = "factorytank",
							x = 672,
							z = 2736,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 328,
							z = 2616,
							facing = 0,
						},
						{
							name = "tankcon",
							x = 3338,
							z = 4081,
							facing = 2,
						},
						{
							name = "staticmex",
							x = 632,
							z = 2984,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 696,
							z = 2968,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 512,
							z = 2736,
							facing = 1,
						},
						{
							name = "tankraid",
							x = 3586,
							z = 1605,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 696,
							z = 2328,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 2104,
							z = 3160,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 632,
							z = 2328,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 664,
							z = 2408,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 2104,
							z = 3096,
							facing = 1,
						},
						{
							name = "tankcon",
							x = 3912,
							z = 2847,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 1304,
							z = 2296,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 1368,
							z = 2280,
							facing = 1,
						},
						{
							name = "staticradar",
							x = 2048,
							z = 3200,
							facing = 1,
						},
						{
							name = "tankriot",
							x = 1080,
							z = 2849,
							facing = 2,
						},
						{
							name = "staticcon",
							x = 552,
							z = 2728,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 672,
							z = 2912,
							facing = 1,
						},
						{
							name = "tankcon",
							x = 4149,
							z = 2880,
							facing = 1,
						},
						{
							name = "tankassault",
							x = 2571,
							z = 3718,
							facing = 3,
						},
						{
							name = "staticmex",
							x = 296,
							z = 4344,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 2744,
							z = 2744,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 248,
							z = 4408,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 232,
							z = 4328,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 2904,
							z = 3960,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 3000,
							z = 3384,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 3064,
							z = 3352,
							facing = 1,
						},
						{
							name = "tankassault",
							x = 1308,
							z = 3374,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 2936,
							z = 3384,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 2136,
							z = 3224,
							facing = 1,
						},
						{
							name = "tankaa",
							x = 4689,
							z = 3111,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 2728,
							z = 2680,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 568,
							z = 2952,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 1960,
							z = 4376,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 2648,
							z = 2680,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 648,
							z = 3048,
							facing = 1,
						},
						{
							name = "staticcon",
							x = 504,
							z = 2696,
							facing = 1,
						},
						{
							name = "tankassault",
							x = 3162,
							z = 1656,
							facing = 1,
						},
						{
							name = "turretaalaser",
							x = 2984,
							z = 3816,
							facing = 1,
						},
						{
							name = "tankcon",
							x = 1753,
							z = 4261,
							facing = 0,
						},
						{
							name = "tankcon",
							x = 2480,
							z = 2170,
							facing = 2,
						},
						{
							name = "turretaalaser",
							x = 4088,
							z = 2792,
							facing = 0,
						},
						{
							name = "staticcon",
							x = 552,
							z = 2680,
							facing = 1,
						},
						{
							name = "tankassault",
							x = 696,
							z = 2736,
							facing = 1,
							buildProgress = 0.90759999,
						},
						{
							name = "turretlaser",
							x = 4080,
							z = 2912,
							facing = 0,
							buildProgress = 0.61110002,
						},
						{
							name = "energysolar",
							x = 1832,
							z = 4392,
							facing = 1,
							buildProgress = 0,
						},
						{	-- Corresponds to Team 8
							name = "staticmex",
							x = 888,
							z = 728,
							facing = 0,
						},
						{
							name = "factoryshield",
							x = 960,
							z = 768,
							facing = 1,
						},
						{
							name = "shieldcon",
							x = 2420,
							z = 1421,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 456,
							z = 584,
							facing = 0,
						},
						{
							name = "shieldbomb",
							x = 1613,
							z = 1045,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 520,
							z = 568,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 872,
							z = 376,
							facing = 0,
						},
						{
							name = "shieldriot",
							x = 3233,
							z = 2302,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 392,
							z = 568,
							facing = 1,
						},
						{
							name = "staticradar",
							x = 864,
							z = 608,
							facing = 1,
						},
						{
							name = "shieldcon",
							x = 4208,
							z = 2899,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 960,
							z = 912,
							facing = 1,
						},
						{
							name = "shieldaa",
							x = 1793,
							z = 738,
							facing = 3,
						},
						{
							name = "shieldcon",
							x = 3596,
							z = 1359,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 824,
							z = 776,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 2056,
							z = 280,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 824,
							z = 696,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 872,
							z = 856,
							facing = 1,
						},
						{
							name = "staticcon",
							x = 808,
							z = 840,
							facing = 1,
						},
						{
							name = "shieldaa",
							x = 3475,
							z = 1374,
							facing = 3,
						},
						{
							name = "staticmex",
							x = 2328,
							z = 984,
							facing = 0,
						},
						{
							name = "energysolar",
							x = 2264,
							z = 1016,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 2504,
							z = 1880,
							facing = 0,
						},
						{
							name = "shieldaa",
							x = 3513,
							z = 1376,
							facing = 3,
						},
						{
							name = "shieldaa",
							x = 3782,
							z = 1370,
							facing = 3,
						},
						{
							name = "factoryshield",
							x = 2528,
							z = 1456,
							facing = 0,
							buildProgress = 0.1794,
						},
						{
							name = "staticradar",
							x = 4112,
							z = 2720,
							facing = 0,
						},
						{
							name = "shieldassault",
							x = 3533,
							z = 1904,
							facing = 2,
						},
						{
							name = "energysolar",
							x = 952,
							z = 600,
							facing = 1,
						},
						{
							name = "turretlaser",
							x = 1008,
							z = 624,
							facing = 1,
						},
						{
							name = "shieldassault",
							x = 3621,
							z = 1182,
							facing = 1,
						},
						{
							name = "shieldaa",
							x = 3703,
							z = 1372,
							facing = 3,
						},
						{
							name = "energysolar",
							x = 776,
							z = 616,
							facing = 1,
						},
						{
							name = "shieldarty",
							x = 2615,
							z = 871,
							facing = 0,
						},
						{
							name = "staticcon",
							x = 760,
							z = 792,
							facing = 1,
						},
						{
							name = "energysolar",
							x = 744,
							z = 728,
							facing = 1,
						},
						{
							name = "shieldassault",
							x = 2814,
							z = 902,
							facing = 0,
						},
						{
							name = "shieldcon",
							x = 4068,
							z = 2624,
							facing = 3,
						},
						{
							name = "shieldraid",
							x = 4305,
							z = 1369,
							facing = 3,
						},
						{
							name = "shieldaa",
							x = 3573,
							z = 1377,
							facing = 3,
						},
						{
							name = "shieldassault",
							x = 3664,
							z = 1504,
							facing = 1,
						},
						{
							name = "shieldaa",
							x = 3541,
							z = 1374,
							facing = 3,
						},
						{
							name = "shieldaa",
							x = 3599,
							z = 1385,
							facing = 3,
						},
						{
							name = "shieldfelon",
							x = 1388,
							z = 1154,
							facing = 1,
						},
						{
							name = "shieldaa",
							x = 3626,
							z = 1375,
							facing = 3,
						},
						{
							name = "shieldassault",
							x = 2727,
							z = 928,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 3336,
							z = 2424,
							facing = 0,
						},
						{
							name = "shieldcon",
							x = 2457,
							z = 1375,
							facing = 0,
						},
						{
							name = "shieldcon",
							x = 2446,
							z = 1414,
							facing = 1,
						},
						{
							name = "shieldassault",
							x = 3062,
							z = 1022,
							facing = 0,
						},
						{
							name = "shieldcon",
							x = 2429,
							z = 988,
							facing = 0,
						},
						{
							name = "turretmissile",
							x = 3680,
							z = 2496,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 4200,
							z = 2824,
							facing = 0,
						},
						{
							name = "staticradar",
							x = 640,
							z = 2528,
							facing = 1,
						},
						{
							name = "shieldraid",
							x = 3486,
							z = 1619,
							facing = 0,
						},
						{
							name = "shieldraid",
							x = 2995,
							z = 2195,
							facing = 1,
						},
						{
							name = "shieldraid",
							x = 3296,
							z = 1371,
							facing = 1,
						},
						{
							name = "staticmex",
							x = 2120,
							z = 248,
							facing = 0,
						},
						{
							name = "staticmex",
							x = 3928,
							z = 1256,
							facing = 0,
						},
						{
							name = "shieldcon",
							x = 1009,
							z = 782,
							facing = 0,
						},
					},
				},
			},
			defeatConditionConfig = {
				-- Indexed by allyTeam.
				[0] = { },
				[1] = {
					ignoreUnitLossDefeat = false,
					vitalCommanders = false,
					vitalUnitTypes = {
						"staticheavyarty",
					},
					loseAfterSeconds = false,
					allyTeamLossObjectiveID = 1,
				},
			},
			objectiveConfig = {
				-- This is just related to displaying objectives on the UI.
				[1] = {
					description = "Destroy the Big Bertha cannon",
				},
				[2] = {
					description = "Protect your Commander",
				},
			},
			bonusObjectiveConfig = {
				
				[1] = { -- Build 12 Scythes
					satisfyOnce = true,
					countRemovedUnits = true, -- count units that previously died.
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 18,
					unitTypes = {
						"cloakheavyraid",
					},
					image = planetUtilities.ICON_DIR .. "cloakheavyraid.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.REPAIR,
					description = "Build 12 Scythes",
					experience = planetUtilities.BONUS_EXP,
				},
				[2] = {
					victoryByTime = 600,
					image = planetUtilities.ICON_OVERLAY.CLOCK,
					description = "Win by 10:00",
					experience = planetUtilities.BONUS_EXP,
				},
				[3] = { -- Make the enemy lose one Sunlance by 8:00
					onlyCountRemovedUnits = true,
					satisfyByTime = 480,
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 1,
					enemyUnitTypes = {
						"turretsunlance",
					},
					image = planetUtilities.ICON_DIR .. "turretsunlance.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.ATTACK,
					description = "Destroy one of the enemy Sunlance turrets by 8:00",
					experience = planetUtilities.BONUS_EXP,
				},
			}
		},
		completionReward = {
			experience = planetUtilities.MAIN_EXP,
			units = {
				"cloakheavyraid",
			},
			modules = {
				"module_high_power_servos_LIMIT_D_2",
			},
			abilities = {
			}
		},
	}
	
	return planetData
end

return GetPlanet

