--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Planet config

local function GetPlanet(planetUtilities, planetID)
	
	local image = LUA_DIRNAME .. "images/planets/tundra03.png"
	
	local planetData = {
		name = "Chatka",
		startingPlanet = false,
		mapDisplay = {
			x = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][1]) or 0.675,
			y = (planetUtilities.planetPositions and planetUtilities.planetPositions[planetID][2]) or 0.235,
			image = image,
			size = planetUtilities.PLANET_SIZE_MAP,
		},
		infoDisplay = {
			image = image,
			size = planetUtilities.PLANET_SIZE_INFO,
			backgroundImage = planetUtilities.backgroundImages[math.floor(math.random()*#planetUtilities.backgroundImages) + 1],
			terrainType = "Arctic",
			radius = "4980 km",
			primary = "Halio Raba",
			primaryType = "K1VI",
			milRating = 1,
			feedbackLink = "http://zero-k.info/Forum/Thread/24614",
			text = "This wealthy ice planet was one of the main Rebel worlds, and the Empire sent a large occupation force to make sure it would never challenge it again. But somehow, the Rebels managed to turn one half of the force against the other."
			.. "\n "
			.. "\nThe civilian population, de facto hostage, would have all become collateral damage - had it not disappeared just as combat started."
			,
			extendedText = "The two groups have awakened and are resuming hostilities. I can defeat them both from a safe distance with the Merlin artillery strider."
		},
		tips = {
			{
				image = "unitpics/striderarty.png",
				text = [[The Merlin is the most powerful mobile artillery piece in the game - its barrage of rockets is most effective against large groups of enemies. Merlins are defenseless at close range so be careful with your starting Merlin until you have a large enough army to escort it.]]
			},
			{
				image = "unitpics/cloakjammer.png",
				text = [[Keep your units invisible with an area cloaker until the time has come for a decisive strike. This is best used to hide your vulnerable artillery pieces or get your short-range fighters up close to enemy positions.]]
			},
			{
				image = "unitpics/energyfusion.png",
				text = [[Remember that in a multi-sided game damaging one of your enemies is often less important than making yourself stronger. Play conservatively and build many energy generators to bolster your economy.]]
			},
		},
		gameConfig = {
			mapName = "SiberianDivide 1.1",
			playerConfig = {
				startX = 6850,
				startZ = 5950,
				allyTeam = 0,
				commanderParameters = {
					facplop = true,
					defeatIfDestroyedObjectiveID = 3,
				},
				extraUnlocks = {
					"striderhub",
					"striderarty",
				},
				startUnits = {
					{
						name = "staticcon",
						x = 6952,
						z = 5992,
						facing = 2,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {6952, 5992}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {6927, 5967}, options = {"shift"}},
						},
					},
 					{
						name = "staticmex",
						x = 8456,
						z = 6536,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 7576,
						z = 6024,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 7256,
						z = 6168,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 7000,
						z = 5560,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 7272,
						z = 5400,
						facing = 0,
					},
 					{
						name = "staticmex",
						x = 5768,
						z = 6296,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 7064,
						z = 5576,
						facing = 2,
					},
 					{
						name = "energysolar",
						x = 6984,
						z = 5624,
						facing = 1,
					},
 					{
						name = "staticheavyradar",
						x = 8096,
						z = 6160,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 6936,
						z = 5544,
						facing = 0,
					},
 					{
						name = "energysolar",
						x = 7016,
						z = 5496,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 7336,
						z = 5416,
						facing = 2,
					},
 					{
						name = "energysolar",
						x = 7256,
						z = 5464,
						facing = 1,
					},
 					{
						name = "energysolar",
						x = 7208,
						z = 5384,
						facing = 0,
					},
 					{
						name = "energysolar",
						x = 7288,
						z = 5336,
						facing = 3,
					},
 					{
						name = "staticmex",
						x = 8824,
						z = 4808,
						facing = 3,
					},
 					{
						name = "turretheavylaser",
						x = 6984,
						z = 5352,
						facing = 2,
					},
 					{
						name = "turretriot",
						x = 7432,
						z = 5336,
						facing = 2,
					},
 					{
						name = "cloakjammer",
						x = 7142,
						z = 5641,
						facing = 2,
					},
 					{
						name = "turretaafar",
						x = 7136,
						z = 5744,
						facing = 2,
					},
 					{
						name = "energysolar",
						x = 8888,
						z = 4824,
						facing = 1,
					},
 					{
						name = "energysolar",
						x = 8808,
						z = 4872,
						facing = 0,
					},
 					{
						name = "energysolar",
						x = 8760,
						z = 4792,
						facing = 3,
					},
 					{
						name = "striderarty",
						x = 7073,
						z = 5888,
						facing = 2,
					},
 					{
						name = "energysolar",
						x = 8840,
						z = 4744,
						facing = 2,
					},
 					{
						name = "turretmissile",
						x = 8640,
						z = 4768,
						facing = 2,
					},
 					{
						name = "energysolar",
						x = 5832,
						z = 6312,
						facing = 1,
					},
 					{
						name = "turretmissile",
						x = 8928,
						z = 4640,
						facing = 2,
					},
 					{
						name = "energysolar",
						x = 5752,
						z = 6360,
						facing = 0,
					},
 					{
						name = "energysolar",
						x = 5704,
						z = 6280,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 5784,
						z = 6232,
						facing = 2,
					},
 					{
						name = "turretmissile",
						x = 5584,
						z = 6384,
						facing = 3,
					},
 					{
						name = "turretmissile",
						x = 5920,
						z = 6192,
						facing = 2,
					},
 					{
						name = "energysolar",
						x = 8520,
						z = 6552,
						facing = 1,
					},
 					{
						name = "energysolar",
						x = 8440,
						z = 6600,
						facing = 0,
					},
 					{
						name = "energysolar",
						x = 8392,
						z = 6520,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 8472,
						z = 6472,
						facing = 2,
					},
 					{
						name = "energyfusion",
						x = 8664,
						z = 6656,
						facing = 2,
					},
 					{
						name = "energysolar",
						x = 7320,
						z = 6184,
						facing = 1,
					},
 					{
						name = "energysolar",
						x = 7240,
						z = 6232,
						facing = 0,
					},
 					{
						name = "energysolar",
						x = 7192,
						z = 6152,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 7272,
						z = 6104,
						facing = 2,
					},
 					{
						name = "energysolar",
						x = 7640,
						z = 6040,
						facing = 1,
					},
 					{
						name = "energysolar",
						x = 7560,
						z = 6088,
						facing = 0,
					},
 					{
						name = "energysolar",
						x = 7512,
						z = 6008,
						facing = 3,
					},
 					{
						name = "energysolar",
						x = 7592,
						z = 5960,
						facing = 2,
					},
 					{
						name = "turretriot",
						x = 6808,
						z = 5720,
						facing = 3,
					},
 					{
						name = "turretmissile",
						x = 5536,
						z = 6464,
						facing = 3,
					},
 					{
						name = "turretmissile",
						x = 6016,
						z = 6160,
						facing = 2,
					},
 					{
						name = "turretmissile",
						x = 8512,
						z = 4816,
						facing = 2,
					},
 					{
						name = "turretmissile",
						x = 9040,
						z = 4592,
						facing = 2,
					},
 					{
						name = "striderhub",
						x = 7056,
						z = 6016,
						facing = 2,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7056, 6016}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7031, 5991}, options = {"shift"}},
						},
					},
 					{
						name = "staticcon",
						x = 7160,
						z = 6008,
						facing = 2,
						commands = {
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7135, 5983}, options = {"shift"}},
							{cmdID = planetUtilities.COMMAND.PATROL, pos = {7160, 6008}, options = {"shift"}},
						},
					},
				}
			},
			aiConfig = {
				{
					startX = 6700,
					startZ = 1500,
					humanName = "Amlamu",
					-- aiLib = "Null AI",
					-- bitDependant = false,
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					commanderParameters = {
						facplop = false,
					},
					allyTeam = 1,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energypylon",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turrettorp",
						"turretgauss",
						"turretheavylaser",
						"turretaalaser",
						"turretaaclose",
						"turretaaflak",
						"shieldshield",
						"staticradar",
						"staticheavyradar",
						"staticcon",
						"staticantinuke",
						"factorygunship",
						"gunshipcon",
						"gunshipbomb",
						"gunshipemp",
						"gunshipaa",
						"gunshipassault",
						"gunshipheavyskirm",
						"gunshipskirm",
						"gunshipraid",
						"gunshipkrow",
						"factoryshield",
						"shieldcon",
						"shieldraid",
						"shieldassault",
						"shieldriot",
						"shieldskirm",
						"shieldbomb",
						"shieldaa",
						"shieldfelon",
						"shieldshield",
						"shieldarty",
						"factoryspider",
						"spidercon",
						"spiderscout",
						"spiderriot",
						"spideremp",
						"spiderskirm",
						"spiderassault",
						"spidercrabe",
						"spiderantiheavy",
						"spideraa",
						"factorytank",
						"tankcon",
						"tankassault",
						"tankheavyassault",
						"tankarty",
						"tankheavyarty",
						"tankaa",
						"tankriot",
						"striderhub",
						"striderdante",
						"striderscorpion",
						"staticnuke",
					},
					commanderLevel = 6,
					commander = {
						name = "K'lor",
						chassis = "engineer",
						decorations = {
						  "skin_support_green",
						},
						modules = {
							"commweapon_hparticlebeam",
							"commweapon_multistunner",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_high_power_servos",
							"module_high_power_servos",
							"module_autorepair",
							"module_autorepair",
							"module_autorepair",
						}
					},
					startUnits = {
					{
							name = "turretlaser",
							x = 5024,
							z = 224,
							facing = 3,
						},
 						{
							name = "spideremp",
							x = 6859,
							z = 1945,
							facing = 3,
						},
 						{
							name = "staticmex",
							x = 7272,
							z = 1240,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7000,
							z = 872,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6200,
							z = 1944,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5832,
							z = 1784,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5224,
							z = 1032,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 5368,
							z = 696,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 6408,
							z = 3304,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 7112,
							z = 3384,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8440,
							z = 3768,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8856,
							z = 552,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 8408,
							z = 312,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 8472,
							z = 328,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 8504,
							z = 3784,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 8392,
							z = 376,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 8424,
							z = 3832,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 8344,
							z = 296,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 8376,
							z = 3752,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 8456,
							z = 3704,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 8920,
							z = 568,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 8840,
							z = 616,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 8792,
							z = 536,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 8872,
							z = 488,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 7032,
							z = 3432,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 7176,
							z = 3432,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 6472,
							z = 3320,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 6392,
							z = 3368,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 6344,
							z = 3288,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 6424,
							z = 3240,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 6264,
							z = 1960,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 6184,
							z = 2008,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 6136,
							z = 1928,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 6216,
							z = 1880,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 5896,
							z = 1800,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 5816,
							z = 1848,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 5768,
							z = 1768,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 5848,
							z = 1720,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 5288,
							z = 1048,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 5208,
							z = 1096,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 5160,
							z = 1016,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 5240,
							z = 968,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 5432,
							z = 712,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 5352,
							z = 760,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 5304,
							z = 680,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 5384,
							z = 632,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 7064,
							z = 888,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 6984,
							z = 936,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 6936,
							z = 856,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 7016,
							z = 808,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 7336,
							z = 1256,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 7256,
							z = 1304,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 7208,
							z = 1224,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 7288,
							z = 1176,
							facing = 2,
						},
 						{
							name = "staticcon",
							x = 8024,
							z = 312,
							facing = 2,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {8024, 312}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7999, 337}, options = {"shift"}},
							},
						},
 						{
							name = "factorygunship",
							x = 8136,
							z = 440,
							facing = 2,
						},
 						{
							name = "staticradar",
							x = 5248,
							z = 816,
							facing = 0,
						},
 						{
							name = "energysingu",
							x = 7544,
							z = 760,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 7016,
							z = 1064,
							facing = 3,
						},
 						{
							name = "turretheavy",
							x = 4984,
							z = 648,
							facing = 3,
							terraformHeight = 118,
						},
 						{
							name = "energypylon",
							x = 6056,
							z = 1048,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 4880,
							z = 880,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 5384,
							z = 904,
							facing = 3,
						},
 						{
							name = "turretemp",
							x = 4976,
							z = 368,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 4816,
							z = 1008,
							facing = 3,
						},
 						{
							name = "turretlaser",
							x = 4864,
							z = 1136,
							facing = 3,
						},
 						{
							name = "turretaaflak",
							x = 5096,
							z = 872,
							facing = 3,
						},
 						{
							name = "turretaaflak",
							x = 5240,
							z = 360,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 6408,
							z = 1816,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 5912,
							z = 2632,
							facing = 1,
						},
 						{
							name = "energypylon",
							x = 6824,
							z = 2616,
							facing = 1,
						},
 						{
							name = "spideremp",
							x = 6828,
							z = 1975,
							facing = 3,
						},
 						{
							name = "energypylon",
							x = 7704,
							z = 2568,
							facing = 1,
						},
 						{
							name = "staticradar",
							x = 5472,
							z = 2352,
							facing = 0,
						},
 						{
							name = "turretemp",
							x = 8928,
							z = 2944,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 8808,
							z = 2872,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 9064,
							z = 2936,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 7328,
							z = 2832,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 5224,
							z = 2104,
							facing = 3,
						},
 						{
							name = "turretheavylaser",
							x = 5112,
							z = 2488,
							facing = 3,
						},
 						{
							name = "turretriot",
							x = 5192,
							z = 2280,
							facing = 3,
						},
 						{
							name = "turretaaflak",
							x = 5448,
							z = 2056,
							facing = 3,
						},
 						{
							name = "turretantiheavy",
							x = 6224,
							z = 2864,
							facing = 0,
						},
 						{
							name = "turretheavy",
							x = 6808,
							z = 3096,
							facing = 0,
						},
 						{
							name = "turretheavy",
							x = 7736,
							z = 3096,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 8600,
							z = 2616,
							facing = 0,
						},
 						{
							name = "turretheavy",
							x = 8600,
							z = 3080,
							facing = 0,
						},
 						{
							name = "turretheavy",
							x = 5640,
							z = 3032,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 5880,
							z = 2808,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 8312,
							z = 2744,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 6728,
							z = 2744,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 6576,
							z = 3056,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 7952,
							z = 3008,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 6400,
							z = 3008,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 8432,
							z = 3008,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 5968,
							z = 3072,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 7336,
							z = 1896,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 7928,
							z = 1128,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 8216,
							z = 1992,
							facing = 0,
						},
 						{
							name = "factoryspider",
							x = 7096,
							z = 2120,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 7208,
							z = 2088,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7208, 2088}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {7183, 2113}, options = {"shift"}},
							},
						},
 						{
							name = "factoryshield",
							x = 6840,
							z = 640,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 6984,
							z = 664,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {6984, 664}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {6959, 689}, options = {"shift"}},
							},
						},
 						{
							name = "factorytank",
							x = 5952,
							z = 1472,
							facing = 3,
						},
 						{
							name = "staticcon",
							x = 6088,
							z = 1432,
							facing = 3,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {6063, 1457}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {6088, 1432}, options = {"shift"}},
							},
						},
 						{
							name = "shieldraid",
							x = 6149,
							z = 536,
							facing = 2,
						},
 						{
							name = "shieldraid",
							x = 6154,
							z = 758,
							facing = 1,
						},
 						{
							name = "shieldraid",
							x = 6194,
							z = 969,
							facing = 0,
						},
 						{
							name = "shieldskirm",
							x = 6369,
							z = 716,
							facing = 3,
						},
 						{
							name = "shieldskirm",
							x = 6355,
							z = 648,
							facing = 3,
						},
 						{
							name = "shieldskirm",
							x = 6410,
							z = 732,
							facing = 3,
						},
 						{
							name = "shieldskirm",
							x = 6348,
							z = 607,
							facing = 3,
						},
 						{
							name = "shieldassault",
							x = 6536,
							z = 625,
							facing = 2,
						},
 						{
							name = "shieldassault",
							x = 6589,
							z = 704,
							facing = 3,
						},
 						{
							name = "shieldassault",
							x = 6580,
							z = 559,
							facing = 3,
						},
 						{
							name = "shieldriot",
							x = 6181,
							z = 698,
							facing = 3,
						},
 						{
							name = "shieldriot",
							x = 6622,
							z = 619,
							facing = 3,
						},
 						{
							name = "shieldriot",
							x = 6623,
							z = 566,
							facing = 3,
						},
 						{
							name = "shieldfelon",
							x = 6669,
							z = 666,
							facing = 3,
						},
 						{
							name = "tankassault",
							x = 5682,
							z = 1439,
							facing = 3,
						},
 						{
							name = "tankriot",
							x = 5726,
							z = 1480,
							facing = 3,
						},
 						{
							name = "tankarty",
							x = 5734,
							z = 1429,
							facing = 3,
						},
 						{
							name = "tankcon",
							x = 5734,
							z = 1385,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 6888,
							z = 2124,
							facing = 3,
						},
 						{
							name = "spidercon",
							x = 6764,
							z = 1909,
							facing = 3,
						},
 						{
							name = "spiderriot",
							x = 6686,
							z = 1907,
							facing = 3,
						},
 						{
							name = "turretantiheavy",
							x = 6784,
							z = 1408,
							facing = 3,
						},
 						{
							name = "spiderriot",
							x = 6674,
							z = 2025,
							facing = 3,
						},
 						{
							name = "spiderassault",
							x = 6700,
							z = 1788,
							facing = 3,
						},
 						{
							name = "spiderassault",
							x = 6785,
							z = 1948,
							facing = 3,
						},
 						{
							name = "spiderskirm",
							x = 6748,
							z = 1983,
							facing = 2,
						},
 						{
							name = "spiderskirm",
							x = 6790,
							z = 1995,
							facing = 2,
						},
					}
				},
				{
					startX = 1200,
					startZ = 1850,
					humanName = "Alkalich",
					-- aiLib = "Null AI",
					-- bitDependant = false,
					aiLib = "Circuit_difficulty_autofill",
					bitDependant = true,
					commanderParameters = {
						facplop = false,
					},
					allyTeam = 2,
					unlocks = {
						"staticmex",
						"energysolar",
						"energywind",
						"energyfusion",
						"energygeo",
						"energypylon",
						"staticstorage",
						"turretlaser",
						"turretmissile",
						"turretriot",
						"turrettorp",
						"turretgauss",
						"turretheavylaser",
						"turretaalaser",
						"turretaaclose",
						"turretaaflak",
						"shieldshield",
						"staticradar",
						"staticheavyradar",
						"staticcon",
						"staticantinuke",
						"staticrearm",
						"factoryplane",
						"planecon",
						"planescout",
						"planefighter",
						"planeheavyfighter",
						"bomberprec",
						"bomberdisarm",
						"bomberheavy",
						"factoryspider",
						"spidercon",
						"spiderscout",
						"spiderriot",
						"spideremp",
						"spiderskirm",
						"spiderassault",
						"spidercrabe",
						"spiderantiheavy",
						"spideraa",
						"factoryveh",
						"vehcon",
						"vehscout",
						"vehraid",
						"vehriot",
						"vehassault",
						"vehaa",
						"vehsupport",
						"veharty",
						"vehheavyarty",
						"vehcapture",
						"factorycloak",
						"cloakcon",
						"cloakraid",
						"cloakriot",
						"cloakskirm",
						"cloakassault",
						"cloakaa",
						"cloakarty",
						"cloaksnipe",
						"cloakheavyraid",
						"cloakbomb",
						"striderhub",
						"striderdante",
						"striderscorpion",
						"staticheavyarty"
					},
					commanderLevel = 6,
					commander = {
						name = "Natrium",
						chassis = "guardian",
						decorations = {
						},
						modules = {
							"commweapon_riotcannon",
							"commweapon_riotcannon",
							"weaponmod_napalm_warhead",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_adv_targeting",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_ablative_armor",
							"module_autorepair",
							"module_autorepair",
						}
					},
					startUnits = {
						{
							name = "vehassault",
							x = 3275,
							z = 1962,
							facing = 1,
						},
 						{
							name = "vehassault",
							x = 3279,
							z = 2013,
							facing = 1,
						},
 						{
							name = "staticmex",
							x = 792,
							z = 3400,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 408,
							z = 2360,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1944,
							z = 1768,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2216,
							z = 1608,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1960,
							z = 1000,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 1656,
							z = 1144,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 760,
							z = 648,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2584,
							z = 2440,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2840,
							z = 2248,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 3448,
							z = 888,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2120,
							z = 3784,
							facing = 0,
						},
 						{
							name = "staticmex",
							x = 2808,
							z = 3880,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 856,
							z = 3416,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 776,
							z = 3464,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 728,
							z = 3384,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 2872,
							z = 3896,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 808,
							z = 3336,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 2792,
							z = 3944,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 2744,
							z = 3864,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 2824,
							z = 3816,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 2184,
							z = 3800,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 472,
							z = 2376,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 2104,
							z = 3848,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 392,
							z = 2424,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 2056,
							z = 3768,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 344,
							z = 2344,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 424,
							z = 2296,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 1720,
							z = 1160,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 1640,
							z = 1208,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 1592,
							z = 1128,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 1672,
							z = 1080,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 2024,
							z = 1016,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 3512,
							z = 904,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 1944,
							z = 1064,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 1896,
							z = 984,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 3384,
							z = 872,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 1976,
							z = 936,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 3464,
							z = 824,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 824,
							z = 664,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 744,
							z = 712,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 696,
							z = 632,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 776,
							z = 584,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 2008,
							z = 1784,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 1928,
							z = 1832,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 1880,
							z = 1752,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 1960,
							z = 1704,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 2280,
							z = 1624,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 2200,
							z = 1672,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 2152,
							z = 1592,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 2232,
							z = 1544,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 2648,
							z = 2456,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 2568,
							z = 2504,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 2520,
							z = 2424,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 2600,
							z = 2376,
							facing = 2,
						},
 						{
							name = "energysolar",
							x = 2904,
							z = 2264,
							facing = 1,
						},
 						{
							name = "energysolar",
							x = 2824,
							z = 2312,
							facing = 0,
						},
 						{
							name = "energysolar",
							x = 2776,
							z = 2232,
							facing = 3,
						},
 						{
							name = "energysolar",
							x = 2856,
							z = 2184,
							facing = 2,
						},
 						{
							name = "turretaafar",
							x = 2592,
							z = 4256,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 2968,
							z = 4312,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 2744,
							z = 4424,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 2312,
							z = 4536,
							facing = 0,
						},
 						{
							name = "turretemp",
							x = 2512,
							z = 4464,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 1920,
							z = 4320,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 1536,
							z = 4416,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 1232,
							z = 4432,
							facing = 0,
						},
 						{
							name = "turretmissile",
							x = 912,
							z = 4416,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 160,
							z = 4448,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 368,
							z = 4368,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 2784,
							z = 4272,
							facing = 0,
						},
 						{
							name = "staticrearm",
							x = 552,
							z = 1576,
							facing = 0,
						},
 						{
							name = "factoryplane",
							x = 536,
							z = 1408,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 408,
							z = 1624,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {408, 1624}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {433, 1649}, options = {"shift"}},
							},
						},
 						{
							name = "staticstorage",
							x = 440,
							z = 1288,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 584,
							z = 1784,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 312,
							z = 1832,
							facing = 0,
						},
 						{
							name = "turretemp",
							x = 752,
							z = 1568,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 536,
							z = 1256,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 3544,
							z = 3832,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 3432,
							z = 3912,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 3672,
							z = 3768,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 3480,
							z = 3640,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 1112,
							z = 3880,
							facing = 0,
						},
 						{
							name = "turretlaser",
							x = 1248,
							z = 3824,
							facing = 0,
						},
 						{
							name = "staticradar",
							x = 3456,
							z = 352,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 3880,
							z = 296,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 3720,
							z = 632,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 3864,
							z = 488,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 4008,
							z = 152,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 3656,
							z = 808,
							facing = 1,
						},
 						{
							name = "turretaafar",
							x = 3392,
							z = 240,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 3360,
							z = 592,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 3552,
							z = 144,
							facing = 1,
						},
 						{
							name = "turretlaser",
							x = 3104,
							z = 928,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 2424,
							z = 1384,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 2648,
							z = 1240,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 2504,
							z = 1272,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 1560,
							z = 1928,
							facing = 0,
						},
 						{
							name = "turretriot",
							x = 1800,
							z = 1896,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 1672,
							z = 1832,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 1720,
							z = 1656,
							facing = 0,
						},
 						{
							name = "turretaaflak",
							x = 2232,
							z = 1272,
							facing = 1,
						},
 						{
							name = "factoryspider",
							x = 616,
							z = 3080,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 488,
							z = 3064,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {488, 3064}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {513, 3089}, options = {"shift"}},
							},
						},
 						{
							name = "energyfusion",
							x = 1176,
							z = 656,
							facing = 0,
						},
 						{
							name = "energyfusion",
							x = 1448,
							z = 720,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 1320,
							z = 904,
							facing = 0,
						},
 						{
							name = "energypylon",
							x = 1928,
							z = 1336,
							facing = 0,
						},
 						{
							name = "turretheavylaser",
							x = 3400,
							z = 2904,
							facing = 1,
						},
 						{
							name = "turretheavylaser",
							x = 3304,
							z = 1848,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 3448,
							z = 1784,
							facing = 1,
						},
 						{
							name = "turretriot",
							x = 3544,
							z = 2968,
							facing = 1,
						},
 						{
							name = "turretemp",
							x = 3376,
							z = 2352,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 2824,
							z = 1880,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {2824, 1880}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {2849, 1905}, options = {"shift"}},
							},
						},
 						{
							name = "factoryveh",
							x = 2976,
							z = 1856,
							facing = 1,
						},
 						{
							name = "factorycloak",
							x = 1360,
							z = 1688,
							facing = 1,
						},
 						{
							name = "staticcon",
							x = 1208,
							z = 1672,
							facing = 1,
							commands = {
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1233, 1697}, options = {"shift"}},
								{cmdID = planetUtilities.COMMAND.PATROL, pos = {1208, 1672}, options = {"shift"}},
							},
						},
 						{
							name = "spidercon",
							x = 833,
							z = 3104,
							facing = 1,
						},
 						{
							name = "spidercon",
							x = 775,
							z = 2997,
							facing = 1,
						},
 						{
							name = "spiderskirm",
							x = 1052,
							z = 3037,
							facing = 2,
						},
 						{
							name = "spiderskirm",
							x = 990,
							z = 2905,
							facing = 1,
						},
 						{
							name = "spiderriot",
							x = 988,
							z = 2948,
							facing = 1,
						},
 						{
							name = "spiderriot",
							x = 1009,
							z = 3039,
							facing = 2,
						},
 						{
							name = "cloakskirm",
							x = 1687,
							z = 1508,
							facing = 2,
						},
 						{
							name = "spiderassault",
							x = 997,
							z = 2996,
							facing = 2,
						},
 						{
							name = "cloakskirm",
							x = 1647,
							z = 1490,
							facing = 2,
						},
 						{
							name = "spiderassault",
							x = 967,
							z = 3032,
							facing = 2,
						},
 						{
							name = "cloakskirm",
							x = 1607,
							z = 1474,
							facing = 2,
						},
 						{
							name = "spideremp",
							x = 944,
							z = 2950,
							facing = 1,
						},
 						{
							name = "cloakskirm",
							x = 1527,
							z = 1442,
							facing = 2,
						},
 						{
							name = "spideremp",
							x = 947,
							z = 2993,
							facing = 0,
						},
 						{
							name = "cloakskirm",
							x = 1758,
							z = 1542,
							facing = 2,
						},
 						{
							name = "cloakskirm",
							x = 1827,
							z = 1608,
							facing = 2,
						},
 						{
							name = "cloakskirm",
							x = 1724,
							z = 1523,
							facing = 2,
						},
 						{
							name = "cloakskirm",
							x = 1568,
							z = 1458,
							facing = 2,
						},
 						{
							name = "veharty",
							x = 3084,
							z = 2299,
							facing = 0,
						},
 						{
							name = "cloakskirm",
							x = 1485,
							z = 1434,
							facing = 2,
						},
 						{
							name = "cloakskirm",
							x = 1818,
							z = 1651,
							facing = 2,
						},
 						{
							name = "veharty",
							x = 3068,
							z = 1597,
							facing = 2,
						},
 						{
							name = "cloakriot",
							x = 1816,
							z = 1697,
							facing = 1,
						},
 						{
							name = "veharty",
							x = 3083,
							z = 2061,
							facing = 0,
						},
 						{
							name = "cloakassault",
							x = 1801,
							z = 1570,
							facing = 2,
						},
 						{
							name = "veharty",
							x = 3142,
							z = 1859,
							facing = 1,
						},
 						{
							name = "veharty",
							x = 3360,
							z = 2005,
							facing = 1,
						},
 						{
							name = "vehriot",
							x = 3355,
							z = 1962,
							facing = 1,
						},
 						{
							name = "vehriot",
							x = 3282,
							z = 2057,
							facing = 1,
						},
 						{
							name = "vehassault",
							x = 3320,
							z = 2020,
							facing = 0,
						},
					}
				},
			},
			defeatConditionConfig = {
				-- Indexed by allyTeam.
				[0] = { },
				[1] = {
					ignoreUnitLossDefeat = false,
					vitalCommanders = true,
					vitalUnitTypes = {
						"factoryshield",
						"factorygunship",
						"factoryspider",
						"factorytank",
					},
					loseAfterSeconds = false,
					allyTeamLossObjectiveID = 1,
					doNotExplodeOnLoss = true,
				},
				[2] = {
					ignoreUnitLossDefeat = false,
					vitalCommanders = true,
					vitalUnitTypes = {
						"factoryspider",
						"factoryveh",
						"factoryplane",
						"factorycloak",
					},
					loseAfterSeconds = false,
					allyTeamLossObjectiveID = 2,
					doNotExplodeOnLoss = true,
				},
			},
			objectiveConfig = {
				-- This is just related to displaying objectives on the UI.
				[1] = {
					description = "Destroy the Commander and Factories of the eastern enemy",
				},
				[2] = {
					description = "Destroy the Commander and Factories of the western enemy",
				},
				[3] = {
					description = "Protect your Commander",
				},
			},
			bonusObjectiveConfig = {
				[1] = {
					satisfyOnce = true,
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 4,
					unitTypes = {
						"striderarty",
					},
					image = planetUtilities.ICON_DIR .. "striderarty.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.REPAIR,
					description = "Have 4 Merlins",
					experience = planetUtilities.BONUS_EXP,
				},
				[2] = {
					onlyCountRemovedUnits = true,
					satisfyForever = true,
					comparisionType = planetUtilities.COMPARE.AT_MOST,
					targetNumber = 1,
					unitTypes = {
						"striderarty"
					},
					image = planetUtilities.ICON_DIR .. "striderarty.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.GUARD,
					description = "Do not lose more than 1 Merlin",
					experience = planetUtilities.BONUS_EXP,
				},
				[3] = {
					satisfyByTime = 18*60,
					comparisionType = planetUtilities.COMPARE.AT_LEAST,
					targetNumber = 18,
					unitTypes = {
						"staticmex",
					},
					image = planetUtilities.ICON_DIR .. "staticmex.png",
					imageOverlay = planetUtilities.ICON_OVERLAY.REPAIR,
					description = "Have 18 Metal Extractors by 18:00",
					experience = planetUtilities.BONUS_EXP,
				},
			}
		},
		completionReward = {
			experience = planetUtilities.MAIN_EXP,
			units = {
				"striderhub",
				"striderarty",
			},
			modules = {
				"module_cloak_field"
			},
			abilities = {
			},
			codexEntries = {
				"location_chatka",
				"faction_dynasty_restored"
			},
		},
	}
	
	return planetData
end

return GetPlanet
