return {
	CppTestAI = true,
	E323AI = true,
	HughAI = true,
	KAIK = true,
	NullJavaAI = true,
	NullOOJavaAI = true,
	RAI = true,
  --NullAI = true,
  ['Chicken: Custom'] = true,
  ['Chicken: Epic!'] = true,
	Sharddev = true,
	AAI = true,
	CircuitAI = true,
	Shard = true,
}